### ISSUE TITLE
Update drawer docs for top-app-bar scrollTarget

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-web#1043]
## Initiative / goal
Our demos and documentation do not properly use standard top-app-bar with drawers. The app bars are fixed instead of scrolling away and peeking back down when scrolling upwards.

### Scope
Document the need to set `scrollTarget` of `<mwc-top-app-bar>` when used with `<mwc-drawer>`, as well as the CSS requirements (explicit height and overflow of the `[slot="appContent"]` element).

See https://webcomponents.dev/edit/KjUN4AlCVAJ6nENcIGw3 for a working example.

## Acceptance criteria and must have scope
Drawer demos for standard app bars should scroll away with content and peek back when scrolling up. Documentation should explicitly label scrollTarget requirements.

**Comment by CaptainCodeman** [comment]
Another gotcha is that it stops working again if you try to add `-webkit-overflow-scrolling: touch;` (required to have smooth, momentum scrolling on iOS). The top bar reverts to not showing until the scroll to the top has completed.
