### ISSUE TITLE
mwc-button with icon breaks in mwc-dialog

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#1045]
**Describe the bug**
when using `icon` attribute in `mwc-button` inside a `mwc-dialog` the icon is not properly aligned with the text.

**Screenshots**
https://polymer.slack.com/archives/CC0Q3PRCL/p1585270713048300

**Issue**
`line-height` css property in the class `.mdc-dialog__content` is what cause this issue.

**Possible fix**
```css
mwc-dialog mwc-button {
  line-height: normal;
}
```

**Browser Version (please complete the following information):**
 - Browser: Chrome
 - Version 80

**Additional context**
`mwc-button` `mwc-icon` `mwc-dialog` version `0.14.1`

**Comment by asyncLiz** [comment]
Fixed in M3
