### ISSUE TITLE
Typography component or way to use typography styles

### ISSUE THREAD

**Issue by fernandopasik** [material-components/material-web#1050]
**Is your feature request related to a problem? Please describe.**
I'm trying to style individual elements with the material typography guidelines.

**Describe the solution you'd like**
Implement @material/mwc-typography component

**Describe alternatives you've considered**
I've tried to import `@material/typography/dist/mdc.typography.css` to use the css classes in my component like `.mdc-typography--body1`, but I can't find an easy way or tool to include that style in my lit-html components

**Comment by fernandopasik** [comment]
My current workaround far from ideal is to use just the css variables

```
.my-class {
    font-size: var(--mdc-typography-body1-font-size, 1rem);
    line-height: var(--mdc-typography-body1-line-height, 1.5rem);
    font-weight: var(--mdc-typography-body1-font-weight, 400);
}
```

**Comment by asyncLiz** [comment]
This is definitely on our roadmap!

I would recommend a plugin/loader for your build system that can turn a CSS file into a LitElement CSSResult, and use that to import `@material/typography` in the meantime.

```ts
import {style} from '@material/typography/dist/mdc.typography.css';
```
You can then include the `style` CSSResult in your LitElement styles.

Alternatively, you can include the raw CSS string into a `<style>` tag of your component's render function. Not as ideal, but it may be easier to get a CSS-to-string loader set up than CSS-to-CSSResult.

**Comment by fernandopasik** [comment]
Thanks for the quick response and the suggestion.

Would it be another alternative to use a sass plugin and call the right mixin for the typography style (which mixin would that be)?

**Comment by asyncLiz** [comment]
Absolutely. You could transform Sass into your component's CSS. You'll want the `typography()` mixin and provide it one of the [text styles](https://github.com/material-components/material-components-web/tree/master/packages/mdc-typography#typography-styles).

```scss
@use "@material/typography";

.my-headline {
  @include typography.typography(headline1);
}
```

**Comment by Alos** [comment]
It would be awesome if this was implemented out of the box

**Comment by aress31** [comment]
@asyncLiz would you mind providing a working code, tutorial on how to use the Typography?

**Comment by aress31** [comment]
Any update on this feature? :)

**Comment by fernandopasik** [comment]
Is there a new strategy for typography in the new implementation yet?

**Comment by asyncLiz** [comment]
> Is there a new strategy for typography in the new implementation yet?

I don't believe so, not yet 😔

That might need to be a 1.1 feature

**Comment by thekvd** [comment]
New to github so forgive if this is bad form.  I created a CSS file with the defaults and some global variables suggested on the demo site.  Not sure if this will be helpful for others but it was for me so I'm sharing it here: https://github.com/thekvd/material-web-typography/

**Comment by asyncLiz** [comment]
Long time coming, but this feature has been added. Check out [our typography guide](https://github.com/material-components/material-web/blob/main/docs/theming/typography.md#classes) for usage docs!
