### ISSUE TITLE
[mwc-textfield] add name property to input

### ISSUE THREAD

**Issue by fernandopasik** [material-components/material-web#1052]
**Is your feature request related to a problem? Please describe.**
Want a way to put a name property into the `input` element inside the textfield so a wrapping form can access it

**Describe the solution you'd like**
Have the `name` property and forward it to the input element

**Describe alternatives you've considered**
To use the textfield I've selected the `mwc-textfield` elements manually and extracted the value property

**Comment by fernandopasik** [comment]
Looking at this issue a bit more, I realize that since the input is in shadow dom, a wrapping form element won't be able to see this in the `FormElement.elements` property.

Is it in consideration to append the input through light dom? That would make the input element accessible from a wrapping form element.

**Comment by dfreedm** [comment]
Related #289

**Comment by fernandopasik** [comment]
I think this one can be closed as it's now in the new text-field component
https://github.com/material-components/material-web/blob/master/textfield/lib/text-field.ts#L140
