### ISSUE TITLE
mwc-checkbox inside mwc-dialog has misaligned mouseover highlight

### ISSUE THREAD

**Issue by CaptainCodeman** [material-components/material-web#1054]
**Describe the bug**
The mouseover highlight for the mwc-checkbox is misaligned when it's inside an mwc-dialog

**To Reproduce**
Render the checkbox inside a dialog, e.g.:
```js
  render() {
    return html`
      <mwc-dialog heading="Edit Permission">
        <div>
          <mwc-formfield label="Admin">
            <mwc-checkbox ?checked=${this.isAdmin}></mwc-checkbox>
          </mwc-formfield>
        </div>
        <mwc-button dialogAction="ok" slot="primaryAction">ok</mwc-button>
        <mwc-button dialogAction="cancel" slot="secondaryAction"> cancel </mwc-button>
      </mwc-dialog>
    `
  }
```

**Expected behavior**
The mouseover highlight should be the same as the ripple

**Screenshots**
![Screen-Recording-2020-03-31-at-9](https://user-images.githubusercontent.com/304910/78043869-1e781780-7331-11ea-9cec-961bce6e7630.gif)

**Browser Version (please complete the following information):**
Chrome 80

**Additional context**
Checkbox highlight works normally when not in the dialog, no styling is applied to the dialog or the checkbox. Once clicked, the highlight appears correct. Same behavior regardless of whether mwc-formfield is used.

**Comment by dfreedm** [comment]
Hmm, this might be fixed by the new checkbox I have in master. Will repro with that and confirm either way.

**Comment by dfreedm** [comment]
Related #1032

**Comment by dfreedm** [comment]
This apparently is an upstream issue as well https://github.com/material-components/material-components-web/issues/5443

**Comment by Misiu** [comment]
@dfreedm in upstream issue there is a fix: https://stackblitz.com/edit/mdc-dialog-ripple-alignment-eoogdd?file=index.js
proposed by @asyncLiz here: https://github.com/material-components/material-components-web/issues/5443#issuecomment-572716990
any ideas on how to fix this here?

**Comment by asyncLiz** [comment]
Fixed in M3
