### ISSUE TITLE
Add support for arbitrary attributes to be added to form controls

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-web#1058]
## Description

Users need to add some corner-case attributes to certain form controls, such as form submission attributes like `required` and text input specific attributes like `validity`.

## Acceptance criteria

MWC exposes a way for users to add arbitrary attributes (likely via a LitElement decorator)

**Comment by e111077** [comment]
Also Ariiiaaa????!?

**Comment by YonatanKra** [comment]
@dfreedm 
Are you working on this one?
We have a need for this feature.
Our needs at the moment is:`form`, `name`, `required`
Is there an open PR for this? If not, would you be interested in one?

**Comment by e111077** [comment]
Hello, this is an issue Epic that is tracking other issues. This Epic and it's related issues are currently iceboxed as we are currently working on getting our components to work with internal tooling to support future SSR capabilities. This unfortunately requires very specific, declarative syntax, so we are currently looking at how we can solve this at the lit-html and lit-element level.

Several ideas have been proposed and deliberated here if you'd like to follow along:

Polymer/lit-html#1182
