### ISSUE TITLE
Add dismissable items for list

### ISSUE THREAD

**Issue by kenchris** [material-components/material-web#1061]
This is a common pattern on mobile and would be nice with "native" support.

I have written such code a couple of times and some can be found here (feel free to reuse) https://github.com/kenchris/webnfc-groceries/blob/master/src/dismissable-item.js

Add a few items and test it here https://kenchris.github.io/webnfc-groceries/

**Comment by dfreedm** [comment]
We'll need some investigation into what "gestures" the Material spec wants for dismissing items, but this does seem useful.
