### ISSUE TITLE
Introduce a timer mocking utility to tests

### ISSUE THREAD

**Issue by 43081j** [material-components/material-web#1066]
In #1024 Sinon has been dropped. However, this lead to us stubbing `setTimeout` manually for the components which have time-based propagation (e.g. menu). 

We should clean this up a little by either introducing a small util which can be reused to stub `setTimeout`, or by introducing a dependency which does this for us. 

Keep in mind I tried sinon's fake timers module originally but I think their bundle causes problems in our build.

**Comment by asyncLiz** [comment]
Fixed in M3
