### ISSUE TITLE
No way to theme icon-button, icon-button-toggle colors

### ISSUE THREAD

**Issue by arthurevans** [material-components/material-web#1067]
**Is your feature request related to a problem? Please describe.**
There's no way to theme icon buttons. As the docs say, you can set the `color` property on them, but that doesn't work if the icon button itself is inside shadow DOM (for example, used inside a custom web component).

**Describe the solution you'd like**
Add a custom property to set the icon color for icon buttons.

**Describe alternatives you've considered**
You can set `color` separately in every scope...

**Additional context**
Possibly related: https://github.com/material-components/material-components-web/issues/5699

**Comment by asyncLiz** [comment]
Fixed in M3
