### ISSUE TITLE
mwc-tab --mdc-icon-size doesn't update icon container

### ISSUE THREAD

**Issue by mbinette** [material-components/material-web#1071]
**Describe the bug**
You can set the --mdc-icon-size but that only changes the font size of the Material Icons. The container it is in still has a width and height of 24px no matter what. This cause the icon to either be too big and overlap the tab text or too small and not be centered next to the text.

**To Reproduce**
1. Using `<mwc-tab icon="flag">`, set mwc-tab { --mdc-icon-size: 48px; }
2. The icon is bigger than the space allowed.
3. Using `<mwc-tab icon="flag">`, set mwc-tab { --mdc-icon-size: 8px; }
4. The icon is not centered and the space for the icon is still 24px x 24px

**Expected behavior**
The container the icon is in also changes size to match the setting and stays centered.

**Screenshots**
Set to 48px:
![image](https://user-images.githubusercontent.com/1036991/78282303-0b5c7780-74ea-11ea-9651-ed54b61c02eb.png)

Set to 8px:
![image](https://user-images.githubusercontent.com/1036991/78282365-27601900-74ea-11ea-8407-d9ee3047197b.png)

**Comment by asyncLiz** [comment]
Fixed in M3
