### ISSUE TITLE
Can't override button ripple color

### ISSUE THREAD

**Issue by arthurevans** [material-components/material-web#1102]
**Describe the bug**

Create an `mwc-button` and set `--mdc-theme-primary` and `--mdc-ripple-color` to different values. The ripple shows up as the primary color.

I think it's not working inside `mwc-button` because it has `primary` set on the ripple.

The docs for `primary` say: "When true, sets the ripple color to --mdc-theme-primary. Will be overridden by --mdc-ripple-color if set." But that doesn't match what I'm seeing.

**To Reproduce**

1. Go to https://glitch.com/edit/#!/zinc-leather-termite?path=index.css:1:0
2. Click on the outlined button or text button. Observe the ripple color.

**Expected behavior**
Ripple color should be red.

**Comment by dfreedm** [comment]
Oh duh, I need to remove the usage of `.primary` on the ripple in button and set the color in `:host` instead.

**Comment by dfreedm** [comment]
This is also the case for `disabled`.
