### ISSUE TITLE
[Textfield] Add forced LTR input

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-web#1145]
## Description
When textfield supports RTL, we need to add support for MDC's `mdc-text-field--ltr-input` class, which forces the input/prefix/suffix to be LTR-aligned. This is useful for RTL languages such as Hebrew that use LTR notation for fractions.

See https://github.com/material-components/material-components-web-components/issues/858

## Acceptance criteria
A textfield in a RTL language with a fractional numerator value and suffix denominator value should appear as LTR when this flag is true.

**Comment by david-curtis** [comment]
I honestly think this a bit higher than a low serverity (for all of us developing apps for an international client base).

Appreciate all the hard work on this.

**Comment by asyncLiz** [comment]
We hear you! Unfortunately we cannot do anything about this until textfields fully support RTL. Having a forced LTR mode is a bit moot.

#858 is tracking that support with a higher priority.

**Comment by asyncLiz** [comment]
Fixed in M3
