### ISSUE TITLE
mini + extended mwc-fab

### ISSUE THREAD

**Issue by govis** [material-components/material-web#1232]
An <code>extended</code> fab appears to be ignoring the <code>mini</code>attribute and remains 48px tall:

![image](https://user-images.githubusercontent.com/971651/80541346-ffdd5e80-8978-11ea-8f24-caed6b9e6b42.png)

It would be useful to be able to make it <code>mini</code> (40px tall):

![image](https://user-images.githubusercontent.com/971651/80541415-1edbf080-8979-11ea-8890-ad8e1ec8c21a.png)

**Comment by e111077** [comment]
Hello, I was speaking to the design team and they think extended is incompatible with mini. Do you have any context on where you would be using it?

**Comment by govis** [comment]
We use it at the bottom of the page to load more items. Need something more subtle as full sized is a bit too heavy. 

All that's needed is to switch the order css <code>height</code> property is applied - first on <code>.mdc-fab--extended</code> and then on <code>.mdc-fab--mini</code>

**Comment by govis** [comment]
Also, if extended can only affect the width and mini in this case the height - why would they be incompatible?

**Comment by e111077** [comment]
Passed your info along. By incompatible I think the designers mean with the design meaning of mini.

**Comment by asyncLiz** [comment]
This may also be related to density, since this is more related to a "dense" extended FAB instead of an extended mini FAB, which we don't have design guidance for.

We'll put this in our backlog for now until we get more guidance from design on how FAB should handle density.

**Comment by govis** [comment]
Like the Customize fab on the default Chrome page

![image](https://user-images.githubusercontent.com/971651/91624801-5337db80-e970-11ea-843b-87298fd3fc10.png)

**Comment by e111077** [comment]
Soon we will be updating fab to use design tokens which should handle this case. There will be a new custom property to handle fab-extended-height

**Comment by asyncLiz** [comment]
Fixed in M3
