### ISSUE TITLE
Convert components with variants to a common `variant=".."` API

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#1267]
**Is your feature request related to a problem? Please describe.**

certain components like button and fab have properties with incompatible variant apis. e.g.

`<mwc-button outlined raised>`

An outlined button cannot be raised

**Describe the solution you'd like**

`<mwc-button variant="outlined">` and `<mwc-button variant="filled-raised">`

same goes for fab extended and mini and standard

**Comment by PaulHMason** [comment]
Is this still the preferred way of implementing variants (value attributes). The main readme.md seems to indicate that the variants will become separate components?

**Comment by e111077** [comment]
Yeah, we decided to go with separate components due to how google's internal build visibility system works as well as internal metrics and tracking across google teams.
