### ISSUE TITLE
Icon button toggle currently ignored/skipped by some AT

### ISSUE THREAD

**Issue by patrickhlauke** [material-components/material-web#1286]
**Describe the bug**
Only tested in iOS/VO/Safari, but possibly happens in others too: the current icon button toggles are completely skipped when navigating through the page with VoiceOver. This is likely due to the fact that they have an empty `aria-label=""` defined (and VO's heuristics decide to skip it altogether)

**To Reproduce**
1. Go to the icon button section on the demo page https://mwc-demos.glitch.me/ with VO running
2. Using swipe gestures (swipe left/right), try to set focus on one of the icon button toggles
3. Note that the buttons are completely skipped

**Expected behavior**
The icon buttons should be reachable (and then, obviously, operable) when navigating with VO

**Browser Version (please complete the following information):**
 - OS: iOS 13
 - Browser: Safari (and all other webview-based browsers on iOS)

**Comment by e111077** [comment]
This seems to be because we never set `label="..."` in the demo. Though mwc-icon-button auto-labels with the icon name but not icon-button-toggle.

@dfreedm mind bunching this up with your L2W work? Perhaps if no label is defined set it to the active icon like icon-button does

**Comment by asyncLiz** [comment]
Fixed in M3
