### ISSUE TITLE
Top App Bar custom colors affect all content within

### ISSUE THREAD

**Issue by dborstelmann** [material-components/material-web#1298]
```
mwc-top-app-bar-fixed {
  --mdc-theme-primary: orange;
}
```

This code flows through all children, it would be nice if customizing the header didn't affect the whole app.

**Comment by e111077** [comment]
This is gross :/ but a workaround for now would be to simply not put your app content inside the top-app-bar but below it. See our demo on glitch which does this:

https://mwc-demos.glitch.me/

Workaround -> decreasing severity
