### ISSUE TITLE
mwc-textfield type date spinner alignment incorrect

### ISSUE THREAD

**Issue by antwonthegreat** [material-components/material-web#1307]
**Describe the bug**
In chrome, mwc-textfield with type="date" displays up and down spinner buttons on hover/focus. These buttons do not line up with the date, drop arrow, or icons. This doesn't seem to be a bug when the textfield is filled.

**To Reproduce**
1. Modify any of mwc-textfield's in the demo (except the filled ones) to have type="date"
2. Hover or focus on the textfield.

**Expected behavior**
spinner buttons should align with other elements in the row

**Screenshots**
![mwc-textfield](https://user-images.githubusercontent.com/5438655/81739228-31195c80-9458-11ea-9045-870d55fe32d9.PNG)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 80.0.3987.163 

**Additional context**
Seems to have broken in 0.15.0 
Can confirm it is not an issue in 0.14.1

**Comment by asyncLiz** [comment]
Addressed in M3, though keep in mind that date text field types aren't fully supported.
