### ISSUE TITLE
mwc-select shadow DOM width does not expand to fill element width

### ISSUE THREAD

**Issue by ForestKatsch** [material-components/material-web#1312]
**Describe the bug**
The shadow DOM inside of an `mwc-select` element does not expand to fit the `mwc-select` width.

**To Reproduce**
1. Go to https://material-components.github.io/material-components-web-components/demos/select/
2. Inspect element on an `mwc-select` and make sure you have the `mwc-select` web component active.
3. Add the CSS rule `width: 500px !important`

**Expected behavior**
The children of `mwc-select` (the actual selector itself, and the menu) are 500px wide.

**Screenshots**
<img width="536" alt="Screen Shot 2020-05-13 at 11 34 50 AM" src="https://user-images.githubusercontent.com/42914657/81851073-c32f6c80-950d-11ea-87d2-12c3bb86963d.png">

**Browser Version (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Chrome 81.0.4044.138 and Safari 13.1 (15609.1.20.111.8)
 - MWC version: 0.15.0

**Additional context**
Setting `mwc-select` width worked at one point.

This can be resolved for me by adding the CSS rule `width: 100%` to `<div class="mdc-select">`.

**Comment by aarondrabeck** [comment]
Adding the "fullwidth" attribute fixes this behavior as a workaround.

**Comment by e111077** [comment]
Seems like we are missing some prop docs on this when this change was implemented, though, it's working as intended
