### ISSUE TITLE
FormElement: handling click events in test automation (e.g. webdriver, geckodriver)

### ISSUE THREAD

**Issue by 43081j** [material-components/material-web#1349]
I noticed inside form elements we have a `click()` method to propagate the click to the child input:

https://github.com/material-components/material-components-web-components/blob/5fe61f4e98ef338aa0189cd75504d629d98fde53/packages/base/src/form-element.ts#L49-L54

This is pretty useful, but it doesn't cover events. If you dispatch a click event, for example, to an mwc-checkbox, it will not be handled and will not check the box.

I guess all form elements should listen (in FormElement) for click events and propagate that state downwards?

This conveniently isn't a problem for humans as when we click an mwc-checkbox, we are actually clicking the inner input. However, for testing, it means right now we would have to penetrate the shadow dom and dispatch events directly to the input instead of the component its self.

**Comment by asyncLiz** [comment]
This isn't actually how events work natively. Dispatching an event on an element will not trigger its native functionality.

See this example: https://jsbin.com/kupegadife/edit?html,output

For testing, the intention should be to call the native method, such as `.focus()` or `.click()`. The element should dispatch events in response calling those functions.

Can you give an example test use case where calling `.click()` does not give the desired result, but dispatching a click event in a pierced shadow dom does?

**Comment by 43081j** [comment]
I'm aware, but this isn't what I meant.

This **is** how most test automation software works (cypress, webdriver, any selenium implementation, pick one).

The point here is mwc-checkbox should be listening on click of `this`, _not_ the inner input. Test automation software simulates clicks by firing the equivalent events to the elements being interacted with.

If a test "clicks" an mwc-checkbox, it is not aware there is an inner input, so it will fire the event on the mwc-checkbox directly. Currently, this event will go ignored and nothing will happen.

Test automation software generally doesn't work the way you wish it did, it works by firing events on elements to simulate user interaction. 

I have put plenty of work into adding shadow dom support to most of these projects, but they won't all have it any time soon so this is a good catch-all solution. In reality, it is true that the test software should know to penetrate the shadow boundaries to the deepest target and "click" that, but it doesn't right now.

**Comment by asyncLiz** [comment]
Hm, I understand a bit better now. I'll update the issue title to better reflect the problem and bring it up with the team in our triage meeting.

I'm pretty confident we don't want to bubble events down since that'd be a bit of an anti-pattern. The only solution I could think of right now would be to listen to bubbling events on the host element instead of directly on children.

That does introduce problems though, especially with elements that have multiple children that dispatch the same event type. We'd need to distinguish between events. It's possible, but it's a performance trade-off that might not be worth it to support testing.

On top of that though, if a component does have multiple click targets, how do you specify which click target is emulated in webdriver?

**Comment by 43081j** [comment]
The one true solution to all this isn't anything on your end really. It's to get all test runners to penetrate shadow dom and emit events directly on the deep element being interacted with at that position. 

But these projects are slow at implementing this unfortunately. 

So my thought was, for simple components like the check box at least, we listen on `this` for the events bubbling up to change our state. But you're right, for more complex elements it would just be a pain. 

Maybe this is a non issue and should just be fixed in the test software

**Comment by asyncLiz** [comment]
We'll keep this issue open for now, but this might be a bit out of scope for what we're able to do in this project for the near future.

We'd be interested in getting some support from the testing and webdriver communities to find solutions and ideas on how best to integrate mocking interactions with web components and shadow dom.

**Comment by asyncLiz** [comment]
This should be addressed with our new M3 test harnesses
