### ISSUE TITLE
mwc-tab[disabled]

### ISSUE THREAD

**Issue by bennypowers** [material-components/material-web#1410]
**Is your feature request related to a problem? Please describe.**
Much like I can disable an item in a list
```html
<mwc-select>
  <mwc-item disabled>Nope</mwc-item>
</mwc-select>
```

**Describe the solution you'd like**
I'd like to be able to disable a tab in a tab bar
```html
<mwc-tab-bar>
  <mwc-tab disabled label="uh-uh"></mwc-tab>
</mwc-tab-bar>
```

**Describe alternatives you've considered**
`event.preventDefault()` on the `MDCTabBar:activated` does not prevent tab selection from changing, so I'm doing this instead, which does not visually disable tabs, or prevent them from momentarily becoming active:

```ts
  onTabBarActivated(event: ActivatedEvent): void {
    const { detail: { index } } = event;
    // HACK: fake `disabled` tab
    if (index !== 1) {
      event.preventDefault();
      event.target.activeIndex = 1;
      return;
    }
    // update state store as appropriate...
  }
```
```ts
type ActivatedEvent = CustomEvent<{ index: number }> & { target: TabBar };
```

**Comment by mahdiridho** [comment]
Yeah, I need this feature as well. I want to use tabs for progress steps. So the tabs should be disabled and there will be next/prev button to change the tab activated index.

**Comment by mahdiridho** [comment]
I'm using this approach for now :

`
mwc-tab-bar {
  pointer-events: none
}
or
mwc-tab {
  pointer-events: none
}
`

**Comment by maicol07** [comment]
Another fix (JS fix):

Navigate inside the shadow root and disabledirectly the tab button:

```javascript
tab.shadowRoot.firstElementChild.disabled = true;
```

`tab` is the `<mwc-tab>` DOM element

**Comment by asyncLiz** [comment]
Tabs are now [disable-able](https://github.com/material-components/material-web/blob/6aa42f3399e9b8433a6920a6e6779d16a0c55cce/tabs/internal/tab.ts#L53) in M3

**Comment by lupodellasleppa** [comment]
looks like they [are no more](https://github.com/material-components/material-web/blob/main/tabs/internal/tab.ts)

EDIT: looks like the [current spec](https://m3.material.io/components/tabs/guidelines) doesn't even consider disabled tabs, though it doesn't speak of an alternative either

**Comment by asyncliz** [comment]
They were removed in https://github.com/material-components/material-web/commit/d18db2a6acb90a059856fbf74e8c2212f7680a68 after receiving design feedback that tabs should never be disabled in Material Design.
