### ISSUE TITLE
CSS Variable for Disabled Textfields and Textareas

### ISSUE THREAD

**Issue by ghost** [material-components/material-web#1444]
**Is your feature request related to a problem? Please describe.**
Disabled textareas and fields have a hard-coded background-color of #fafafa 
`:host([disabled]) .mdc-text-field:not(.mdc-text-field--outlined) {
     background-color: #fafafa;
}`

**Describe the solution you'd like**
Introduce a new CSS variable covering theming of disabled textfields and textareas for customization needs

**Comment by ronnyMichaleck** [comment]
✓

**Comment by asyncLiz** [comment]
Currently blocked by https://github.com/material-components/material-components-web/issues/5784

**Comment by asyncLiz** [comment]
Fixed in M3
