### ISSUE TITLE
mwc-select, preselected value is not shown "rendered" inside the component

### ISSUE THREAD

**Issue by josemsantos** [material-components/material-web#1493]
**Describe the bug**
If the selected attribute is set in one of the mwc-list-item, inside the mwc-select, you can clearly see that the label goes up but no value is rendered as selected.
If I try to select an item dynamically using the .select() method it works correctly.

**To Reproduce**
1. Add a new mwc-select component
2. set one of the child mwc-list-item with the selected attribute
3. Load the page
4. See that the label was moved up but no value was rendered

**Expected behavior**
The Selected Content should be rendered when an item has the selected attribute

**Screenshots**
![mwc-selected](https://user-images.githubusercontent.com/6525414/86599096-11a13a80-bf96-11ea-8da8-b9eb88cfb25a.png)
![mwc-selected-2](https://user-images.githubusercontent.com/6525414/86599107-16fe8500-bf96-11ea-8320-c70b54396f02.png)

**Browser Version (please complete the following information):**
 - OS: Ubuntu 2004
 - Browser chrome 81.0.4044.138
 - Version 0.17.2

**Additional context**
None

**Comment by dfreedm** [comment]
Can't seem to reproduce with a simple JSBin: https://jsbin.com/fimoxixacu/edit?html,output

Can you modify that example to demonstrate what you're seeing?

**Comment by josemsantos** [comment]
Hello,

I've tested the JSBin and it works in my browser then I took your example into my project.
I've added the 3 imports to my main HTML layout and removed all other JS and it worked as expected.

So I can only assume the issue is coming from my **rollupJS setup**.
I've created a simple **component.ts** file and added there all the imports like this

```
import '@material/mwc-list';
import '@material/mwc-list/mwc-list-item';
import '@material/mwc-select';
```
I tried a simple rollupjs setup like this

```
export default {
  input: ['client/js/components.ts'],
  output: {
    file: 'public/js/main.min.js',
    format: 'es',
    sourcemap: false
  },
  plugins: [
    commonjs(),
    typescript({
      tsconfigOverride: { 
        compilerOptions : {
          module: "es2015",
        }, 
        experimentalDecorators: true 
      },
      useTsconfigDeclarationDir: true,
      clean: true
    }),
    resolve({
      extensions: ['.js', '.ts', '.json' ]
    }),
    copy({
      targets: [
        {
          src: `public/js/main.min.js`,
          dest: `dist/public/js/main.min.js`,
        }
      ]
    })
  ],
};
```

In Chrome, this setup causes the issue I've reported, the selected item is not rendered in the select slot.
I've also tested in Firefox and it is working correctly.

So I decided to kinda copy from the one in this repo to something like this
```
export default {
  input: ['client/js/components.ts'],
  output: {
    file: 'public/js/main.min.js',
    format: 'iife',
    sourcemap: false
  },
  plugins: [
    commonjs(),
    typescript({
      tsconfigOverride: { 
        compilerOptions : { 
          target: "es2017",
          module: "es2015",
          lib: ["es2017", "dom", "dom.iterable"],
          declaration: true,
          sourceMap: true,
          inlineSources: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
          experimentalDecorators: true,
          skipLibCheck: true,
          noImplicitAny: false,
          composite: true,
          importHelpers: true,
        }, 
        experimentalDecorators: true 
      },
      useTsconfigDeclarationDir: true,
      clean: true
    }),
    resolve({
      extensions: ['.js', '.ts', '.json' ]
    }),
    terser(),
    strip({
      functions: ['console.log'],
    }),
    babel({
      presets: [['@babel/preset-env', {modules: false}]],
      plugins: ['@babel/plugin-transform-runtime'],
      babelHelpers: 'runtime'
    }),
    copy({
      targets: [
        {
          src: `public/js/main.min.js`,
          dest: `dist/public/js/main.min.js`,
        }
      ]
    })
  ],
};
```
I got the same result, in Chrome the mwc-select doesn't render the selected element, but in Firefox it works well.
I eventually updated Chrome to the latest version and still happens.

**Comment by asyncLiz** [comment]
Can you provide us a Glitch reproduction using this rollup config that shows the problem?

**Comment by e111077** [comment]
Hello we have not been able to reproduce this issue; we are going to close this issue, but if you're able to provide a live example we will reopen this issue for further debugging

**Comment by josemsantos** [comment]
Hello,

Find here a Glitch reproduction of the issue
https://ribbon-wary-niece.glitch.me

The Source code
https://glitch.com/~ribbon-wary-niece
https://glitch.com/edit/#!/join/3390c361-213b-4960-b757-3b3b1044c226

**Comment by fref** [comment]
Is there any progress on this?
This makes the composent half-useless on Chrome (seems fine on Firefox though)

**Comment by fref** [comment]
Note that if one does modify the uwc-select.value property via the console, after it was rendered, the select value is rendered properly.

**Comment by e111077** [comment]
No progress yet. Haven't had a good time to just sit down and tackle this. It seems as if the components are being appended to the dom before the innerText is set. It seems like it might be build related but parsing es5 binaries is not a quick task - especially with a component like select.

I believe in the meantime you can call mwc-select.layout()

**Comment by fref** [comment]
Unfortunately, that doesn't seem to work. I just tried in the console, this just returns:

Promise {<fulfilled>: undefined}__proto__: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: undefined

**Comment by fref** [comment]
I can vaguely reach something by saving the current value, setting the value to null, then resetting the old saved value (but this only works with a delayed operation).
This is a workaround, but a fix would be better.

**Comment by fref** [comment]
And of course, this triggers any behaviour linked to changes onto the select :/

**Comment by e111077** [comment]
We have progressed to find a smaller repro of the issue. It seems as if there is a rare case where the webcomponent lifecycle does not finish projecting the contents inside a component's slot at the appropriate time. In the meantime, the `layoutOptions` method should provide a workaround:

#2209

**Comment by asyncLiz** [comment]
This is fixed in M3
