### ISSUE TITLE
textfield outlined label error shake does not shake

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#1495]
**Describe the bug**

when the floating label is supposed to shake on an outlined textfield, it instead quivers.

**To Reproduce**

1. set outlined and type="email" label="qwerty" on a textfield
2. type "asdf" into the textfield
3. unfocus
4. observe the quiver

**Expected behavior**

label is supposed to shake dat thing

**Screenshots**

it's an animation, yo

**Browser Version (please complete the following information):**
 - OS: allofem
 - Browser: the current ones
 - Version: this one

**Comment by asyncLiz** [comment]
No more shake-y shake in spec
