### ISSUE TITLE
mwc-top-app-bar disappears in a lazy-loaded page

### ISSUE THREAD

**Issue by govis** [material-components/material-web#1513]
**Describe the bug**
mwc-top-app-bar  does not appear to initialize properly in a page that's initially <code>display: none;</code> and later becomes visible upon navigation to it. In such case <code>topAppBarHeight_</code> property is set to 0 causing it to disappear when page starts scrolling

**To Reproduce**
1. Go to https://typescript-sanmxq.stackblitz.io/
2. Click on 'Add item' until vertical scroll bar appears
3. Scroll down less then the height of the app bar
4. See the app bar disappear

**Expected behavior**
App bar is partially visible

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/971651/87090474-0eac8100-c206-11ea-8a2f-2cce99dc70ff.png)

Expected:
![image](https://user-images.githubusercontent.com/971651/87090619-461b2d80-c206-11ea-9ad7-1c3d623c5591.png)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 83.0.4103.116

**Additional context**
topAppBarHeight_ is set to 0 in MDCTopAppBarFoundation function
currentAppBarOffsetTop_ is then set to -topAppBarHeight_(96) in MDCTopAppBarFoundation.handleTargetScroll function, which causes it to collapse completely when it should still be visible

**Comment by dfreedm** [comment]
Yep, there are a few components that need to measure on render to layout correctly, or you get _this_.
We usually have a `layout()` method on the component for you to call when you make the container visibile, but I may need to add one.
Either way, I'll make sure to add this to the docs!

**Comment by govis** [comment]
There's no <code>layout()</code> method in the mwc-top-app-bar. Is there any other way to fix it?

**Comment by iMrDJAi** [comment]
I had the same problem with the MDCTopAppBar.

**Comment by asyncLiz** [comment]
Obsolete with M3
