### ISSUE TITLE
mwc-fab button color cannot be overridden in IE11.

### ISSUE THREAD

**Issue by kaseyhinton** [material-components/material-web#155]
mwc-fab is not letting me override its color in IE11. 

It is stuck on the default teal. This is how i am currently overriding it and it seems to work in other browsers.
```css
--mdc-theme-secondary:  #3B95FF;
```

**Comment by kaseyhinton** [comment]
I am currently using a polyfill for them and my other CSS variables are working correctly in IE.

**Comment by azakus** [comment]
Related to https://github.com/material-components/material-components-web/issues/3685

**Comment by asyncLiz** [comment]
IE11 is no longer supported
