### ISSUE TITLE
`close` and `cancel` events for dialog and snackbar

### ISSUE THREAD

**Issue by bennypowers** [material-components/material-web#1583]
**Is your feature request related to a problem? Please describe.**
Consider the case of a `<pwa-update>` element, which defines a UI for the popular "click to update" pattern in PWAs

```html
<pwa-update>
  <dialog slot="notifyer">
    <form method="dialog">
      <p>App Updated</p>
      <button type="submit" value="reload">OK</button>
      <button type="submit" value="cancel">Cancel</button>
    </form>
  </dialog>
</pwa-update>
```

The authors of `<pwa-update>` would like to give users flexibility to put any dialog implementation in the `notifyer` slot, including `<mwc-dialog>` and `<mwc-snackbar>`

By adopting the standard interface of `<dialog>`, in addition to the custom APIs already present, users could more easily use the material components as drop-in replacements.

`HTMLDialogElement` fires `close` and `cancel` events depending on how it was interacted with. `Dialog` and `Snackbar`, however, fire `closing` and `closed` events. By implementing the `close` and `cancel` events as well, `Dialog` and `Snackbar` could function as drop-in replacements for `HTMLDialogElement`.

**Describe the solution you'd like**
Dialog and Snackbar should implement `close` and `cancel` events in addition to the existing `closing` and `closed` events. It's open to discussion when in the lifecycle `close` and `cancel` should fire. An initial intuition suggests after non-default-prevented `closing` and before `closed`. 

**Describe alternatives you've considered**
Our aforementioned `<pwa-update>` authors would likely expose a JavaScript API to their element as an escape hatch, and for gluing in non-standard custom-elements, however, we'd prefer a "just works" composable solution using standard, class-agnostic interfaces.

Users could also write their own wrappers

```html
<pwa-update>
  <wraps-mwc-dialog-as-dialog slot="notifyer">
    <mwc-dialog>
      <form method="dialog">
        <p>App Updated</p>
        <button type="submit" value="reload">OK</button>
        <button type="submit" value="cancel">Cancel</button>
      </form>
    </mwc-dialog>
  </wraps-mwc-dialog-as-dialog>
</pwa-update>
```

But that seems to my mind a bit of a reach 

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement

**Comment by YonatanKra** [comment]
Hi @dfreedm and @e111077 .
I've created a PR for this for the`dialog` (#1697). Could you please check it?
I have no issue creating a PR for the same issue for the`snackbar` or adding the snackbar to this PR.
It's probably be the same technique.

**Comment by e111077** [comment]
forwent close in favor of closing + closed, and don't know how it will interact with the dialog interaction model. Though re-dispatched the cancel event
