### ISSUE TITLE
Add ability to define different box-shadow to the menu's menu surface

### ISSUE THREAD

**Issue by YonatanKra** [material-components/material-web#1614]
**Is your feature request related to a problem? Please describe.**
We have our design guidelines and one of them is to set different box-shadow properties to the menu's surface.

**Describe the solution you'd like**
Expose a css variable like `mdc-shape-medium` is exposed. Might call it `-mdc-shape-box-shadow`.

**Describe alternatives you've considered**
None.

**Comment by dfreedm** [comment]
This should come eventually with a full rollout of https://github.com/material-components/material-components-web/issues/5242.

I don't know what the name of the CSS Custom Property will be, but it should be something descriptive for box-shadow.

**Comment by YonatanKra** [comment]
@dfreedm would you like me to take this one?

**Comment by asyncLiz** [comment]
Obsolete with M3
