### ISSUE TITLE
[TopAppBar] Super Dense Variant / Custom Height

### ISSUE THREAD

**Issue by aress31** [material-components/material-web#1768]
**Is your feature request related to a problem? Please describe.**
Right now, the `top-app-bar-(fixed)` is quite rigid in the way that it is hard to customise to fit various common front-end dev cases. I understand that MWC follows the `Material Design` specs and that the specs is not flexible, however, the lack of flexibility when it comes the `top-app-bar` makes the app layout and customisation process a pain. I also understand that you may advise to just hardcode a different top-app-bar container but that would defeat the purpose of using the MWC library to build the application from top to bottom.

This feature would allow web devs to easily design top application bands to display let's say contact information, social medias follow, etc.

**Describe the solution you'd like**
What I suggest is to either implement a `superDense` variant of this the `top-app-bar-(fixed)` of let's say `32px` height or even better to allow web dev to arbitrarily set the `height` of the `top-app-bar-(fixed)`, this would really boost the customisation possibilities of this component and would be a useful complement for the already customisable `width`.

This would allow to create quite common layouts like:
![image](https://user-images.githubusercontent.com/11601622/92328066-337e7280-f056-11ea-90d3-8010463e690d.png)

**Describe alternatives you've considered**
Totally ditching the `top-app-bar-(fixed)` and implement my own component which unfortunately will most likely not match the `Material Design specs`, will not be able to be customised using the same `CSS vars`, will hardly work the `MDC Drawer` and would look totally off compared to rest of my application which is built a 100% using MWC.

**Comment by e111077** [comment]
This seems to be a mix of #781 and #841
