### ISSUE TITLE
[MWCList] Implement list group subheaders

### ISSUE THREAD

**Issue by aress31** [material-components/material-web#1770]
Could you consider adding a property to either `mwc-list` or `mwc-list-item` to set a title to the list - with customisable typography for the title.

See the following list example, with `Company` just being a `<h3>` tag, this title should I believe be part of the list and not a separate tag.

![image](https://user-images.githubusercontent.com/11601622/92340856-bbdf3080-f0b3-11ea-8797-aaf49244760b.png)

**Comment by e111077** [comment]
Why is it not possible to do the following? Does this not fit the need?

```
<mwc-list>
  <mwc-list-item noninteractive class="title">Company</mwc-list-item>
  <mwc-list-item>About</mwc-list-item>
  <mwc-list-item>Contact</mwc-list-item>
</mwc-list>
<style>
  .title {
    font-weight: bold;
    font-family: sans;
    margin-bottom: 8px;
  }
</style>>
```

**Comment by aress31** [comment]
It is possible to do that indeed, but I just thought that similarly to the `React Material UI` library you would want to differentiate the title from the items by setting a title `slot` or `prop` on the `mwc-list`.

**Comment by e111077** [comment]
I think that would be a bit extraneous. Additionally, you can also just slot in an h3 without a list item, but you don't get the nice material styling. THOUGH, the material guidance does seem to have a concept of a title-like section for a list linked in the image below (1 and 3). Do you mind upstreaming the implementation of list titles to the MDC library?

![image](https://user-images.githubusercontent.com/5981958/92521682-7cf3cc80-f1d2-11ea-9340-de0627381a07.png)

**Comment by e111077** [comment]
please also leave the issue number here, it would be super helpful

**Comment by aress31** [comment]
https://github.com/material-components/material-components-web/issues/6460

**Comment by asyncLiz** [comment]
This is available to be implemented as [list groups subheaders](https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#list-groups)
