### ISSUE TITLE
Select SVG Leading Icon Support

### ISSUE THREAD

**Issue by aress31** [material-components/material-web#1812]
I am in the process of implementing a language switch using the `mwc-select` component. My goal is to add as a left icon the flags for the supported languages. I downloaded a pack of `SVG flags` but I cannot use them with `mwc-select` component...

Could you please consider supporting custom SVG icons (strings) for the MWC components using icons?

Edit: considering supporting SVG using their URLs too would be great!

**Comment by asyncLiz** [comment]
Thanks for the issue! We'll add this to our backlog to track SVG support for select's leading icon.

**Comment by aress31** [comment]
Whilst thinking about this request feature, to cover more use cases that could be extended to both leading AND trailing icons.

**Comment by stucker71** [comment]
This indeed would  be a very useful feature

**Comment by aress31** [comment]
Is there an update or ETA for this feature?

**Comment by asyncLiz** [comment]
Available in M3 now
