### ISSUE TITLE
[mwc-icon-button] can't set ripple opacity

### ISSUE THREAD

**Issue by nadinetetz** [material-components/material-web#1819]
**Describe the bug**
If I create a `mwc-icon-button` and change the opacity of the ripple by setting `--mdc-icon-button-ripple-opacity` to `0.5` it doesn't have any effect. It is still `0.04`.

In the docs for the `mwc-icon-button` the default value of `--mdc-icon-button-ripple-opacity` is `0.12`. The default value of the `mwc-ripple` is `0.04`. (`--mdc-ripple-hover-opacity`)

**To Reproduce**
1. Create a `mwc-icon-button`
2. Set `--mdc-icon-button-ripple-opacity` to, for example, 0.5
3. Opacity of ripple is still 0.04 (default value of `--mdc-ripple-hover-opacity`)

See an example here: https://codesandbox.io/s/practical-elgamal-9jykk?file=/src/styles.css

**Expected behavior**
Opacity of ripple should be 0.5

**Browser Version**
 - OS: macOS Catalina 10.15.6
 - Browser: chrome
 - Version: 84.0.4147.135

**Comment by taylor-vann** [comment]
Hey @nadinetetz!

Thanks for reaching out.

You should be able to directly affect the mwc-ripple by following our [ripple theming](https://github.com/material-components/material-components-web-components/tree/master/packages/ripple) guide.

Unfortunately, `--mdc-icon-button-ripple-opacity` is no longer supported.

I'll add a bug and update the docs for mwc-icon-button.

I'll also add instructions to our theming docs to include mwc-ripple.

Sorry for the confusion and thanks for bringing this to our attention.

**Comment by nadinetetz** [comment]
Hi @taylor-vann !

Thanks for your help.

I’ve tried to set the opacity by following the ripple theming guide but it has no effect to the ripple of my `mwc-icon-button`.

See an example here: https://codesandbox.io/s/distracted-pare-ls29y?file=/src/styles.css

The color of the ripple should be red and the opacity should be 1.

**Comment by taylor-vann** [comment]
@nadinetetz you are correct. I don't think this is the intended behavior.

I will submit this as a separate bug.

Thank you for providing code examples btw, it's really explicit and helpful.

**Comment by asyncLiz** [comment]
This is possible now with M3 tokens
