### ISSUE TITLE
Ripple not working in Safari 13 and radius not being applied

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#1827]
**Describe the bug**

The ripple does not ripple on click on safari 13 and the ripple border radius doesn't seem to be applying

**To Reproduce**

1. Go to https://material-components.github.io/material-components-web-components/demos/fab/
2. Click on the white fab

**Expected behavior**

A ripple should ripple out and the secondary hover ripple should be bounded to the round button

**Screenshots**

Safari 13
![safari 13](https://user-images.githubusercontent.com/5981958/93636472-dc0ec980-f9a8-11ea-9b35-00101fa2f681.gif)

Safari 14
![Safari 14](https://user-images.githubusercontent.com/5981958/93636481-df09ba00-f9a8-11ea-84b5-38492786fdb3.gif)

**Browser Version (please complete the following information):**
 - OS: Mac OS 10.15.5
 - Browser Safari
 - Version 14.0, WebKit 15610.1.21.0.2 & 13.1.1, WebKit 15609.2.9.1.2

**Comment by asyncLiz** [comment]
b/168313305 for upstream internal issue

**Comment by Eduardogbg** [comment]
It may be related to this [question](https://stackoverflow.com/questions/49395464/ripple-effect-is-not-working-on-mac-browsers).
Focus on Safari apparently doesn't trigger focus

**Comment by asyncLiz** [comment]
Obsolete with new `<md-ripple>`
