### ISSUE TITLE
status of textfield/textarea readonly attribute

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#1882]
readonly attributes for textfield and textarea does not seem to be documented, although implemented as properties in codebase. 

A couple of questions: 
- should we not have `readonly` (instead of `readOnly`) as it is now (capitalized attributes makes things harder - for instance in Polymer templates; it would be consistent with native attribute): 
```html
<input
          aria-labelledby="label"
          class="mdc-text-field__input"
          type="${this.type}"
          .value="${live(this.value)}"
          ?disabled="${this.disabled}"
          placeholder="${this.placeholder}"
          ?required="${this.required}"
          ?readonly="${this.readOnly}"
```
- readonly textfield still animates label on focus (change of color + floating label), is this the expected behavior? (note that I am aware of `disabled` properties)
- According to the specs: " A read-only text field is styled the same as a regular text field and is clearly labeled as read-only.". Who's responsibility is that ? The component (like the * for required fields) or the application ? 

Thanks

**Comment by asyncLiz** [comment]
M3 text field has readonly now
