### ISSUE TITLE
mwc-slider: CSS rotation breaks the slider

### ISSUE THREAD

**Issue by stephenwade** [material-components/material-web#1894]
**Describe the bug**
If the `<mwc-slider>` element or a parent element is rotated with CSS, the user cannot click and drag the slider to change the value.

Example in CodePen: https://codepen.io/stephenwade/pen/PozqJKN

**To reproduce**
1. Apply the following CSS rule to `mwc-slider` or a parent element:
    `transform: rotate(90deg);`
1. Try to click and drag on the slider.

**Screenshot**
![GIF demonstrating the issue](https://user-images.githubusercontent.com/4148577/95684347-0fff9800-0bbf-11eb-9186-8d36ba1f199c.gif)

**Browser version**
 - OS: macOS 10.15.6
 - Browser: Chrome 85

**Comment by taylor-vann** [comment]
Hey @stephenwade!

Thanks for filing this bug.

Unfortunately we do not have planned support for a vertical slider.
But I will file a request for one!

**Comment by luccap11** [comment]
I have same problem. There is a workaround?

**Comment by asyncLiz** [comment]
Vertical sliders are not something the Material spec defines... but I checked and it seems to work with the new `<md-slider>` so closing as fixed

**Comment by asyncliz** [comment]
Last I checked, the new md-slider supported being rotated. Is it not working for you?
