### ISSUE TITLE
Provide fix for delegatesFocus issues in Safari 14

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-web#1908]
## Description
Safari 14 on Catalina has been broken with `delegatesFocus` for a while, with no updates from Apple.
Given the increasing reports of this issue, we should provide some workaround.

## Acceptance criteria
Provide a workaround, either built in or as a patch, for Safari 14 users and `delegatesFocus`

Related #1720

**Comment by asyncLiz** [comment]
No longer supporting Safari 14
