### ISSUE TITLE
mwc-textfield-base has mismatching lit-html dependency version

### ISSUE THREAD

**Issue by fxedel** [material-components/material-web#1915]
**Describe the bug**

The `mwc-textfield-base` package uses lit-html's `live` directive (see [mwc-textfield-base.ts#L32](https://github.com/material-components/material-components-web-components/blob/master/packages/textfield/mwc-textfield-base.ts#L32)), which was introduced by lit-html in version [1.2.0](https://github.com/Polymer/lit-html/releases/tag/v1.2.0). However, the `mwc-textfield-base` package has a lit-html dependency version of 1.1.2 (see [package.json#L27](https://github.com/material-components/material-components-web-components/blob/master/packages/textfield/package.json#L27)), so the needed `live` directive is not available when using the version specified in `package.json`.

**Comment by dfreedm** [comment]
Thanks for catching that!

**Comment by fxedel** [comment]
I just ran into that issue, because I had lit-html installed at 1.1.x and when I imported `mwc-textfield` there was an error at importing the `live` directory :wink:

**Comment by asyncLiz** [comment]
Obsolete with M3
