### ISSUE TITLE
mwc-select does not dispatch input event

### ISSUE THREAD

**Issue by bigjpg** [material-components/material-web#1936]
Based on this page: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event, a select should dispatch an input event when its value changes. Currently mwc-select only dispatches a change event. This causes problems for our forms which detect changes using the input event. This is especially relevant in the shadow dom because the input event is composed but the change event is not. So you can capture input events across shadow boundaries.

1. List for the 'input' event on a mwc-select component
2. Select a value

**Expected behavior**
An input event and a change event should be dispatched.

**Browser Version (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 86.0.4240.111 (Official B

**Comment by dgoogles** [comment]
The behavior I was looking for can be implemented by dispatching an input event whenever the mwc-menu dispatches an action event.

**Comment by e111077** [comment]
it's been a while since I've worked with select; does it still fire the `change` event? It may simply be undocumented

**Comment by dgoogles** [comment]
It fires a change event but not an input event. The change event isn't composed, so doesn't cross shadow boundaries.

**Comment by asyncLiz** [comment]
It does now!

https://github.com/material-components/material-web/blob/6aa42f3399e9b8433a6920a6e6779d16a0c55cce/select/internal/select.ts#L572
