### ISSUE TITLE
Insert components inside mwc-top-app-bar 

### ISSUE THREAD

**Issue by fuintis** [material-components/material-web#1965]
**Is your feature request related to a problem? Please describe.**
Can be really helpfull to add a component inside the mwc-top-app-bar one. At this moment its "only" possible to add a text using the "title" slot. When i try to add a mwc-select, the style has completly broken, hidding the floating list when i clicked over it.

**Describe the solution you'd like**
The mwc-top-app-bar component should support web components inside "title" slot (or a new one) to allow create top-app-bars like the Google Drive's one.

**Describe alternatives you've considered**
I was try to add all kind of custom components inside "title" slot. Some of these works pretty well (like mwc-button), but its more frequent that the style breaks inside the aforementioned slot.

**Additional context**
None.

**Comment by dfreedm** [comment]
I'll take a look to see what type of content should be allowed in the Top App Bar.
