### ISSUE TITLE
[Feature Request] mwc-snackbar configurable position

### ISSUE THREAD

**Issue by ManuelCalavera97** [material-components/material-web#1978]
Current snackbar implementation dosen't allow for any flexibility in terms of positioning. It's either leading or in the middle of the viewport.

If we have UI controls at the bottom of the page, the snackbar will just overlap it, which isn't ideal. The same goes if we have some kind of panel, be it on the right, or left.

Would be nice to have an option for the snackbar to be dependant not only from viewport, but from the parent component. Or at least to be able to control snackbar elevation.

**Comment by asyncLiz** [comment]
Thanks for the issue!

There are several [configurable styles from the MDC snackbar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar#sass-mixins) that we should expose a CSS custom properties, such as:

- `--mdc-snackbar-container-color`
- `--mdc-snackbar-label-color`
- `--mdc-snackbar-z-index`
- `--mdc-snackbar-viewport-margin`
- `--mdc-snackbar-min-width`
- `--mdc-snackbar-max-width`

We could also look into splitting viewport-margin into separate mixins/variables to control left/right margin and the bottom margin.

**Comment by mecirmartin** [comment]
@asyncLiz  any progress on this? Would need at least to set z-index on the snackbar, otherwise the component is quite useless...
