### ISSUE TITLE
configurable z-index for mwc-dialog

### ISSUE THREAD

**Issue by johnstonmatt** [material-components/material-web#2027]
**Is your feature request related to a problem? Please describe.**
Hi, Thanks for sharing this work! I'm using `<mwc-dialog>` in an open source project, and it is rendering underneath a navbar. I'd like to be able to configure the `z-index` that the dialog renders at myself, so I can position it in the z stack where it is meant to be.

(The z-index might not be static, in which case the dynamic solution to putting the dialog on top of all other nodes is failing)

**Describe the solution you'd like**
If there was a property used to configure the z-index using a property in css like `--mdc-overlay-z-index` it could be used as the target index to render the overlay.

**Describe alternatives you've considered**
Setting all other application nodes lower on z-index, but when other web apps import the component (my component that leverages mwc-dialog, or even mwc-dialog itself), they must all do this, which is not good.

**Additional context**
Note how in the image, the dialog card is beneath the nav, and it looks weird :)
<img width="1098" alt="Screen Shot 2020-12-23 at 2 45 32 AM" src="https://user-images.githubusercontent.com/5455542/102967738-fa64f380-44c8-11eb-8455-0644480fa913.png">

**Comment by CICCIOSGAMINO** [comment]
I'm thinking i've noticed the same root of problem try to stand up a mwc-fab  to mwc-drawer (when open in type=modal) ! I cannot bring the mwc-fab on top of the aside/content of drawer when opened ...

**Comment by asyncLiz** [comment]
Obsolete with M3, which uses a native `<dialog>` for positioning, not z-index
