### ISSUE TITLE
mwc-top-app-bar with 100% content

### ISSUE THREAD

**Issue by nicolasr75** [material-components/material-web#2029]
I was wondering whether it is possible to have a default content slot in the app bar that fills the rest of the screen?

An example would be a data visualization page that uses the app bar to display tools for manipulating the content of a chart and the chart below the bar fills the rest of the screen.

As it looks now the content slot grows with the provided content and scrolls if the content exceeds the screen.

Is there any way to achieve a 100% content height already that I have not yet found?

Alternatives that I have considered:

- Don't use `mwc-top-app-bar` and roll out my own app bar  :-(
- Subclass and override `contentClasses()` to inject a class that makes the content slot `height: calc(100% - 64px)` (in this case for the default appearance of the bar)
- Don't use the content slot of the bar but place the content side by side with the bar either with `height: calc(100% - 64px)` or  in a flexbox.

What do you think?

**Comment by e111077** [comment]
Seems like the best way to handle this for now would be to simply add a custom property for height that defaults to `auto`

**Comment by yinonov** [comment]
or alternatively [this](https://github.com/material-components/material-components-web-components/issues/2028#issuecomment-774135444)?
