### ISSUE TITLE
Wrong placement of the icon in mwc-button in a mwc-dialog.

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#2131]
Here's a reproduction

https://jsbin.com/qeconuw/edit?html,output

The icon in the `mwc-button` is not aligned with the text, when used in a `mwc-dialog`.

Last year I opened this issue : https://github.com/material-components/material-components-web-components/issues/1045 for the same reason.
It was fixed, but recently I noticed that the misplacement appears again.

**Comment by taylor-vann** [comment]
Hey @vdegenne 

Thanks for providing a jsbin to reference!

Here's a [jsbin](https://jsbin.com/wuxobakehe/1/edit?html,output) where the icon in `mwc-button` is centered and styled correctly by using the slot property on your 'open' button.

`<mwc-button slot="secondaryAction">`

We control the styling more heavily in our slotted actions. I wouldn't recommend putting buttons in a dialog other than in the "primaryAction" and "secondaryAction" slots. The intention of dialog is to have a 'yes / no' or 'okay / cancel' between the user, the dialog, and dialog's actions (the buttons).

**Comment by taylor-vann** [comment]
It's still technically a wayward CSS property inheritance so I will be taking ownership of this bug :)
Thanks for submitting!

**Comment by christophe-g** [comment]
Anything new on this ?
Thanks

**Comment by vdegenne** [comment]
I am the author of this post.
After almost a whole year this bug is still there.
Can we hope to see this fixed soon?
Maybe levelling up the priority? as it is common to have buttons with icon in dialogs.

Thanks

**Comment by asyncLiz** [comment]
Fixed in M3

**Comment by vdegenne** [comment]
M3 for the win! :+1:
