### ISSUE TITLE
MWC Snackbar: CSS variable for background color

### ISSUE THREAD

**Issue by maicol07** [material-components/material-web#2162]
**Is your feature request related to a problem? Please describe.**  
Can't change the background color of a snackbar.  
For example, the standard snackbar is great for dark themes, but not on light ones

**Describe the solution you'd like**  
Support snackbar theming (css variable for background color)

**Describe alternatives you've considered**  
It's possible to do this only with JS at the moment

**Comment by dfreedm** [comment]
Thanks for the issue!

**Comment by veller** [comment]
@maicol07 out of curiosity: how are you handling it with JS?

**Comment by maicol07** [comment]
@veller at the moment you have only two possibilities:

*   Extending the webcomponent and then add the background color (recommended):

```js
import {Snackbar as MWCSnackbar} from '@material/mwc-snackbar`;
import {css} from 'lit';

export class Snackbar extends MWCSnackbar {
	static styles = [MWCSnackbar.styles, css`.mdc-snackbar__surface { background-color: white }`]
}
```

*   Traverse the shadow root to change the color manually (might not work):

```js
document.getElementsByTagName('mwc-snackbar')[0].shadowRoot.firstElementChild.firstElementChild.style['background-color'] = 'white'
```
