### ISSUE TITLE
[mwc-drawer] Drawer not following content in a `dismissible` context.

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#2252]
**Describe the bug**
The drawer (`dismissible`) sticks at the top of the document when scrolling if `appContent` is longer than the drawer's content.

**Expected behavior**
In my use-case I was expecting the drawer to follow the content on scrolling.
I am using `modal` drawer on the mobile version so It's fine. `dismissible` on PC and tablets. On PC it's also fine because the content is all visible on the screen but on tablet I would wish my users to scroll the content and they still could have an eye on the drawer content because it displays live update information.

**Screenshots**

https://user-images.githubusercontent.com/2827383/111066596-183a6700-84c0-11eb-9314-6d4f1e95e063.mp4

**Fixes**
I could get what I wanted but just changing the css directive `position` on the `.mdc-drawer` selector, like so:
```typescript
this.drawer.shadowRoot!.querySelector<Drawer>('.mdc-drawer--dismissible')!.style.position = 'fixed'
```

**Browser Version (please complete the following information):**
 - OS: Linux, Windows
 - Browser Chromium 88.0.4324.182
 - Version `mwc-drawer` version 0.20.0

**Comment by e111077** [comment]
@taylor-vann this might be related to your current work
