### ISSUE TITLE
IOS Safari: Floating label misaligned

### ISSUE THREAD

**Issue by parag-aegon** [material-components/material-web#2259]
**Describe the bug**
Placeholder label & cursor when focus-in overlaps with each other. This happens only in iOS (Safari) Browser.

**To Reproduce**
1. Open 'Safari 13.x & open the demo page
2. Focus on the input text field
3. Observe the floating label & cursor, they are overlapping each other.

**Expected behavior**
This should not overlap with the label, how it's working for Chrome.

**Screenshots**

https://user-images.githubusercontent.com/5981958/111559687-3d440980-874e-11eb-9c16-da7bcaa44a55.mp4

**Browser Version (please complete the following information):**
 - iOS
 - Safari
 - 13.x

**Additional context**
`none.`

**Comment by asyncLiz** [comment]
Un-assigning myself since I may not be the one working on the MWC implementation. b/183405688 for the internal tracking of the task to update text field.

**Comment by asyncLiz** [comment]
Fixed in the new M3 text field
