### ISSUE TITLE
mwc-menu fixed position outside of viewport

### ISSUE THREAD

**Issue by JacobBlana** [material-components/material-web#2281]
Opening fixed mwc-menu with anchor on its opener while page content is longer than 100vh makes it position the surface incorrectly. The incorrect position is only aplied when the opener sits in the DOM below initial scrollHeight so that said everything works just fine when the page has no scroll. 

After checking dev tools it seems that the surface gets position relative to the document not the viewport as it should, because the menu is set up as fixed. I kinda think that the problem is caused when setting menu.corner to "TOP_START" but that should not be a problem.

**To Reproduce**
I copied part of the code from my App, so you can check live demo of the problem:
https://codesandbox.io/s/fixed-menu-position-y4m32

- You can clearly see that the first two openers in the top works just fine
- Scroll down the page and try opening the 3rd menu opener
- Visually it does nothing, but if you inspect the code menu opens just fine, but is incorrectly positioned as already described

**Expected behavior**
Menu opening with correct position cords relative to the browser viewport.

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrom 89

**Comment by e111077** [comment]
fixed in M3

https://codesandbox.io/s/fixed-menu-position-forked-dxmw9h?file=/src/index.js
