### ISSUE TITLE
[a11y][mwc-top-app-bar] role toolbar attribute misaligned with element section

### ISSUE THREAD

**Issue by gullerya** [material-components/material-web#2319]
According to [Deque Axe - accessibility automation tool](https://dequeuniversity.com/rules/axe/3.5/aria-allowed-role?application=AxeChrome) role `toolbar` SHOULD NOT be used on element `section`.

Yet, this is the current usage in the `mwc-top-app-bar` component (which seemingly goes back to the [Material Design approach](https://material.io/components/app-bars-top/web#regular-top-app-bar)).

According to [this W3 document](https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html) role `toolbar` MAY be used on `div` element, for example.

Please consider replacing (or rearranging) the DOM structure to allow passing the a11y tests of axe, which is quite a standard in the industry.

> Note: same applies to the `mwc-top-app-bar-fixed` component.

**Comment by dfreedm** [comment]
Thanks for the feedback. This construction with `<section role="tooltip">` is directly from the MDC top app bar, as you noticed, so I'll have to double check what a more appropriate element would be there.
