### ISSUE TITLE
TextField label not shown when has onChange, defalut value, is outlined and textField "appears"

### ISSUE THREAD

**Issue by vsaona** [material-components/material-web#2332]
Okay, this is a super specific bug, but it is definitely a bug:
![image](https://user-images.githubusercontent.com/44838784/115298869-08035080-a12c-11eb-8ee1-09f3baa350af.png)

### In code
```css
.invisible { display: none; }
```
```html
<script>
  function foo () {
    document.getElementById("1").classList.remove("invisible");
  }
</script>
<div class = "invisible" id="1">
  <mwc-textfield
    outlined
    label="something"
    value = "0"
    onchange = "doSomething(this)">
  </mwc-textfield>
</div>
<button onClick = "foo()">
    Make it appear
</button>
```

### In words
You have a ``mwc-textField`` wich is Material outlined style, has a default value, and has a function as ``onChange`` property (it doesn't matter if the function actually exists, but the ``onChange`` property must be setted)
The ``mwc-textField``is inside something with ``display: none``, and you can programatically make it appear.

### Problem
When it appears, the label just doesn't appear. It doesn't appear even if you change the value of the text field, unless you erase all of its content. When empty and unfocused, the label appears (it takes the main place of the ``mwc-textField``).

### Further information
I tested this on Windows 10, using Node.js v14.16.1 as server, and using both Firefox and Edge as browsers.

**Comment by e111077** [comment]
Hello, this is a known issue with textfield. Upstream MDC library refactor in the works right now should fix this. In the meantime you'll have to call [`textfield.layout()`](https://github.com/Polymer/lit-html/blob/f6ad532defc6dc03bda6a98bb83f9d3d01efc9f4/packages/reactive-element/src/reactive-element.ts#L427).

**Comment by asyncLiz** [comment]
Fixed in M3

**Comment by lasamarndi1994** [comment]
I am facing the same issue. a label is not showing while changing the dynamic value.

**Comment by asyncLiz** [comment]
> I am facing the same issue. a label is not showing while changing the dynamic value.

The old beta `<mwc-textfield>` won't receive this fix. I'd recommend trying to update to 1.0 and use `<md-filled-text-field>` or `<md-outlined-text-field>`, which doesn't have this problem.
