### ISSUE TITLE
[mwc-menu] multi selection shouldn't close the menu

### ISSUE THREAD

**Issue by yinonov** [material-components/material-web#2345]
**Describe the bug**
a use case of multi selection should leave menu open to enable multi selection without reopening the menu on each select

**To Reproduce**
1. compose the following html
```html
<mwc-menu activatable multi forceGroupSelection>
  <mwc-check-list-item>item 1</mwc-check-list-item>
  <mwc-check-list-item>item 2</mwc-check-list-item>
  <mwc-check-list-item>item 3</mwc-check-list-item>
</mwc-menu>
```
2. open menu
3. check 1 of the items
4. menu closes

**Expected behavior**
it is expected from menu to remain open and enable multi selection smoothly

**Screenshots**
![image](https://user-images.githubusercontent.com/15140652/116139934-4629e280-a6df-11eb-975a-56fdff4d96e4.png)

**Comment by taylor-vann** [comment]
Hey @yinonov thanks for submitting!

If you could provide a little more context here, maybe a JSBin or an example of your code?

Reason being, this feels like an implementation detail, not a bug in the component set.

Clicks in `mwc-menu` shouldn't close the menu.

Is it possible that the `open menu` button toggles a binary on / off variable? Or is menu a child of a component with an event listener, as in clicks in menu effect parent event listeners?

[mwc-menu](https://github.com/material-components/material-components-web-components/tree/master/packages/menu#mwc-menu-) is similar to [mwc-list](https://github.com/material-components/material-components-web-components/tree/master/packages/list#mwc-list-) but with a few api methods to show and hide the list surface.

**Comment by yinonov** [comment]
you're actually right, something must have gone wrong with my subclassing and [this](https://codepen.io/yinonov/pen/YzNgdWo) actually works ok but still, why in [mwc menu demo](https://material-components.github.io/material-components-web-components/demos/menu/) all items close the menu ?

**Comment by taylor-vann** [comment]
That's ... a good question! I'll look into it :)

**Comment by gullerya** [comment]
For your @taylor-vann intention, the below override of the `createAdapter` solves this issue, since as far as I can see the MDC foundation `handleItemAction` has unconditional `closeSurface` call:
```js
createAdapter(): any {
  const baseAdapter = super.createAdapter();
  const baseCloseSurface = baseAdapter.closeSurface;
  baseAdapter.closeSurface = () => {
    if (!this.multi) {
      baseCloseSurface();
    }
  }
  return baseAdapter;
}
```

WDYT?

**Comment by yinonov** [comment]
just to understand, should menu remain open always by API? or it depends on its content?

**Comment by asyncLiz** [comment]
This issue will depend on two things:

1. Some guidance from design. We don't have explicit guidance on how multi-selection lists within menus should work and whether or not menus should persistently stay open. Our only guidance right now is that menus close when items are selected, which is vague given the context of the UX for multi-select.
2. List refactor! `<mwc-list>` needs to be updated, so any changes to its behavior (and menu's) likely will not come until that happens.

I'll keep this issue open in our backlog to track the issue while we wait on these two things.
