### ISSUE TITLE
[mwc-textfied] Setting custom validity removes the mark up for an error/helper, hence causing the form to jerk

### ISSUE THREAD

**Issue by rutwick-alic** [material-components/material-web#2365]
I am using setCustomValidity to validate an email address onInput. When the page loads, the markup for an error/helper message is there along with the input field. Now when I use setCustomValidity to set the field as valid and set the message as blank, the markup is removed, hence causing the form to jerk.

Any ideas on how to fix this, and whether this is a bug or no?

**Comment by taylor-vann** [comment]
related to [971](https://github.com/material-components/material-components-web-components/issues/971)

**Comment by taylor-vann** [comment]
Hey @rutwick-alic thanks for submitting!

The quick solve might be to set the `pattern` attribute to an empty string.

Then set the `validationMessage` to a single space to preserve spacing.

```
<mwc-textfield pattern="" validationMessage=" " ></mwc-textfield>
```

**Comment by rutwick-alic** [comment]
> Hey @rutwick-alic thanks for submitting!
> 
> The quick solve might be to set the `pattern` attribute to an empty string.
> 
> Then set the `validationMessage` to a single space to preserve spacing.
> 
> ```
> <mwc-textfield pattern="" validationMessage=" " ></mwc-textfield>
> ```

Hey @taylor-vann, thanks a lot! Let me try doing this. I will update here accordingly.
