### ISSUE TITLE
Remove the need to call layout and layoutOptions in mwc-select

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#2393]
**Is your feature request related to a problem? Please describe.**

There have been several requests to not require calling `layout` or `layoutOptions` on several of our components like MWC select. It's generally bad DX

**Describe the solution you'd like**

Change or rewrite these components so that the user doesn't have to manually call a layout function

**Describe alternatives you've considered**

Asking users to write mutation or resize observers

**Additional context**

Dan working on pitching core to enable slotchanged in wit

**Comment by asyncLiz** [comment]
Fixed in M3
