### ISSUE TITLE
mwc-select fixedMenuPosition - inconsistent menu width

### ISSUE THREAD

**Issue by yujiri8** [material-components/material-web#2423]
**Describe the bug**
When using mwc-select with fixedMenuPosition and a set of mwc-list-items that:
* is long enough that the whole menu doesn't fit vertically on the screen
* contains one item with a long label (I'm not sure exactly how long it has to be, but "a rather long item label")
On first opening the select, the dropdown is wide enough to show the long item. If you close and reopen it, the long item is cut off with an ellipsis.

**To Reproduce**
1. Go to https://codesandbox.io/s/fixed-menu-position-forked-5jlfe
2. Open the menu, note the whole item label being displayed
3. Close and reopen the menu, note the long item being cut off

**Expected behavior**
The menu is wide enough to show the whole item, or at least is as wide as the select itself, and either way the width should not change by closing and reopening

**Screenshots**
![20210517_21h32m06s_grim](https://user-images.githubusercontent.com/16864184/118576849-59b4f000-b757-11eb-8ccd-36f7d550f54d.png)
![20210517_21h31m54s_grim](https://user-images.githubusercontent.com/16864184/118576854-5b7eb380-b757-11eb-9cc6-961c8c39278e.png)

**Browser Version (please complete the following information):**
 - OS: Linux
 - Browser: Chromium (on Firefox, the item is always cut off)
 - Version: 90

**Additional notes**

The bug appears without increasing the width of mwc-select, but I did that in the demo to show that it can result it forcing the label to be even narrower than the select itself.

**Comment by e111077** [comment]
Hmm this is likely upstream and seems to always be having issues specifically sizing with the scrollbar

**Comment by asyncLiz** [comment]
@e111077 is this obsolete with M3's select?
