### ISSUE TITLE
Release all components in a single package as a convenience

### ISSUE THREAD

**Issue by djlauk** [material-components/material-web#2435]
**Is your feature request related to a problem? Please describe.**

When there is a new release of MWC I usually want to update all of the mwc packages in my project, as they need to be on the same version anyway. I am always frustrated when I have to fiddle around until I get the shell one-liner right to update the mwc-packages in one shot.

**Describe the solution you'd like**

I would like to install (and later update) a single package as a dependency in my npm project. This could be sort of a _meta_ package, that has only dependencies and no content of its own, but I don't know if that is possible with npm (I know this is a thing with RPM based Linux distributions.)

**Describe alternatives you've considered**

Things I have used to mitigate this (all with some frustration):
- I have created one-liners ad-hoc
- I have tried putting the one-liners into `package.json`'s `scripts` section
- I have used [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)

**Additional context**

I asked for this a while ago on Slack: https://lit-and-friends.slack.com/archives/CC0Q3PRCL/p1593640316036200

**Comment by e111077** [comment]
This is so on point. We are in the process of doing this! Thanks for writing up the issue for us

**Comment by tveinfeld** [comment]
had that same requirement:

we have automated the creation of one package that exports components from all our individual packages.
our cd publishes all individual packages, then creates a "_virtual_" package (not manually maintained within our monorepo) complete with:

- **package.json** - includes all deps with specific version qualifiers
- **index.js** - containing a list of named exports. e.g.:

  `export { VWCAudio } from "@vonage/vwc-audio";`
 `export { VWCCircularProgress } from "@vonage/vwc-circular-progress";`

our users consume that single package. when they upgrade, all underlying components are also being updated.

**Comment by asyncLiz** [comment]
We are now with `@material/web`!
