### ISSUE TITLE
Implement Material You

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-web#2441]
Hey everyone! Hopefully by now you've seen the Google I/O keynote news about [Material You](https://material.io/blog/announcing-material-you)!
You've also probably noticed that updates to this repository have been rather slow for a while, and I'm happy to say that we can finally announce that the two are related!

We've been working with the Material Design UX team to ensure that Material You will be well supported on the Web, and will be updating our components with the new specifications as they become available.

In the short term, we'll be making significant changes across the repository to prepare for implementation of Material You. We'll have an updated roadmap available soon.

**Comment by zandaqo** [comment]
> You've also probably noticed that updates to this repository have been rather slow for a while, and I'm happy to say that we can finally announce that the two are related!

Is there a timetable or a priority list of planned features for MWC in general? Does this mean that implementation of missing components (chip, card, tooltip, etc.) will be postponed till the styling of all components is updated to the Material You standards?

**Comment by yinonov** [comment]
would be nice if you expose the expected updates and components addressed.
I guess the MWCs are built to integrate in google apps, but in practice are open source and actually affect decisions in teams whether to wait for a mwc subclassing of a production ready component or build components from scratch.
so any info will help navigate the boat

**Comment by leonardorafael** [comment]
Hello my friends, if you need MATERIAL DESIGN 3 how about https://www.beercss.com?

![theme-1](https://user-images.githubusercontent.com/12979016/149222946-f7158c88-8052-434f-94ac-ce0cfa350f97.gif)

**Comment by arcodebonte** [comment]
I was hoping on the last month, the last week and the last day of 2022. Is there an update about the next release?

**Comment by asyncLiz** [comment]
See https://github.com/material-components/material-web/issues/3050#issuecomment-1370047324 for the latest update. TL;DR; we have new requirements/timelines and a roadmap to v1 is on our todo list :)

**Comment by asyncLiz** [comment]
(psst it's implemented)
