### ISSUE TITLE
mwc-button rendering different on Safari to Chrome

### ISSUE THREAD

**Issue by halloweenman** [material-components/material-web#2457]
**Describe the bug**
In Safari the button has additional 2px margin/padding to both the left and right.

In additon, the button label text does not appear to be correctly vertically aligned with the icon in **IOS Mobile Safari only**.

**To Reproduce**
Either fully left or right align button and you'll see a 2px gap in Safari. However, in Chrome, it there is no gap.

In **IOS Mobile Safari only** you will see trailing icon and label text are not vertically aligned correctly.

**Expected behavior**
No left or right margin/padding.

Icon and label text vertically aligned correctly in IOS Mobile Safari.

**Screenshots**
Chrome (renders correct)
![image](https://user-images.githubusercontent.com/10757745/119968519-7fd35f00-bfa5-11eb-8b74-5c9dc84905d8.png)

Safari (renders incorrect, 2px gap to right of button)
![image](https://user-images.githubusercontent.com/10757745/119968560-8d88e480-bfa5-11eb-9526-06c50a2d5a9d.png)

IOS Mobile Safari only ('Templates' label text not vertically aligned correctly)

Code uses 'menu' Material Icon
```
<mwc-button label="Templates" title="Template">
<svg slot="trailingIcon" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px">
<path d="M0 0h24v24H0V0z" fill="none" />
<path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" />
</svg>
</mwc-button>
```

![image](https://user-images.githubusercontent.com/10757745/120072620-a3bda000-c08c-11eb-9050-09b15d9afd27.png)

**Browser Version (please complete the following information):**
Safari Version 14.1
IOS Safari, version 14.5.1
Version 90.0.4430.212

**Comment by stucker71** [comment]
Interestingly, if you remove `slot="trailingIcon"` the vertical alignment is correct.

```
<mwc-button label="Templates" title="Template">
                            <svg xmlns="http://www.w3.org/2000/svg" height="18px" viewBox="0 0 24 24" width="18px">
                                <path d="M0 0h24v24H0V0z" fill="none" />
                                <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" />
                            </svg>
                        </mwc-button>
```

**Comment by asyncLiz** [comment]
Should be obsolete with M3
