### ISSUE TITLE
Update Contributing guide

### ISSUE THREAD

**Issue by krumware** [material-components/material-web#246]
The current Contributing guide looks to be leftover from the Polymer mono-repo, which may no longer be relevant here and could cause confusion.
It may also be worth including some information relevant to those who would like to contribute or get support, to address questions like these: https://github.com/material-components/material-components-web-components/issues/226

**Comment by mohe2015** [comment]
I currently have issues with testing my local changes with another project. It seems like this project is using lerna which I don't know anything about. Are there easy instructions on how to link the packages or maybe how to publish your own to import them in the other project? Any help would be really appreciated. Also this would be worth for inclusion in the contribution guide.

**Comment by mohe2015** [comment]
A simple hack is replacing all @materai/mwc- instances with @npmusername/mwc- and then publishing using lerna.
