### ISSUE TITLE
mwc-select change event is fired even when changing value from code

### ISSUE THREAD

**Issue by davidkudera** [material-components/material-web#2466]
**Describe the bug**
Standard `<select>` `change` event is fired only when the value is changed by a user, not when it is changed by code. But `<mwc-select>` fires the `change` event in both cases. Using `selected` event does not help, because it is fired also on `<mwc-select>` init.

**To Reproduce**
I prepared example in Lit playground with comparison to native `<select>`: [example](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgc3RhdGUsIHF1ZXJ5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIEBxdWVyeSgnbXdjLXNlbGVjdCcpIHByaXZhdGUgc2VsZWN0OiBhbnk7XG4gIEBzdGF0ZSgpIHByaXZhdGUgY291bnRlcjogbnVtYmVyID0gMDtcbiAgXG4gIEBxdWVyeSgnc2VsZWN0JykgcHJpdmF0ZSBuYXRpdmVTZWxlY3Q6IGFueTtcbiAgQHN0YXRlKCkgcHJpdmF0ZSBuYXRpdmVDb3VudGVyOiBudW1iZXIgPSAwO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxoMz5XYWl0IGEgYml0Li4uPC9oMz48aHI-XG4gICAgICAgIFxuICAgICAgPHA-Y2hhbmdlczogJHt0aGlzLmNvdW50ZXJ9PC9wPlxuICAgICAgXG4gICAgICA8bXdjLXNlbGVjdFxuICAgICAgICBAY2hhbmdlPVwiJHsoKSA9PiB0aGlzLmNvdW50ZXIrK31cIlxuICAgICAgICBsYWJlbD1cIlNlbGVjdFwiXG4gICAgICA-XG4gICAgICAgIDxtd2MtbGlzdC1pdGVtIHNlbGVjdGVkPjwvbXdjLWxpc3QtaXRlbT5cbiAgICAgICAgPG13Yy1saXN0LWl0ZW0gdmFsdWU9XCIwXCI-SXRlbSAwPC9td2MtbGlzdC1pdGVtPlxuICAgICAgICA8bXdjLWxpc3QtaXRlbSB2YWx1ZT1cIjFcIj5JdGVtIDE8L213Yy1saXN0LWl0ZW0-XG4gICAgICAgIDxtd2MtbGlzdC1pdGVtIHZhbHVlPVwiMlwiPkl0ZW0gMjwvbXdjLWxpc3QtaXRlbT5cbiAgICAgICAgPG13Yy1saXN0LWl0ZW0gdmFsdWU9XCIzXCI-SXRlbSAzPC9td2MtbGlzdC1pdGVtPlxuICAgICAgPC9td2Mtc2VsZWN0PlxuICAgICAgICBcbiAgICAgIDxocj5cbiAgICAgICAgXG4gICAgICA8cD5uYXRpdmUgY2hhbmdlczogJHt0aGlzLm5hdGl2ZUNvdW50ZXJ9PC9wPlxuICAgICAgXG4gICAgICA8c2VsZWN0XG4gICAgICAgIEBjaGFuZ2U9XCIkeygpID0-IHRoaXMubmF0aXZlQ291bnRlcisrfVwiXG4gICAgICAgIGxhYmVsPVwiU2VsZWN0XCJcbiAgICAgID5cbiAgICAgICAgPG9wdGlvbiBzZWxlY3RlZD48L29wdGlvbj5cbiAgICAgICAgPG9wdGlvbiB2YWx1ZT1cIjBcIj5JdGVtIDA8L29wdGlvbj5cbiAgICAgICAgPG9wdGlvbiB2YWx1ZT1cIjFcIj5JdGVtIDE8L29wdGlvbj5cbiAgICAgICAgPG9wdGlvbiB2YWx1ZT1cIjJcIj5JdGVtIDI8L29wdGlvbj5cbiAgICAgICAgPG9wdGlvbiB2YWx1ZT1cIjNcIj5JdGVtIDM8L29wdGlvbj5cbiAgICAgIDwvc2VsZWN0PlxuICAgIGA7XG4gIH1cbiAgXG4gIGZpcnN0VXBkYXRlZCgpXG4gIHtcbiAgICBzZXRUaW1lb3V0KCgpID0-IHtcbiAgICAgIHRoaXMuc2VsZWN0LnZhbHVlID0gJzMnO1xuICAgICAgdGhpcy5uYXRpdmVTZWxlY3QudmFsdWUgPSAnMyc7XG4gICAgfSwgMzAwMCk7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCI-XG4gIGltcG9ydCBtYXRlcmlhbE13Y1NlbGVjdCBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi9AbWF0ZXJpYWwvbXdjLXNlbGVjdCc7XG48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn1d)

**Expected behavior**
To not dispatch `change` event when the select value is changed from code.

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 91.0.4472.77

**Comment by asyncLiz** [comment]
Should be resolved with M3
