### ISSUE TITLE
Avoid importing `.css` files in the published files

### ISSUE THREAD

**Issue by abdonrd** [material-components/material-web#2561]
**Describe the bug**

https://unpkg.com/browse/@material/mwc-button@0.22.1/mwc-button.js

I just checking the `@material/mwc-button` and it has this CSS import line:

```javascript
import { styles } from './styles.css';
```

But the browser can't load this `.css` file (at least without server magic).

**Expected behavior**

Use code that the browser understand.

Maybe as `.css.js`?

```javascript
import { styles } from './styles.css.js';
```

**Comment by dfreedm** [comment]
I think for both this reason, and future support of [Import Maps](https://wicg.github.io/import-maps/), we'll have to evaluate adding `.js` file extensions to our built files.

Our internal styleguide for Typescript precludes adding using file extensions on source files, so we'll probably look first at using some tooling in the build process to add file extensions.

**Comment by thescientist13** [comment]
> Our internal styleguide for Typescript precludes adding using file extensions on source files, _so we'll probably look first at using some tooling in the build process to add file extensions._

This would be great to see!  Started [testing out MWC myself](https://github.com/ProjectEvergreen/greenwood-getting-started/pull/42) and also ran into this.

Also and apologies if I am missing it, but I don't see [a _styles.css_ in the published package](https://unpkg.com/browse/@material/mwc-button@0.22.1/).  Is that expected?  🔍 👀 

<img width="1017" alt="Screen Shot 2021-08-02 at 5 04 32 PM" src="https://user-images.githubusercontent.com/895923/127923692-50f2c2f0-e4fc-46b6-81d1-bf52b85a2181.png">

----

On a related note, would this effort also address the missing _.js_ extension as well from files also referenced in the entry point?  Like _mwc-button-base_?  I'm think that per the spec that files need to have an extension, so would / could this be part of a related effort to address extensions within the project?

----

Not sure if any of these points are worth raising on the README but happy to submit a PR to help highlight any of these considerations and / or making an issue to track.

Thanks!  ✌️

**Comment by thescientist13** [comment]
Ah, after thinking about it some more, it seems that the assumption is that _@material/mwc-button/styles.css_ will be resolved to _@material/mwc-button/styles.css.js_ presumably. (with the .js extension already attached)?  Sorry if I missed all this in the docs.  😞 

Should be easy enough to work around but I think per spec compliance, and to favor being explicit over implicit, it would be great if MWC could always set the extension of the file being imported.  🙏

**Comment by dfreedm** [comment]
Merging this issue into #2632
