### ISSUE TITLE
Implement menu hoisting for select

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#2577]
### Context

In select's shadow root, we use `<mwc-menu>` this creates an `<mwc-menu-surface>` which creates a surface that is `position:absolute`. This gives the correct behavior of menu sticking and following around with the select.

### Problem

The problem with this is that the stacking context of menu-surface is its current position in the tree. This means if there is an element after it in the tree with `position: absolute`, then it will very likely cover the element. If the menu is placed inside of an element with `position: absolute` or `position: fixed` then the stacking context of the menu-surface is now placed inside that element.

### Example / Repro

[lit playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCxjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0LWVsZW1lbnQnO1xuXG5pbXBvcnQgJ0BtYXRlcmlhbC9td2Mtc2VsZWN0QDAuMjIuMSc7XG5cblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgICNjb3ZlcmluZyB7XG4gICAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICAgICAgd2lkdGg6IDUwMHB4O1xuICAgICAgICBoZWlnaHQ6IDMwcHg7XG4gICAgICAgIGJhY2tncm91bmQtY29sb3I6IHdoaXRlO1xuICAgICAgICB6LWluZGV4OiA4OyAvKiB0aGUgc2FtZSBhcyBtZW51LXN1cmZhY2UgKi9cbiAgICAgIH1cbiAgICAgIFxuICAgICAgI2Fic29sdXRlUGFyZW50IHtcbiAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgICB0b3A6IDEwMHB4O1xuICAgICAgICBoZWlnaHQ6IDEwMHB4O1xuICAgICAgICBib3JkZXI6IDFweCBzb2xpZCBibGFjaztcbiAgICAgICAgb3ZlcmZsb3cteTogYXV0bztcbiAgICAgIH1cbiAgYDtcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgICA8ZGl2IGlkPVwiY292ZXJcIj5cbiAgICAgICAgICA8bXdjLXNlbGVjdCBvdXRsaW5lZD5cbiAgICAgICAgICAgIDxtd2MtbGlzdC1pdGVtIHZhbHVlPVwiYVwiPkE8L213Yy1saXN0LWl0ZW0-XG4gICAgICAgICAgICA8bXdjLWxpc3QtaXRlbSB2YWx1ZT1cImJcIj5CPC9td2MtbGlzdC1pdGVtPlxuICAgICAgICAgICAgPG13Yy1saXN0LWl0ZW0gdmFsdWU9XCJjXCI-QzwvbXdjLWxpc3QtaXRlbT5cbiAgICAgICAgICAgIDxtd2MtbGlzdC1pdGVtIHZhbHVlPVwiZFwiPkQ8L213Yy1saXN0LWl0ZW0-XG4gICAgICAgICAgPC9td2Mtc2VsZWN0PlxuICAgICAgICAgIDxkaXYgaWQ9XCJjb3ZlcmluZ1wiPlRISVMgRElTUExBWVMgT1ZFUiBUSEUgTUVOVTwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBpZD1cImFic29sdXRlUGFyZW50XCI-XG4gICAgICAgICAgPGRpdj5USEUgTUVOVSBJUyBISURERU4gQkVDQVVTRSBPRiBTVEFDS0lORyBDT05URVhUPC9kaXY-XG4gICAgICAgICAgPG13Yy1zZWxlY3Qgb3V0bGluZWQ-XG4gICAgICAgICAgICA8bXdjLWxpc3QtaXRlbSB2YWx1ZT1cImFcIj5BPC9td2MtbGlzdC1pdGVtPlxuICAgICAgICAgICAgPG13Yy1saXN0LWl0ZW0gdmFsdWU9XCJiXCI-QjwvbXdjLWxpc3QtaXRlbT5cbiAgICAgICAgICAgIDxtd2MtbGlzdC1pdGVtIHZhbHVlPVwiY1wiPkM8L213Yy1saXN0LWl0ZW0-XG4gICAgICAgICAgICA8bXdjLWxpc3QtaXRlbSB2YWx1ZT1cImRcIj5EPC9td2MtbGlzdC1pdGVtPlxuICAgICAgICAgIDwvbXdjLXNlbGVjdD5cbiAgICAgICAgPC9kaXY-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuICA8c3R5bGU-Ym9keSB7XG4gICAgICBoZWlnaHQ6IDcwdmg7XG4gICAgfTwvc3R5bGU-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9XQ)

### Workaround

In most cases the workaround is to add `fixedMenuPosition` to `mwc-select`. This will make the menu `position: fixed` which creates a window-level stacking context thus positioning it above all `position: absolute`s in the document.

Though this means if the user scrolls while the menu is open, then the menu will not "follow" the select on the page since fixed is relative to window not a relatively position element.

### Proposed fix

The "Correct" fix for this is that `mwc-menu` should be `position:absolute` and placed as the last element in the document. This is what we call "hoisting the menu (to document.body)".

It does not make sense for the user to have to do this themselves and we don't want to do this within mwc-select itself as we don't want to step outside the lit WC rendering system as we do not know what renderers mwc-select will be placed in.

We should create a menu-hoisting / menu-requesting system. The real problem is how to handle templating, and css custom properties. e.g. something we napkined at the office

```html
<body>
  <nav>
    <mwc-overlay-scope>
      <nav-item>...</nav-item>
      <nav-item>...</nav-item>
      <nav-item>...</nav-item>
      <nav-item>...</nav-item>
      <nav-menu title="...">
        <!-- without lit-html -->
        <mwc-menu id="navMenu"></mwc-menu>
    </mwc-overlay-scope>
  </nav>
  <mwc-overlay-scope>
    <div id="application">
      ...
      <!- with lit-html -->
      <mwc-select @input=${...} label="fruits" .renderer=${(node: HTMLElement) => {
        // import {html, render} from 'lit';
        const template = html`
          <mwc-list-item value="NONE" @click=${...}></mwc-list-item>
          ${items.map(item => html`
            <mwc-list-item ?selected=${item.selected} value=${item.value}>
              ${item.text}
            </mwc-list-item>
          `)}
        `;
      }}>
      </mwc-select
    </div>
  </mwc-overlay-scope>
  
  <script type="jsx">
    // or innerHTML or whatever rendering system you choose
    import {render} from 'react-dom';
    window.navMenu.renderer = async (node) => {
      const template = (
        <>
          <ListItem>...</ListItem>
          <ListItem>...</ListItem>
          <ListItem>...</ListItem>
          ...
        </>
      );
      
      render(template, node);
    }
  </script>
</body>
```

where the template of `menu-overlay-scope` is:

```html
<style>
  :host {
    display: contents;
  }
</style>
<slot></slot>
<!-- some abstract surface that is used across tooltip and menus etc -->
<mwc-surface>
  ${callChildRenderer()}
</mwc-surface>
```

**Comment by yinonov** [comment]
suggestion (as in #2409)
align with native select behavior -

- menu is fixed
- opened menu **inert the outside** context
- user can't interact with the rest of the tree until menu is close

it is partially a modal like there's an invisible scrim underlying the menu
 
**reasons -**

- aligns with [native select](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select)

- prevents adding - knowledge dependent - hoisting system for users to work against 

- bonus: aligns with [angular material select](https://material.angular.io/components/select/overview)

**Comment by asyncLiz** [comment]
Think this is obsolete with M3 now
