### ISSUE TITLE
[mwc-checklist-item] selected state won't apply if not rendered to dom

### ISSUE THREAD

**Issue by yinonov** [material-components/material-web#2601]
**Describe the bug**
https://user-images.githubusercontent.com/15140652/128464410-680c9665-f272-4a51-afe5-c4fbaf408b7b.mov

toggling the _**selected**_ state of non-rendered items will not apply the change until rendered back, results in a quick jumpy repainting of the checkbox

**To Reproduce**
1. apply `display none` to `mwc-list` containing `mwc-checklist-item`s
2. toggle all items' selected state
3. remove `display none` from `mwc-list`
4. the list will reveal and show the selected state change

**Expected behavior**
change should occur while not rendered and render back as the actual _**selected**_ state

**Screenshots**

https://user-images.githubusercontent.com/15140652/128464410-680c9665-f272-4a51-afe5-c4fbaf408b7b.mov

**Comment by allan-chen** [comment]
This is a consequence of using animations to reflect state changes. Browsers queue up animations on an element that is hidden until it becomes visible, similar to what can be seen in this watered down example: https://codepen.io/allanchenmdc/pen/xxdBePY

One way to deal with this is to disable the animations when the element is hidden.

**Comment by yinonov** [comment]
As in https://developer.chrome.com/blog/timer-throttling-in-chrome-88/#animation

**Comment by asyncLiz** [comment]
Obsolete with M3, checkbox list items are built manually (we'll have prebuilt ones again in the future)
