### ISSUE TITLE
Expose custom property for mwc-tab min-width

### ISSUE THREAD

**Issue by elalish** [material-components/material-web#2609]
I have 5 icon tabs running just fine using `<mwc-tab>` v0.18.0: https://modelviewer.dev/editor/

If I update to v0.21 or v0.22.1, I get only four, with a horizontal scroll to find the fifth, which is definitely not what I want. Tracking it down, there now appears to be a `min-width: 90px` set inside your shadow root where I can't get to it. I was hoping adding your `minWidth` attribute (described as "Shrinks tab as narrow as possible without causing text to wrap.") would do the trick, but alas no. You can find our tab code here: https://github.com/google/model-viewer/tree/master/packages/space-opera/src/components/shared/tabs

Is there any way around this breaking change that doesn't seem to be mentioned in the release notes?

**Comment by allan-chen** [comment]
Hey Emmett,

This change was added in this MDC [pull request](https://github.com/material-components/material-components-web/pull/6642) to align tabs to the material.io [spec](https://material.io/components/tabs#specs):

![Screen Shot 2021-08-12 at 10 10 59 AM](https://user-images.githubusercontent.com/7828061/129239320-b7ada67b-0cf4-44b8-85a7-df23842d1445.png)

Is it possible to adjust the `me-tabs` min-width and max-width to 450px to accomodate this change?

**Comment by elalish** [comment]
I don't think that's a great solution. Take a look at my link above; the tabs don't have text, just icons, so they look pretty ridiculous at 48px high and 90px wide.

**Comment by allan-chen** [comment]
We'll look into possibly supporting customizing this min-width property. At the same time, we can clarify with the UX folks whether icon-only tabs should also adhere to the min-width. This screenshot indicates that might be the case:

![Screen Shot 2021-08-12 at 10 31 49 AM](https://user-images.githubusercontent.com/7828061/129242191-77545707-77c9-43df-8555-b5ce6e7ce9d8.png)


For future visual reference re: the tabs in question,
Before: 
![Screen Shot 2021-08-12 at 10 29 53 AM](https://user-images.githubusercontent.com/7828061/129241899-220ab944-10e6-4c08-ac47-4fe3520a1348.png)

After:
![Screen Shot 2021-08-12 at 10 29 39 AM](https://user-images.githubusercontent.com/7828061/129241927-80ae43ac-b2b1-409f-b62b-482963b067f6.png)

**Comment by asyncLiz** [comment]
With M3 you can now set `min-width` directly on a `<md-tab>`
