### ISSUE TITLE
mwc components not working with lit@2 (lit.dev)

### ISSUE THREAD

**Issue by dejan9393** [material-components/material-web#2623]
The mwc components do not currently work with lit 2.0.0-rc.2, even when forcing resolutions for lit-html and lit-element to match due to requirement for importing directives with an extension. e.g:

Currently:
`import { ifDefined } from 'lit-html/directives/if-defined';`

Should be:
`import { ifDefined } from 'lit-html/directives/if-defined.js';`

**Comment by dfreedm** [comment]
I don't think lit cares about file extensions directly, but this is probably more important for your serving or bundling infrastructure to have file extensions.

This is related to #2561

**Comment by dfreedm** [comment]
Merging this issue into #2632
