### ISSUE TITLE
Components draw [object Object] everywhere

### ISSUE THREAD

**Issue by LasseRosenow** [material-components/material-web#2640]
**Describe the bug**
When I use materail web components, I get weird issues all over the place. Some components like mwc-button "sort of work" as they draw themselves correctly, but the mwc-ripple inside of them is broken for example.

**To Reproduce**
1. Download the lit starter ts project: https://github.com/lit/lit/tree/main/packages/lit-starter-ts
2. install mwc-button and mwc-ripple etc.
3. import mwc-button and mwc-ripple in typescript
4. use the components in the render method
5. run npm run build:watch
6. run npm run serve
7. open "http://localhost:8000/dev/index.html"
8. move the mouse over the button to activate the not working mwc-ripple effekt

**Expected behavior**
The components should not draw weird text containing [object Object]

**Screenshots**
![image](https://user-images.githubusercontent.com/10547444/130336704-66527d94-3472-4c8f-9707-04e32e298ec5.png)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 92

**Comment by LasseRosenow** [comment]
After deleting node_modules and package-lock.json its working

**Comment by chandruchiku** [comment]
@LasseRosenow  Your solution worked for me. I would never know if it was not for you.
