### ISSUE TITLE
Button classes method should align with that of switch

### ISSUE THREAD

**Issue by yinonov** [material-components/material-web#2658]
**Describe the bug**
Button `getRenderClasses` returns a classMap

https://github.com/material-components/material-web/blob/fab48beeb9356f47eee4c481419c7ea6ef97e692/packages/button/mwc-button-base.ts#L92-L99

Switch, on the other hand, returns a simple object and is easy to extend if subclassed

https://github.com/material-components/material-web/blob/fab48beeb9356f47eee4c481419c7ea6ef97e692/packages/switch/mwc-switch-base.ts#L111-L117

**Expected behavior**
Align to a convention, preferably that of switch so it will be easier to control and manipulate if need be

**Comment by yinonov** [comment]
if this should be a convention, would it make sense to align other components to it? can I PR?
it helps with the subclassing. instead of overriding templates, we can just extend the `getRenderClasses` member

**Comment by asyncLiz** [comment]
Obsolete with M3
