### ISSUE TITLE
Cascading Menu / Sub Lists

### ISSUE THREAD

**Issue by a11delavar** [material-components/material-web#2696]
### Is your feature request related to a problem?
Cascading menu: it is described in Material spec [here](https://material.io/components/menus#dropdown-menu) under "Cascading menu (Desktop only)".

![image](https://user-images.githubusercontent.com/38350963/133232326-33d2f4a8-b493-496b-b448-8441d2f15949.png)

### Describe the solution you've considered

I have more or less implemented it by creating a `MenuItem` which extends `ListItem`. MenuItem has now `sub` slot that can contain another menu element (and nothing that doesn't extend `Menu`). Also the `MenuItem` handles the open/close state of that slotted menu element. It works well but does not have accessibility features as it was an emergency solution, so if it would be relevant to have insight on the implementation, please ask.

Telling all that, I would propose that Material team implements something more generic and dynamic, because I have noticed that having **"sub-lists"** for `ListItem`s also makes much sense which is very related to Cascading Menus, technically speaking. Also extending `ListItem` for sub lists doesn't work as well, as its logic and ripple element make it very hard.

Maybe the end-solution should be that `ListItem`s have that `sub` slot, which open the sub-lists inline, and `MenuItem` can override that behavior so it opens as overlay.

The proposal with `ListItem` is not speced in Material, so if it is rejected feel free to consider only the Cascading Menu part and rename the issue, and I will look further to describe extensibility issues with `ListItem` in another issue.

**Comment by arshia11d** [comment]
@neilvanlandingham Hey,

Yeah I thing as an "emergency fix" you can take a look at my code:

https://github.com/3mo-esolutions/model/blob/main/packages/shell/contextMenu/ContextMenuItem.ts

**Comment by asyncLiz** [comment]
Submenus are available now in M3
