### ISSUE TITLE
Support snackbar theming for z-index

### ISSUE THREAD

**Issue by komasoftware** [material-components/material-web#2735]
Is your feature request related to a problem? Please describe.
Can't change the z-index of a snackbar.
The snackbar is hidden under a component not under my control in the page 

Describe the solution you'd like
Support snackbar theming (--mdc-snackbar-z-index) for z-index

Describe alternatives you've considered
I am using rollup to rewrite the z-index during build as a workaround

**Comment by asyncLiz** [comment]
Thanks for the issue! We'll investigate a better solution for z-index in our updated components
