### ISSUE TITLE
Update lit imports (The main 'lit-element' module entrypoint is deprecated. )

### ISSUE THREAD

**Issue by ba55ie** [material-components/material-web#2736]
## Description
The components are upgraded to Lit `2` but the module imports still point to the old and now deprecated `lit-element` package. 

For example: 

- https://github.com/material-components/material-web/blob/master/packages/button/mwc-button.ts#L10
- https://unpkg.com/@material/mwc-linear-progress@0.25.1/mwc-linear-progress.js

## Acceptance criteria

Re-write your module imports appropriately:

From:

`import {LitElement} from 'lit-element';`

To:

`import {LitElement} from 'lit';`

See the Lit upgrade guide: https://lit.dev/docs/releases/upgrade/#update-packages-and-import-paths

**Comment by dfreedm** [comment]
We actually have some work to do internally before we can make this change.

**Comment by ba55ie** [comment]
OK, reading the `v0.25.1` changelog gave me the impression you already had switched to Lit 2 completely.

**Comment by asyncLiz** [comment]
Should be fixed in #2749

**Comment by ba55ie** [comment]
Thanks! 👍
