### ISSUE TITLE
<list-item> Multiple Items selected at the same time with click Gesture in iphone

### ISSUE THREAD

**Issue by icaceresreply** [material-components/material-web#2737]
**Describe the bug**
In iPhone when the user clicks over the list item can select multiple items and we can't disable the multi-selection list item with any code recommendation in the documentation.

**To Reproduce**
1. Go to an mwc-list on an iPhone.
2. Click on  several mwc-list-item at time
3 See error "all the list items are selected and you can't unselect these list-item until you click out side the list item"

**Expected behavior**
when clicking over a  list-item the previous selected list-item be unselect.

**Screenshots**
![image](https://user-images.githubusercontent.com/43349043/134199393-eee50806-7376-4286-b37d-a08999888d98.png)
![multi-selected-items](https://user-images.githubusercontent.com/43349043/134199545-cf57ed33-ba13-4762-856e-10a3709cd7b1.png)

**Browser Version (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome, safari]
 - Version [latestone]

**Additional context**

**Comment by asyncLiz** [comment]
Thanks for the bug report! We'll look into this and see if we can provide a workaround. It may be fixed in our upcoming rewrite for list

**Comment by asyncLiz** [comment]
This shouldn't be an issue anymore with the new `<md-list>` in M3
