### ISSUE TITLE
mwc-switch theming boilerplate

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#2748]
**Describe the bug**
Providing a `--mdc-theme-primary` color to `mwc-switch` does not happen to be enough as this color won't apply to all states (`focused/active/hover`). 

You would need to specify - in addition: 
```css
    --mdc-switch-selected-pressed-handle-color: red;
    --mdc-switch-selected-focus-handle-color: red;
    --mdc-switch-selected-hover-handle-color: red;
```

**To Reproduce**
Steps to reproduce the behavior :
1. Go to https://material-components.github.io/material-web/demos/switch/
2. apply `--mdc-theme-primary: red` to one of the switch
3. see the behavior
 
**Expected behavior**
Colors applied to switch states should be derived from `--mdc-theme-primary`. 

I am aware there is a guide for applying themes to sass, but one (of the many) reasons for using WC is to reduce build steps and tooling in development. 

**Screenshots**

https://user-images.githubusercontent.com/1168053/134536228-18fd9a6b-97c8-475f-a945-ca379de5fede.mp4

**Comment by asyncLiz** [comment]
The updated switch has separate color tokens for multiple states that do not inherit from the primary color (they use a darker variant of the primary color).

As the components are updated, these will use new theme tokens (`--md-sys-color-primary-state-content`), but in the meantime each token should be set individually. You can also set the custom properties to `var(--mdc-theme-primary)` to link them to the primary color custom property.

**Comment by christophe-g** [comment]
Thanks a lot for the answer @asyncLiz 

As an (early) consumer of the material web-components, it would be great to have those details exposed somewhere to be able to plan ahead, and have some visibility on the broader vision/direction.
