### ISSUE TITLE
Importing material/mwc-dialog library from jsDelivr CDN does not work

### ISSUE THREAD

**Issue by IgorNovozhilov** [material-components/material-web#2753]
**Describe the bug**
Importing a library from a CDN does not work:
https://cdn.jsdelivr.net/npm/@material/mwc-dialog/+esm

The associated dependency cannot be resolved:
https://cdn.jsdelivr.net/npm/lit-html@2.0.0/+esm

**To Reproduce**
https://demo-source.github.io/mwc-dialog.v1.html

**Expected behavior / Screenshots**
https://github.com/lit/lit/issues/2190

**Additional context**
Is this problem solved by changing the dependencies in the `material` or do you need fixes from `lit`?

**Comment by asyncLiz** [comment]
Thanks for the issue! Unfortunately we can't support all CDN services and the variety of behaviors that they offer. We recommend installing from npm directly and bundling for production.

For short demos, we try to maintain compatibility with https://unpkg.com and recommend using that when not bundling for production.

**Comment by MartinKolarik** [comment]
@IgorNovozhilov this was an issue at jsDelivr that we just fixed - the demo works now 😄
