### ISSUE TITLE
[mwc-textfield] breaks UI if `type` is set to 'submit', 'reset', 'button'

### ISSUE THREAD

**Issue by yinonov** [material-components/material-web#2759]
**Describe the bug**
the types values of 'submit', 'reset', 'button' will render the native input element as a button, therefore breaks the UI and place a button instead of the expected `contenteditable` input.

**To Reproduce**

**Expected behavior**
The above mentioned types should be restricted / ignored or fallback to a default value and keep textfield as a `contenteditable` input.

**Screenshots**
![image](https://user-images.githubusercontent.com/15140652/134765970-a8a8db00-0de8-4971-b1d0-53038b13ea31.png)

**Comment by dfreedm** [comment]
Thanks for the bug report! 
Given that this looks _obviously_ broken, and that there are probably very few use cases for `submit`, `reset` or `button` types, I think we can just add some documentation and Typescript type validation.

**Comment by yinonov** [comment]
Fair enough!

**Comment by schirrel** [comment]
@dfreedm do you think would be a good approach to throw an error when using these types? Once they are not int `TextFieldType` and are being used at `type` property:
``` @property({type: String}) type: TextFieldType = 'text';```
Or maybe at the `renderInput` return the mwc-button?

**Comment by asyncLiz** [comment]
M3 now has explicit supported and unsupported text field types that are enforced with typescript
