### ISSUE TITLE
[mwc-button] missing value attribute

### ISSUE THREAD

**Issue by yinonov** [material-components/material-web#2766]
**Describe the bug**
`mwc-button` should feature `value` attribute and delegate its actual value to shadow tree `button` element to align with [native behavior](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-value).

**Expected behavior**
`mwc-button` submitting a form should define the value associated with the button’s name alongside form data.

**Additional context**
Not sure this should be a bug report or a feature request.
the reason is that button within shadow tree doesn't associate with form in the light tree, therefore supporting value attribute might not even work as expected until browsers support shadow tree form association out of the box.

#2761 sets the ground for this...

**Comment by patrickrodee** [comment]
We'd recommend using an hidden `<input>` with the value you wish you include or listen for the `"formdata"` event and append the information there. [Here's an example from the MWC checkbox](https://github.com/material-components/material-web/blob/987a534fe75555a1a6b0854f0f9b9f999d72b7d0/packages/checkbox/mwc-checkbox-base.ts#L196).
