### ISSUE TITLE
"step" property of mwc-textfield should take "any" as a valid value

### ISSUE THREAD

**Issue by lsatheeshkumar** [material-components/material-web#2776]
**Describe the bug**
mwc-textfield component ignores step="any" and restricts to whole number while the expectation is that the control should accept any number of decimals. Document about mwc-textfield points to "HTMLInputElement.prototype.step" constraint page which also acknowledges that "any" can be passed as an input to step property.

**To Reproduce**
1. Use mwc-textfield with type="number" and step="any", 
     like., `<mwc-textfield label="AnyDecimals" type="number" step="any"></mwc-textfield>`
2. The control should accept any number of decimals
3. But it ignores the step attribute and restricts only to integers

**Expected behavior**
There should be a way to let the component take any number of decimals if the need be. 
Going by the HTMLInputElement.prototype.step convention, passing in "any" as step's value can be considered as best option.

**Comment by dfreedm** [comment]
Thanks for the bug report!

It looks like the typing of the attribute is set to `Number`, which will discard the `any` string, defaulting to `1`.

As a workaround for now, you can set the `step` property to `any` for now

```ts
class Wrapper extends LitElement {
  @query('mwc-textfield') textfield!: TextField;
  render() {
    return html`<mwc-textfield label="AnyDecimals" type="number"></mwc-textfield>`
  }
  firstUpdated() {
    this.textField.step = 'any';
  }
}
```
