### ISSUE TITLE
mwc-tab-bar does not work when importing with unpkg.com

### ISSUE THREAD

**Issue by IgorNovozhilov** [material-components/material-web#2780]
Сmponent `@material/mwc-tab-bar` does not work when importing with: `import 'https://unpkg.com/@material/mwc-tab-bar?module'`.

 [`mwc-tab-bar-base.ts`](https://github.com/material-components/material-web/blob/6278ee5df98ca7eae0d694e58b052fdbf4b0519d/packages/tab-bar/mwc-tab-bar-base.ts#L18) imports file [`mwc-tab-base.ts`](https://github.com/material-components/material-web/blob/6278ee5df98ca7eae0d694e58b052fdbf4b0519d/packages/tab/mwc-tab-base.ts) as `import {TabBase} from '@material/mwc-tab/mwc-tab-base';`
At the same time file `mwc-tab-base.ts` imported as nested file in [`mwc-tab.ts`](https://github.com/material-components/material-web/blob/6278ee5df98ca7eae0d694e58b052fdbf4b0519d/packages/tab/mwc-tab.ts#L12), which is also imported from `mwc-tab-bar-base.ts` as `import {Tab} from '@material/mwc-tab';`.
And as a result, this check does not work: [`.filter((e: Node) => e instanceof TabBase`](https://github.com/material-components/material-web/blob/6278ee5df98ca7eae0d694e58b052fdbf4b0519d/packages/tab-bar/mwc-tab-bar-base.ts#L78), because the class TabBase declaration is duplicated, because `mwc-tab-base.js`is being downloaded repeatedly:

![Снимок экрана от 2021-09-29 19-59-29](https://user-images.githubusercontent.com/3082812/135315303-4a0aacb7-9d69-4f7c-8dd9-cb98cd913922.png)

![Снимок экрана от 2021-09-29 20-07-12](https://user-images.githubusercontent.com/3082812/135316749-32d2fb70-3b3b-4aec-9756-6c56a0a6653c.png)
2 files:
https://unpkg.com/@material/mwc-tab@0.25.1/mwc-tab-base?module
https://unpkg.com/@material/mwc-tab@%5E0.25.1/mwc-tab-base?module

Example: 
https://demo-source.github.io/mwc-tab-bar.v1.html
https://demo-source.github.io/mwc-tab-bar.v2.html

Problem in https://github.com/material-components/material-web/blob/master/packages/tab-bar/package.json#L20
```  "@material/mwc-tab": "^0.25.1", ```
Specifying a floating version results in 2 different import paths

**Comment by dfreedm** [comment]
Thanks, for the bug report. We can update the tab imports to use the same path and that should fix this issue.

**Comment by asyncLiz** [comment]
Obsolete with M3
