### ISSUE TITLE
No access to change `mwc-select` -> `.mdc-select__anchor` -> `200px`

### ISSUE THREAD

**Issue by IgorNovozhilov** [material-components/material-web#2801]
I have a need to set `mwc-select` field width to `auto`.
At the moment, this is limited by the style `.mdc-select__anchor { width: 200px; }` and is not available for modification.

actual  | expected
------------- | ------------
![Снимок экрана от 2021-10-02 15-21-29](https://user-images.githubusercontent.com/3082812/135716356-6de683c2-9709-4381-a9c0-07e7d2672b01.png) | ![Снимок экрана от 2021-10-02 15-21-40](https://user-images.githubusercontent.com/3082812/135716388-a75e451e-f36a-4155-8950-babdc6c37c5d.png)

Is it possible to implement this as a configurable option value?

**Comment by asyncLiz** [comment]
The new `<md-select>` width and inner `<md-menu>` should be customizable using `md-select::part(menu)`
