### ISSUE TITLE
[mwc-menu-surface] right-click does not close the menu

### ISSUE THREAD

**Issue by mkorenko** [material-components/material-web#2805]
**Describe the bug**
mwc-menu-surface dependent controls do not close on right-click on the body

**To Reproduce**
1. Open any control that depends on mwc-menu-surface (mwc-select, mwc-menu, etc.)
2. Right-click somewhere on the page

**Expected behavior**
The menu should close, same as when left-clicked

**Additional context**
mwc-menu-surface only listens for the 'click' event, however when right-clicked the 'click' event is not fired by the browser. I suppose a separate 'contextmenu' event listener needs to be added along with the 'click' event listener to handle right-clicks.

**Comment by patrickrodee** [comment]
The context menu (right click) does not close the menu by design.
