### ISSUE TITLE
[mwc-menu] Updating the x and y properties does not update the menu's position

### ISSUE THREAD

**Issue by neilvanlandingham** [material-components/material-web#2833]
An example of the bug:
https://jsfiddle.net/weft_digital/s6m94cpn/18/

**Expected behavior**
The menu position should update when the x and y properties are changed without having to close and reopen the menu.

**Additional context**
This is important for using mwc-menu as a context menu that updates its position on repeated right clicks without closing first.

**Comment by asyncLiz** [comment]
Obsolete with M3
