### ISSUE TITLE
<mwc-checkbox> ignores `backface-visibility: hidden` CSS property

### ISSUE THREAD

**Issue by EvilTosha** [material-components/material-web#284]
Demo: https://codepen.io/anon/pen/mYgVRP

<mwc-checkbox> continues to be visible on the other side of the element after it's been flipped, ignoring `backface-visibilit: hidden` property.

**Comment by azakus** [comment]
We'll need to explore this a bit, but it probably needs to fit into our theming capabilities, tracked in #526

**Comment by asyncLiz** [comment]
Should be fixed in M3, please open a new issue if `<md-checkbox>` does not fix the problem!
