### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-icon" has already been used with this registry

### ISSUE THREAD

**Issue by maicol07** [material-components/material-web#2844]
**Describe the bug**
Exception after building the project with Vite:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-icon" has already been used with this registry
```
Uncompiled version when using the Vite server works fine

**To Reproduce**
1. Import two components in two different places and import one in the other
2. Build with Vite
3. Open your page in the browser

**Expected behavior**
Custom element doesn't get defined the second time if it already exists. You should add a check if it already exists

**Browser Version (please complete the following information):**
 - OS: Windows 11
 - Browser: All
 - Version: 0.25.2

**Additional context**
I think it's related to #1999 but no official fix was pushed. You should put common dependencies in `peerDependencies`, like he said in this comment: https://github.com/vitejs/vite/issues/1235#issuecomment-745036564

**Comment by allan-chen** [comment]
Thanks for the issue. I will discuss with the team during triage on using `peerDependencies`. In the meantime please try the workaround in https://github.com/material-components/material-web/issues/1999#issuecomment-744718091 regarding bundling everything into one module.

In the long term, we will likely forego the one-component-per-package publishing structure, and instead publish the entirety of MWC in one node package.

**Comment by allan-chen** [comment]
Discussed in triage. As mentioned above, we will be merging all the packages in the future and hence will not be tinkering with the peer dependency structure for now. Please continue to use the workaround above until then.
