### ISSUE TITLE
accepts input other that the specified

### ISSUE THREAD

**Issue by GanesanDinesh** [material-components/material-web#2897]
**Describe the bug**
When we specify the type to the text area as tel or number , the user can able to input a different type other than one which is specified and there are no validation css applied for end user to know it is a wrong input

**To Reproduce**

<mwc-textarea type="number" label="Standard" helper="Helper Text" helperpersistent=""></mwc-textarea>
<mwc-textarea type="tel" label="Standard" helper="Helper Text" helperpersistent=""></mwc-textarea>

**Expected behavior**
there could be error stating the input is invalid when the input value is other than specified type

![image](https://user-images.githubusercontent.com/93591748/139847384-4cfda590-32ce-46bc-8bbf-cb6a0155fcee.png)

**Comment by asyncLiz** [comment]
Thanks for the bug! This is working as intended since the `<textarea>` native element does not have a `type` attribute. Use `<mwc-textfield type="number">` instead of a textarea, or the `inputmode` attribute to suggest which keyboard should be displayed.

**Comment by GanesanDinesh** [comment]
Hi I looked into below link https://github.com/material-components/material-web/tree/master/packages/textarea where type is one of property , can you please let me know if the documentation is wrong or support will be provided
