### ISSUE TITLE
Textarea: validation is not happened correctly when maximum value is set even ValidateOnInitialRender

### ISSUE THREAD

**Issue by GanesanDinesh** [material-components/material-web#2899]
Textarea: validation is not happened correctly when maximum value is set even ValidateOnInitialRender

I have text area with maxLength="6". But when we have longer text more than 6 in value(in code) or set value to the field with longer text then still all values are getting displayed . validation is happened only when clicking on text area field and backspace is pressed.

Expected: 1. Either only max length of 6 letter should display.
OR
2. validation should throw when we try to type some value in text area and tab out.

Please find the attached sample project

**Comment by dfreedm** [comment]
Hi, I'm not seeing any attached example.

Can you make one on the [lit.dev playground](https://lit.dev/playground/)?

**Comment by GanesanDinesh** [comment]
Hi,
Please find the attached html input for text area if we set max length=6 and set the initial value the validation is not happening on inital render even if we set  ValidateOnInitialRender.
So if we have empty value and type in some text validation is correct.

 <mwc-text-area
      label="Relation Code"
      helper="Helper text"
      helperPersistent
      type="number"
      maxLength="6"
      charCounter
      value="testing in new text area"      
  ></mwc-text-area>

**Comment by patrickrodee** [comment]
Thanks for filing this bug. This is the native behavior for HTMLInput elements: value set programmatically is not restricted by `maxlength` (see https://jsbin.com/xupadusivo/edit?html,output) while user input is. For that reason, I'm going to close this. Let me know if you have any questions!
