### ISSUE TITLE
[mwc-button] Icon is not vertically aligned with the button text

### ISSUE THREAD

**Issue by contis2908** [material-components/material-web#2900]
**Describe the bug**
Displaying a button containing an icon and text will not show them both vertically aligned.

**To Reproduce**
Implement mwc-button with property icon and label

**Expected behavior**
Text and icon should be automatically alligned.

**Screenshots**
<img width="221" alt="Screenshot 2021-11-03 at 12 13 50" src="https://user-images.githubusercontent.com/28650465/140050722-e42e00db-ca42-4e88-9432-04046dc43930.png">

**Browser Version (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: tested in chrome
 - Version: Version 95.0.4638.54 (Official Build) (x86_64)

**Additional context**
The problem can be fixed if the `span` container with class `leading-icon` (that holds the slotted icon)
css display  is set to `display: contents;`

**Comment by dfreedm** [comment]
Ah, the span's line-height is larger than the icon's. Good catch!

**Comment by contis2908** [comment]
Yes, then line-height inheritance is a problem. However, I believe that this isn't enough depending on the expected outcome.
I would expect the text and icon to be aligned in the center. Fixing the line-height will position them just on their baseline.
While this is fine I believe that depending on the icon in many situations this will give a weird look to the button.
<img width="223" alt="Screenshot 2021-11-04 at 11 07 10" src="https://user-images.githubusercontent.com/28650465/140295453-0d178afe-ad46-49ea-af73-556b01d51684.png">
<img width="228" alt="Screenshot 2021-11-04 at 11 07 24" src="https://user-images.githubusercontent.com/28650465/140295455-be0de018-8e7d-4b8a-a475-3a31b6445406.png">

**Comment by christophe-g** [comment]
> in many situations this will give a weird look to the button.

Like, possibly related: #1045, #2131.

**Comment by asyncLiz** [comment]
Fixed in M3
