### ISSUE TITLE
Ensure repository information is included in published `package.json` file

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-web#2902]
As laid out in https://github.com/material-components/material-web/pull/2878, the repository field in `package.json` is used to by some companies to verify that PRs are made to correct packages from npm.

**Comment by asyncLiz** [comment]
It sure is!

https://github.com/material-components/material-web/blob/6aa42f3399e9b8433a6920a6e6779d16a0c55cce/package.json#L8-L11
