### ISSUE TITLE
Import of 'nothing' from 'lit' creates error in rollup build

### ISSUE THREAD

**Issue by jannikkerczynski** [material-components/material-web#2905]
Hey, 

In the mwc-select-base the import of 'nothing' like this

**import { html, nothing } from 'lit';**

creates a error in the rollup build:

[!] Error: 'nothing' is not exported by node_modules/lit/index.js, imported by node_modules/@material/mwc-select/mwc-select-base.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@material/mwc-select/mwc-select-base.js (20:15)
18: import { lineRipple } from '@material/mwc-line-ripple';
19: import MDCSelectFoundation from '@material/select/foundation';
20: import { html, nothing } from 'lit';
                   ^
21: import { eventOptions, property, query, state } from 'lit/decorators.js';
22: import { classMap } from 'lit/directives/class-map.js';
Error: 'nothing' is not exported by node_modules/lit/index.js, imported by node_modules/@material/mwc-select/mwc-select-base.js

https://github.com/material-components/material-web/blob/4f1c42271ddce379e5fdb742810718a622f348ef/packages/select/mwc-select-base.ts#L29

**Comment by asyncLiz** [comment]
Obsolete with M3
