### ISSUE TITLE
[mwc-list] 'request-selected' fires twice 

### ISSUE THREAD

**Issue by yinonov** [material-components/material-web#2917]
**Describe the bug**
checklist item `request-selected` fires twice when mouse clicked

**Expected behavior**
it should only fire once

**Screenshots**

https://user-images.githubusercontent.com/15140652/141305445-81a39c05-04b9-431c-afec-bd5a48ccda0d.mov

**Additional context**
note this only happens on mouse click and not on keydown (enter)

**Comment by patrickrodee** [comment]
Thanks for your report! A new version of list is on our roadmap that will have this issue resolved.

**Comment by e111077** [comment]
N/A in M3
