### ISSUE TITLE
[textarea] missing icons implementation

### ISSUE THREAD

**Issue by yinonov** [material-components/material-web#2926]
**Describe the bug**
textarea documents `icon` and `trailingicon` as part of its API but in practice there's no implementation
 
![image](https://user-images.githubusercontent.com/15140652/141813927-75ba3b20-3ee6-45b4-9a32-d4fccbc576eb.png)

https://github.com/material-components/material-web/blob/987a534fe75555a1a6b0854f0f9b9f999d72b7d0/packages/textarea/mwc-textarea-base.ts#L97-L114

**Expected behavior**
textarea should implement icons in template

**Comment by asyncLiz** [comment]
Thanks for the bug! This is definitely a documentation issue since textarea does not have icons.

**Comment by yinonov** [comment]
couldn't find any ref to textarea in the material.io guidelines.
mind sharing the reasons?

**Comment by yinonov** [comment]
oh there's this reference pointing out textarea as a text field type
![image](https://user-images.githubusercontent.com/15140652/141933493-8a290edd-6d12-4603-a4b4-89762c5cfc5d.png)
