### ISSUE TITLE
[mwc-textfield/area] labels should use theming

### ISSUE THREAD

**Issue by opaldes** [material-components/material-web#2932]
Currently it seems that the textfield/area component uses a fixed font for the label. 

It should use fonts set by the theme.

currently inside CSS:
font-family: Roboto, sans-serif;

How it should be set:
font-family:var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family, Roboto,))

**Comment by sayris** [comment]
Hello! Textfield label is currently using themeing (see [this example](https://jsbin.com/duhiboxuta/edit?html,output)) -- looks like maybe you're using the wrong var name (`--mdc-typography-body2-font-family` vs `--mdc-typography-subtitle1-font-family`). 

I'm closing this for now, but feel free to reopen if you run into more issues.
