### ISSUE TITLE
How do we override sass variables?

### ISSUE THREAD

**Issue by MrHBS** [material-components/material-web#2934]
I have noticed that the sass variables are not defined with the `!default` flag. How do we override sass variables?

**Comment by sayris** [comment]
You don't -- if there's not a `!default` flag then it's not intended to be overwritten. 

Can you give more info on what specifically you're trying to do?

**Comment by MrHBS** [comment]
@sayris How do you change the default theme of a switch for example?

**Comment by sayris** [comment]
You can use the Theme API (see [`_switch-theme.scss`](https://github.com/material-components/material-web/blob/master/components/switch/lib/_switch-theme.scss) for what is themable) -- you can use the `theme` and/or `theme-styles` mixin to apply your desired theme (the `$light-theme` map has all possible values that you can configure, you can supply a subset of those values or override all of them).
