### ISSUE TITLE
Got error Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by matishwlocusview** [material-components/material-web#2943]
**Describe the bug**
I have an angular project and use web component with  lit library.
I follow the tutorial how to install material-web.
When I run the project with ng serve I go this error
'Got error Uncaught SyntaxError: Cannot use import statement outside a module' and it from this

import { __decorate } from "tslib";

**To Reproduce**
Create a new angular project
install lit
install material web
add  to app.component.html  <mwc-button id="myButton" label="Click Me!" raised></mwc-button>

**Expected behavior**
will show the button

**Screenshots**
![image](https://user-images.githubusercontent.com/69752363/143217781-6cf2a1ac-bc23-4cdb-b675-bec99be6f75c.png)

**Browser Version (please complete the following information):**

 - Browser [chrome]

**Comment by joyzhong** [comment]
This error seems specific to your project's build / serve configuration. Closing as this is not a MWC-specific bug.

Please see e.g. https://stackoverflow.com/questions/58211880/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-import for debugging ideas.
