### ISSUE TITLE
On select event on text field not triggering 

### ISSUE THREAD

**Issue by GanesanDinesh** [material-components/material-web#2956]
Hi Team,

We have a requirement to do some work when the user selects the text in the mdc text field component using ( ctlr + a  key board event or mouse select event)

in the below example i can see there is a onselect event triggering for the both the scenarios but in our mdc text field there is a event called select which i tired for the same & it did not trigger.

Can you please let me know if there is any solution for the req.

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onselect

**Comment by abhiomkar** [comment]
Can you please share example that you've tried which didn't work for you? MDC Text Field uses native input element and it should trigger same events as native input element.

**Comment by GanesanDinesh** [comment]
find the attached sample below where i am able to trigger onblur,onfocus events but onselect is not triggered even though i selected the text as in w3 schools example where it triggered correctly

![image](https://user-images.githubusercontent.com/93591748/144966101-5024696d-2a7b-45f6-84b9-eebb079fdbd8.png)

![image](https://user-images.githubusercontent.com/93591748/144966117-9351b177-de3c-4c13-8c7c-3b0f88c6012a.png)

**Comment by asyncLiz** [comment]
Thanks for the bug! We'll need to forward this event since `select` events aren't composed like others (such as `copy`).

We should also check other [`<input>` events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#events) for additional events that may need forwarded.
