### ISSUE TITLE
form.reportValidity() doesn't appear to work properly

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#2972]
If I have an `<mwc-textarea required>` inside a form (that's the only element) then check the form for validity using `f.reportValidity()` it always returns true. Even though the textarea is displaying as invalid with red border. 

**To Reproduce**

```html
<form id="comment-form">
<mwc-textarea required>
</form>

<script>
let f = document.querySelector("#comment-form")
console.log("VALID?", f.reportValidity(), f.checkValidity())
</script>
```

**Comment by asyncLiz** [comment]
Thanks for the bug! Currently our components participate in forms using the `formdata` event. Additional features like report validity are part of the form associated elements spec, which we have not implemented.

**Comment by treeder** [comment]
Feels like these issues shouldn't be closed if they are open bugs. Or at least document it is a known issue or even if it's not considered an issue and something that will never be implemented, should still be documented as almost every developer in the world depends on these standard APIs for form validation.

**Comment by treeder** [comment]
related: https://github.com/material-components/material-web/issues/971
