### ISSUE TITLE
mwc-switch does not pass the value 

### ISSUE THREAD

**Issue by malakeel** [material-components/material-web#2985]
**Describe the bug**
When an event is emitted, the value of the control is always "on"

**To Reproduce**

<mwc-switch id="my-switch" selected title="display" ></mwc-switch>

const mySwitch = document.querySelector('#my-switch')

mySwitch.addEventListener('click', (e) => {
    console.log(e.target.value)
});

**Expected behavior**
The value should be updated to reflect the state of the control. I couldn't find a way to tell the value

**Browser Version (please complete the following information):**
 - OS: Linux/Gentoo
 - Browser: Firefox
 - Version: 91.4.0esr (64-bit)

**Additional context**
Missing documentation and example on how to use it, to make it easier to test and generate the errors

**Comment by asyncLiz** [comment]
This is [working as intended for checkbox-like components](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value). The value is static (defaults to `"on"`) and is either submitted in the form if checked, or is not added to the form at all if unchecked (it does not change the value to `"off"`).

**Comment by brownieboy** [comment]
> This is [working as intended for checkbox-like components](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value). The value is static (defaults to `"on"`) and is either submitted in the form if checked, or is not added to the form at all if unchecked (it does not change the value to `"off"`).


Errmm... so why does `<mwc-checkbox>` have a `change` event then?

**Comment by asyncLiz** [comment]
I don't see how the `change` event is related. `change` on `<input type="checkbox">` is an event that dispatches when the `checked` attribute changes, not the `value` attribute.

`value` is the string that is submitted to the form _only when_ the checkbox is checked. It _will not be included_ in the form submission if the checkbox is unchecked.

**Comment by brownieboy** [comment]
Okay, where do I get the `checked` attribute?   I'm not seeing it what's returned by the `click` event anywhere either.

**Comment by asyncLiz** [comment]
```html
<mwc-checkbox name="checkbox" value="User accepted conditions"></mwc-checkbox>
<mwc-switch name="switch" value="Switch is on"></mwc-switch>

<script>
  document.querySelector('mwc-checkbox').addEventListener('change', e => {
    const isChecked = e.target.checked; // Changes, same as e.target.hasAttribute('checked')
    const formValue = e.target.value; // Does not change
  });
  
  document.querySelector('mwc-switch').addEventListener('click', e => {
    const isSelected = e.target.selected; // Changes, same as e.target.hasAttribute('selected')
    const formValue = e.target.value; // Does not change
  });
</script>
```

If both the checkbox and switch are checked/selected respectively and a form is submitted, this is the form data:
```json
{
  "checkbox": "User accepted conditions",
  "switch": "Switch is on"
}
```

If both are unchecked/unselected, the form data is empty
```json
{
}
```


This is the native equivalent of:
```html

<input type="checkbox" value="User accepted conditions">

<script>
  document.querySelector('input').addEventListener('change', e => {
    const isChecked = e.target.checked; // Changes, same as e.target.hasAttribute('checked')
    const formValue = e.target.value; // Does not change
  });
</script>
```

**Comment by asyncLiz** [comment]
aka, there's no point in syncing `selected` to and setting `value="off"`. It will never be submitted in a form (the point of name/value attributes)

**Comment by brownieboy** [comment]
Actually `evt.target.selected` _does_ get changed when I use the `@change` event.

The Chrome Dev tools weren't showing it when I used `console.log(evt)`.  But when I use `console.log(evt.target.selected)` I can see the value change from `true` or `false`. 

So all good. 😊

Thanks again for your help, @asyncLiz .
