### ISSUE TITLE
Harmonizing Custom Colors: Is HCT Documented?

### ISSUE THREAD

**Issue by michaelurban** [material-components/material-web#3058]
I'd like to start using M3, Material You, the other name I heard it being called, today but I'm having some trouble with color. 

I've been able to generate tonal color palettes using LCH, but when it comes to "harmonizing" colors [0] the method isn't described at all. Looking at the Android code it's pretty simple but the harmonized color is expressed in HCT, which I can't find any information about at all. Anywhere.

I'm working on the web. Returning the final color as LCH gives me something *close* to the expected result, but, I don't know enough about color and color spaces to confidently say what "close" means in this context. 

**What is HCT and is there a library to use it with Sass/CSS?** If you have a Sass implementation internally, could you release it sooner rather than later? 

I love Material, but it's often frustrating to read about the what (like harmonizing colors) without any discussion of methods. One more tab with technical details would really help. I happy to help if there's any interest in this.

```
$custom: #1f70f5;
$primary-color: #4e8335;

$harmonize-max-degrees: 24 !default;
$harmonize-percentage: 5 !default;

@function _difference-degrees($a, $b) {
  @return 180deg - math.abs(math.abs($a - $b) - 180deg);
}

@function _sanitize-degrees($degrees) {
  @if ($degrees < 0deg) {
    @return ($degrees % 360deg) + 360deg;
  } @else if ($degrees >= 360deg) {
    @return $degrees % 360deg;
  }

  @return $degrees;
}

@function _rotation-direction($from, $to) {
  $a: $to - $from;
  $b: $to - $from + 360;
  $c: $to - $from - 360;

  $aAbs: math.abs($a);
  $bAbs: math.abs($b);
  $cAbs: math.abs($c);

  @if ($aAbs <= $bAbs and $aAbs <= $cAbs) {
    @return if($a >= 0, 1, -1);
  } @else if ($bAbs <= $aAbs and $bAbs <= $cAbs) {
    @return if($b >= 0, 1, -1);
  } @else {
    @return if($c >= 0, 1, -1);
  }
}

@function harmonize($from, $to) {
  $fromLightness: blend.lightness($from);
  $fromChroma: blend.chroma($from);
  $fromHue: blend.hue($from);

  $toHue: blend.hue($to);

  $degDiff: _difference-degrees($fromHue, $toHue);

  $rotationDegrees: math.min(
    $degDiff * $harmonize-percentage,
    $harmonize-max-degrees
  );

  $rotationDirection: _rotation-direction($fromHue, $toHue);

  $harmonizedHue: _sanitize-degrees(
    $fromHue + ($rotationDegrees * $rotationDirection)
  );
  // @oddbird/blend
  @return blend.lch($fromLightness $fromChroma $harmonizedHue);
}

@debug harmonize($custom, $primary-color);
```

**Comment by joyzhong** [comment]
Take a look at https://github.com/material-foundation/material-color-utilities, I believe this has utilities for harmonizing: https://github.com/material-foundation/material-color-utilities#blend.

**Comment by michaelurban** [comment]
@joyzhong THANK YOU! I've been using material for years and I've never seen the foundation repo.
