### ISSUE TITLE
Helper text not consistent

### ISSUE THREAD

**Issue by lsatheeshkumar** [material-components/material-web#3066]
**Is your feature request related to a problem? Please describe.**
Text-field and its derived components have helper and helperPersistent properties. Setting just the helper property would show the helper only on focus and setting helperPersistent would show the helper always.
Select has helper that always shows by default and controls like checkbox or radio doesn't have helper at all
On a form with mixed input fields, the helper behavior is inconsistent. 

**Describe the solution you'd like**
Good to have helper and helperPersistent properties(as its in text-field) in all the input controls in order to provide a consistent look and feel when used in a form that has mixed controls

**Comment by LisaPritchard** [comment]
Any update?  The different helper text behaviours of the components is problematic on our forms.

**Comment by christophe-g** [comment]
Possibly related: https://github.com/material-components/material-web/issues/1838

**Comment by asyncLiz** [comment]
In M3 things should be aligned as "supporting text" for taxonomy
