### ISSUE TITLE
Two material web repositories in this org, what's the difference and which one should we be using?

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#3067]
I found this: https://github.com/material-components/material-components-web which also looks active.

Can someone explain the difference and which is better to use going forward?

**Comment by yaraju** [comment]
Please see issue #3050 where one of the repo contributors, @jbingham shared info about this last week... Quoting for reference...

"material-components-web is our Material 2 implementation, available today. It will not be updated for Material 3.
material-web will be the Material 3 implementation. It's in progress and will launch in late 2022.

Our goal is for material-web to be a long-term supported library that supports M3 and future design refreshes as well."

**Comment by jbingham** [comment]
That's correct! Thanks @treeder  for asking, and thanks to @yaraju for answering.
