### ISSUE TITLE
Allow mwc-fab to be used without an icon

### ISSUE THREAD

**Issue by portlandnorway** [material-components/material-web#3094]
**Is your feature request related to a problem? Please describe.**
I would like to use mwc-fab extended without an icon. Currently, it is required. So, I have to override it.

**Describe the solution you'd like**
When using mwc-fab extended, if icon isn't provided, don't leave icon spacing. Here's what it looks like when I don't provide an icon='something'

![Screen Shot 2022-02-02 at 3 02 31 PM](https://user-images.githubusercontent.com/57449291/152168597-7351581b-3487-4ad9-9107-e002373d348b.png)

**Describe alternatives you've considered**
I'm currently using a workaround in Lit to hide the icon area: 
```
@query('mwc-fab') fab;

async firstUpdated() {
        await this.fab.updateComplete;
        this.fab
            .shadowRoot
            .querySelector('.mdc-fab__icon')
            .style.display = 'none';
}
```

**Additional context**
N/A

**Comment by asyncLiz** [comment]
Thanks for the issue! This would be WAI since the Floating Action Button is primarily an icon button (that may optionally have text).

If you want just a regular button, use `<mwc-button>` and customize it for a pill shape.

**Comment by portlandnorway** [comment]
Sounds good. I just like the additional effects that come with FAB, and see that MDC has this [option](https://material.io/components/buttons-floating-action-button/web#extended-fabs), but really, not a big deal! Thanks for the time :)
