### ISSUE TITLE
[mwc-button] outlined button --mdc-theme-primary will also set button text color

### ISSUE THREAD

**Issue by chxx-v** [material-components/material-web#3119]
[mwc-button] outlined button **--mdc-theme-primary** will also set button text color, using **--mdc-theme-on-primary** won't set the text color. 
eg: 

```
<body>
  <style>

    mwc-button[outlined] {
      --mdc-theme-primary: yellow;
      --mdc-theme-on-primary: black;
      --mdc-button-outline-color: red;
    }
    
  </style>
  <mwc-button outlined label="Button" unelevated></mwc-button>
  <mwc-button outlined label="Button"></mwc-button>
</body>
```

<img width="216" alt="Screen Shot 2022-02-14 at 3 26 58 PM" src="https://user-images.githubusercontent.com/86745553/153944358-6bc0b409-82e6-456b-8f13-7a88728cf27d.png">
The button text is controlled by --mdc-theme-primary; and at unelevated state, the whole button will be yellow, with no text shown. I want an outlined unelevated button with different background color and text color.

**Comment by chxx-v** [comment]
![Screen Shot 2022-02-14 at 3 47 54 PM](https://user-images.githubusercontent.com/86745553/153944255-c744cc6e-056d-4090-921b-1a43477d7b51.png)
this will be my goal

**Comment by maicol07** [comment]
> ![Screen Shot 2022-02-14 at 3 47 54 PM](https://user-images.githubusercontent.com/86745553/153944255-c744cc6e-056d-4090-921b-1a43477d7b51.png)
> this will be my goal

@chxx-v you can override the CSS vars in your button element through the style attribute or via CSS class:

```
<mwc-button style="--mdc-theme-primary: black;"></mwc-button>
```

**Comment by chxx-v** [comment]
@maicol07 but when the option is selected, it will fill the whole background with black color, no text can be read.

**Comment by asyncLiz** [comment]
Fixed in M3
