### ISSUE TITLE
FR: New theme tool that generate styles that support this library

### ISSUE THREAD

**Issue by omar2205** [material-components/material-web#3173]
**Is your feature request related to a problem? Please describe.**
Using [material-theme-builder](https://material-foundation.github.io/material-theme-builder/#/custom) doesn't export colors for this library.

**Describe the solution you'd like**
A tool to generate theming colors that support `--mdc-theme-`

**Additional context**
The tool mentioned above produces `--md-sys-color-primary` CSS variables, which this library doesn't use.

**Comment by asyncLiz** [comment]
This is actively being added with [the M3 component tokens](https://github.com/material-components/material-web/tree/master/components/sass/tokens) and `theme()` mixins :)
