### ISSUE TITLE
mwc-dialog with a fixedMenuPosition mwc-select has a transparency/bleeding issue on iOS chrome/safari

### ISSUE THREAD

**Issue by kaseyhinton** [material-components/material-web#3232]
**Describe the bug**
When using an mwc-dialog containing an mwc-select with the fixedMenuPosition attribute on it causes the footer actions to bleed through the slotted mwc-list-items.

**To Reproduce**
1. open the select
2. look for footer actions bleeding through the list items

**Expected behavior**
The mwc-menu and mwc-list-items it contains should appear over the footer actions with no actions bleeding through

**Screenshots**
Here is a screenshot of the issue on an up-to-date iPhone SE.
![IMG_2088](https://user-images.githubusercontent.com/20712428/157544430-ab560427-b44c-4ab7-ada2-4ce8677ce9c1.jpg)

Code sandbox that demonstrates the issue.
https://codesandbox.io/s/silly-shirley-2gve70?file=/index.html

**Browser Version**
 - OS: iOS 15.3.1
 - Browser Safari, Chrome

**Comment by omar2205** [comment]
it's not bleeding for me
![image](https://user-images.githubusercontent.com/1373867/158917285-e01c0e99-9186-4885-8e91-f23935935324.png)

**Comment by omar2205** [comment]
Do you have hardware acceleration off?

**Comment by kaseyhinton** [comment]
> 

What version of iOS are you trying to use to reproduce?

**Comment by omar2205** [comment]
Sorry my bad, didn't see iOS part.

**Comment by asyncLiz** [comment]
Should be fixed in M3
