### ISSUE TITLE
`mwc-checkbox` link is incorrect

### ISSUE THREAD

**Issue by hello-smile6** [material-components/material-web#3252]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/material-components/material-web/blob/d8bcc64a45c84fbcfee430f98d1bdf51b8e0fc3e/README.md?plain=1#L41
2. Scroll to the right
3. Observe that the `npmjs.com` link is incorrect.

**Expected behavior**
I was expecting the link to be correct.

**Screenshots**

**Browser Version (please complete the following information):**
 - OS: Not applicable
 - Browser: Not applicable
 - Version: Not applicable

**Additional context**
The bug was introduced in af9c0471443819082850b13b9c9efb6a7a088aed. Prior to that commit, the content did not exist at all. Additionally, it appears that some links to content within the repo are outdated. Fixing would just require this:
```bash
dd if=README.md|tr "https://github.com/material-components/material-components-web-components" "https://github.com/material-components/material-web"|dd of=README.md
```
It appears that there are 50 instances of incorrect github links, 25 of which are for the individual components.
I'd create a pull request, but I don't want to make my Github email public.

**Comment by schirrel** [comment]
I have no problems sharing my email, can i update this?

**Comment by asyncLiz** [comment]
Closing this as obsolete
