### ISSUE TITLE
Add TypeScript typings for events

### ISSUE THREAD

**Issue by samuelli** [material-components/material-web#326]
It'll be great to export the type of a custom event. For example: with https://github.com/material-components/material-components-web-components/blob/master/packages/tab-bar/src/mwc-tab-bar-base.ts#L148 it'll be helpful to have `detail: index` typed and documented.

**Comment by aomarks** [comment]
Good idea. I think we can augment the global `HTMLElementEventMap` interface, so that `addEventListener` callbacks are automatically typed correctly (similar to the `HTMLElementTagNameMap` interface).

**Comment by web-padawan** [comment]
> I think we can augment the global HTMLElementEventMap interface, so that addEventListener callbacks are automatically typed correctly

Do you have any actual example of how to handle it correctly?
We'd like to use the same approach for Vaadin components.

**Comment by bennypowers** [comment]
I've been doing `Event & { detail: SomeType }`, but that's less than ideal

**Comment by asyncLiz** [comment]
Obsolete with M3, we should be providing typings for events that have unique types/values. Overall we're no longer using `CustomEvent` with data as the norm in M3
