### ISSUE TITLE
mwc-tab-bar should have `activeTab` and `tabs` properties

### ISSUE THREAD

**Issue by samuelli** [material-components/material-web#327]
AFAIK, there's no way to get the tab element, besides looking into the slots. Given that `index` is a semantic defined by `mwc-tab-bar`, it would make sense to return the tab element that triggered the event. Currently only `index` is returned.

Source: https://github.com/material-components/material-components-web-components/blob/d3ed76bc3f49e547007157d6463d035f7bd449d6/packages/tab-bar/src/mwc-tab-bar-base.ts#L148-L149

**Comment by asyncLiz** [comment]
Will be fixed in M3
