### ISSUE TITLE
`elevation-overlay` demo is broken

### ISSUE THREAD

**Issue by hello-smile6** [material-components/material-web#3277]
**Describe the bug**
The [`elevation-overlay` demo](https://material-components.github.io/material-web/demos/elevation-overlay/) fails to run.

**To Reproduce**
1. Go to [material-components.github.io/material-web/demos/elevation-overlay](https://material-components.github.io/material-web/demos/elevation-overlay/)
2. Observe the content. Or, if you prefer, the absence of it.

**Expected behavior**

**Screenshots**

**Browser Version (please complete the following information):**
 - OS: Windows
 - Browser: Chromium
 - Version: [99.0.4844.74](https://chromium.googlesource.com/chromium/src.git/+/refs/tags/99.0.4844.74)

**Additional context**
It seems like [`index.js`](https://material-components.github.io/material-web/demos/elevation-overlay/index.js) failed to build, based on the content of the first line. An empty commit might fix it...
```js
import{style as t}from"@material/mwc-elevation-overlay/mwc-elevation-overlay-css";
```
Based on the error in IE11, the CSS for the component might be failing to load while building.
```log
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
elevation-overlay
HTML1300: Navigation occurred.
elevation-overlay
SCRIPT5009: 'mwcElevationOverlayCss' is undefined
index.es5.js (1,2)
```
Based on the build log, it seems that building the CSS failed.
https://github.com/material-components/material-web/runs/5677794914?check_suite_focus=true#step:4:520
Chromium DevTools log:
[material-components.github.io-1648168319660.log](https://github.com/material-components/material-web/files/8346497/material-components.github.io-1648168319660.log)

**Comment by asyncLiz** [comment]
Thanks for the bug! We'd welcome a PR to address it

**Comment by asyncLiz** [comment]
Obsolete in M3
