### ISSUE TITLE
mwc-menu placement gets affected be parent height (placed with offset)

### ISSUE THREAD

**Issue by Biggisb** [material-components/material-web#3293]
**Describe the bug**
In some cases when using the fox-menu (or select) we saw that the component does not get placed where we would want it to be. For us its somehow random but maybe i miss something. Therefore i created a stackblitz file

**To Reproduce**
1. Go to  https://stackblitz.com/edit/node-l5vcwq?file=index.js
2. Click on the "more_vert" icon of the list elements.

**Expected behavior**
Menu should be placed like in the first example. 
![image](https://user-images.githubusercontent.com/17909825/160885867-086ea792-f7e5-4ff6-97b3-8f74c36c0ab4.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17909825/160885806-912efafb-f90b-4229-a99f-b419e3644f0a.png) 
 

**Additional context**
The same "offset" problem apply both horizontal and vertical

**Comment by asyncLiz** [comment]
Obsolete with M3
