### ISSUE TITLE
Change mdc-notched-outline-stroke-width

### ISSUE THREAD

**Issue by azoom-du-cong-cuong** [material-components/material-web#3304]
Hi, I'm having a problem that I need to change the variable
--mdc-notched-outline-stroke-width from 2px to 1px,
  i have tried
@import '@material/notched-outline/mixins';
.mdc-text-field.mdc-text-field--focused .mwc-notched-outline {
         @include mdc-notched-outline-stroke-width(1px);
       }
but it doesn't work,
can you give me how to solve this problem or related documents no

**Comment by asyncLiz** [comment]
The outline is already 1px, but you can set the `--mdc-notched-outline-stroke-width` variable to values other than 1: https://jsbin.com/dihuturuqo/1/edit?html,output

**Comment by asyncLiz** [comment]
Gotcha, this is fixed now in the Material 3 `<md-outlined-text-field>`, which has separate custom properties for the width in default/hover/focus states. That will be made available in the next couple of weeks :)
