### ISSUE TITLE
[mwc-slider] label next to value

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#3335]
https://github.com/material-components/material-web/blob/9ab9eb38812a745961181f00b85d4cddf18a60da/packages/slider/slider-base.ts#L228

Would it be possible to add an element's property `label`, `unit`, or something similar so when the value changes the indicator shows the text value + the label (e.g. `24px`, `2km`, ...). It's not just candy to the eye, when used in a form it'd be nice to have a more verbose slider.

What do you think?

<img width="700" alt="image" src="https://user-images.githubusercontent.com/2827383/163666813-1314e31d-19b8-4506-b053-3b5bfd988a32.png">

**Comment by asyncLiz** [comment]
Thanks for the issue! We'll sync up with design to make sure this pattern works 🙂

**Comment by joyzhong** [comment]
Closing this issue, as this is already possible by setting this function: https://github.com/material-components/material-web/blob/9ab9eb38812a745961181f00b85d4cddf18a60da/packages/slider/slider-base.ts#L73

**Comment by vdegenne** [comment]
@joyzhong As a end user I am not supposed to understand and know how the inner logic of a custom Element works.
My request was dedicated to all the users to which you provide this element, modifying the typescript codebase, compiling in an independent repository for individual use is not really a solution.
