### ISSUE TITLE
mwc-tab documentation

### ISSUE THREAD

**Issue by malakeel** [material-components/material-web#3385]
Documentation for mwc-tab and mwc-tab-bar does not show how to create or add tab contents. 

The following snippet creates only the tabs without any contents:
```
<mwc-tab-bar>
  <mwc-tab label="Tab one"></mwc-tab>
  <mwc-tab label="Tab two"></mwc-tab>
  <mwc-tab label="Tab three"></mwc-tab>
</mwc-tab-bar>

<script type="module">
  import '@material/mwc-tab-bar';
  import '@material/mwc-tab';
</script>
```

Any example or instructions on how to create a fully functional tabs with contents ? 

Thank you

**Comment by abhiomkar** [comment]
MWC Tab bar emits events whenever a tab is selected. Please use this event to modify or set the content associated with that tab outside of this component. Component itself does not provide slot to render tab content.

```
wrapperEl.addEventListener('MDCTabBar:activated', (e) => {
  if (e.detail.index === 0) {
    tabPanel_0_El.innerHTML = 'contents of first tab';
  } else if (e.detail.index === 1) {
    tabPanel_1_El.innerHTML = 'contents of second tab';
  }
  // ...
});
```

Please let me know if you've any questions!
