### ISSUE TITLE
Cannot call focus on tab bar

### ISSUE THREAD

**Issue by steverep** [material-components/material-web#3396]
**Describe the bug**
The `mwc-tab-bar` component cannot be focused programmatically via focus method.  For example, if a tab bar is desired to gain focus inside a dialog, focusing the active tab by calling focus on the tab bar element is not possible.

**To Reproduce**
1. Try to call `focus` on `mwc-tab-bar` and nothing happens

**Expected behavior**
Focus should be placed on the active tab.

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox or Chrome
 - Version latest

**Additional context**
[ARIA Authoring Practices on Tabs](https://www.w3.org/TR/wai-aria-practices-1.2/#tabpanel)

**Comment by asyncLiz** [comment]
Fixed in M3, md-tabs will focus its active child
