### ISSUE TITLE
How to get started to make a dark theme?

### ISSUE THREAD

**Issue by fredprodibi** [material-components/material-web#3402]
Hello, I m new to this project and I would like to use the components in a dark theme.

Does a dark theme already exists?
What would be the best way to get started to have a default dark theme up ?

Thank you by advance

**Comment by omar2205** [comment]
There is this guide https://github.com/material-components/material-web/blob/master/docs/theming.md

**Comment by treeder** [comment]
Modify the ones from the docs: https://github.com/material-components/material-web/blob/main/docs/theming.md

Or use the theme builder: https://m3.material.io/theme-builder#/custom

**Comment by asyncLiz** [comment]
Closing since we've got some good replies in here. Feel free to start a discussion for more help!
