### ISSUE TITLE
Form textfields autofill

### ISSUE THREAD

**Issue by silizza** [material-components/material-web#3462]
Is there a way to enable form autofill? The password managers (Bitwarden, google etc) are not able to autocomplete the Textfields because of shadow root. It is a big inconvenience for user experience.

**Comment by drk-mtr** [comment]
I guess this would need to be implemented?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals

**Comment by steverep** [comment]
Safari already supports shadow DOM, but autofill only works when the  `Autocomplete` attribute is present, which the text field does not support at the moment.

**Comment by asyncLiz** [comment]
Text field has `autocomplete` now in 1.0
