### ISSUE TITLE
Classless api

### ISSUE THREAD

**Issue by janat08** [material-components/material-web#3471]
Here are examples some of the classless frameworks, what I like about it is that they're somewhat interchangeable along with 40 others on npm. 

Newcss.net
Barecss.com
Classless.css
https://github.com/shawn-sandy/fp-kit/tree/main/first-paint
https://simplecss.org/

A case could be made that you can have non alpha stable api that is classless.

**Comment by pTinosq** [comment]
I can understand where you're coming from but I highly doubt that classless CSS is what Material UI is trying to provide.

**Comment by janat08** [comment]
Making your design components public means it's cached more on browsers, so
having it more accessible by not needing to learn the api is beneficial.

**Comment by asyncLiz** [comment]
Hi! Thanks for the issue. We believe strongly in the use case of web components for modern browsers, which is the technology stack that this library is built on.
