### ISSUE TITLE
Broken demos and links from demos

### ISSUE THREAD

**Issue by slightlyoff** [material-components/material-web#3542]
Hey friends,

It looks like a few of the demos are broken, e.g.:

https://material-components.github.io/material-web/demos/elevation-overlay/

Also, links from demos to the "view source" button at the upper right hand side end up at 404's today.

Lastly, the top-level GH Pages url does not resolve:

https://material-components.github.io/

/cc @asyncLiz @rictic

**Comment by noelmace** [comment]
There isn't a `demos/` directory anymore because https://github.com/material-components/material-web/pull/3451 changed the whole structure of the project.

And here is why: https://github.com/material-components/material-web/issues/3050#issuecomment-1159152536
