### ISSUE TITLE
M3 Badge can use a trimvalue to convert values into '9+'

### ISSUE THREAD

**Issue by omar2205** [material-components/material-web#3628]
![image](https://user-images.githubusercontent.com/1373867/186562458-37423da2-975b-4956-9a2b-f3023210518e.png)

```<md-navigation-tab badgevalue="7" showbadge trimvalue />```

![image](https://user-images.githubusercontent.com/1373867/186562413-a613659b-de50-4b1c-8b7e-4791602c041e.png)

Or this should be the default behaviour.

**Comment by asyncLiz** [comment]
Hi! This is WAI since the badge only displays the text provided. It's the responsibility of the application to determine whether or not it should be truncated.
