### ISSUE TITLE
Where is the Material 3 contribution guide ?

### ISSUE THREAD

**Issue by ghost** [material-components/material-web#3634]
I'm looking for the Material 3 contribution guide, like in the [Material 2](https://github.com/material-components/material-web/tree/mwc#Contributing). 

Does anyone know how I can contribute ?
How I run and develop the project in my computer ?

I already had cloned the repository, installed the dependencies, checked for the scripts session on the package.json and I'm not understand how I can start something like a dev server...

Thanks

**Comment by asyncLiz** [comment]
Thanks for the issue! @rodydavis is working on this now :)

**Comment by asyncLiz** [comment]
Going to track this in https://github.com/material-components/material-web/issues/246
