### ISSUE TITLE
Issue with menu component using CDN

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#3655]
If I import these two components via jsdelivr CDN:

```js
import 'https://cdn.jsdelivr.net/npm/@material/web@0.1.0-alpha.0/menu/menu-button.js/+esm'
import 'https://cdn.jsdelivr.net/npm/@material/web@0.1.0-alpha.0/menu/menu.js/+esm'
```

I get:

![image](https://user-images.githubusercontent.com/75826/187802125-8c3cb793-dba3-403e-9259-0f11c89a3be6.png)

_Originally posted by @treeder in https://github.com/material-components/material-web/issues/3050#issuecomment-1233536219_

**Comment by asyncLiz** [comment]
Internal b/245950067

**Comment by treeder** [comment]
Any ideas how to get past this?

**Comment by asyncLiz** [comment]
Obsolete with M3's single `@material/web` package
