### ISSUE TITLE
Wrong links in docs for `mwc` branch

### ISSUE THREAD

**Issue by DannyMoerkerke** [material-components/material-web#3661]
When I click on one of the links for a component in the Components table on this page https://github.com/material-components/material-web/tree/mwc it still links to the master branch, resulting in a 404.

For example, clicking on `<mwc-button>` links to https://github.com/material-components/material-web/tree/master/packages/button while this should be https://github.com/material-components/material-web/tree/mwc/packages/button.

**Comment by MrBirb** [comment]
@EstebanG23 Might want to close this one as well

**Comment by treeder** [comment]
This is fixed looks like.
