### ISSUE TITLE
Merge md-navigation-drawer and md-navigation-drawer-modal into a single element

### ISSUE THREAD

**Issue by govis** [material-components/material-web#3708]
As in previous implementations <code>modal</code> should be an attribute of the <code>md-navigation-drawer</code>.

This way it can be used in responsive layouts that react to changes in screen width, orientation, etc.

**Comment by abh80** [comment]
does `md-navigation-drawer` work for you?

**Comment by govis** [comment]
It works when when user is on a wide view port, but when screen width becomes narrow I'd like to set its <code>modal</code> attribute to <code>true</code>. It doesn't have one though, instead there's a separate <code>navigation-drawer-modal</code> component and it can't be swapped dynamically

**Comment by asyncLiz** [comment]
We'll likely be merging these two as we work on nav drawer
