### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by RudraSen2** [material-components/material-web#3709]
If material-web is incomplete, how is m3.material.io is using Material 3 UI?

**Comment by Aworldc** [comment]
I'm wondering the same thing.

I have no idea but i guess they may be using some janky, incomplete css that was quickly whipped up for internal use.

**Comment by afnecors** [comment]
As you can see in page source that is an Angular web application.

This is an incomplete list of components that it uses:
```
<mio-landing-page>, <mio-header>, <mio-footer>
<mio-card-set>, <mio-card>
<mio-left-nav-rail>, <mio-navigation-drawer>, <mio-navigation-drawer-item>
<mio-cookie-notice>
<mio-dark-mode-switch>
<mio-toolbar>
<mio-title>
<mio-image>, <mio-video>, <mio-figure>
<mio-icon-badge>
```
I believe these components are exclusively for "internal use".

It also has `<mwc-drawer>` https://www.npmjs.com/package/@material/mwc-drawer

**Comment by asyncLiz** [comment]
The MIO team built their own internal versions of components with fewer requirements (and no client usage). That allowed them to spin up some early M3 components quickly for the website :)

**Comment by RudraSen2** [comment]
And how Gmail, Drive and other google products are also using M3? Using the same way or some other way?

**Comment by NeekoVN** [comment]
They would certainly have a "custom" M3 version to use internally with their products
