### ISSUE TITLE
Nested use of multiple tab-group, how to set different label orientations

### ISSUE THREAD

**Issue by GromLi** [material-components/material-web#3761]
Hi, as issue title.
I need to use <mat-tab-group> again within a <mat-tab-group>, I found I just set .mat-tab-labels to update title direction, but I can't set different direction, can you help me? 
Thanks!

**Comment by asyncLiz** [comment]
> .mat-tab-labels

Are you using [Angular Material](https://material.angular.io/)? If so, try asking on [their github repo](https://github.com/angular/components)!
