### ISSUE TITLE
Conflict of ReactiveElement properties and native mixin

### ISSUE THREAD

**Issue by odinr** [material-components/material-web#3770]
on the NavigationDrawer there is a property called ariaModal, which has a default value when constructed. This property is also a native mixin [see](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal#ariamixin_api)

this does not affect when rendering in dom, but throws `Failed to construct 'CustomElement': The result must not have attributes` when created programatically

```js
document.createElement('md-navigation-drawer');
```  

[ref](https://github.com/material-components/material-web/blob/443b24a00925517d98004b363b14a8a4bf17b0fd/navigationdrawer/lib/navigation-drawer-modal.ts#L31)

**Comment by techanvil** [comment]
Hi, I am also seeing the same error for `md-menu-item`:

![image](https://user-images.githubusercontent.com/18395600/203386324-9b201071-10c1-4306-b92c-c2e3395241e7.png)

**Comment by asyncLiz** [comment]
Should be fixed now that the aria update is applied
