### ISSUE TITLE
Icons are using Material Icons instead of Material Symbols

### ISSUE THREAD

**Issue by kamiya10** [material-components/material-web#3802]
I was playing in the lit playground and found out that I need to use Material Icons instead of Material Symbols for the icons to work correctly, which is confusing since the [Applying icons](https://m3.material.io/styles/icons/applying-icons#:~:text=Material%20Symbols%20are%20the%20new%20default) page says that the default icon used in Material You should be Material Symbols

After some code digging, I found that the current icon component uses Material Icons

https://github.com/material-components/material-web/blob/933cb14ac8ee02b0d3a8b36ef8045472adecfb32/icon/lib/icon-styles.scss#L7

Is there any reason that the Icons aren't implemented as Material Symbols?

code: [lit](https://lit.dev/playground/#gist=1b64d71d9bb0d452fc06d065ab941861) [gist](https://gist.github.com/kamiya10/1b64d71d9bb0d452fc06d065ab941861)

**Comment by asyncLiz** [comment]
Yes it has! Thank you :)
