### ISSUE TITLE
Setting native property 'role' in constructor of List and other elements causes DOMException "The result must not have attributes"

### ISSUE THREAD

**Issue by pgbross** [material-components/material-web#3804]
Setting native property 'role' in constructor of List and other elements causes DOMException (tested in Chrome 109 on Linux).

```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
```

I am using `material-web` (0.1.0-alpha.0) in an application that uses `Vue 3` as its framework. Most elements are working well but there are a few that cause the DOMException above including: list, list-item, list-divider, menu-item.

These elements all define an `ariaProperty` so that a corresponding `data-role` attribute is applied at runtime. However the parent class HTMLElement has a native property `role` so setting that in the custom element's constructor is not allowed and will cause an error depending on the custom element implementation.

The error can be prevented by setting the `role` to `null` in the constructor and then setting its value in the `connectedCallback()` function.

E.G.

```javascript
export class List extends LitElement {
  constructor() {
    super(...arguments);
    this.role = null;
    this.listId = '';
    this.listTabIndex = 0;
    this.items = [];
    this.activeListItem = null;
    this.listItemTagName = 'md-list-item';
  }
  connectedCallback() {
    super.connectedCallback();
    this.role = 'list';
  }

// ... rest of the code
```

**Comment by asyncLiz** [comment]
This also occurs with nav drawer (see https://github.com/material-components/material-web/issues/3846)

**Comment by pgbross** [comment]
Now that  `material-web` (1.0.0-pre.2) is available with `list` and `menu` marked as _beta_ , is there any progress on including a fix?

In order to successfully use `material-web` in my `Vue 3` project I have to use the sources and tweak `menu-item`, `list-item` and `list` to use an override connectedCallback().

eg. the latest update for `menu-item` would change:

original
```typescript
export class MenuItemEl extends ListItemEl implements MenuItem {
  override role: ARIARole = 'menuitem';

 // ... rest of the code
```
becomes

```typescript
export class MenuItemEl extends ListItemEl implements MenuItem {

  override role: ARIARole | null = null;

  override connectedCallback() {
    super.connectedCallback();

    this.role = 'menuitem';
  }
 // ... rest of the code
```

**Comment by asyncLiz** [comment]
@e111077 FYI

**Comment by maicol07** [comment]
Same error reported here: [Autocomplete issues when creating it from JS · Issue #3933 · material-components/material-web (github.com)](https://github.com/material-components/material-web/issues/3933)

Maybe it can help debug the issue

**Comment by pgbross** [comment]
I note issue #4107 shows the same fault in React and that there is a proposed fix in #4108 which is great news.

**Comment by asyncLiz** [comment]
Yup, this will be fixed as well

**Comment by asyncLiz** [comment]
Fixed now!
