### ISSUE TITLE
I can't see them on release.

### ISSUE THREAD

**Issue by Choneas** [material-components/material-web#3814]
I can't see html files in release. because it's white screen when you open that html.
![image](https://user-images.githubusercontent.com/57039359/206337367-ab0fb529-889a-42c7-a091-6e9507125a36.png)
![image](https://user-images.githubusercontent.com/57039359/206337465-2a2c6db2-ff79-431b-aa33-05dd3a2b8b69.png)

**Comment by YUCLing** [comment]
Please make sure you have installed all dependencies before opening the page.

zaima，装个前置
