### ISSUE TITLE
Custom component shapes

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-web#3841]
Will it be possible to provide a custom shape for a material 3 web component? I have in mind that rather than (say) a button or text field with a rounded rectangle outline (or filled shape), I would want to apply a squircle.

**Comment by asyncLiz** [comment]
Unfortunately no, I don't believe so. All of the components use `border-radius` in their shape implementations, so we're limited to what can be expressed in CSS 😔

**Comment by simonziegler** [comment]
Thanks @asyncLiz
