### ISSUE TITLE
Error while using `md-navigation-drawer` or `md-navigation-drawer-modal`

### ISSUE THREAD

**Issue by abh80** [material-components/material-web#3846]
I am trying to use material 3 web components with react and I am facing this error in browser console while using `md-navigation-drawer-modal` or `md-navigation-drawer`  ,

![image](https://user-images.githubusercontent.com/50198413/208235775-45e47779-fc0e-4d5d-a015-cbd26b9122a5.png)

> Note that other components work fine with no such errors also there is no output in the webpage, it means its not working

Here is the code,
```jsx
import "./App.css";
import "@material/web/textfield/filled-text-field";
import "@material/web/navigationdrawer/navigation-drawer-modal";
import "@material/web/navigationtab/navigation-tab"

function App() {
  return (
    <div className="App">
      <md-navigation-drawer-modal>
        <div>
          <p>Nav!</p>
        </div>
      </md-navigation-drawer-modal>
    </div>
  );
}

export default App;
```

**Comment by asyncLiz** [comment]
This is an underlying problem with a few components, see https://github.com/material-components/material-web/issues/3804 for a continued discussion!

**Comment by abh80** [comment]
Thanks for clarifying my bad missed a similar issue
