### ISSUE TITLE
Add demos

### ISSUE THREAD

**Issue by Tony20221** [material-components/material-web#3847]
The first thing I want to do when I go to some UI controls is I want to see what they look like before I read walls of text or look at code.
Where are the demos of the controls?

**Comment by 3kh0** [comment]
I think v2 is here: https://material-components.github.io/material-web/demos/index.html

v3 is still in the works

**Comment by abhijeet-shelhalkar** [comment]
Material Web Components Playground: https://mwc-demos.glitch.me/

**Comment by KTibow** [comment]
also see https://lit.dev/playground/#gist=3704ea8df1a2f252be6012db2c5403df

**Comment by maischus** [comment]
I found this overview of working components:
https://olkus.com/projects/using-web-components-with-material-3/

**Comment by asyncLiz** [comment]
Demos are available at our WIP catalog [material-web.dev](https://material-web.dev/)
