### ISSUE TITLE
npm install not working in mwc folder 

### ISSUE THREAD

**Issue by abhijeet-shelhalkar** [material-components/material-web#3848]
Hi,

As per instructions given in mwc branch, I am trying to install material-web on local but getting below error while installation.

![material-web-install-issue](https://user-images.githubusercontent.com/32697900/208386703-c0d4a466-4861-4d1c-91e8-e19be3a3d66e.png)

**Comment by asyncLiz** [comment]
Have you tried using [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install)?

**Comment by abhijeet-shelhalkar** [comment]
First I tried ( npm install - mwc branch ) in Windows 11.
then I tried ( npm install - mwc branch ) in Ubuntu 20.04 but getting same error.

**Comment by asyncLiz** [comment]
Closing since the mwc branch is no longer under active development
