### ISSUE TITLE
Can't create Landing Page with TS

### ISSUE THREAD

**Issue by volkankaban** [material-components/material-web#3864]
I'm currently using Tailwindcss and when I try to remove Tailwind then start getting many errors. I'm wondering if any of the Contributors here can help me correct my profile page without Tailwindcss. Thank you!

Repo: https://github.com/volkankaban/volkankaban

**Comment by asyncLiz** [comment]
Hi! Unfortunately we don't have bandwidth to help debug Tailwindcss issues. I would recommend joining their [discord server](https://discord.gg/7NF8GNe) and asking there.
