### ISSUE TITLE
textfield error/errorText attributes

### ISSUE THREAD

**Issue by govis** [material-components/material-web#3910]
It looks like a new validation message related attributes have been added in the recent 1.0.0 prerelease version:

<code>nativeError</code>
<code>nativeErrorText </code>

Methods <code>setCustomValidity/reportValidity</code> appear to be using the new attributes now, but old attributes have not been removed no there's no note of a breaking change

<code>error</code>
<code>errorText</code>

why do we need 2 sets of identical attributes?

**Comment by asyncLiz** [comment]
The `nativeError` and `nativeErrorText` are protected properties, so you should only be using `error` and `errorText`!

While native validation (`setCustomValidity()`/`reportValidity()`) works wondrously, the `error` and `errorText` are available as simple overrides. This is necessary in some cases like server side rendering.

Hopefully things will be better documented soon to help explain things!
