### ISSUE TITLE
can't use npm install @material/web in sveltekit

### ISSUE THREAD

**Issue by yzn-h** [material-components/material-web#3921]
+page.svelte
```html
<script>
    import("@material/web/button/outlined-button")
</script>
 
<md-outlined-button></md-outlined-button>
```

error
```bash
Failed to load url ./lib/outlined-styles.css.js (resolved id: ./lib/outlined-styles.css.js). Does the file exist?
Failed to load url ./lib/shared-styles.css.js (resolved id: ./lib/shared-styles.css.js). Does the file exist?
undefined:12
const global = globalThis ;
      ^

SyntaxError: Identifier 'global' has already been declared
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///C:/Users/yzn/projects/guest_approve_invite/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:52223:28)

Node.js v18.12.1
 ELIFECYCLE  Command failed with exit code 1.
```

this works fine
```html
<svelte:head>
    <script type="module" src="https://unpkg.com/@material/web@1.0.0-pre.1/button/elevated-button.js?module"></script>

</svelte:head>
<md-outlined-button></md-outlined-button>
```

**Comment by asyncLiz** [comment]
Thanks for the issue!

We unfortunately don't have the bandwidth to help debug framework-specific issues. Have you tried asking for help from Svelte community members?

You can also try joining lit.dev/discord and ask for help there!

**Comment by AxelBriche** [comment]
I'm also looking forward to full support for Svelte/Sveltekit.

**Comment by asyncLiz** [comment]
> I'm also looking forward to full support for Svelte/Sveltekit.

Are there similar or different problems you're running into? As far as I'm aware, web components should be compatible in most frameworks with little to no effort.

**Comment by Aworldc** [comment]
technically, yes. but svelte doesn't play nice with them

**Comment by Aworldc** [comment]
for the import error, have you tried using standard imports instead of calling `import()` on them?
```js
import '@material/web/button/outlined-button.js';
```
