### ISSUE TITLE
How Can I Do It?

### ISSUE THREAD

**Issue by salihkartal** [material-components/material-web#3922]
Hello there. Sorry for posting here. How can I make a Google Blogspot (https://www.blogger.com) theme using Material Web? I couldn't find any resources on how to do it online. I don't know much about coding. I really like Material Web and I want to try to make it a theme like this.

**Comment by asyncLiz** [comment]
Hi there! We're working on getting demos and documentation set up. In the meantime, you can join lit.dev/discord to chat with community members for assistance!
