### ISSUE TITLE
Text areas

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-web#3929]
Hi, are text areas part of the roadmap? I don't see them here: https://github.com/material-components/material-web#roadmap

**Comment by asyncLiz** [comment]
Yes! They'll be part of text field stable :)

**Comment by simonziegler** [comment]
Superb. You folks are doing really good work here. I've started experimenting with migration from material-components-web to material-web for an ASP.NET/Blazor OSS library I maintain. material-web is much easier to handle!
