### ISSUE TITLE
modaless misspelled in dialog/lib/_dialog.scss 

### ISSUE THREAD

**Issue by djarekg** [material-components/material-web#3950]
Lines [81](https://github.com/material-components/material-web/blob/8eb07e24ec0e2ee276d813591f0fe524055222a1/dialog/lib/_dialog.scss#L81) and [82](https://github.com/material-components/material-web/blob/8eb07e24ec0e2ee276d813591f0fe524055222a1/dialog/lib/_dialog.scss#L82)  in _dialog.scss currently has modeless. Shouldn’t it be modaless?

**Comment by djarekg** [comment]
There is also 7 different places in [dialog_test.ts](https://github.com/material-components/material-web/blob/master/dialog/dialog_test.ts) where the spelling is modeless.

**Comment by asyncLiz** [comment]
Do you mind submitting a PR to fix this?

**Comment by asyncLiz** [comment]
Closing since we're removing modeless dialogs since they're against the Material spec
