### ISSUE TITLE
Label not showing when using type "month" on mwc-textfield

### ISSUE THREAD

**Issue by SketchBookkeeper** [material-components/material-web#3964]
Browser: Chrome 110.0.5481.97
Package: mwc-textfield 0.27.0

Markup:
```<mwc-textfield outlined type="month" label="Start date"></mwc-textfield>```

Results:
![image](https://user-images.githubusercontent.com/18709288/218586447-2e0949c7-60ae-4e09-bf64-d0f911d6b62e.png)

**Comment by asyncLiz** [comment]
Unfortunately this won't be fixed for Material 2's mwc-textfield. It is fixed in the new Material 3 text field though.

**Comment by lasamarndi1994** [comment]
When will it fixed?

**Comment by asyncLiz** [comment]
This won't be fixed for the beta `<mwc-textfield>`. The fix is available in the 1.0 `<md-filled-text-field>` and `<md-outlined-text-field>`.
