### ISSUE TITLE
Documentation: Status Colors

### ISSUE THREAD

**Issue by jhairau** [material-components/material-web#4021]
Could you please select a different color scheme for representing the status of each component.

As a person with Deuteranopia (red-green color blindness, which is the most common form of color blindness), I find it almost impossible to see the different between `Not Started` and `Complete` on this page https://github.com/material-components/material-web.

My suggestion is that you switch the red or the green to blue. This will enable Deuteranopia people to see the difference and blue will also present well when github is rendering the dark theme.

**Comment by asyncLiz** [comment]
Thanks for calling this out! I'll update the icons :)

**Comment by jhairau** [comment]
Thanks so much @asyncLiz !
