### ISSUE TITLE
datetime , 6 digits for the year

### ISSUE THREAD

**Issue by FranGomezVenegas** [material-components/material-web#4025]
Hi,

I cannot find if this was posted before, Do anyone else find this same? I found this on running automated testing .... but then I reproduce it by typing manually the year value too.

![imagen](https://user-images.githubusercontent.com/26067165/222963567-50910bcd-5d55-4fde-93d0-19c0da942ed9.png)

**Comment by asyncLiz** [comment]
Hi! It looks like that is a native `<input>` component rather than one of our text fields. If there's an issue with our text field, please post a reproduction and we can re-open!

**Comment by FranGomezVenegas** [comment]
ok, Thanks
