### ISSUE TITLE
Form Field and/or Switch styling is different in IE/Edge vs Chrome/Firefox

### ISSUE THREAD

**Issue by aomarks** [material-components/material-web#404]
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What browser(s) is this bug affecting:**

Edge and IE11

**Current behavior:**

IE11 and Edge looks like this:
![image](https://user-images.githubusercontent.com/48894/63462020-cc702a80-c40e-11e9-8c43-0964baacbdcf.png)

Chrome and Firefox looks like this:
![image](https://user-images.githubusercontent.com/48894/63462026-d134de80-c40e-11e9-9737-6753280c6e79.png)

**Expected behavior:**

I'm not sure what how the spacing here is supposed to work, but it should be the same in all browsers. See also https://github.com/material-components/material-components-web-components/issues/380 which describes how the styling of Form Field seems is kind of odd in all browsers.

**Steps to reproduce:**

```html
<mwc-formfield label="Label">
  <mwc-switch></mwc-switch>
</mwc-formfield>
```

**Comment by dfreedm** [comment]
Probably related to #380
