### ISSUE TITLE
Provide a global way to change the components font

### ISSUE THREAD

**Issue by maicol07** [material-components/material-web#4042]
Hi.,
currently we can only change the font via the component CSS props (I.e. `--md-filled-button-label-font-type`). However, this isn't ideal if you have a lot of different components with a lot of text blocks.

Proposal: add a SCSS helper o global CSS property to change the font family globally.

**Comment by asyncLiz** [comment]
We're working on adding system typography tokens to what is generated, that will fix this!

**Comment by hermantolim** [comment]
@asyncLiz will this work like `md-sys-color` token? because currently the generated `md-sys-typescale` will use hardcoded value, instead of grabbing value from `--md-sys-typescale-${token}`

**Comment by asyncLiz** [comment]
This is now implemented! You can use the following tokens:

```
--md-ref-typeface-brand
--md-ref-typeface-plain

--md-sys-typescale-body-large
--md-sys-typescale-body-medium
--md-sys-typescale-body-small
--md-sys-typescale-display-large
--md-sys-typescale-display-medium
--md-sys-typescale-display-small
--md-sys-typescale-headline-large
--md-sys-typescale-headline-medium
--md-sys-typescale-headline-small
--md-sys-typescale-label-large
--md-sys-typescale-label-medium
--md-sys-typescale-label-small
--md-sys-typescale-title-large
--md-sys-typescale-title-medium
--md-sys-typescale-title-small
```

**Comment by treeder** [comment]
Any examples of how to use this? Like how would I set this to use 'Roboto Flex' for instance?

**Comment by treeder** [comment]
Would it just be:

```
--md-ref-typeface-brand: 'Roboto Flex'
--md-ref-typeface-plain: 'Roboto Flex'
```

**Comment by maicol07** [comment]
@treeder yes, these ones plus the others

**Comment by treeder** [comment]
Ahh, so typescale is also the font name?

like:

```
--md-sys-typescale-title-small: 'Roboto Flex'
```

**Comment by treeder** [comment]
This information would be really useful in the docs here or something: https://github.com/material-components/material-web/blob/main/docs/theming.md

**Comment by ronnieroyston** [comment]
I find that setting `--md-ref-typeface-plain` on CSS `:root` sets the font on all `<md-` elements except for `md-dialog div[slot="headline"]`?

<img width="299" alt="image" src="https://github.com/material-components/material-web/assets/12751611/a8bac327-44c6-40d4-b840-b99a498f4d8a">

**Comment by asyncLiz** [comment]
@ronnieroyston try setting [`--md-ref-typeface-brand`](https://github.com/material-components/material-web/blob/main/docs/theming/typography.md#tokens) as well

**Comment by ronnieroyston** [comment]
Material / Fonts Docs do talk about using multiple fonts but the idea is to have _secondary_ (and or _tertiary_) fonts not explicitly a `brand` font. https://fonts.google.com/knowledge/choosing_type/pairing_typefaces

[Material Design Docs](https://m3.material.io/styles/typography/type-scale-tokens) talk about `headline`, `title`, `body`, and `label` fonts but not a `brand` font?
 
> In Material there are plain and brand typefaces.

**Comment by asyncLiz** [comment]
The [tokens section](https://m3.material.io/styles/typography/type-scale-tokens#a734c6ed-634c-4abb-adb2-35daf0aed06a) of that page is where you can view how the system typescales map to reference typefaces.

<img width="976" alt="Screenshot 2024-01-23 at 3 29 19 PM" src="https://github.com/material-components/material-web/assets/34382620/4d645580-4c7c-4a47-be7c-d5bdd5627ed2">

**Comment by treeder** [comment]
Be sure you're importing all the required font weights too, I think it's 400, 600 and 700 or something.

**Comment by ronnieroyston** [comment]
I see it now. ..."Brand".   ¯\_(ツ)_/¯ 

> The Material Design typescale distinguishes between two types of reference tokens: brand and plain. This enables you to use two different typefaces within your design. The brand typeface (which has the token md.ref.typeface.brand) is recommended for larger font sizes, such as Headline and Display, while plain typeface (with the token md.ref.typeface.plain) is suitable for smaller font sizes, such as Body and Label.
