### ISSUE TITLE
FABs don't apply disabled styles

### ISSUE THREAD

**Issue by EdricChan03** [material-components/material-web#4045]
The FAB and FAB extended components don't appear to apply their disabled styling correctly - see [my playground](https://edricchan03.github.io/mw3-playground/components/button) for an example:

![Screenshot of playground website, with all button variants disabled except the FAB and extended FAB](https://user-images.githubusercontent.com/20047125/224996925-89a1068d-15d7-4acf-b07b-2602cf550088.png)

The ripple does appear to be disabled though should I attempt to click on them.

[Code for the example](https://github.com/EdricChan03/mw3-playground/blob/c100daf657cda18f4c03140fb8f54391e6688500/src/routes/components/button/%2Bpage.svelte#L36-L44)

```html
<div class="flex items-center gap-3 p-6">
  <md-elevated-button label="Elevated" {disabled} />
  <md-filled-button label="Filled" {disabled} />
  <md-outlined-button label="Outlined" {disabled} />
  <md-text-button label="Text" {disabled} />
  <md-tonal-button label="Tonal" {disabled} />
  <md-fab icon="add" {disabled} />
  <md-fab-extended label="Add" icon="add" {disabled} />
</div>
```

Library version used: [v1.0.0-pre.4](https://github.com/material-components/material-web/releases/tag/v1.0.0-pre.4)

**Comment by asyncLiz** [comment]
FABs are not disable-able. It looks like we need to remove the disabled property from it.
