### ISSUE TITLE
Are Data Tables coming to Material 3?

### ISSUE THREAD

**Issue by andrewhainen-slalom** [material-components/material-web#4052]
I'm only finding Data Table component in Material 2

**Comment by bivens-dev** [comment]
Take a look at the Readme file. Yes but not for 1.0

**Comment by asyncLiz** [comment]
Yup! Closing this for now

**Comment by maicol07** [comment]
@andrewhainen-slalom In the meantime, I've made a Material 3 data table web component using the M2 component as a base: [Docs](https://main--625eadb22bf40d003a32215a.chromatic.com/?path=/docs/components-data-table--docs) ([Github](https://github.com/maicol07/material-web-additions/blob/main/data-table))
