### ISSUE TITLE
Bug [1.0.0-pre.4] Slider background color on page load incorrect.

### ISSUE THREAD

**Issue by mavyfaby** [material-components/material-web#4061]
## Problem

As the title suggests.

## Actual Behavior

Light | Dark 
--- | --- |
![Screenshot from 2023-03-17 09-11-41](https://user-images.githubusercontent.com/51808724/225787386-2617bbe7-5306-44d6-905d-b2617de91f40.png) | ![Screenshot from 2023-03-17 09-12-09](https://user-images.githubusercontent.com/51808724/225787445-6603a359-d1e1-41ef-a245-970f5698cfce.png)

## Expected Behavior

Light | Dark 
--- | --- |
![Screenshot from 2023-03-17 09-12-19](https://user-images.githubusercontent.com/51808724/225787588-bc7feaf8-629b-47c9-897f-348e2f6a7a7a.png) | ![Screenshot from 2023-03-17 09-12-32](https://user-images.githubusercontent.com/51808724/225787612-3fe91fe9-6616-4fb5-a9fb-202f339d2826.png)

**Comment by sorvell** [comment]
Thanks for reporting this. The root cause is a bug in Lit's styleMap directive: https://github.com/lit/lit/issues/3738
