### ISSUE TITLE
Component based style

### ISSUE THREAD

**Issue by nitipit** [material-components/material-web#4070]
Hi material-web team,

I'm a web developer from Thailand (exp 10+ years).
I'm very appriciate your hard work in this project and how you introduce it to developer community. I'm also waiting for this project to release in the future.

Recently, I just discovered some new technique to implement **Component Based Style** (for calling in short) using **CSS-in-JS**. I think it's much more flexible and and much more modular, also easily controlled by **Javascript** runtime and packaging.
 
I've a sample project here : https://nitipit.github.io/gadjet/ which I think can explain a lot of ideas.

**Comment by asyncLiz** [comment]
Thanks for posting! We're pretty happy with our current component architecture, so changes are not planned right now :)
