### ISSUE TITLE
Bug on @theme mixin in _text-button.scss, _tonal-button.scss, and _outlined-button.scss

### ISSUE THREAD

**Issue by hermantolim** [material-components/material-web#4095]
extra `--md-elevated-button-` on token loop, should not be there, this cause wrong token when generating using theme mixin

https://github.com/material-components/material-web/blob/bfa1bec320b6a73f4a4a89e508223e873920e3ac/button/lib/_text-button.scss#L20

also in 
https://github.com/material-components/material-web/blob/bfa1bec320b6a73f4a4a89e508223e873920e3ac/button/lib/_tonal-button.scss#L22

and 

https://github.com/material-components/material-web/blob/bfa1bec320b6a73f4a4a89e508223e873920e3ac/button/lib/_outlined-button.scss#L24

or is it intentional?

**Comment by asyncLiz** [comment]
Oof I don't think that is intentional. I'll send out a fix
