### ISSUE TITLE
Issue with `role` property when used in React, probably bug

### ISSUE THREAD

**Issue by hermantolim** [material-components/material-web#4107]
When using the component in react I had this issue:

### Dependencies
- React - v18.0.0
- @material/web - 1.0.0-pre.5
### Related Components:
- Menu
- Menu Item
- Sub Menu Item
- List
- List Item

### Error Message:
`NotSupportedError Failed to construct 'CustomElement': The result must not have attributes`

### Problem:
- cause by property initialization

https://github.com/material-components/material-web/blob/3adab6ae192489db5d5eb1dfd54552f69a0f0ad7/list/lib/list.ts#L50-L54

https://github.com/material-components/material-web/blob/3adab6ae192489db5d5eb1dfd54552f69a0f0ad7/list/lib/listitem/list-item.ts#L36-L40

https://github.com/material-components/material-web/blob/3adab6ae192489db5d5eb1dfd54552f69a0f0ad7/menu/lib/menu.ts#L134-L136

https://github.com/material-components/material-web/blob/3adab6ae192489db5d5eb1dfd54552f69a0f0ad7/menu/lib/menuitem/menu-item.ts#L17

https://github.com/material-components/material-web/blob/3adab6ae192489db5d5eb1dfd54552f69a0f0ad7/menu/lib/menuitemlink/menu-item-link.ts#L17

https://github.com/material-components/material-web/blob/3adab6ae192489db5d5eb1dfd54552f69a0f0ad7/menu/lib/submenuitem/sub-menu-item.ts#L29

### Fix:

late initialization of the property in `connectedCallback` solve it

```ts
export class ListItemEl extends LitElement implements ListItem {
  @ariaProperty
  // tslint:disable-next-line
  @property({type: String, attribute: 'data-role', noAccessor: true})
  // @ts-ignore(b/264292293): Use `override` with TS 4.9+
  role: ARIARole;

...

  override connectedCallback() {
      super.connectedCallback();
      if (!this.role) {
        this.role = 'listitem';
      }
  }
```

**Comment by asyncLiz** [comment]
This should be fixed once the aria delegation shim lands (https://github.com/material-components/material-web/pull/4108) and the components are updated to use it

**Comment by christophe-g** [comment]
Oh, #4108 is great news - thanks a lot !

**Comment by asyncLiz** [comment]
Should be fixed now!
