### ISSUE TITLE
[1.0.0-pre.5] <md-icon> slotted content isn't vertically centered

### ISSUE THREAD

**Issue by zmullett** [material-components/material-web#4135]
While using `<md-x-icon-button>`  I observe that the slotted content (within `<md-icon>`) isn't vertically centered.

Changing `<md-icon>`'s `line-height` to 0 solves this. i.e. here:

https://github.com/material-components/material-web/blob/7368e2a2e23cd4509e27860ef513dd6fc832964a/icon/lib/_icon.scss#L36

**Comment by zmullett** [comment]
This appears to be an issue only if the Material Symbols font hasn't been loaded.

**Comment by asyncLiz** [comment]
Do you mind creating a reproduction for us on https://lit.dev/playground?

**Comment by zmullett** [comment]
https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9kZW1vLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-In0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6ImRlbW8udHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCByZW5kZXJ9IGZyb20gJ2xpdCc7XG5pbXBvcnQgJ0BtYXRlcmlhbC93ZWIvYnV0dG9uL2ZpbGxlZC1idXR0b24uanMnO1xuaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL2ljb25idXR0b24vZmlsbGVkLWljb24tYnV0dG9uLmpzJztcblxucmVuZGVyKGh0bWxgXG4gIDxtZC1maWxsZWQtaWNvbi1idXR0b24-XG4gICAgPCEtLSBNYXRlcmlhbCBJY29uOiByYWRpb19idXR0b25fdW5jaGVja2VkIC0tPlxuICAgIDxzdmcgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiIGhlaWdodD1cIjI0cHhcIiB2aWV3Qm94PVwiMCAwIDI0IDI0XCIgd2lkdGg9XCIyNHB4XCIgZmlsbD1cIiMwMDAwMDBcIj48cGF0aCBkPVwiTTAgMGgyNHYyNEgwVjB6XCIgZmlsbD1cIm5vbmVcIi8-PHBhdGggZD1cIk0xMiAyQzYuNDggMiAyIDYuNDggMiAxMnM0LjQ4IDEwIDEwIDEwIDEwLTQuNDggMTAtMTBTMTcuNTIgMiAxMiAyem0wIDE4Yy00LjQyIDAtOC0zLjU4LTgtOHMzLjU4LTggOC04IDggMy41OCA4IDgtMy41OCA4LTggOHpcIi8-PC9zdmc-XG4gIDwvbWQtZmlsbGVkLWljb24tYnV0dG9uPlxuYCwgZG9jdW1lbnQuYm9keSk7In1d

**Comment by asyncLiz** [comment]
It looks like this has been fixed since that version, possibly a side effect of other changes.

Let us know if you're still running into issues after updating!
