### ISSUE TITLE
Bug [1.0.0-pre.6] `md-filled-text-field` background color incorrect.

### ISSUE THREAD

**Issue by mavyfaby** [material-components/material-web#4145]
It appears to work in `v1.0.0-pre.5`, but not in the most recent version, `v1.0.0-pre.6`. Maybe related in this commit f15d8ca.

## Actual Behavior (v1.0.0-pre.6)

Light | Dark 
--- | --- |
![Screenshot from 2023-04-11 19-08-28](https://user-images.githubusercontent.com/51808724/231143245-f8c5b27c-5aa4-4725-ad53-0103cb69e262.png)|![Screenshot from 2023-04-11 19-08-04](https://user-images.githubusercontent.com/51808724/231143271-e4d19845-1be4-4366-a3ba-9771e2cc4e3a.png)

## Expected Behavior (v1.0.0-pre.5)

Light | Dark 
--- | --- |
![image](https://user-images.githubusercontent.com/51808724/231144015-2fc53df3-a4e7-4f24-bbdd-baff5e4a10d4.png)|![image](https://user-images.githubusercontent.com/51808724/231144232-f9e458d1-9636-469d-89b7-5578eaaf3697.png)

**Comment by mavyfaby** [comment]
Thank you for your response, however instead of creating custom CSS stylings, I'm using the [`@material/material-color-utilities`](https://www.npmjs.com/package/@material/material-color-utilities) package's default styles to produce dynamic colors and apply the theme.

Here is my textfield component:

```vue
<md-filled-text-field
  v-model="user"
  label="Username"
  placeholder="Enter username"
>
  <md-icon slot="leadingicon">person</md-icon>
</md-filled-text-field> 
```

**Comment by asyncLiz** [comment]
Ahh yea the material color utilities broke with the new tonal surface updates. I believe they're actively fixing it though :)

**Comment by mavyfaby** [comment]
Ahh I see, thanks again for the response. I'll close this issue once they fixed it :)

**Comment by asyncLiz** [comment]
Closing since this isn't actionable for our team
