### ISSUE TITLE
Select menu closes before opening animation completes

### ISSUE THREAD

**Issue by pgbross** [material-components/material-web#4160]
Using the following example select element, after the first time an option is selected, subsequent clicks on the select field start to animate open, but immediately close before an option can be selected.

```html
      <md-outlined-select label="fruits">
        <md-select-option value="apple" headline="Apple"></md-select-option>
        <md-select-option value="banana" headline="Banana"></md-select-option>
      </md-outlined-select>
```

If the `md-outlined-select` has the `quick` attribute, the problem does not occur.

Analysis:

The select element handles the `focusout` event:

```html
      <span class="select ${classMap(this.getRenderClasses())}" @focusout=${this.handleFocusout}>
        ${this.renderField()} ${this.renderMenu()}
      </span>
```

In `handleFocusout()`  it checks the event's `relatedTarget` to see if the element that gained focus is in the subtree, if not it closes the menu by setting `this.open = false`. When the menu is set to animate `relatedTarget` is `undefined` so the menu is closed.

The `relatedTarget` is `undefined` once there is a selected item because in `handleOpening`  it attempts to set the focus to that item.

```html
    if (selectedItem) {
      selectedItem.active = true;
      selectedItem.focus();
    }
```
In the case when the menu is using `animateOpen` the selected item will not be in a state where it can receive the focus, so when the `focusout` event is received in `handleFocusout()` there is no relatedTarget, and it therefore closes the menu. That causes the `menu` to abort the opening animation giving the symptom described of the menu closing before the animation completes.

One possible solution might be to listen for the `opened` event, which is fired once the animation has rendered the select options, in the `Select` element so that it can be given focus succesfully.

**Comment by pgbross** [comment]
Ok so on further investigation this issue arises from an interaction with some global css I have in my project. Specifically I have in a css style file:

```css
  .hidden { display: none; }
```

I see that in `md-menu` (which is used by `md-select`) it has css used in its animation process that applies to slotted elements, specifically:

```css
    &.animating ::slotted(.hidden) {
      opacity: 0;
    }
```

The effect of setting `.hidden` to `display: none;` causes the element to not be rendered in the DOM and the focus can't be assigned, and therefore the behaviour described originally happens and the menu closes abruptly.

see [live demo](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9pbmRleC5qc1wiPjwvc2NyaXB0PlxuICA8c3R5bGU-LmhpZGRlbiB7ZGlzcGxheTogbm9uZTt9PC9zdHlsZT5cbiAgPC9oZWFkPlxuPGJvZHk-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoiaW5kZXguanMiLCJjb250ZW50IjoiaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL3NlbGVjdC9vdXRsaW5lZC1zZWxlY3QuanMnO1xuaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL3NlbGVjdC9zZWxlY3Qtb3B0aW9uLmpzJztcbmltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50LCByZW5kZXJ9IGZyb20gJ2xpdCc7XG5cbiBleHBvcnQgY2xhc3MgQXBwUm9vdCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBjb25zdHJ1Y3RvcigpIHtcbiAgICBzdXBlcigpO1xuICB9XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYCA8bWQtb3V0bGluZWQtc2VsZWN0PlxuICAgICAgICA8bWQtc2VsZWN0LW9wdGlvbiB2YWx1ZT1cIm9uZVwiIGhlYWRsaW5lPVwiT25lXCI-PC9tZC1zZWxlY3Qtb3B0aW9uPlxuICAgICAgICA8bWQtc2VsZWN0LW9wdGlvbiB2YWx1ZT1cInR3b1wiIGhlYWRsaW5lPVwiVHdvXCI-PC9tZC1zZWxlY3Qtb3B0aW9uPlxuICAgICAgICA8bWQtc2VsZWN0LW9wdGlvbiB2YWx1ZT1cInRocmVlXCIgaGVhZGxpbmU9XCJUaHJlZVwiPjwvbWQtc2VsZWN0LW9wdGlvbj5cbiAgICAgIDwvbWQtb3V0bGluZWQtc2VsZWN0PmA7XG4gIH1cbiAgXG4gIFxuICAgc3RhdGljIHN0eWxlcz1jc3NgXG4gICAgICAgLmhpZGRlbntcbiAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgIH1cbiAgICAgICBgXG59XG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ2FwcC1yb290JywgQXBwUm9vdCk7XG5cbihmdW5jdGlvbiBtYWluKCkge1xuICByZW5kZXIoaHRtbGAgPGFwcC1yb290PjwvYXBwLXJvb3Q-IGAsIGRvY3VtZW50LmJvZHkpO1xufSkoKTtcbiJ9XQ)

_Notice that after selecting from the drop down once, after that the menu closes abruptly when trying to select_.

So effectively in order to use the `<md-select>` there are some restrictions that should be included in the documentation. Given `.hidden` is fairly descriptive and I suspect is a classname that many people might choose, perhaps the class name used internally to make the animation function could be changed to, say, `.md-hidden` or something as that would be less likely to classh or at least less surprising to folk if it were to clash.

**Comment by asyncLiz** [comment]
@e111077 can you take a look at this?

**Comment by e111077** [comment]
That's a my-bad. `.hidden` is a terrible name for clashes what was I thinking?
