### ISSUE TITLE
Implement Chip

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-web#418]

**Comment by Misiu** [comment]
Any updates on this?
Not sure about the status in the Readme. 
Chips development will start in Q3 2020 or Chips will be released in Q3 2020?
Any workaround for now? Can we style buttons to look like chips?

**Comment by gullerya** [comment]
Bump! Any updates on chips implementation?
Thanks a lot!

**Comment by asyncLiz** [comment]
Chips have been implemented in `@material/web`

**Comment by Misiu** [comment]
@asyncLiz awesome news! When they will be released?

**Comment by asyncLiz** [comment]
There's an alpha version published at https://www.npmjs.com/package/@material/web
