### ISSUE TITLE
md-dialog doesn't seem to work well with dark theme by default (pre.7)

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4194]
Maybe there's some trick to style it properly, but default is barely legible: 

![image](https://user-images.githubusercontent.com/75826/234158356-aa39636d-3c14-42b2-b644-43ea07e178e1.png)

```html
 <md-dialog id="terms-dialog" width="300">
        <div slot="header">
           ${msg('Terms and conditions')}
        </div>
        <p class="">
          ${msg(
          'By continuing, you agree to our Terms of Service and Privacy Policy.' }
        )}
        </p>
        <md-filled-button slot="footer" dialogAction="close">
          Cancel
        </md-filled-button>
        <md-filled-button
          id="confirm-button"
          slot="footer"
          @click=${this.handleAcceptTermsAndConditions}>
          ACCEPT
        </md-filled-button>
      </md-dialog>
```

**Comment by treeder** [comment]
If I change my `--md-sys-color-on-surface-variant-dark: black;` the the text shows up black so it's legible. 

It appears to be using the dark theme for the text color, but light theme for the surface of the dialog. I can see this when I switch from dark to light, everything else changes except the dialog backgrounds.

**Comment by juanpmarin** [comment]
![image](https://user-images.githubusercontent.com/13415603/234174402-defd927b-fca0-46ff-8066-90ed11cb9c2b.png)
Same bug here for md-menu!

**Comment by treeder** [comment]
This is a pretty bad regression, makes pre.7 basically unusable, can we get a quick hotfix for this and a pre.8 release?

**Comment by mavyfaby** [comment]
As per comment in https://github.com/material-components/material-web/issues/4145#issuecomment-1509437477.

If you're using [@material/material-color-utilities](https://www.npmjs.com/package/@material/material-color-utilities), the library broke due to the new tonal surface updates.

**Comment by christopher-kleine** [comment]
Is there an ETA for this? Would be nice to know.

**Comment by asyncLiz** [comment]
This is more of an issue with the material color utilities project, not MWC :/

I heard they were working on it though! @rodydavis and @e111077 might know more

**Comment by e111077** [comment]
If you are using material theme builder, the tokens there are missing the container tokens. While the team is updating that, please use the "Dynamic" scheme here to generate your tokens to match the behavior of material theme builder's color generator

https://lit.dev/playground/#gist=abcc77f636c1b76506df860db6dc0faf&view-mode=preview

**Comment by juanpmarin** [comment]
@rodydavis container are still not included in theme builder, is there a way to generate them?

**Comment by rodydavis** [comment]
Working on preparing the release! It will be on the next update

**Comment by juanpmarin** [comment]
@rodydavis awesome, thanks! is there a place to track theme builder's releases?

**Comment by treeder** [comment]
This released yet?

**Comment by e111077** [comment]
Md-dialog should work with the latest tokenset. Confirmed in pre.16

**Comment by treeder** [comment]
I tried the material theme builder again today and it still doesn't have any new tokens.

**Comment by asyncLiz** [comment]
> I tried the material theme builder again today and it still doesn't have any new tokens.

Have you tried the Material Figma plugin? I think that's up to date for generating the new surface tokens

https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder

https://github.com/material-foundation/material-color-utilities would be the best place to raise these types of issues with the TS library.

According to https://github.com/material-foundation/material-color-utilities/issues/98, it looks like the changes have landed. Maybe verify that you're on the latest? One of the comments suggested running `npm install @material/material-color-utilities@0.2.7 --save-exact`, since npm wasn't auto updating it.

**Comment by treeder** [comment]
I'm using this one linked from the material spec site: https://m3.material.io/theme-builder#/custom

**Comment by asyncLiz** [comment]
> I'm using this one linked from the material spec site: https://m3.material.io/theme-builder#/custom

Unfortunately I don't know when that tool will be updated. I'd suggest trying out the figma plugin if possible
