### ISSUE TITLE
Make text-field.handleInput and renderSupportingText protected

### ISSUE THREAD

**Issue by govis** [material-components/material-web#4200]
Change <code>handleInput</code> and <code>renderSupportingText</code> methods of <code>TextField</code> from <code>private</code> back to <code>protected</code> to allow for extensibility

**Comment by asyncLiz** [comment]
Thanks for the issue! At the moment extending the components and overriding methods are not part of our API surface.

We'll be happy to revisit extensibility in a future release :)
