### ISSUE TITLE
Why are the fourColor names of linear and circular different?

### ISSUE THREAD

**Issue by bre97-web** [material-components/material-web#4237]
Hello.
When I looked at the code of the linear progress and circular progress, I found that the linear and circular "fourColor" are not the same.
Why does "**fourColor**" in LinearProgress need to be spelled "**fourColors**"?

```html
<md-circular-progress fourColor></md-circular-progress>
```

```html
<md-linear-progress fourColors></md-linear-progress>
```

**Comment by asyncLiz** [comment]
Fixed in #4241
