### ISSUE TITLE
[md-dialog] escapeKeyAction not working

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#4244]
**Describe the issue**

Setting the attribute `escapeKeyAction=""` on `md-dialog` doesn't seem to work.

**Expected result**

Pressing the escape key on the keyboard while the dialog is opened SHOULD prevent the dialog from closing.

**Current behavior**

dialog closes.

**Reproduction steps / Example**

[example on Lit Playground](https://lit.dev/playground/#gist=eec8bb7e8cd6951d8c899b8ad46c2d51)

**Comment by asyncLiz** [comment]
@sorvell is this the right way to disable dialog closing on escape key press? Is this a feature that is supported?

**Comment by vdegenne** [comment]
@asyncLiz Just to corroborate, this was a working feature in `mwc-` branch.
