### ISSUE TITLE
State of SSR?

### ISSUE THREAD

**Issue by AxelBriche** [material-components/material-web#4245]
Hello, is the "SSR" compatibility planned for 1.0 or even later?

There are now many fullstack frameworks like Next, Nuxt, Sveltekit, is a compatibility planned?

Currently using Material Web in one of these frameworks creates a delay of one second during which the components are not visible.

![CleanShot 2023-05-08 at 15 43 18](https://user-images.githubusercontent.com/1295251/236840083-774020c6-c70a-4c72-8cf1-9e5b92f03812.gif)

**Comment by asyncLiz** [comment]
Not officially planned* for 1.0, but lit-ssr support may come out of the box :)

**Comment by e111077** [comment]
Hello, update: he components should be SSRable via `@lit-labs/ssr`.

For NextJS integration see `@lit-labs/nextjs`:

https://www.npmjs.com/package/@lit-labs/nextjs

for React sans next see `@lit-labs/ssr-react`:

https://www.npmjs.com/package/@lit-labs/ssr-react

Nuxt lit implementation is in progress. I am going to close this issue because this component set complies with lit-ssr requirements. Future issues for integrations of lit-ssr should be filed on the Lit project over at https://github.com/lit/lit

**Comment by e111077** [comment]
Here is a NextJS example using button and textfield:

https://stackblitz.com/edit/stackblitz-starters-cbt8zs?description=The%20React%20framework%20for%20production&file=next.config.js,pages%2Findex.js&title=Next.js%20Starter

**Comment by benjamincox** [comment]
@e111077 Why do the labels of both of these show up as some default Serif font in Chrome? Kind of looks like Times to me. Shouldn't these appear as Roboto or something? Selecting the button and inspecting, it seems there are no values for var(--_label-text-type).

<img width="779" alt="image" src="https://github.com/material-components/material-web/assets/137004/408b9fa5-dc3d-4fe6-8ffb-520d3dae37ed">

**Comment by e111077** [comment]
You need to load the actual Roboto font (or whatever font you change the label type to)

https://fonts.google.com/specimen/Roboto

**Comment by benjamincox** [comment]
@e111077 I don't seem to have edit privileges on your StackBlitz

**Comment by e111077** [comment]
Heya I've updated the link with an external link import of Roboto. Please let me know if there are other issues

**Comment by benjamincox** [comment]
@e111077 Looks perfect now - thanks much!

**Comment by benjamincox** [comment]
@e111077 Hmmm... any idea why there is a FOUC effect? Is it somehow because the components load their CSS via Javascript?

**Comment by e111077** [comment]
If you mean a fouc from the fonts it's likely because font has font-display swap. Personally I'd recommend hosting the font locally and setting swap to not block render as well as keep the FOUC time low since you don't have to open a new network connection

**Comment by JosefJezek** [comment]
@e111077 please resolve an issue in Astro, see https://stackblitz.com/edit/github-uiraud?file=src%2Fpages%2Findex.astro

**Comment by JosefJezek** [comment]
I created issue https://github.com/withastro/astro/issues/8216
