### ISSUE TITLE
change palette color

### ISSUE THREAD

**Issue by Olatechworld** [material-components/material-web#4280]
Hello, I would like to thank all the contributors for their work. I would like to know in which file or folder I can modify the default color palette in order to adapt it. THANKS

**Comment by tanishqmanuja** [comment]
all components use certain design token, which in case of web is implemented using css variables. You can change css variable using https://www.npmjs.com/package/@material/material-color-utilities.

Example Snippet:
```typescript
import {
  themeFromSourceColor,
  argbFromHex,
  applyTheme,
} from "@material/material-color-utilities";

const hexColor = "#ff00ff"; // any color you want
const theme = themeFromSourceColor(argbFromHex(hexColor));

applyTheme(theme, {dark: true})
```
