### ISSUE TITLE
[md-dialog] [md-button] [md-icon] dialog-action not working

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#4285]
**What problem are you having ?**

When using `dialog-action` attribute on a button in a dialog, clicking the leading icon won't close the dialog.

**Demonstration**
Reproducible example : https://lit.dev/playground/#gist=77b206c931c6a2f3590b54e7a22220f1

**Version**
@material/web : v1.0.0-pre.12

**Comment by asyncLiz** [comment]
Obsolete with https://github.com/material-components/material-web/pull/4677
