### ISSUE TITLE
md-outlined-select options list height: 100%

### ISSUE THREAD

**Issue by gdevacc12** [material-components/material-web#4291]
# Problem
When the list of options is longer than the height of the browser window, it is difficult to scroll through the options list to select the desired option, as the option list height is 100%.
# Expected behaviour
To have the option list with a scroll bar and to be able to set the max-height of the list.
# Comments
Apologies if this my ignorance on styling the component. Please advise if I missed something.

**Comment by asyncLiz** [comment]
Can you provide a lit.dev/playground or screenshots of the issue?

**Comment by gdevacc12** [comment]
@asyncLiz attached image.
![image](https://github.com/material-components/material-web/assets/1928736/35938427-7f57-44df-9984-06ec64db610d)

**Comment by e111077** [comment]
md menu can have max-height set on it, but unfortunately it's in the shadow root of md-select, so it's not settable. Will investigate adding a css custom property
