### ISSUE TITLE
outlined-text-field label disappearing (overflow hidden) 

### ISSUE THREAD

**Issue by VandeurenGlenn** [material-components/material-web#4318]
![image](https://github.com/material-components/material-web/assets/8685280/78cdaed5-10de-48ed-b2b8-658cd82fd228)

**Comment by asyncLiz** [comment]
This is to be expected, since the outlined text field's label extends beyond the bounds of the container.

Removing `overflow: hidden` from the text field will solve the problem. Can you provide a use case for when you need to set the overflow directly on a text field?

**Comment by VandeurenGlenn** [comment]
@asyncLiz In de console I tried putting like everything in it to overflow: auto

In the code there isn't  an overflow set the example above is the md-dialog with md-text-field in it.

**Comment by asyncLiz** [comment]
Gotcha, d'you mind putting together a lit.dev/playground repro?

**Comment by bre97-web** [comment]
try to set padding or margin.

**Comment by bre97-web** [comment]
<img width="387" alt="image" src="https://github.com/material-components/material-web/assets/67639369/1873ae14-aa09-440a-9aea-893fd151f024">

**Comment by VandeurenGlenn** [comment]
> Gotcha, d'you mind putting together a lit.dev/playground repro?

@asyncLiz Ill see if I can do that today

**Comment by VandeurenGlenn** [comment]
@bre97-web 
https://github.com/material-components/material-web/blob/f9da93553bd64e7e8475f8acb8ee12206af12ac4/dialog/lib/_dialog.scss#L193

When overflow is set to hidden in the contrainer then it doesn't matter if content has auto

**Comment by VandeurenGlenn** [comment]
@asyncLiz https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCAnQG1hdGVyaWFsL3dlYi9kaWFsb2cvZGlhbG9nLmpzJztcbmltcG9ydCAnQG1hdGVyaWFsL3dlYi90ZXh0ZmllbGQvb3V0bGluZWQtdGV4dC1maWVsZC5qcyc7XG5cbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogYmx1ZSB9YDtcblxuICBzdGF0aWMgcHJvcGVydGllcyA9IHtcbiAgICBuYW1lOiB7dHlwZTogU3RyaW5nfSxcbiAgfTtcblxuICBjb25zdHJ1Y3RvcigpIHtcbiAgICBzdXBlcigpO1xuICAgIHRoaXMubmFtZSA9ICdTb21lYm9keSc7XG4gIH1cblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPG1kLWRpYWxvZyBvcGVuPlxuICAgIDxtZC1vdXRsaW5lZC10ZXh0LWZpZWxkIGxhYmVsPVwidGVzdFwiPjwvbWQtb3V0bGluZWQtdGV4dC1maWVsZD5cbiAgPC9tZC1kaWFsb2c-YDtcbiAgfVxufVxuY3VzdG9tRWxlbWVudHMuZGVmaW5lKCdzaW1wbGUtZ3JlZXRpbmcnLCBTaW1wbGVHcmVldGluZyk7XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbiAgXG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d
