### ISSUE TITLE
Using system color

### ISSUE THREAD

**Issue by drsounds** [material-components/material-web#4346]
Will you make it possible to set so the accent color matches the host os session color (eg the color of Material You on Android >= 12, accent color on macOS etc.
Is there any Web API supporting getting the user accent colors except the old deprecated ones?
This is one of the key features of Material You

**Comment by asyncLiz** [comment]
At the moment there is not a Web API for this, it'd need a proposal and buy-in from the major browser vendors.

Closing since this is out of our scope, but I'd encourage you to file feature requests in Chromium and/or Android ! That'd be a good place to start the discussion.
