### ISSUE TITLE
[md-radio] 1.0.0-pre.9 breaks radio behavior in radio groups

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#4347]
Thanks a lot for the new release - it starts to look really good. 

1.0.0-pre.9 seems to break (SingleSelectionController) `md-radio` as illustrated below: 
- radio are not selected on click
- navigation through radio with keyboard arrows do not select the active radio

**non working example (1.0.0-pre.9)** 
![vokoscreenNG-2023-05-26_15-37-40](https://github.com/material-components/material-web/assets/1168053/958b15de-264d-41c2-bdd2-a133d25eebe9)

**working example (1.0.0-pre.8)** 
replace pre.9 by pre.8 in playground

[link to playground](https://lit.dev/playground/#gist=0426053e25d912925515d641cd8313ff)

**Comment by asyncLiz** [comment]
rip 🙃

**Comment by christophe-g** [comment]
> rip upside_down_face

Oh yeah sorry, two animations in the same issue is a bit too much.

**Comment by austinw-fineart** [comment]
To be more technical, the radios still function logic-wise. It's just that the styling relied on the existence of the checked attribute on the input that is no longer reflected by the corresponding property.

**Comment by asyncLiz** [comment]
Yup! I've got a PR coming to fix the styling soon, just gotta investigate a client failure
