### ISSUE TITLE
Consider using semantic HTML for the switch component

### ISSUE THREAD

**Issue by DeadlyMissile** [material-components/material-web#4354]
Switch component uses a button with role switch and aria properties. Consider switching (pun unintended) to `<input type=“checkbox” role=“switch” >` instead.

**Comment by asyncLiz** [comment]
Switches are toggle buttons, which is why we're using a button instead of a checkbox :)

**Comment by DeadlyMissile** [comment]
@asyncLiz According to the [APG](https://www.w3.org/WAI/ARIA/apg/patterns/switch/#), this is not exactly true.

> A switch is an input widget that allows users to choose one of two values: on or off. Switches are similar to checkboxes and toggle buttons, which can also serve as binary inputs. One difference, however, is that switches can only be used for binary input while checkboxes and toggle buttons allow implementations the option of supporting a third middle state. Checkboxes can be checked or not checked and can optionally also allow for a partially checked state. Toggle buttons can be pressed or not pressed and can optionally allow for a partially pressed state.

**Comment by asyncLiz** [comment]
That describes switches as similar to checkboxes and toggle buttons, which is still accurate. Our switch is most similar to a toggle button in Material Design.

From an assistive technology's perspective though, they are identical. `<button role="switch">` is semantically the same as `<input type="checkbox" role="switch">` or `<div role="switch">`.
