### ISSUE TITLE
md-standard-icon-button doesn't show icon but md-icon does

### ISSUE THREAD

**Issue by VandeurenGlenn** [material-components/material-web#4355]
## doesn't work
```html
<md-standard-icon-button data-variant="icon" slot="end" ?public=${this.public === 'true'} @click=${this.#publicClicked}>public</md-standard-icon-button>
```
<img width="228" alt="Screenshot 2023-05-29 at 18 20 26" src="https://github.com/material-components/material-web/assets/8685280/1ae16dd8-02a0-44d9-bdde-e4df846ad82d">

## works
```html
 <md-icon data-variant="icon" slot="end" ?public=${this.public === 'true'} @click=${this.#publicClicked}>public</md-icon>
```
<img width="139" alt="Screenshot 2023-05-29 at 18 22 57" src="https://github.com/material-components/material-web/assets/8685280/f17308d1-c7b3-4ae8-8e6f-d0275db356e4">

**Comment by asyncLiz** [comment]
This was recently changed. Use `<md-icon>` as a child of `<md-standard-icon-button>` to use font ligature icons.

```html
<md-standard-icon>
  <md-icon>public</md-icon>
</md-standard-icon>
```
