### ISSUE TITLE
md-select: Item in "start" slot only displays when open, but not after it's selected

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4377]
For example, open select:

![image](https://github.com/material-components/material-web/assets/75826/c2286e49-698d-4762-a983-484e31fa714d)

And after selected:

![image](https://github.com/material-components/material-web/assets/75826/70b96b39-8327-4433-a162-2237cd4501e7)

**Comment by asyncLiz** [comment]
What is the expected intention? For the menu item icon to also display in the select?

If so, I don't believe that's a default behavior. You could add it by updating the select's leading icon on changes.

**Comment by treeder** [comment]
I think I would expect that... I'm trying to think of a use case where I wouldn't expect it to show the same thing I selected. 🤔

**Comment by asyncLiz** [comment]
For this use case, we'd recommend dynamically updating the select's leading icon to match the icon of the item selected.

**Comment by treeder** [comment]
That's what I did, not very intuitive, but it works. Thanks.

**Comment by treeder** [comment]
BTW, this is what happens by default if you don't do some hacking to update the icon slot on the select, doesn't feel or look right. 

[Screen recording 2023-08-03 2.33.53 PM.webm](https://github.com/material-components/material-web/assets/75826/0f7336ba-6518-496c-aaec-0e8fa12c8723)
