### ISSUE TITLE
How to create a textarea?

### ISSUE THREAD

**Issue by fhuonder** [material-components/material-web#4386]
Hi,

I am working with the new material 3 components.
My page is running on version v1.0.0-pre.9.

I am askign myself how I can create a text field (e.g. `<md-outlined-text-field>`) that is a textarea?
In the code I find some hints that it might already work, but I dont see how.

Regards,
Florian

**Comment by asyncLiz** [comment]
It's not implemented yet, but there will be multiline attributes to text field to change it to a textarea.

See https://github.com/material-components/material-web/issues/4171 for the tracking issue :)
