### ISSUE TITLE
Rewriting property attributes to kebab-case

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#4393]
Property attributes should be rewritten as kebab-case.  
I opened a PR there : https://github.com/material-components/material-web/pull/4392

Here's a progress list:

- [x] badge/
- [x] button/
- [ ] catalog/
- [ ] checkbox/
- [ ] chips/
- [ ] circularprogress/
- [ ] controller/
- [ ] dialog/
- [ ] divider/
- [ ] docs/
- [ ] elevation/
- [ ] fab/
- [ ] field/
- [ ] focus/
- [ ] icon/
- [ ] iconbutton/
- [ ] internal/
- [ ] labs/
- [ ] linearprogress/
- [ ] list/
- [ ] localization/
- [ ] menu/
- [ ] motion/
- [ ] navigationbar/
- [ ] navigationdrawer/
- [ ] navigationtab/
- [ ] node_modules/
- [ ] radio/
- [ ] ripple/
- [ ] sass/
- [ ] segmentedbutton/
- [ ] select/
- [ ] segmentedbuttonset/
- [ ] slider/
- [ ] switch/
- [ ] tabs/
- [ ] testing/
- [ ] textfield/
- [ ] tokens/

**Comment by asyncLiz** [comment]
Think this is done now
