### ISSUE TITLE
Clarify design of mwc-card

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-web#442]
Related #254

Card seem to be extremely flexible in design, which makes the API problematic to implement.

It also seems like some of the design examples aren't completely internally consistent (https://github.com/material-components/material-components-web-components/pull/254#discussion_r318165980)

This issue exists both to document a good design for the mwc-card component, and to reference for talking to the design team

**Comment by fernandopasik** [comment]
Is there an issue in https://github.com/material-components/material-components-web to follow about the block?

**Comment by e111077** [comment]
Hello, unfortunately no. This is the prime issue on this topic, it's just stuck in our backlog.

**Comment by e111077** [comment]
de-prioritized for SSR work first

**Comment by asyncLiz** [comment]
Card is coming soon... 👀
