### ISSUE TITLE
Material components with react TSX

### ISSUE THREAD

**Issue by BlRaphael** [material-components/material-web#4428]
Hi! Is there anyway to use material components in my react project, in .tsx file?

**Comment by asyncLiz** [comment]
Tracking in https://github.com/material-components/material-web/issues/4433

**Comment by anlexN** [comment]
@asyncLiz, does material web team have a plan to follow [android compose](https://developer.android.com/develop/ui/compose) code style?

After all, android compose is belong to google. react is belong to facebook(meta).

If you have such a plan, I can understand more source codes about material design.

compose and tsx are the similar, I recommand material web team can try and try.
