### ISSUE TITLE
Update M2 docs to point to M3

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#4442]
The old docs published on NPM are published to individual packages. We need to go through the https://github.com/material-components/material-web/tree/mwc branch, update all the READMEs and then lerna publish them.

Q3 but a good choice for an easy, yet laborious PR

**Comment by Vue-Pu** [comment]
`#4442`

**Comment by asyncLiz** [comment]
Closing this as complete since we added deprecation warnings to all the old M2 packages: https://www.npmjs.com/package/@material/mwc-button
