### ISSUE TITLE
Do not publish catalog\node_modules\typescript directory to NPM

### ISSUE THREAD

**Issue by govis** [material-components/material-web#4446]
Please exclude catalog\node_modules\typescript directory from the Node module - it's unnecessary 60MB to download

**Comment by Aworldc** [comment]
Does the catalog need to be published to npm at all? Unless I'm missing something, you could probably just exclude the whole /catalog directory.

**Comment by asyncLiz** [comment]
Think this is just an oversight

**Comment by e111077** [comment]
yikes on it rn

**Comment by e111077** [comment]
PR out for review. it was package.json's `files` overriding `.npmignore`
