### ISSUE TITLE
[BUG] [v1.0.0-pre.10] Buttons not working on Safari mobile 

### ISSUE THREAD

**Issue by kkachniarz220** [material-components/material-web#4451]
### Bug description
Since version _v1.0.0-pre.10_ the buttons are not rendering on mobile iOS v15.7.5.

### Screenshoots

<img width="1440" alt="Zrzut ekranu 2023-06-15 o 12 51 54" src="https://github.com/material-components/material-web/assets/50884231/0427d1ec-6067-4c57-aa25-6e4ce0680ede">

<img width="1440" alt="Zrzut ekranu 2023-06-15 o 12 52 29" src="https://github.com/material-components/material-web/assets/50884231/c65735a0-c092-4f31-b5a7-e6bec89e87bc">

<img width="1440" alt="Zrzut ekranu 2023-06-15 o 13 09 36" src="https://github.com/material-components/material-web/assets/50884231/5db4242b-ce1a-400f-9924-eabd0e51360c">

![IMG_91020F677570-1](https://github.com/material-components/material-web/assets/50884231/69c18d97-e638-4e96-86ce-a6d20a9235a0)

**Comment by asyncLiz** [comment]
I have a bug to update our readme with browser support levels, but the project right now only supports Safari 16.4+

**Comment by kkachniarz220** [comment]
Is planning to support at least v15?

**Comment by asyncLiz** [comment]
ElementInternals polyfills may make it work! Though we haven't done extensive testing on it due to time constraints :(
