### ISSUE TITLE
Not working/Partially working textfield types

### ISSUE THREAD

**Issue by maicol07** [material-components/material-web#4457]
The following textfield types are not rendered correctly or are partially working (i.e. missing right button feature):
- Date
- Time
- Datetime-local
- Month
- Week
- Color
- File

[Demo and comparison with browser default](https://lit.dev/playground/#project=W3sibmFtZSI6Im1haW4udHMiLCJjb250ZW50IjoiaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL3RleHRmaWVsZC9maWxsZWQtdGV4dC1maWVsZC5qcyc7In0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL21haW4uanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8aDE-Tm90IHdvcmtpbmcvbm90IGRpc3BsYXllZCBjb3JyZWN0bHkgZmllbGQgdHlwZXM8L2gxPlxuICA8aDI-RGF0ZTwvaDI-XG4gIDxtZC1maWxsZWQtdGV4dC1maWVsZCBsYWJlbD1cIkRhdGVcIiB0eXBlPVwiZGF0ZVwiPjwvbWQtZmlsbGVkLXRleHQtZmllbGQ-XG4gIDxpbnB1dCB0eXBlPVwiZGF0ZVwiLz5cbiAgPGgyPlRpbWU8L2gyPlxuICA8bWQtZmlsbGVkLXRleHQtZmllbGQgbGFiZWw9XCJUaW1lXCIgdHlwZT1cInRpbWVcIj48L21kLWZpbGxlZC10ZXh0LWZpZWxkPlxuICA8aW5wdXQgdHlwZT1cInRpbWVcIi8-XG4gIDxoMj5EYXRldGltZS1sb2NhbDwvaDI-XG4gIDxtZC1maWxsZWQtdGV4dC1maWVsZCBsYWJlbD1cIkRhdGV0aW1lXCIgdHlwZT1cImRhdGV0aW1lLWxvY2FsXCI-PC9tZC1maWxsZWQtdGV4dC1maWVsZD5cbiAgPGlucHV0IHR5cGU9XCJkYXRldGltZS1sb2NhbFwiLz5cbiAgPGgyPk1vbnRoPC9oMj5cbiAgPG1kLWZpbGxlZC10ZXh0LWZpZWxkIGxhYmVsPVwiTW9udGhcIiB0eXBlPVwibW9udGhcIj48L21kLWZpbGxlZC10ZXh0LWZpZWxkPlxuICA8aW5wdXQgdHlwZT1cIm1vbnRoXCIvPlxuICA8aDI-V2VlazwvaDI-XG4gIDxtZC1maWxsZWQtdGV4dC1maWVsZCBsYWJlbD1cIk1vbnRoXCIgdHlwZT1cIndlZWtcIj48L21kLWZpbGxlZC10ZXh0LWZpZWxkPlxuICA8aW5wdXQgdHlwZT1cIndlZWtcIi8-XG4gIDxoMj5Db2xvcjwvaDI-XG4gIDxtZC1maWxsZWQtdGV4dC1maWVsZCBsYWJlbD1cIkNvbG9yXCIgdHlwZT1cImNvbG9yXCI-PC9tZC1maWxsZWQtdGV4dC1maWVsZD5cbiAgPGlucHV0IHR5cGU9XCJjb2xvclwiLz5cbiAgICA8aDM-V2l0aCA8Y29kZT53aWR0aDogMjUwcHg8L2NvZGU-PC9oMz5cbiAgICA8bWQtZmlsbGVkLXRleHQtZmllbGQgbGFiZWw9XCJDb2xvclwiIHR5cGU9XCJjb2xvclwiIHN0eWxlPVwid2lkdGg6IDI1MHB4XCI-PC9tZC1maWxsZWQtdGV4dC1maWVsZD5cbiAgXG4gIDxoMj5GaWxlPC9oMj5cbiAgPG1kLWZpbGxlZC10ZXh0LWZpZWxkIGxhYmVsPVwiRmlsZVwiIHR5cGU9XCJmaWxlXCI-PC9tZC1maWxsZWQtdGV4dC1maWVsZD5cbiAgPGlucHV0IHR5cGU9XCJmaWxlXCIvPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

**Comment by asyncLiz** [comment]
These types of text fields are [not fully supported](https://github.com/material-components/material-web/blob/47614f3c6760197f7296b64127d55cf8ff54802f/textfield/lib/text-field.ts#L25-L29) and may have missing features or undefined designs. You may find that some things need to be manually added, like icon buttons or a width.
