### ISSUE TITLE
[top-app-bar-fixed] div.mdc-top-app-bar--fixed-adjust element should be sizable

### ISSUE THREAD

**Issue by justinfagnani** [material-components/material-web#449]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Current behavior:**
If you size `<mwc-top-app-bar-fixed>` so that it's 100% height, the inner `div.mdc-top-app-bar--fixed-adjust` element is not sized the same, so that if you give a background to the slotted content element, the background doesn't actually affect the entire content area.

**Expected behavior:**
The `div.mdc-top-app-bar--fixed-adjust` element should be an implementation detail, so it should be at least default sized to cover the full content area. There might be use cases where devs need to style the element too (flex box or grid?).

**Comment by hunterloftis** [comment]
Is there a recommended way to use `mwc-top-app-bar` in a full-screen application? Specifically, I'd like its `content` slot to extend from the bottom of the app bar to the bottom of the viewport.

**Comment by asyncLiz** [comment]
Obsolete in M3
