### ISSUE TITLE
[md-icon-button] Incorrect spacing on iOS Safari

### ISSUE THREAD

**Issue by sc10101** [material-components/material-web#4497]
Is it possible to add support for `spacing-leading` and `spacing-trailing` tokens? 
This is because browser's default stylesheet is causing varied behaviour rendering the `md-*-icon-button`.

**Screenshots**
Rendered on Chrome 114
<img width="190" alt="image 1" src="https://github.com/material-components/material-web/assets/19958320/e71963ce-fd9e-4752-b81c-a4877dc996fc">

Rendered on iOS 16.4 Safari
<img width="255" alt="image" src="https://github.com/material-components/material-web/assets/19958320/18cd64c5-c841-4bb3-b730-6c6dca2e4f8d">

**Comment by OMARIHAMZA** [comment]
Same issue here

**Comment by OMARIHAMZA** [comment]
also found a similar issue: https://github.com/material-components/material-web/issues/2457

**Comment by asyncLiz** [comment]
We won't be exposing direct padding tokens right now for icon button. It looks like this is just a bug that needs to be fixed

**Comment by asyncLiz** [comment]
This should be fixed now!

**Comment by sc10101** [comment]
Thank you!
