### ISSUE TITLE
md-icon is not rendering icon

### ISSUE THREAD

**Issue by govis** [material-components/material-web#4507]
https://lit.dev/playground/#sample=examples%2Fhello-world&project=W3sibmFtZSI6Im15LWljb24udHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQgJ0BtYXRlcmlhbC93ZWIvaWNvbi9pY29uLmpzJztcbmltcG9ydCAnQG1hdGVyaWFsL3dlYi9pY29uYnV0dG9uL3N0YW5kYXJkLWljb24tYnV0dG9uLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ215LWljb24nKVxuZXhwb3J0IGNsYXNzIE15SWNvbiBleHRlbmRzIExpdEVsZW1lbnQge1xuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPG1kLWljb24-cHVibGljPC9tZC1pY29uPlxuPG1kLXN0YW5kYXJkLWljb24tYnV0dG9uPlxuICA8bWQtaWNvbj5wdWJsaWM8L21kLWljb24-XG48L21kLXN0YW5kYXJkLWljb24tYnV0dG9uPiAgICAgICAgXG4gICAgICAgIGA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9teS1pY29uLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPG15LWljb24-PC9teS1pY29uPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ

**Comment by asyncLiz** [comment]
Looks like you need to add a font import for Material Symbols. Add this to your HTML and it'll start working

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined" rel="stylesheet">
```
