### ISSUE TITLE
No animated md-dialog for testing

### ISSUE THREAD

**Issue by chumaltd** [material-components/material-web#4511]
Hi, I cannot click contents inside `md-dialog` with Selenium.

An error example, testing with -pre10 & -pre11, is as follows:

```python
>       wait_clickable(driver, "md-list-item:defined md-icon[slot='end']").click()

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7ff197e21370>
response = {'status': 400, 'value': '{"value":{"error":"element click intercepted","message":"element click intercepted: Element ...\\n#20 0x564e6b6be3bf \\u003Cunknown>\\n#21 0x564e6b6d8abe \\u003Cunknown>\\n#22 0x7f5bdae44609 \\u003Cunknown>\\n"}}'}

>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <md-icon slot="end">...</md-icon> is not clickable at point (74, 85). Other element would receive the click: <md-dialog transition="grow-down" showing-open="">...</md-dialog>
E         (Session info: headless chrome=104.0.5112.79)
```

`md-dialog` transforms contents after Selenium gets element by a selector.
I think `transition="none"` is a nice to have option, as Selenium cannot wait transition completeion.

Mitigation
------------
There may be some workarounds, I haven't found perfect one yet.

* I tried Chrome with `--force-prefers-reduced-motion`, but it doesn't work for some environments like [Official container image](https://hub.docker.com/r/selenium/standalone-chrome).
* Replacing `.click()` with `.send_keys(Keys.ENTER)` woks well. But `.send_keys()` compatible elements are limited. For example, `a` tag or `md-icon` doesn't handle keyboard operations.

**Comment by vdegenne** [comment]
Could this be related: https://github.com/material-components/material-web/issues/4285 ?

**Comment by chumaltd** [comment]
@vdegenne 
I have #4285 case, too. #4285 also happens on manual operations.

But this #4511 cases look another timing issue, including plain tags like `<a></a>` and so on.
`md-dialog` contents can be clicked manually, but cannot by auto tester like Selenium.

I just tested with latest pre12 build, but no luck.
Still `.click()` are rejected, while `.send_keys()` work.

**Comment by vdegenne** [comment]
@chumaltd Can't you just wait for the dialog to complete update? (e.g. `await dialog.updateComplete`). There is also `opened` event that gets dispatch when the dialog is fully interoperable.

**Comment by chumaltd** [comment]
@vdegenne No, browser testing tools like Selenium don't provide access to internal states, intentionally.
I agree that your approach will work with Javascript test runners like Jest w/JSDOM.

I'm using Selenium for total system testing purpose including backend services.
At this time, sending Enter key emulation looks the most feasible workaround.

**Comment by chumaltd** [comment]
I just tested w/ latest -pre17, and now Selenium can  `.click()` elements just after opening `md-dialog`.
It's a great rework !

At this time, I can get stable behavior without `--force-prefers-reduced-motion` option.
This behavior is preferrable for Selenium settings.
