### ISSUE TITLE
Add a Webcomponent Manifest 

### ISSUE THREAD

**Issue by jogibear9988** [material-components/material-web#4516]
I've a Designer Framework for webcomponents: https://node-projects.github.io/web-component-designer-demo/index.html

It could use external NPM packages, but depends that they have a webcomponent manifest (see: https://github.com/webcomponents/custom-elements-manifest).
Would it be possible to add one to the npm package?

**Comment by jogibear9988** [comment]
for example see: the shoelace elemnts could be used directly

<img width="958" alt="image" src="https://github.com/material-components/material-web/assets/364896/2ef9771a-e66b-4e50-a94c-eb1f4ca46a66">

**Comment by break-stuff** [comment]
This would also be really helpful to add framework and IDE integrations to the project.

**Comment by asyncLiz** [comment]
Duplicate of https://github.com/material-components/material-web/issues/545, we'll track it there
