### ISSUE TITLE
Typography: letter-spacing / tracking not applied

### ISSUE THREAD

**Issue by roundduck** [material-components/material-web#4517]
I see that the letter-spacing / tracking is not applied in components.

I'm aware that letter-spacing is not part of the font shorthand.

Is there an actual reason it was not included? Could it just be added with a pull request?

**Comment by asyncLiz** [comment]
Letter-spacing and tracking customization has historically not been heavily used in Material, and designers are considering removing those tokens.

To avoid future breaking changes and reduce typography complexity, we're not including letter-spacing or tracking until design is more confident with their use cases.
