### ISSUE TITLE
v1.0.0-pre.10 changes list does not mention removed alpha components

### ISSUE THREAD

**Issue by Burtan** [material-components/material-web#4522]
Hi,

some of the components for future versions have been removed from pre.9 to pre.10, like navigation bar. But this is not mentioned in the changes log. I would like to have them in the non final releases, but you could at least mention it as a breaking change?

**Comment by asyncLiz** [comment]
Hi!

Future components are still present and published to use, but they've been moved to `@material/web/labs` to indicate their status from the stable 1.0 components.

```js
import '@material/web/labs/navigationbar/navigation-bar.js';
```
