### ISSUE TITLE
md-button doesn't integrate with form data

### ISSUE THREAD

**Issue by jkrems** [material-components/material-web#4526]
I was adding an `md-button` to an existing form and thought it would act "just like a button with different styles". But it looks like the `type=submit` just emulates the behavior on a non-button element. But at least one behavior is missing from that emulation: A named submit button should show up in the form data. Example:

```
<form>
  <input name="txt" type="text" />
  <md-button name="btn" value="a" type="submit">Submit A</md-button>
  <md-button name="btn" value="b" type="submit">Submit B</md-button>
</form>
```

When submitting, I would expect `btn=a` or `btn=b` to appear in the form data, depending on which button was clicked to submit.  If the form is submitted by pressing `<enter>` while focussing the text input field, I would expect the first submit button's value to appear in the form data.

Example (hopefully stays online): https://jsfiddle.net/au82xrv9/1/

**Comment by jkrems** [comment]
It looks like there is a button inside of the custom element but it gets none of the attributes (name/value/type). Not sure if that would be the simplest fix or if there are downside to that approach.

**Comment by asyncLiz** [comment]
I just noted this yesterday while doing a review of button :)
