### ISSUE TITLE
[md-radio] Radio fail to render properly on Safari after some kind of threshold

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#4531]
Safari seems to not render radio-buttons after some time.

Tested on : 
- on 16.1 Ventura with `element-internals-polyfill`
- on 16.0 on Monterey, with same polyfill.

Everything happens as if the reference to the mask id (`#cutout`) is lost by Safari after some time or a certain amount of radio-buttons being rendered in the DOM (or potentially hidden / removed from the DOM).  

```svg
<svg class="icon" viewBox="0 0 20 20">
          <mask id="cutout">
            <rect width="100%" height="100%" fill="white" />
            <circle cx="10" cy="10" r="8" fill="black" />
      </mask>
      <circle class="outer circle" cx="10" cy="10" r="10" mask="url(#cutout)" />
      <circle class="inner circle" cx="10" cy="10" r="5" />
  </svg>
```

Radio buttons start to render as expected: 
![image](https://github.com/material-components/material-web/assets/1168053/daec7307-8366-4dff-8d92-d911496f6d94)

And then looks like: 
![Selection_296](https://github.com/material-components/material-web/assets/1168053/dac0da53-0beb-4ec3-8ef7-9304481d860c)

## Reproduction: 

- Go to https://lit.dev/playground/#gist=ff8acfb44f22190449c6c8863af8b07e;
- click on different top radio buttons  a couple of times 

## Workaround / fix: 

use a unique mask id for each radio button. 

I am aware it is not a md bug, but this can be pretty annoying for end-users.

**Comment by asyncLiz** [comment]
Is this problem present in Safari 16.4+? Versions before 16.4 [are not fully supported](https://github.com/material-components/material-web/#browser-support)

**Comment by christophe-g** [comment]
> Is this problem present in Safari 16.4+?

I cannot confirm as I do not have access to Safari 16.4+, and I don't know if Safari rendering engine has fixed this bug (that i could not find a report for btw). 

Can anyone with Safari 16.4 try the lit playground above and confirm ?

I am aware that versions before 16.4 are not officially supported, but it is going to be hard to disregard users with browsers older than Safari 16.4, released in march 2023. 

We distribute our app (accessiblesurveys.com) with relevant polyfills to support older browsers - it is working for older versions of Safari so far, while we are progressively migrating the MD2 base to MD3.

**Comment by asyncLiz** [comment]
Another thing that would be really helpful is a stripped down pure CSS reproduction and remove our web component logic entirely. If it's a bug and still present in Safari, that will help with the bug we can file on them.

I verified this is still a bug in Safari 16.4

**Comment by asyncLiz** [comment]
But in any case, it sounds like we may be able to solve this by using a uniquely generated ID for each radio's `<mask>` and setting that in the lit template?

**Comment by christophe-g** [comment]
>  it sounds like we may be able to solve this by using a uniquely generated ID for each radio's <mask>

This is what I have in my local override; it works.

**Comment by InsightfulFuture** [comment]
Same thing in Firefox 114.4 on iPadOS 16.5.1

**Comment by asyncLiz** [comment]
> Same thing in Firefox 114.4 on iPadOS 16.5.1

Yea, it'll be in Chrome on iOS too. Apple forces iOS browser vendors to use webkit, which is where the bug is.
