### ISSUE TITLE
[Feature Request] Custom icons state for `md-switch`

### ISSUE THREAD

**Issue by mavyfaby** [material-components/material-web#4549]
The current implementation of `md-switch` use only the `close` and `check` icon as seen in the source code.

## On Icon

![image](https://github.com/material-components/material-web/assets/51808724/c87a7997-4ed5-4fee-a110-2944bdb5491f)
https://github.com/material-components/material-web/blob/0ab5fd595d8c163065860a2e0deec8b77c8c9d77/switch/lib/switch.ts#L173-L179

## Off Icon

![image](https://github.com/material-components/material-web/assets/51808724/18fff0a7-88e8-4970-a8b7-c5ba50f2b614)
https://github.com/material-components/material-web/blob/0ab5fd595d8c163065860a2e0deec8b77c8c9d77/switch/lib/switch.ts#L184-L190

It would be great if this component `<md-switch />` implements this custom icon feature!

**Comment by asyncLiz** [comment]
I think I remember when design added icons into switch, I was like yo someone's gonna wanna change them sometime 😂

**Comment by mavyfaby** [comment]
That's me then 😂

**Comment by mavyfaby** [comment]
@asyncLiz Any news for this?

**Comment by asyncLiz** [comment]
This is likely low on our priority right now, but I think this could be a good community contribution if you want to take a stab at it!

```html
<md-switch>
  <md-icon slot="on-icon">...</md-icon>
  <md-icon slot="off-icon">...</md-icon>
</md-switch>
```

Inside the component we can use a slot with the current icons as fallbacks.

```html
<slot name="on-icon">
  <svg>...</svg>
</slot>
```
