### ISSUE TITLE
When does filled tonal become just tonal

### ISSUE THREAD

**Issue by austinw-fineart** [material-components/material-web#4553]
Not a biggie issue but I just thought it was funny that for buttons we've got md-filled-button and md-tonal-button, but for icon buttons we've got md-filled-icon-button and md-filled-tonal-icon-button. But it's always been that way so I guess there must be a reason. Totally doesn't bother me at all.

**Comment by asyncLiz** [comment]
We need to align on that naming. "Filled tonal" is redundant (a tonal button can never not be filled), but it's also what design refers to

**Comment by asyncLiz** [comment]
Button and icon button now use "filled-tonal" terminology
