### ISSUE TITLE
md-standard-icon-button getting squooshed

### ISSUE THREAD

**Issue by VandeurenGlenn** [material-components/material-web#4559]
<img width="355" alt="image" src="https://github.com/material-components/material-web/assets/8685280/887f7713-b6e9-4187-87bf-f5edc63c4b34">

**Comment by asyncLiz** [comment]
Commented on the PR, but can you provide a reproduction for this? At a glance it looks like the item is being placed inside a flex container and probably should have `flex-shrink: 0` set on it.
