### ISSUE TITLE
md-filled-text-field (type="textarea") not display line break in Firefox 

### ISSUE THREAD

**Issue by hakataminamiWS** [material-components/material-web#4581]
### Description:
using ```<md-filled-text-field> (type="textarea")```, line breaks entered in the textarea are not displayed in Firefox.
![image](https://github.com/material-components/material-web/assets/66231467/11c60d7f-ec00-450c-8215-5423fadbbb99)

However, they are displayed in Chrome.
![image](https://github.com/material-components/material-web/assets/66231467/1667f589-e657-465d-a0c7-615f68ec99c5)

Additionally, when setting ```style="white-space:pre-wrap;"``` with \<md-filled-text-field\>, line breaks are displayed.
But the label's display position changes.
Specifically, it appears to be center-aligned rather than left-aligned.
![image](https://github.com/material-components/material-web/assets/66231467/9136cb0a-f0c6-4a44-a70d-659400551329)
![image](https://github.com/material-components/material-web/assets/66231467/b1772e41-49da-47fa-a5d6-1f7f49d75dd5)

### Question:
Is it possible to set ```style="white-space:pre-wrap;"``` only for the \<textarea\> element of inside \<md-filled-text-field\>?

### Environment information:
- OS: Windows 11
- Firefox: 115.0.2 (64 bit)
- Chrome: 114.0.5735.201（Official Build）（64 bit）
- Version of md-filled-text-field: cloned and rebuild from
https://github.com/material-components/material-web/tree/2dabbdc142c88e4c94bcbcbaa333811e7126ba97

**Comment by asyncLiz** [comment]
Sounds reasonable, we'll investigate it
