### ISSUE TITLE
Text Field components do not support name attribute

### ISSUE THREAD

**Issue by caleb-sideras** [material-components/material-web#4589]
The md-[filled/outlined]-text-field components do not give you access to the underlying "name" input field attribute; so cannot use this component in a form without using JS. It's a bit unusual that these components do not support the name attribute, as it is pretty standard and would make these components more versatile and compatible with traditional form handling. 

The example below does not post the name attribute:
```html
<md-filled-text-field label="Add a new task" type="text" name="task"></md-filled-text-field>
```

**Comment by asyncLiz** [comment]
I believe [text field has a `name` property](https://github.com/material-components/material-web/blob/b5712f3d4b4845e98cfb74f145e400647b492823/textfield/lib/text-field.ts#L124-L132) and should work in form submission.

Example: https://lit.dev/playground/#gist=4bacf0a4b874c4a825f943bf8d0d946a

**Comment by caleb-sideras** [comment]
You're right thanks, rookie mistake. Couldn't see the name attribute in docs/source nor on the input element in DOM.

**Comment by engrbm87** [comment]
I noticed that the name attribute is not added to the input element. This disables autocomplete in the browser. The above example uses `form` but in case a form is not used the autocomplete doesn't work if the name attribute is not added to the input element.

**Comment by asyncLiz** [comment]
> I noticed that the name attribute is not added to the input element. This disables autocomplete in the browser. The above example uses `form` but in case a form is not used the autocomplete doesn't work if the name attribute is not added to the input element.

Do you mind opening a PR to forward the name attribute onto the inner `<input>` and `<textarea>` elements to support browser inferring autocomplete outside of a form?
