### ISSUE TITLE
Windows postinstall issue

### ISSUE THREAD

**Issue by anoblet** [material-components/material-web#459]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**
Windows 10 (Build 18362.295)

**What browser(s) is this bug affecting:**

**Current behavior:**
```
PS C:\Users\Andy\Web Development\material-components-web-components> npm i
> material-components-web-components@ postinstall C:\Users\Andy\Web Development\material-components-web-components      > ./scripts/bootstrap.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-components-web-components@ postinstall: `./scripts/bootstrap.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-components-web-components@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andy\AppData\Roaming\npm-cache\_logs\2019-09-05T23_53_37_874Z-debug.log
```
**Expected behavior:**
npm install runs without error
**Steps to reproduce:**
git clone
npm i

**Related code:**

NA

**Other information:**

**Comment by anoblet** [comment]
Seems to be a Windows only issue. I don't mind closing this in order to not overwhelm (hopefully with support for Windows in the future)

**Comment by tavisca-nrajpurohit** [comment]
@dfreedm any update on this issue?

**Comment by Misiu** [comment]
maybe this could be solved using dev containers? I'd like to work on some components, but can't start because Windows isn't supported :/
@asyncLiz any chance to priorities this? 🙂

**Comment by e111077** [comment]
Hello, we will get to this at some point, but in the meanwhile we recommend using WSL on windows.
