### ISSUE TITLE
md-navigation-drawer-modal missing scrim css property

### ISSUE THREAD

**Issue by caleb-sideras** [material-components/material-web#4619]
## Description
It seems no css property is set/generated for '--_scrim-color' for 'navigation-drawer-modal' 

![image](https://github.com/material-components/material-web/assets/66019710/919de513-57f6-41f4-ae42-5b2dabaea645)

I cannot override '--_scrim-color' in the css as it's in a constructed stylesheet
```css
--_scrim-color: var(--md-navigation-drawer-modal-scrim-color, default)
```

## Question
Maybe it's due to setting 'scrim-color' to null in the scss?
![image](https://github.com/material-components/material-web/assets/66019710/d72d3bb3-079f-4437-ac5f-1c01f1248cce)

## Environment
OS: Windows 11
Brave: 1.52.130
Chromium: 114.0.5735.198 (Official Build) (64-bit)
Build npm: "@material/web": "^1.0.0-pre.14"

**Comment by asyncLiz** [comment]
Closing since we're tracking nav drawer component support separately
