### ISSUE TITLE
Add per-component size tracking

### ISSUE THREAD

**Issue by sujato** [material-components/material-web#4626]
Before adding a component, i want a simple way to check the size of the download. I have been caught out by this in the past, adding what I thought was a simple material text field, only to find that it added 100kb of download, doubling the javascript on our home page.

Can we get a simple indication of component size in the documentation? Something like bundlephobia? Thanks!

**Comment by asyncLiz** [comment]
We don't have good numbers per-component yet, but we do have sizes for [all](https://github.com/material-components/material-web/blob/main/all.ts) components and [common](https://github.com/material-components/material-web/blob/main/common.ts) components: 89k and 69k g-zip'd.

**Comment by jfbrennan** [comment]
Yes, please fix the package so Bundlephobia works (https://bundlephobia.com/package/@material/web yields nothing)

**Comment by asyncLiz** [comment]
Sizes are now tracked at https://github.com/material-components/material-web/blob/main/docs/size.md
