### ISSUE TITLE
No height/width set on md-icon

### ISSUE THREAD

**Issue by VandeurenGlenn** [material-components/material-web#4639]
https://github.com/material-components/material-web/blob/2568d4fbac69c8b5e9a5d5198c6525224ebf778d/icon/internal/_icon.scss#L29

Setting the height and with to svg but not the element itself disables setting the desired width/height on the slotted svg element

**Comment by asyncLiz** [comment]
This has been fixed at head https://github.com/material-components/material-web/blob/65d04a3cf3cba46deb12cd0affa2649bf3e45407/icon/internal/_icon.scss#L29-L30
