### ISSUE TITLE
md-list-item headline truncation

### ISSUE THREAD

**Issue by kkachniarz220** [material-components/material-web#4666]
![image](https://github.com/material-components/material-web/assets/50884231/d66a5a8f-326b-45f1-9f54-a517145a8635)
![image](https://github.com/material-components/material-web/assets/50884231/a3a91159-4ef3-4165-bc83-4f51260ae519)

**Comment by davidurco** [comment]
@kkachniarz220 @asyncLiz I just opened a PR for this issue #4671 :)

**Comment by e111077** [comment]
fixed by #4671

**Comment by e111077** [comment]
thanks for the contribution!
