### ISSUE TITLE
[docs] Interactive demos are broken

### ISSUE THREAD

**Issue by Aworldc** [material-components/material-web#4672]
The interactive demos on material-web.dev are broken.

I get this error log in the console:

<img width="530" alt="image" src="https://github.com/material-components/material-web/assets/83331712/af61a020-a4c1-4a89-bce2-a40eb38add61">

here's the full log:

[material-web.dev-1691402211304.log](https://github.com/material-components/material-web/files/12285851/material-web.dev-1691402211304.log)

**Comment by asyncLiz** [comment]
Should be fixed with the next published version

**Comment by asyncLiz** [comment]
Fixed now
