### ISSUE TITLE
'Type 'TemplateResult' is not generic' error

### ISSUE THREAD

**Issue by liamsain** [material-components/material-web#4701]
Hi. Trying to build a project that imports linear-progress 
```ts
import '@material/web/progress/linear-progress.js';
```
```lit
     <md-linear-progress 
      .indeterminate="${false}"
      .progress="${0.5}"
      .buffer="${0}"
      .reverse="${0}"
      .closed="${false}"
      ></md-linear-progress>
```

When trying to build I'm getting the following error
```cmd
../../node_modules/@material/web/progress/internal/linear-progress.d.ts:23:34 - error TS2315: Type 'TemplateResult' is not generic.

23     protected renderIndicator(): import("lit-html").TemplateResult<1>;
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If I change 'lit-html' to 'lit' in the linear-progress.d.ts file it seems to fix the issue.

I've tried to replicate the issue by initalising a new lit ts project using the @open-wc tool and importing the linear progress from the @material/web library but unfortunately I'm not getting the same error.

Not sure how best to progress the issue. Any ideas?

**Comment by asyncLiz** [comment]
What version of `@material/web` and `lit` is the project using? Can you check your package-lock.json and make sure there are not multiple versions of lit?
