### ISSUE TITLE
Dialog content not showing on iPadOS 16.6 in Safari

### ISSUE THREAD

**Issue by pgbross** [material-components/material-web#4716]
Dialog content (slot="content") not showing in Safari on iPadOS 16.6.

The remainder of the dialog is functioning correctly - headline and actions slots show their markup and the action "buttons" work as expected.

To demonstrate the issue:
Go to [https://material-web.dev/components/dialog/](https://material-web.dev/components/dialog/ ) and open the interactive demo. Choose, say, the first simple dialog and notice the headline and actions are shown but the supporting text is missing.

Also note there are black "corners" showing around the dialog container.

![httpsmaterial-web devcomponentsdialog](https://github.com/material-components/material-web/assets/2621238/7753f2fd-b3ee-4c5b-9b8e-00b2cf720930)

**Comment by pgbross** [comment]
So on trying to find a workaround I note that the dialog.scss has an item that sets the css display property to flex when open

```css
dialog[open] {
    display: flex;
  }
```

if I change this to be block

```css
  dialog[open] {
    display: block;
  }
```

then the dialogs appear to show correctly on Safari (and I checked in Chrome on other devices).

There is no note or hint as to why on opening the dialog it is set to flex so can't tell the consequences of changing that to block. I do note that the immediate child is  `<div class="container">` and see that it is set to display flex so one might speculate the layout will be correct with the dialog element set to display block.

**Comment by asyncLiz** [comment]
Hm interesting. The dialog needs display: flex to handle automatic scrolling. I'll see if I can find a way around it

**Comment by asyncLiz** [comment]
Fixed in https://github.com/material-components/material-web/pull/4763
