### ISSUE TITLE
[Dialog] dialog opened by default not showing

### ISSUE THREAD

**Issue by maicol07** [material-components/material-web#4728]
Hi,
it seems that setting the open attribute before page loading/creation (before the element is added to the DOM) causes to show only the scrim and not the dialog. Subsequent openings work fine.
[Live demo](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4LnRzIiwiY29udGVudCI6ImltcG9ydCAnQG1hdGVyaWFsL3dlYi9kaWFsb2cvZGlhbG9nLmpzJztcbmltcG9ydCAnQG1hdGVyaWFsL3dlYi9idXR0b24vdGV4dC1idXR0b24uanMnO1xuXG5jb25zdCBkaWFsb2cgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdtZC1kaWFsb2cnKTtcblxuZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI29wZW5CdG4nKSEuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiBkaWFsb2cuc2hvdygpKTtcbmRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJyNjbG9zZUJ0bicpIS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0-IGRpYWxvZy5jbG9zZSgpKSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxtZC1kaWFsb2cgb3Blbj48L21kLWRpYWxvZz5cbiAgPG1kLXRleHQtYnV0dG9uIGlkPVwib3BlbkJ0blwiPk9wZW4gZGlhbG9nPC9tZC10ZXh0LWJ1dHRvbj5cbiAgPG1kLXRleHQtYnV0dG9uIGlkPVwib3BlbkJ0blwiPkNsb3NlIGRpYWxvZzwvbWQtdGV4dC1idXR0b24-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)
**Current behaviour**
![image](https://github.com/material-components/material-web/assets/9463142/f63c00c3-dabf-47eb-89d1-0096d3fc7313)
**Expected behaviour**
![image](https://github.com/material-components/material-web/assets/9463142/428b966a-d488-43a8-8381-24ec5c8a93b9)

**Comment by VandeurenGlenn** [comment]
Just encountered this also

Updating open in firstUpdate should fix it
