### ISSUE TITLE
The new "every button is a submit button" default behavior...

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4753]
With [this change](https://github.com/material-components/material-web/releases/tag/v1.0.0-pre.15), even icon buttons (eg: `<md-icon-button>`) and things are submitting forms, so I suppose we'll have to basically add `type="button"` to all icon buttons and what not too?  

I mostly use forms to group validation so I can call `form.reportValidity()` to validate all the children in one shot or `form.reset()`, but I never want my forms to actually old school submit (does anyone do that anymore?). 

Is there a way we could disable this new behavior or something? 

And yes, I understand this is to go along with the HTML spec, but preferred how it worked prior to pre.15.

**Comment by asyncLiz** [comment]
Historically the two ways of not submitting the form have been to add `type="button"` or by calling `submitEvent.preventDefault()`.

If you're using lit, you could create a `noSubmit` [custom directive](https://lit.dev/docs/templates/custom-directives/) to add to forms and reduce boilerplate.

```ts
html`
  <form ${noSubmit()}>
    <md-filled-button>Won't submit</md-filled-button>
  </form>
`;
```

Alternatively, you could change the built-in behavior by [adding an initializer](https://lit.dev/docs/components/lifecycle/#addInitializer) to the element's class.

```ts
import {MdFilledButton} from '@material/web/button/filled-button.js';

MdFilledButton.addInitializer(element => {
  (element as MdFilledButton).type = 'button';
});
```

Would either of those options work?

**Comment by treeder** [comment]
Initializer sounds interesting, I'll try that.
