### ISSUE TITLE
Add ability to add attributes to underlying inputs for checkbox and other form elements

### ISSUE THREAD

**Issue by aszenz** [material-components/material-web#4757]
Is their a possibility to pass attributes to underlying inputs, it would help us in migrating from native inputs to this library.

**Comment by asyncLiz** [comment]
Hi! Unfortunately no, the elements encapsulated by the shadow dom cannot allow arbitrary attributes.

Can you give more details to what attributes you want to set and why?

**Comment by asyncLiz** [comment]
Closing since this isn't a planned feature, but we'd love to hear more about your use case!

Generally we recommend treating the element itself as an "`<input>`" and adding attributes to it as needed.

```html
<md-outlined-text-field label="Label" data-custom-info="foo">
```

**Comment by aszenz** [comment]
Primary use case for behaving like native input fields is to ease integration with our backend form libraries that only know about html attributes. This can be solved in various other ways though.

Issue is each web component library defining its own api for things like inputs (onchange/ handlechange), making integration complicated unnecessarily.

**Comment by asyncLiz** [comment]
> Issue is each web component library defining its own api for things like inputs

Can you elaborate what APIs are not compatible? Our components aim for parity with platform elements, so `<md-outlined-text-field>` should have the same API structure as `<input>`, including events, properties, and attributes.
