### ISSUE TITLE
Console error for md-outlined-select in surfacePositionController.ts

### ISSUE THREAD

**Issue by MoaLeonhardt** [material-components/material-web#4780]
The issue is a console error saying "Uncaught (in promise)" in onUpdate() method of surfacePositionController.ts.

### Reproduce issue
Given below HTML code and versions, click to expand the menu and then click again. At every new click the console error is being output.

### package.json
```JSON
"dependencies": {
    "@material/web": "^1.0.0-pre.16",
    "lit": "^2.6.1"
  }

```

### HTML
```HTML
<md-outlined-select>
      <md-select value="1" headline="First option">First option</md-select>
      <md-select value="2" headline="Second option">Second option</md-select>
</md-outlined-select>

```
![stacktrace](https://github.com/material-components/material-web/assets/82035050/b7cebaed-de1c-4a67-aa2a-da541adaa608)

**Comment by asyncLiz** [comment]
Hi, sorry for the delay on this. Can you provide a reproduction link on lit.dev/playground? That'd help us in debugging this

**Comment by asyncLiz** [comment]
Closing for now, please post a repro if you're still having issues!
