### ISSUE TITLE
Required textfields are always unfilled in Safari

### ISSUE THREAD

**Issue by danilotomaccio** [material-components/material-web#4796]
Required textfields on Safari return an error also when filled. To reproduce the error just open the [interactive demo](https://material-web.dev/components/text-field/#interactive-demo), set the fields to required and fill them
<img width="633" alt="image" src="https://github.com/material-components/material-web/assets/21012635/a2424e8b-ad2e-464e-82ed-ce618db424f4">

**Comment by christophe-g** [comment]
As fields now rely on [element internals](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals), you might need  `import 'element-internals-polyfill'` depending on your version of Safari.

**Comment by asyncLiz** [comment]
Hm I'm getting this error in Safari 16.4, it doesn't appear to be ElementInternals related

**Comment by asyncLiz** [comment]
Looks like an underlying webkit bug. I filed https://bugs.webkit.org/show_bug.cgi?id=261432

Should have a workaround fix coming shortly
