### ISSUE TITLE
md-list - question re stopping click event propagation

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#4817]
md-list stops click event propagation: https://github.com/material-components/material-web/blob/9389e26b68705e82c1cde5469ab7777790db5477/list/internal/list.ts#L94

This potentially break the use of  `md-list` with an application router (for instance, https://github.com/andreasbm/router-slot) as the router will not receive a click event in a scenario like this : 

```html
<md-list>
  <md-list-item href="${window.location.href}/../routerLink1" headline="click should not reload the page"></md-list-item>
  <md-list-item href="${window.location.href}/../routerLink2" headline="click should not reload the page"></md-list-item>
</md-list>

```

If this is WAI, is it possible to : 
- mark the `renderContent` method as `protected` so that it is easier to override. 
- include a warning somewhere in the doc about this behavior. 

Thanks!

**Comment by asyncLiz** [comment]
@e111077 do you have insight into why list stops item click propagation? Could we let them bubble and handle list's situation differently?

**Comment by e111077** [comment]
I believe this is mostly vestigial code. I will likely have to make some changes to make sure parent menus do not ripple though

**Comment by e111077** [comment]
PR open #4825 for tracking. needs to go through internal test suite and review
