### ISSUE TITLE
Wrong links to Material Web

### ISSUE THREAD

**Issue by nicolasr75** [material-components/material-web#4818]
There are several wrong links to Material Web in the docs, f.e. on the page for text-field, progress and chips.

Unfortunately the URLs on Material Web don't seem to be very consistent. Sometimes it's singular, sometimes plural (chip, chips).

F.e. in the documentation for text-field the link "Material Web catalog" does not work, while the link "Design article" further below does work. I haven't tested all pages but at least text-field, progress and chips have wrong links.

Some components have the link "This documentation is fully rendered on the [Material Web catalog](https://material-web.dev/components/progress/)", some don't, not sure if this is by intention.

**Comment by asyncLiz** [comment]
Thanks for the report! Do you mind sending a CL to fix any inconsistencies you find?

**Comment by nicolasr75** [comment]
What do you mean by CL? Just a listing here in the issue or any special Git thing?

**Comment by asyncLiz** [comment]
Ah sorry, wrong terminology. Meant a pull request 😅

**Comment by nicolasr75** [comment]
OK, I'll try it. I am currently reading the documentation anyway because we are preparing for migration from the older mwc components.
Btw, I mixed up material-web.dev and material.io in my comment above. The URLs in material-web seem to use singular very consistently. Material.io seems to use pretty random URLs regarding singular/plural.

**Comment by asyncLiz** [comment]
I'm going to close this for now since it's not very actionable and the catalog is still a WIP. If there's something broken in the catalog, please let us know! Otherwise a discussion for feedback and suggestions would be welcome :)
