### ISSUE TITLE
Focus effect on checkboxes is not aligned correctly in Safari on iOS.

### ISSUE THREAD

**Issue by arn80** [material-components/material-web#4819]
Focus effect on checkboxes is not aligned correctly in Safari on iPadOS 16.6.

When pressing the checkboxes the focus effect is displayed to far to the right and to the bottom.

Go to https://material-web.dev/components/checkbox/ and open the interactive demo. Press some of the checkboxes.

![image0](https://github.com/material-components/material-web/assets/12843350/b2204e60-3251-4112-9d70-f7c6562bdd4b)

**Comment by asyncLiz** [comment]
Verified that this was fixed in https://github.com/material-components/material-web/commit/0e8afc01757c3f1f8a5bf904e8cb857ea88bd7bf. The catalog will update on the next prerelease.
