### ISSUE TITLE
md-text-field ignoring autocomplete attribute

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#4837]
It seems that `autocomplete="off"` on textfields is not working properly, and do not seem to turn off the autocompletion.  
I am not sure how to reproduce that, but setting `autocomplete="off"` manually on the internal `input` element gets rid of the problem.  
Which means we should probably find a way to explicitly relay the value from the outside.

**Comment by vdegenne** [comment]
Note I was also thinking about this solution which delegates all the logic to the internal input directly:

```typescript
  @property({reflect: true, attribute: 'autocomplete'})
  get autocomplete() {
    return this.getInput().autocomplete as TextFieldAutoCompleteType;
  }

  set autocomplete(value: TextFieldAutoCompleteType) {
    this.getInput().setAttribute('autocomplete', value);
  }
```

However this looks more intensive and it doesn't work well with IDE intellisense.

**Comment by asyncLiz** [comment]
> @asyncLiz Even after the cast (and removing the custom type) there is this error:
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/2827383/265937668-09c4c11c-60fe-4ec9-a0ec-ad837852ab52.png">
> Can we just ignore it then?

Might need an `as any`, lemme import it and see what gets yelled at
