### ISSUE TITLE
slider label get's lost when it's host is scrollable

### ISSUE THREAD

**Issue by VandeurenGlenn** [material-components/material-web#4859]
<img width="505" alt="image" src="https://github.com/material-components/material-web/assets/8685280/eed28d9e-9d6c-43e4-9849-0d935c371b19">

https://lit.dev/playground/#gist=78e7d70f821261084616cb7bd214379c

**Comment by asyncLiz** [comment]
This is unfortunately what we're limited to with CSS. You would need to add padding to the scrollable container to show overflowing content.

In the future we may be able to use the popover api and make the label tooltip appear independent of scroll areas, but not today 😭
