### ISSUE TITLE
mwc-tabs don't appear to support scrolling on desktop

### ISSUE THREAD

**Issue by iantrich** [material-components/material-web#487]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**
Windows 10

**What browser(s) is this bug affecting:**
Chrome Version 77.0.3865.75 (Official Build) (32-bit)

**Current behavior:**
Unable to scroll through tabs in browser

**Expected behavior:**
Using a mouse you should be able to scroll through tabs

**Steps to reproduce:**
https://material-components.github.io/material-components-web-components/demos/tabs.html

If you shrink your desktop browser so that the "Scrolling" example does not display all ten tabs, you'll find that there is no way to scroll through them using your mouse unless you click and use the mouse wheel. On mobile, it works as expected. 

**Related code:**

```js
// insert any relevant code here or add a include a codepen
```

**Other information:**

**Comment by bramkragten** [comment]
Why is this low severity? This makes the tabs pretty much useless on a desktop?

The paper tabs could be dragged by the mouse and had arrows on both sides. This has neither and thus a tab bar with a lot of tabs is not useable.

**Comment by ForestKatsch** [comment]
This works for me with horizontal touchpad scrolling on macOS 11 and Chrome 87.

**Comment by bramkragten** [comment]
Yes, it works with normal scroll events, but that is not something a user with a mouse will likely use. They will click and drag the tabs, and that is no longer possible. That is also how it used to work with `paper-tabs`.

**Comment by johnthad** [comment]
Additionally I think the tab bar should have indicators to let the user know that there _are_ tabs to the left or right. Depending on the width of the tab-bar and the visible tabs, it may not be obvious that there is any more than what is showing.

**Comment by asyncLiz** [comment]
Obsolete with M3 once tabs are ready

**Comment by Misiu** [comment]
@asyncLiz any updates on this?
This is the functionality that we want to use mwc-tabs instead of paper tabs:
![tabs](https://github.com/user-attachments/assets/d7984700-05da-4b6b-ac58-1c1694d07ddb)
https://demo.home-assistant.io/

**Comment by asyncLiz** [comment]
The pre-1.0 beta `<mwc-tabs>` will not be updated. The current 1.0 `<md-tabs>` supports scrolling

**Comment by Misiu** [comment]
Thank you for the update. And what about arrows? When the tabs didn't fit the screen the paper tabs added arrows that allowed users to scroll tabs as seen in video

**Comment by asyncLiz** [comment]
We don't have plans to add those arrows since it isn't part of the M3 design spec for tabs, but you could add `<md-icon-button>` arrows absolutely positioned on top of the `<md-tabs>` to add that feature!
