### ISSUE TITLE
mwc-checkbox missing name property.

### ISSUE THREAD

**Issue by rdrgcnn** [material-components/material-web#494]
**I'm submitting a:**

- [ X ] bug report
- [ ] feature request

**OS**
Hiegh Sierra 10.13.6

**What browser(s) is this bug affecting:**

Latest Firefox - Last Chrome

**Current behavior:**
I've been using `mwc-checkbox` knowing that it is still under development. 
Although, I've found out that name property is not passed to the input. 

Result is by using a form element that wraps up the checkbox, when parsing the checkbox value is never returned.

**Expected behavior:**
`mwc-checkbox` should pass the name property to the inner input.

**Related code:**

```js
<iron-form id="ironForm">
        <form id="form">
          <mwc-checkbox checked name="a"></mwc-checkbox>
        </form>
 </iron-form>
/*  ...  */
let a = form.serializeForm();
// a = {};
```
_Again I am aware that this is still under development._

**Comment by 43081j** [comment]
I don't think it is as simple as propagating the name.

Some form-participation stuff is probably needed so the form picks it up as a "form element". This is a brand new API/spec though (form participation) so not sure how you'd make it backwards-compatible..

**Comment by azakus** [comment]
This depends on implementing #289

**Comment by reno1979** [comment]
What about the role attribute ?
http://rawgithub.com/w3c/aria-in-html/master/index.html#recommendations-table

**Comment by asyncLiz** [comment]
Fixed in M3
