### ISSUE TITLE
Use Tokens outside of components

### ISSUE THREAD

**Issue by cjgammon** [material-components/material-web#4943]
Hi, is there a way to use the tokens like `var(--md-sys-color-primary);` outside of the components, like if I just want to use it within the larger application somewhere to style things in the same theme easily.  I didn't see an example or a clear way to do this.

Thanks.

**Comment by asyncLiz** [comment]
If you're using Sass, it's pretty simple.

```scss
@use '@material/web/color/color';

:root {
  @include color.light-theme;

  @media (prefers-color-scheme: dark) {
    @include color.dark-theme;
  }
}
```

We're working on more/better APIs for non-Sass projects.

Outside of Sass, you can use the [Material theme builder Figma plugin](https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder) or the [material-color-utilities library](https://www.npmjs.com/package/@material/material-color-utilities) to generate the custom properties.

(See https://github.com/material-components/material-web/blob/main/docs/theming/color.md)
