### ISSUE TITLE
Form submit event submitter value is null on Firefox with buttons

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#4949]
When submitting a form on FF with an Md button, the event.submitter value is `null`

Repro:

open on FF and click submit button. submitter name should appear as "submitter" but `event.submitter` is null so `undefined` is shown.

https://lit.dev/playground/#gist=65cdfdaa104065812d8b069bac15e01e

**Comment by asyncLiz** [comment]
Looks like this is fixed now, testing in Firefox 120
