### ISSUE TITLE
Add event for Chip select

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#4951]
Right now `<md-filter-chip>` only has 2 events: `update-focus` and `remove`. There's no way to know when it's selected. The workaround right now is to handle a `click` event and "predict" the behavior (because at the time of `click`, `selected` is not updated yet).

---

Just found a better workaround for now: manually dispatch the event using `MutationObserver`:

```js
#observeChips() {
    const obs = new MutationObserver(changes => {
        for (const change of changes) {
            const name = change.target.nodeName.toUpperCase();
            if (name.startsWith("MD") && name.endsWith("CHIP")) {
                const chip = change.target;
                chip.dispatchEvent(new CustomEvent("selected", {
                    bubbles: true,
                    detail: {
                        value: chip.value,
                        checked: chip.selected,
                    }
                }));
            }
        }
    });

    obs.observe(document.body, {
        attributeFilter: ["selected"],
        attributes: true,
        subtree: true,
    })
}
```

**Comment by asyncLiz** [comment]
This sounds like a bug with how we're setting selected. The click event is intended to be used for that state.

```js
filterChip.addEventListener('click', event => {
  // event.target.selected has not been updated! it should be
});
```

Instead of waiting to see if the click event was `defaultPrevented` before changing selected, we should change it immediately, then wait and revert it if `event.preventDefault()` was called.

**Comment by datvm** [comment]
@asyncLiz I'd happy to help if you are accepting contribution/PR. Is there any policy on adding events? I can do a PR with adding a proper `selected` event as well. Unfortunately I am not familiar with writing JS test though.

**Comment by vdegenne** [comment]
related PR: https://github.com/material-components/material-web/pull/5113

Note that if you are preventing the default you would still have to wait for the element to update to get the correct value, e.g.

```html
<md-filter-chip
  selected
  @click=${async (event) => {
    event.preventDefault();
    const chip = event.target;
    // Here `selected` is false even though it was prevented.
    // Need to wait the reverted value.
    await chip.updateComplete;
    // Here `selected` reflects the correct value (true)
  }}
></md-filter-chip>
```

**Comment by asyncLiz** [comment]
Fixed with https://github.com/material-components/material-web/pull/5113, the correct event to listen to will be `click`
