### ISSUE TITLE
icon-button do not react to keyboard when slotted in tab

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#4961]
When focusing an `icon-button` slotted in a `tab`, pressing `space` or `enter` does not trigger any event on the icon-button. I would expect that the `handleClick` handler is called (and toggles the button in this case). 

The only way to toggle the icon-button here is through a mouse click.

![image](https://github.com/material-components/material-web/assets/1168053/14c8a15e-d8ad-4e9b-8964-56d4f415c971)

Playground: 
https://lit.dev/playground/#gist=f1fad9558091a90c9ef2424b19a1ddff

**Comment by e111077** [comment]
Not sure how this works in regards to a11y, but workaround for now is to stop propagation on the keydown event on the icon button. If you would like to stop the ripple, i'd suggest doing the same for click

https://lit.dev/playground/#gist=6e6894a04c4e31f82ba7742305f775b0

**Comment by asyncLiz** [comment]
What's your use case for having an icon button inside of a tab?

**Comment by christophe-g** [comment]
> What's your use case for having an icon button inside of a tab?

My use case is tabs that can close : editing certain items adds tabs - navigating through tabs allow multiple items to be open - closing a tab closes resp. item. 

Re a11y - the tab announce itself as closable. 

>  workaround for now is to stop propagation on the keydown event on the icon button

Thanks - that's what I ended up doing.
