### ISSUE TITLE
md-select does not scroll if the options don't fit on the screen making it so you can't select all options

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4976]
To reproduce: 1) make a select with a a lot of options. 2) try to use it.

**Comment by treeder** [comment]
It should probably not grow bigger than the screen automatically.

**Comment by e111077** [comment]
This is fixed on main by this commit https://github.com/material-components/material-web/commit/235a2033d7e492e5ed245e7a81b0082e8ecd35ac. Just awaiting release
