### ISSUE TITLE
md-list-item do not fill the width of the list

### ISSUE THREAD

**Issue by Burtan** [material-components/material-web#4988]
### What is affected?

Component

### Description

When adding md-list-item to md-list, the md-list-item is not filling the whole width of md-list but only the width its content is requesting. I think it should fill the width of its parent md-list

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9saXN0L2xpc3QuanNcIjtcbmltcG9ydCBcIkBtYXRlcmlhbC93ZWIvbGlzdC9saXN0LWl0ZW0uanNcIjsifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9tYXRlcmlhbC1pbXBvcnRzLmpzXCI-PC9zY3JpcHQ-XG5cbjxtZC1saXN0IHN0eWxlPVwid2lkdGg6IDMwMHB4OyBiYWNrZ3JvdW5kLWNvbG9yOiBibHVlXCI-XG4gIDxtZC1saXN0LWl0ZW0gaGVhZGxpbmU9XCIxXCI-PC9tZC1saXN0LWl0ZW0-XG4gIDxtZC1saXN0LWl0ZW0gaGVhZGxpbmU9XCIyXCI-PC9tZC1saXN0LWl0ZW0-XG48L21kLWxpc3Q-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 1.0.0-pre-17

### Browser/OS/Node environment

Firefox 115

**Comment by asyncLiz** [comment]
Looks like this has been fixed, it'll be released in the next update!
