### ISSUE TITLE
Add a size-limit check to CI

### ISSUE THREAD

**Issue by abdonrd** [material-components/material-web#5]
For example, `lit-html` has this script:

https://github.com/Polymer/lit-html/blob/master/package.json#L25

It would be great add something similar to the CI to check the components size.

Another reference from the vaadin components: https://github.com/vaadin/vaadin-core/pull/177

bundlesize package: https://github.com/siddharthkp/bundlesize

**Comment by asyncLiz** [comment]
We've implemented this internally with our size tracking tools :)
