### ISSUE TITLE
Color theme menu doesn't open

### ISSUE THREAD

**Issue by zZHorizonZz** [material-components/material-web#5009]
### Description

The theme menu, which should appear on the documentation page, is not displaying. When attempting to open it, there seems to be something opened, as scrolling is disabled and the page stops responding. Therefore, it's likely that the menu is present, but it's just not visible?

### Browser/OS Environment

Browser: Chrome 116.0.5845.188
OS: Windows 11

**Comment by vdegenne** [comment]
Material Web just got updated to `v1.0.0`, there were many modifications regarding the `menu` element. This was expected, and this will be fixed soon.

**Comment by e111077** [comment]
Have you visited material-web.dev in the past or is this the first time? We have done some changes to the caching behavior and want to see if I can rule that out

**Comment by vdegenne** [comment]
(The menu is showing again now for me)

**Comment by zZHorizonZz** [comment]
> Have you visited material-web.dev in the past or is this the first time? We have done some changes to the caching behavior and want to see if I can rule that out

Yeah, I have visited it in the past. Now I have visited it on a device where I hadn't visited it before, and it works fine. So probably just old cache?

**Comment by christophe-g** [comment]
Works on incognito window for me. 

Does not work otherwise, even after hard refresh. 

Log throws while hovering on the color theme menu: 
```
chunk-IWKN7XWV.js:1 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "md-focus-ring" has already been used with this registry
    at https://material-web.dev/js/chunk-IWKN7XWV.js:1:1417
    at https://material-web.dev/js/chunk-IWKN7XWV.js:1:1432
    at H (https://material-web.dev/js/chunk-IWKN7XWV.js:1:985)
    at https://material-web.dev/js/chunk-3TIZYVWE.js:2:42
(anonymous) @ chunk-IWKN7XWV.js:1
(anonymous) @ chunk-IWKN7XWV.js:1
H @ chunk-IWKN7XWV.js:1
(anonymous) @ chunk-3TIZYVWE.js:2
await in (anonymous) (async)
(anonymous) @ lit-island.js:1
```

**Comment by e111077** [comment]
Any luck with the following link?

https://material-web-catalog--pr5007-auto-update-docs-hmr22yni.web.app/

**Comment by christophe-g** [comment]
> Any luck with the following link?

Yes - works

**Comment by zZHorizonZz** [comment]
So I have tested it and now everything is working correctly. Closing the issue.
