### ISSUE TITLE
[menu] iOS: tapping outside menu does not close it

### ISSUE THREAD

**Issue by sorvell** [material-components/material-web#5015]
### What is affected?

Component

### Description

On iOS after tapping a menu to open it, tapping outside the menu does not close it. Tapping an item in the menu does close the menu.

### Reproduction

1. On iOS, go to https://material-web.dev/components/menu/, expand the interactive demo section, and tap one of the open menu butons.
2. Tap outside the menu to close it.

Expected: the menu closes.
Actual: the menu remains open.

### Workaround

N/A

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0

### Browser/OS/Node environment

Browser: Safari
Platform: iOS 17

**Comment by e111077** [comment]
Safari particularly on iOS will not bubble a click event up to window. I honestly don't have the mental fortitude for this
