### ISSUE TITLE
[md-fab] style cursor: pointer isn't working

### ISSUE THREAD

**Issue by jodekirk** [material-components/material-web#5017]
### What is affected?

Theming

### Description

Trying to set the fab style doesn't change cursor on hover.

### Reproduction

set style to

`md-fab {
        cursor: pointer;
}`

### Workaround

not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

Chrome 117

**Comment by jodekirk** [comment]
Also a problem adding setting cursor: pointer; to `md-switch` and possibly others.

**Comment by asyncLiz** [comment]
We need to move cursor styles to the `:host` and call `cursor: inherit` on the inner button. Could be a good community contribution!
