### ISSUE TITLE
Menu goes off screen by default in mobile view, but not on desktop view. 

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#5029]
This is still an issue in 1.0.0

Desktop:

![image](https://github.com/material-components/material-web/assets/75826/92241004-0a15-425d-b5cb-359d14e87036)

Mobile: 

![image](https://github.com/material-components/material-web/assets/75826/016f14c3-6219-427a-9ec8-dce480625a46)

_Originally posted by @treeder in https://github.com/material-components/material-web/issues/4161#issuecomment-1665939681_

**Comment by e111077** [comment]
Can you please provide what OS, Browser, and version you're using on mobile?

If android, is this reproducible across all browsers?

**Comment by e111077** [comment]
I have been unable to reproduce this in Android Chrome 117:

https://lit.dev/playground/#gist=1dd9e672efd49bc8cd94db91872fcbc7

Does that repro for you? If not, can you edit the code and share it back with a reproduction?

**Comment by sorvell** [comment]
The above playground does not repro the issue for me on iPhone 15 using iOS 17, Chrome/Safari.

**Comment by treeder** [comment]
I take that back, I had some non-default anchoring stuff, but when I remove it all, it seems to work. Thanks!

**Comment by e111077** [comment]
As in you entered a value that is not a valid corner? We should be exporting a Corner enum to help out with that in the non-html case.

Otherwise do you mind sharing the value?
