### ISSUE TITLE
List docs show incorrect start-image/end-image slots

### ISSUE THREAD

**Issue by Burtan** [material-components/material-web#5035]
See https://github.com/material-components/material-web/blob/main/docs/components/list.md#image-list-item-example

### What is affected?

Component

### Description

When using md-list-item the slots start-image/end-image won't work in contrast to start/end. But with the latter, the image is not resized automatically.

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9saXN0L2xpc3QuanNcIjtcbmltcG9ydCBcIkBtYXRlcmlhbC93ZWIvbGlzdC9saXN0LWl0ZW0uanNcIjsifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9tYXRlcmlhbC1pbXBvcnRzLmpzXCI-PC9zY3JpcHQ-XG5cbjxtZC1saXN0IHN0eWxlPVwid2lkdGg6IDMwMHB4OyBiYWNrZ3JvdW5kLWNvbG9yOiBwaW5rXCI-XG4gIDxtZC1saXN0LWl0ZW0-XG4gICAgPGRpdiBzbG90PVwiaGVhZGxpbmVcIj5cbiAgICAgIDFcbiAgICA8L2Rpdj5cbiAgICA8aW1nIHNsb3Q9XCJlbmQtaW1hZ2VcIiBzcmM9XCJodHRwczovL2xpdC5kZXYvaW1hZ2VzL2xvZ28uc3ZnXCI-PC9pbWc-XG4gICAgPGltZyBzbG90PVwic3RhcnQtaW1hZ2VcIiBzcmM9XCJodHRwczovL2xpdC5kZXYvaW1hZ2VzL2xvZ28uc3ZnXCI-PC9pbWc-XG4gIDwvbWQtbGlzdC1pdGVtPlxuICA8bWQtbGlzdC1pdGVtPlxuICAgIDxkaXYgc2xvdD1cImhlYWRsaW5lXCI-XG4gICAgICAyXG4gICAgPC9kaXY-XG4gICAgPGltZyBzbG90PVwiZW5kXCIgc3JjPVwiaHR0cHM6Ly9saXQuZGV2L2ltYWdlcy9sb2dvLnN2Z1wiPjwvaW1nPlxuICAgIDxpbWcgc2xvdD1cInN0YXJ0XCIgc3JjPVwiaHR0cHM6Ly9saXQuZGV2L2ltYWdlcy9sb2dvLnN2Z1wiPjwvaW1nPlxuICA8L21kLWxpc3QtaXRlbT5cbjwvbWQtbGlzdD5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0

### Workaround

None.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

Firefox 113

**Comment by Burtan** [comment]
This is still used in the docs though

Elizabeth Mitchell ***@***.***> schrieb am Fr., 29. Sept.
2023, 19:52:

**Comment by asyncLiz** [comment]
Oh you're right! Let's get that fixed. If you'd like to send a PR that'd be appreciated :)
