### ISSUE TITLE
Menu closes and reopens on anchor click with touch screen

### ISSUE THREAD

**Issue by SDBonhof** [material-components/material-web#5036]
### What is affected?

Component `Menu`

### Description

When I click a menu anchor with a touch screen, I expect the menu to close. However, when I click (touch) the anchor now, the menu closes momentarily and opens immediately again.

V1.0.0 mentions fixied something related in commit [c7c276f](https://github.com/material-components/material-web/commit/c7c276fdfa5eb2c7b4d06c7ccef8e36deaa96e5c), but that has not fixed it for me on a touch screen. Also: the V1.0.0 release notes mention `do not close menu if anchor is clicked`, but even with a mouseclick, it does close? I am not sure what the preferred behavior is from Material Design.

### Reproduction

Menu should close on clicking the anchor with a touch screen, the way it does with a mouse click

[playground url](https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9idXR0b24vZmlsbGVkLWJ1dHRvbi5qc1wiO1xuaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL21lbnUvbWVudSc7XG5pbXBvcnQgJ0BtYXRlcmlhbC93ZWIvbWVudS9tZW51LWl0ZW0nO1xuaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL21lbnUvc3ViLW1lbnUnO1xuXG4vLyBUaGlzIGV4YW1wbGUgdXNlcyBhbmNob3IgYXMgYW4gSUQgcmVmZXJlbmNlXG5jb25zdCBhbmNob3JFbCA9IGRvY3VtZW50LmJvZHkucXVlcnlTZWxlY3RvcignI3VzYWdlLWFuY2hvcicpO1xuY29uc3QgbWVudUVsID0gZG9jdW1lbnQuYm9keS5xdWVyeVNlbGVjdG9yKCcjdXNhZ2UtbWVudScpO1xuXG4gIGFuY2hvckVsLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4geyBtZW51RWwub3BlbiA9ICFtZW51RWwub3BlbjsgfSk7In0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbWF0ZXJpYWwtaW1wb3J0cy5qc1wiPjwvc2NyaXB0PlxuXG48c3BhbiBzdHlsZT1cInBvc2l0aW9uOiByZWxhdGl2ZVwiPlxuICA8bWQtZmlsbGVkLWJ1dHRvbiBpZD1cInVzYWdlLWFuY2hvclwiPlNldCB3aXRoIGlkcmVmPC9tZC1maWxsZWQtYnV0dG9uPlxuICA8bWQtbWVudSBpZD1cInVzYWdlLW1lbnVcIiBhbmNob3I9XCJ1c2FnZS1hbmNob3JcIj5cbiAgICA8bWQtbWVudS1pdGVtPlxuICAgICAgPGRpdiBzbG90PVwiaGVhZGxpbmVcIj5BcHBsZTwvZGl2PlxuICAgIDwvbWQtbWVudS1pdGVtPlxuICAgIDxtZC1tZW51LWl0ZW0-XG4gICAgICA8ZGl2IHNsb3Q9XCJoZWFkbGluZVwiPkJhbmFuYTwvZGl2PlxuICAgIDwvbWQtbWVudS1pdGVtPlxuICAgIDxtZC1tZW51LWl0ZW0-XG4gICAgICA8ZGl2IHNsb3Q9XCJoZWFkbGluZVwiPkN1Y3VtYmVyPC9kaXY-XG4gICAgPC9tZC1tZW51LWl0ZW0-XG4gIDwvbWQtbWVudT5cbjwvc3Bhbj4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

V1.0.0, but also pre-17.

### Browser/OS/Node environment

Firefox version: 117.0.1
Chrome version: 117.0.5938.92

**Comment by SDBonhof** [comment]
Found a workaround. Setting `stay-open-on-focusout` to `true` fixes this issue, but I am not sure if this is the intended behavior. 

A probably related issue is when trying to open the menu on holding the anchor on touch closes the menu on touchend due to focusout events, but I am not sure whether this is something to bring up here to fix.

**Comment by e111077** [comment]
Heya this is not standard behavior. Will be looking into a fix
