### ISSUE TITLE
Linear progress does not stretch in flex box

### ISSUE THREAD

**Issue by Burtan** [material-components/material-web#5042]
### What is affected?

Component

### Description

Linear progress does not stretch when used in a flex box. See the example.

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9wcm9ncmVzcy9saW5lYXItcHJvZ3Jlc3MuanNcIjtcbmltcG9ydCBcIkBtYXRlcmlhbC93ZWIvc2xpZGVyL3NsaWRlci5qc1wiO1xuaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9idXR0b24vZmlsbGVkLWJ1dHRvbi5qc1wiOyJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL21hdGVyaWFsLWltcG9ydHMuanNcIj48L3NjcmlwdD5cblxuPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGFsaWduLWl0ZW1zOiBjZW50ZXI7XCI-XG4gIDxtZC1saW5lYXItcHJvZ3Jlc3MgaW5kZXRlcm1pbmF0ZT48L21kLWxpbmVhci1wcm9ncmVzcz5cbiAgPG1kLXNsaWRlciB2YWx1ZT1cIjUwXCI-PC9tZC1zbGlkZXI-XG4gIDxtZC1maWxsZWQtYnV0dG9uPlRlc3QgQnV0dG9uPC9tZC1maWxsZWQtYnV0dG9uPlxuPC9kaXY-XG48YnI-XG48YnI-XG48YnI-XG48YnI-XG48ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsgYWxpZ24taXRlbXM6IHN0cmV0Y2g7XCI-XG4gIDxtZC1saW5lYXItcHJvZ3Jlc3MgaW5kZXRlcm1pbmF0ZT48L21kLWxpbmVhci1wcm9ncmVzcz5cbiAgPG1kLXNsaWRlciB2YWx1ZT1cIjUwXCI-PC9tZC1zbGlkZXI-XG4gIDxtZC1maWxsZWQtYnV0dG9uPlRlc3QgQnV0dG9uPC9tZC1maWxsZWQtYnV0dG9uPlxuPC9kaXY-In0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ

### Workaround

None

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

Firefox 115

**Comment by loanngo99** [comment]
**Problem**: I see linear progress has a fixed width of 80px as the default.
**Solution**: I'm not sure why the publisher chose this particular value. I'm thinking of adding some properties to change the horizontal value, such as 25% - 50% - 75% - 100%.
If this is acceptable, I believe I can contribute to the addition of these features.

**Comment by asyncLiz** [comment]
Just looks like `width: 80px` was supposed to be `min-width: 80px`. It was originally `min-block-size`, and I messed up when changing it. D'you mind sending a PR to fix that?

In the meantime as a workaround, use `width: unset`.
