### ISSUE TITLE
[Feature Request] A simple way to change <md-icon> size

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#5055]
### Description

Right now to set the size of `<md-icon>` you have to use 3 separate CSS (from https://github.com/material-components/material-web/blob/main/docs/components/icon.md#theming):

```
md-icon {
    font-size: 100px;
}

md-icon,
md-icon > * {
  /* Resizes any slotted images or SVGs */
  width: 100px;
  height: 100px;
}
```

There should be an easy way to change the icon size, like a token `--md-icon-size`. I would also love if we can have the `md-icon` to use the font size as its size if possible. And while we are at it, I know this is a big stretch to ask, can it be the default behavior?

**Comment by e111077** [comment]
Hello, the slot for SVGs in `md-icon` is just a convenience. All of our components should be compatible with slotting svg's directly.

Therefore there's really only one _necessary_ way to change `md-icon` size which is `font-size`.

Going to close this for now as answered, but if you still feel strongly about this, please respond with your use case for needing to slot an svg into md-icon and I'll reopen.

**Comment by datvm** [comment]
@e111077 Hi, sorry if I misunderstood your point, did you mean `md-icon` is meant for putting stuff in _other_ components only?

Right now I cannot use `<md-icon>` as an "inline" icon because changing the `font-size` would break it, for example: https://jsfiddle.net/datvm/j4asq5yx/1/

![image](https://github.com/material-components/material-web/assets/6388546/41f717cd-3139-4d39-b08f-8c4e694a7ba3)

```css
md-icon {
    font-size: 100px;
}

.slot-size {
    md-icon,
    md-icon > * {
      /* Resizes any slotted images or SVGs */
      width: 100px;
      height: 100px;
    }
}
```

```html
<p>This icon does not fit: <md-icon>search</md-icon></p>


<div class="slot-size">
    <p>
        This icon fits because the the width and height are set:
        <md-icon>search</md-icon></p>
    </p>
</div>
```

Again, this is nice to have but if you didn't design it for this, no problem ;)

**Comment by e111077** [comment]
Oh I see, this affects font icons

**Comment by scherler** [comment]
I creates https://github.com/material-components/material-web/pull/5150

**Comment by datvm** [comment]
@scherler  Wonderful, thank you so much 🎉

@asyncLiz  is there any schedule on when 1.0.2 will be released please? Thank you!
