### ISSUE TITLE
md-select default cursor

### ISSUE THREAD

**Issue by kkachniarz220** [material-components/material-web#5066]
### What is affected?

Component

### Description

Select component should have pointer cursor.

### Reproduction

Not applicable

### Workaround

Not applicable

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

Chrome 117.0.5938.150
Windows 11

**Comment by e111077** [comment]
You are correct here, the guidance seems to show a pointer:

https://m3.material.io/components/menus/guidelines
