### ISSUE TITLE
**tl;dr MWC is 1.0 and ready to use in production!**

### ISSUE THREAD

**Issue by bernabe44123** [material-components/material-web#5071]
**tl;dr MWC is 1.0 and ready to use in production!**

After a long journey, Material Web has launched its 1.0 set of [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) using Google's latest [Material 3](https://m3.material.io/) design system!

Each component has been reviewed by Material 3 designers and accessibility engineers for use in production.

😱 🥳 👏 

Thank you to everyone who participated in our beta and provided feedback ❤️

**What's in 1.0?**

- ⚙️ 19 components, including buttons, checkboxes, chips, text fields, selects, and dialogs
- 🎨 CSS theming for dynamic color, fonts, and Material tokens
- ♿️ Accessibility for screen readers and high contrast
- 📖 Documentation and guides
- 📋 `<form>` element support
- 🏗️ Cross-framework support, including Lit, React, Vue, and Svelte
- 🤖 Basic [Lit SSR](https://lit.dev/docs/ssr/overview/) support
- 👏 Fewer breaking changes

Check out our [roadmap](https://github.com/material-components/material-web/blob/main/docs/roadmap.md) for what's coming next!

We're excited to help you build beautifully customized and accessible applications 🎉

The Material Web team

_Originally posted by @asyncLiz in https://github.com/material-components/material-web/discussions/5004_

**Comment by Ernesto44123** [comment]
>
