### ISSUE TITLE
md-list

### ISSUE THREAD

**Issue by vikjung** [material-components/material-web#5072]
### Description

Examples in code dont work -

      <md-list style="min-width: 400px">
     <md-list-item
     headline="User Name"
      supportingText="user@name.com">
    <md-icon slot="start-icon">account_circle</md-icon>
    <md-icon slot="end-icon">check</md-icon>
  </md-list-item>
  </md-list>

1)  supportingText should be supporting-text

2)  div slots do not work 
 
  <md-list style="min-width: 400px">
     <md-list-item>
     <div slot="headline">User Name</div>
     <div slot="supporting-text">"user@name.com"L</div>
    <md-icon slot="start-icon">account_circle</md-icon>
    <md-icon slot="end-icon">check</md-icon>
  </md-list-item>
  </md-list>

**Comment by e111077** [comment]
This is fixed at HEAD. This change should be deployed at next NPM release
