### ISSUE TITLE
md-switch default cursor

### ISSUE THREAD

**Issue by kkachniarz220** [material-components/material-web#5075]
### What is affected?

Component

### Description

Switch component should have pointer cursor.
https://m3.material.io/components/switch/accessibility#c0e9fae1-48df-428b-b028-4f7be071ada3

### Reproduction

Not applicable

### Workaround

Not applicable

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

Chrome 117.0.5938.150
Windows 11

**Comment by e111077** [comment]
There are unfortunately no Material guidelines. Need to follow up with Design.

**Comment by kkachniarz220** [comment]
it should be like a checkbox button, shouldn't it?

**Comment by e111077** [comment]
native `<input type="checkbox">` does not have a pointer hence the need for clarification
