### ISSUE TITLE
Required select causes "An invalid form control with name='' is not focusable"

### ISSUE THREAD

**Issue by austinw-fineart** [material-components/material-web#5078]
### What is affected?

Component

### Description

Adding a required select to a form will print the following error in the console when submitting:
`An invalid form control with name='' is not focusable.`

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9idXR0b24vb3V0bGluZWQtYnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL3NlbGVjdC9maWxsZWQtc2VsZWN0LmpzXCI7XG5pbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL3NlbGVjdC9zZWxlY3Qtb3B0aW9uLmpzXCI7XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9tYXRlcmlhbC1pbXBvcnRzLmpzXCI-PC9zY3JpcHQ-XG5cbjxmb3JtPlxuICA8bWQtZmlsbGVkLXNlbGVjdCByZXF1aXJlZD5cbiAgICA8bWQtc2VsZWN0LW9wdGlvbiB2YWx1ZT1cIm9uZVwiPlxuICAgICAgPGRpdiBzbG90PVwiaGVhZGxpbmVcIj5PbmU8L2Rpdj5cbiAgICA8L21kLXNlbGVjdC1vcHRpb24-XG4gICAgPG1kLXNlbGVjdC1vcHRpb24gdmFsdWU9XCJ0d29cIj5cbiAgICAgIDxkaXYgc2xvdD1cImhlYWRsaW5lXCI-VHdvPC9kaXY-XG4gICAgPC9tZC1zZWxlY3Qtb3B0aW9uPlxuICA8L21kLWZpbGxlZC1zZWxlY3Q-XG4gIDxtZC1vdXRsaW5lZC1idXR0b24gdHlwZT1cInN1Ym1pdFwiPlN1Ym1pdDwvbWQtb3V0bGluZWQtYnV0dG9uPlxuPC9mb3JtPlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

Browser: Edge 117.0.2045.60
OS: Windows 11 22H2
Node version: 18.18.0
npm version: 10.2.0

**Comment by e111077** [comment]
Investigation notes:

Need to figure out whether this is an us bug or a browser bug. Cannot reproduce with md-textfield. Adding `delegatesFocus: true` and changing the text inside select to `<input readonly>` does not work. Need to look deeper into the diff between textfield and select.

Additionally, need to see what's going on with the native form error not triggering our custom state

**Comment by austinw-fineart** [comment]
I think I figured it out. There's no anchor element in setValidity:
https://github.com/material-components/material-web/blob/06909e5b20e06a76ce97ff6700fbc7a9509cce52/select/internal/select.ts#L804
Simply give it the field and it should work.

**Comment by e111077** [comment]
Oh wow! that's a good find! Do you want to file a PR or would you like us to handle it?

**Comment by austinw-fineart** [comment]
I'll leave it to you 🙂

**Comment by e111077** [comment]
I'll implement a fix and confirm tomorrow
