### ISSUE TITLE
md-checkbox default cursor

### ISSUE THREAD

**Issue by kkachniarz220** [material-components/material-web#5079]
### What is affected?

Component

### Description

Checkbox component should have pointer cursor.

### Reproduction

Not applicable

### Workaround

Not applicable

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

Chrome 117.0.5938.150
Windows 11

**Comment by e111077** [comment]
more context: Material guidance shows pointer:

https://m3.material.io/components/checkbox/overview#6b1ada17-4e3c-4f51-a228-c14156caf605

**Comment by e111077** [comment]
Thanks for the issue. You can follow PR #5084 for progress
