### ISSUE TITLE
Dark theme not applying on input filled 

### ISSUE THREAD

**Issue by isaacwein** [material-components/material-web#5099]
### What is affected?

Theming

### Description

I made a simple project with sveltekit using MWC 1.1 but the dark theme doesn't apply on filled inputs or select 
i am using @material/material-color-utilities i tried with predefined themes too and it has the same issue

dark mode 
![image](https://github.com/material-components/material-web/assets/34663972/c0b72f53-bc1a-4ed0-839d-484c4182b625)
light mode 

![image](https://github.com/material-components/material-web/assets/34663972/a0e79f41-3306-48f7-a851-4f2382950d3f)

### Reproduction

my project is on [GitHub](https://github.com/isaacwein/svelte-mwc) and [stackblitz](https://stackblitz.com/github/isaacwein/svelte-mwc?file=src%2Froutes%2F%2Bpage.svelte)

### Workaround

i didn't find any workarounds

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.1

### Browser/OS/Node environment

Google Chrome
Chrome is up to date
Version 118.0.5993.89 (Official Build) (64-bit)
Microsoft Windows 11
Version 22H2 (0S Build 22621.2428)

**Comment by thekvd** [comment]
I can speak to the Typescript version of Material Web Color only:  There are several styles that don't get created when using the Theme Utilities, this being one of them I ran into.  Anything that uses the list component was the same.

You'll need to create your own option using the `DynamicScheme ` class or, if you just need something to get through for now you can check out https://github.com/thekvd/material-web-color.  It's a bit involved but not too much.  I put that up for my own reference, but if it helps someone else.  Cool.

I'm using the `Scheme` class which is going away, but I can't get `DynamicScheme` to generate the right colors at the moment.

**Comment by isaacwein** [comment]
It’s not the dynamic theme problem even I created a static theme with
https://m3.material.io/theme-builder#/custom
Its will have the same results

**Comment by GoHarder** [comment]
@isaacwein I have come across this problem when I was trying to make my own dark theme. I found that the `--md-sys-color-on-surface-variant` changes the color of the text.

**Comment by isaacwein** [comment]
> @isaacwein I have come across this problem when I was trying to make my own dark theme. I found that the `--md-sys-color-on-surface-variant` changes the color of the text.

the text color is accurate. 
what variable is for changing the color from the input background that can be a temporary fix

**Comment by asyncLiz** [comment]
`@material/material-color-utilities` is unfortunately not up to date with the latest Material tokens. It's a separate project and it's hard for our team to help get it updated 😔

In the meantime, I recommend using https://material-web.dev and its theme generator (palette icon in the top right corner). This is a site just for this project and is kept up to date.

You can press the copy button after setting your hex color to get all the correct tokens, including the new `surface-container` tokens that the color utilities are missing, which is why some surface containers like text field's aren't being set.

We're working on better resources for generating themes that isn't reliant on other libs that may be using a different Material token version.

**Comment by isaacwein** [comment]
![Screenshot 2023-11-13 162157](https://github.com/material-components/material-web/assets/34663972/cf178a7c-9294-4f03-9c22-8da645b32642)


dynamic themes from @material/material-color-utilities are supported based on the https://material-web.dev/,

what is the material-web.dev website using to generate themes at runtime, can i use it too

**Comment by isaacwein** [comment]
Thank you for clarifying

**Comment by isaacwein** [comment]
in https://github.com/material-components/material-web/blob/main/catalog/src/utils/material-color-helpers.ts#L13C45-L13C45
I see that `@material/material-color-utilities` is being used that strange

**Comment by asyncLiz** [comment]
I believe it's using the HCT colorspace utilities from that package, but not the [main `Scheme` class](https://github.com/material-foundation/material-color-utilities/blob/main/typescript/scheme/scheme.ts) from the utilities, which doesn't have all the correct system tokens.

**Comment by isaacwein** [comment]
Thank you for pointing me to that file it will help me a lot

I was wondering why if I have that bug why the material-web.dev doesn't have the same bug, now everything make sense thank you very much for your time

**Comment by GoHarder** [comment]
> > @isaacwein I have come across this problem when I was trying to make my own dark theme. I found that the `--md-sys-color-on-surface-variant` changes the color of the text.
> 
> 
> 
> the text color is accurate. 
> 
> what variable is for changing the color from the input `<md-filled-text-field>` background that can be a temporary fix

It's one of the surface colors. I'll let you know which one exactly when I'm at work tomorrow.

**Comment by GoHarder** [comment]
@isaacwein For the text field specifically the background is `--md-sys-color-surface-container-highest`. I found that using the tools inside the Figma template will help you create a color palate that can plug into the component css.

**Comment by asyncLiz** [comment]
No, they are separate teams, which unfortunately makes it difficult to keep things in sync.

We plan on building our own API for theme generation that uses the theme builder, but keeps things up to date with our specific version of tokens.
