### ISSUE TITLE
Icon not showing up, only icon text visible

### ISSUE THREAD

**Issue by kartikwatwani** [material-components/material-web#5101]
### What is affected?

Component

### Description

I am first using rollup to create `material-web.js` for material components as a separate build process from `index.js`, then injecting material-web.js in the webpage using the <script> tag.

index.js
```
import '@material/web/fab/fab.js';
import '@material/web/icon/icon.js';
import '@material/web/fab/branded-fab.js';
import '@material/web/iconbutton/icon-button.js';

```

Using the approach above I am unable to make the icon visible inside the fab button or icon button. Instead of the icon, only the text of the icon is visible. For e.g., If I want to show the `edit` icon it shows up as `ed` inside the fab button. I am using the below html.

`<md-fab aria-label="Edit">
  <md-icon slot="icon">edit</md-icon>
</md-fab>`

How can I fix this issue?

### Reproduction

I was able to reproduce this issue on [lit playground](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9pbmRleC5qc1wiPjwvc2NyaXB0PlxuICBcbiAgPHN0eWxlPlxuICAgIDpyb290IHtcbiAgICAgIGZvbnQtZmFtaWx5OiAnUm9ib3RvJywgc3lzdGVtLXVpLCBzYW5zLXNlcmlmO1xuICAgIH1cbiAgICBcbiAgICBsYWJlbCB7XG4gICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICB9XG4gIDwvc3R5bGU-XG48L2hlYWQ-XG48Ym9keT5cbiA8bWQtZmFiIGFyaWEtbGFiZWw9XCJFZGl0XCI-XG4gIDxtZC1pY29uIHNsb3Q9XCJpY29uXCI-ZWRpdDwvbWQtaWNvbj5cbjwvbWQtZmFiPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6ImluZGV4LmpzIiwiY29udGVudCI6ImltcG9ydCAnQG1hdGVyaWFsL3dlYi9mYWIvZmFiLmpzJztcbmltcG9ydCAnQG1hdGVyaWFsL3dlYi9pY29uL2ljb24uanMnO1xuaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL2ZhYi9icmFuZGVkLWZhYi5qcyc7XG5pbXBvcnQgJ0BtYXRlcmlhbC93ZWIvaWNvbmJ1dHRvbi9pY29uLWJ1dHRvbi5qcyc7XG4ifV0).

### Workaround

Using the whole svg with the path inside `<md-icon><svg>...</svg></md-icon>` makes the icon visible in icon-button but for fab, even that is not working.,

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 1.0.1, using this library for the first time.

### Browser/OS/Node environment

Browse: Chrome 118.0.5993.88

**Comment by zmullett** [comment]
+1 returned to a project after a long hiatus; `md-icon-button` was WAI in `1.0.0-pre.7`, but now the slot font is Arial and is rendered as text.

**Comment by asyncLiz** [comment]
It looks like you're missing a link to the icon font. When I add it to your reproduction the icon appears.

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined" rel="stylesheet">
```

More info can be found on our [icon usage docs](https://github.com/material-components/material-web/blob/main/docs/components/icon.md#usage). Lemme know if you run into other problems!
