### ISSUE TITLE
Gigantamax Radio Buttons in 1.0.1 update

### ISSUE THREAD

**Issue by thekvd** [material-components/material-web#5103]
### What is affected?

Component

### Description

Updated to 1.0.1 today and noticed that the Radio Button component is now gigantic! 

v1.0.0
![image](https://github.com/material-components/material-web/assets/43453019/68233661-3a12-42f5-b8f6-7bcf02deab44)

v1.0.1
![image](https://github.com/material-components/material-web/assets/43453019/5d16f96b-7ce5-4545-abb9-a83df903c6f3)

### Reproduction

I've tried looking for anything that may be different but the only thing I can see is that the Div containing the Ripple, Focus Ring, and SVG of the Icon no longer has the Checked class on it.

### Workaround

Revert back to 1.0.0 for now.  Have tried updating again, but the issue persists.  Always goes away when reverting to 1.0.0.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

1.0.1

### Browser/OS/Node environment

Browser: Chrome 118.0.5993.89
OS: Windows 11 23H2 22631.2428
Node: 18.12.1
npm: 8.19.2

**Comment by asyncLiz** [comment]
I'm not able to reproduce this on lit.dev/playground, and it looks like the radio button's div has the `checked` class.

Can you provide a reproduction?

**Comment by thekvd** [comment]
Thanks for reaching back so fast Liz!

I feel like I'm taking crazy pills.  I just dumped my full JS and CSS files into lit.dev/playground as well as a copy/paste of the code I'm using to replicate this on a page that is just the radio button.  And like you, no problem.
 https://lit.dev/playground/#gist=7cd0d30f6f5487d355f5a1622a0a2920

The exact same code on my machine: 
![image](https://github.com/material-components/material-web/assets/43453019/cb55e940-bfe5-430e-a03b-5ccfd7bb7664)

So I decided to pull the compiled version of the code into lit.dev and boom: https://lit.dev/playground/#gist=6f03eb5a35c299c885c1dfc702c3f05f

Just adding my compiled JS into the mix made it all go screwy.  Precompiled is fine, compiled is crazybits.  The setup I'm using is from the [lit.dev's modern build for production](https://lit.dev/docs/tools/production/#modern-only-build) the dev site recommended.  Could it be something on my end only, like in my setup of that stack?

**Comment by thekvd** [comment]
Found the problem!  Don't know how it shows only when compiled but I at least isolated the setting where it goes awry.

`.container` sets a `height: 100%;` pre-compiled.  That's missing when compiled.

pre-compiled
![image](https://github.com/material-components/material-web/assets/43453019/26590eaf-57c1-4720-9bc4-80eda6ee28ef)


compiled
![image](https://github.com/material-components/material-web/assets/43453019/47d8fd81-0e20-49f9-a7bb-42b29dcc7a3f)

Means I might have a workaround for now, but I'd love to know why.

**Comment by asyncLiz** [comment]
Does it work if you remove the `minifyHTML()` plugin from your rollup build?

**Comment by thekvd** [comment]
And we have a culprit!  That worked.

**Comment by asyncLiz** [comment]
Glad to hear it!

I wrote that plugin, and it hasn't been updated to support new lit features in a while. It doesn't surprise me that it's causing issues.

I would remove it for now and re-add it once the Lit team finishes taking over and updating it
