### ISSUE TITLE
md-select-options don't inherit width from md-select

### ISSUE THREAD

**Issue by CollinHerber** [material-components/material-web#5133]
### What is affected?

Component

### Description

When changing the width of a mdc-select the options menu do not inherit the same width.
![Screenshot 2023-10-26 at 9 22 16 AM](https://github.com/material-components/material-web/assets/24656209/8cdb957e-1093-41fc-900c-af366e66d925)

### Reproduction

https://stackblitz.com/edit/au2-conventions-testrq?file=src%2Fmy-app.html

### Workaround

None known at this time

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.1

### Browser/OS/Node environment

Chrome
MacOS
Node 20
PNPM Package Manager v8

**Comment by e111077** [comment]
please use min-width. This needs documenting
