### ISSUE TITLE
md-list-item should enable md-icon-button at slot="end"

### ISSUE THREAD

**Issue by MarcosBustamante** [material-components/material-web#5134]
### What is affected?

Component

### Description

It is common the need to append actions in some list items. These actions could be a menu, edit, delete, ...

Given that, we should add the md-icon-button as a supported component in the md-list-item, it will bring all the hove, focus and press animations with it and enable the applications to expand their use cases.

### Reproduction

md-list-item should allow md-icon=-button as a valid option on the slot="end"

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.0

### Browser/OS/Node environment

OS: macOS 14.0

**Comment by asyncLiz** [comment]
Adding an icon button into the list's end slot is already supported.

https://lit.dev/playground/#gist=6dff3cd3ad40ce2885213dd15eb0e8e0

```html
<md-list-item>
  Item with button
  <md-icon-button slot="end"><md-icon>star</md-icon></md-icon-button>
</md-list-item>
```
