### ISSUE TITLE
Tabs have a shadow if its parent has --md-elevation-level

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#5137]
### What is affected?

Component

### Description

I was so confused why my tabs have dark borders except the 3 tabs surrounding the selecting tab:

![image](https://github.com/material-components/material-web/assets/6388546/1f655628-0f39-455a-88ba-e2d88dd9ed4d)

Turned out it's due to a parent's `--md-elevation-level` (for `md-elevation` effect).

### Reproduction

[Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiOyJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgXG48L2hlYWQ-XG48Ym9keT5cbiAgPGRpdiBzdHlsZT1cInBvc2l0aW9uOiByZWxhdGl2ZTsgLS1tZC1lbGV2YXRpb24tbGV2ZWw6IDM7IHBhZGRpbmc6IDFyZW07XCI-XG4gICAgPG1kLWVsZXZhdGlvbj48L21kLWVsZXZhdGlvbj5cbiAgICBcbiAgICA8cD5PdGhlciBjb250ZW50PC9wPlxuICAgIFxuICAgIDxtZC10YWJzPjxtZC1zZWNvbmRhcnktdGFiPvCfmIQgU21pbGV5cyAmYW1wOyBQZW9wbGU8L21kLXNlY29uZGFyeS10YWI-PG1kLXNlY29uZGFyeS10YWI-8J-QlSBBbmltYWxzICZhbXA7IE5hdHVyZTwvbWQtc2Vjb25kYXJ5LXRhYj48bWQtc2Vjb25kYXJ5LXRhYj7wn42KIEZvb2QgJmFtcDsgRHJpbms8L21kLXNlY29uZGFyeS10YWI-PG1kLXNlY29uZGFyeS10YWI-8J-SgyBBY3Rpdml0eTwvbWQtc2Vjb25kYXJ5LXRhYj48bWQtc2Vjb25kYXJ5LXRhYj7inIjvuI8gVHJhdmVsICZhbXA7IFBsYWNlczwvbWQtc2Vjb25kYXJ5LXRhYj48bWQtc2Vjb25kYXJ5LXRhYj7wn46BIE9iamVjdHM8L21kLXNlY29uZGFyeS10YWI-PG1kLXNlY29uZGFyeS10YWI-8J-VmyBTeW1ib2xzPC9tZC1zZWNvbmRhcnktdGFiPjxtZC1zZWNvbmRhcnktdGFiPuKavSBTcG9ydHM8L21kLXNlY29uZGFyeS10YWI-PG1kLXNlY29uZGFyeS10YWI-8J-aqSBGbGFnczwvbWQtc2Vjb25kYXJ5LXRhYj48L21kLXRhYnM-XG5cbiAgICA8cD5Xb3JrYXJvdW5kOjwvcD5cbiAgICA8bWQtdGFicyBzdHlsZT1cIi0tbWQtZWxldmF0aW9uLWxldmVsOiAwXCI-PG1kLXNlY29uZGFyeS10YWI-8J-YhCBTbWlsZXlzICZhbXA7IFBlb3BsZTwvbWQtc2Vjb25kYXJ5LXRhYj48bWQtc2Vjb25kYXJ5LXRhYj7wn5CVIEFuaW1hbHMgJmFtcDsgTmF0dXJlPC9tZC1zZWNvbmRhcnktdGFiPjxtZC1zZWNvbmRhcnktdGFiPvCfjYogRm9vZCAmYW1wOyBEcmluazwvbWQtc2Vjb25kYXJ5LXRhYj48bWQtc2Vjb25kYXJ5LXRhYj7wn5KDIEFjdGl2aXR5PC9tZC1zZWNvbmRhcnktdGFiPjxtZC1zZWNvbmRhcnktdGFiPuKciO-4jyBUcmF2ZWwgJmFtcDsgUGxhY2VzPC9tZC1zZWNvbmRhcnktdGFiPjxtZC1zZWNvbmRhcnktdGFiPvCfjoEgT2JqZWN0czwvbWQtc2Vjb25kYXJ5LXRhYj48bWQtc2Vjb25kYXJ5LXRhYj7wn5WbIFN5bWJvbHM8L21kLXNlY29uZGFyeS10YWI-PG1kLXNlY29uZGFyeS10YWI-4pq9IFNwb3J0czwvbWQtc2Vjb25kYXJ5LXRhYj48bWQtc2Vjb25kYXJ5LXRhYj7wn5qpIEZsYWdzPC9tZC1zZWNvbmRhcnktdGFiPjwvbWQtdGFicz5cbiAgPC9kaXY-XG4gIFxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMi4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjQuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4zLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ) with both the problematic one and a workaround one:

![image](https://github.com/material-components/material-web/assets/6388546/cec02731-d6bd-493d-b5f2-b31aeb38f40b)

```html
  <div style="position: relative; --md-elevation-level: 3; padding: 1rem;">
    <md-elevation></md-elevation>
    
    <p>Other content</p>
    
    <md-tabs><md-secondary-tab>😄 Smileys &amp; People</md-secondary-tab><md-secondary-tab>🐕 Animals &amp; Nature</md-secondary-tab><md-secondary-tab>🍊 Food &amp; Drink</md-secondary-tab><md-secondary-tab>💃 Activity</md-secondary-tab><md-secondary-tab>✈️ Travel &amp; Places</md-secondary-tab><md-secondary-tab>🎁 Objects</md-secondary-tab><md-secondary-tab>🕛 Symbols</md-secondary-tab><md-secondary-tab>⚽ Sports</md-secondary-tab><md-secondary-tab>🚩 Flags</md-secondary-tab></md-tabs>

    <p>Workaround:</p>
    <md-tabs style="--md-elevation-level: 0"><md-secondary-tab>😄 Smileys &amp; People</md-secondary-tab><md-secondary-tab>🐕 Animals &amp; Nature</md-secondary-tab><md-secondary-tab>🍊 Food &amp; Drink</md-secondary-tab><md-secondary-tab>💃 Activity</md-secondary-tab><md-secondary-tab>✈️ Travel &amp; Places</md-secondary-tab><md-secondary-tab>🎁 Objects</md-secondary-tab><md-secondary-tab>🕛 Symbols</md-secondary-tab><md-secondary-tab>⚽ Sports</md-secondary-tab><md-secondary-tab>🚩 Flags</md-secondary-tab></md-tabs>
  </div>
```

### Workaround

See above, setting `<md-tabs style="--md-elevation-level: 0">` fix it. I think the component itself should reset this.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.1

### Browser/OS/Node environment

Microsoft Edge Version 118.0.2088.69 (Official build) (64-bit)

**Comment by asyncLiz** [comment]
I agree that the tab should include `:host { --md-elevation-level: 0; }`

On a bigger note, these individual tab elevations do not make sense. We may want to consider deprecating tab elevation in favor of using `<md-elevation>` wrapped around the `<md-tabs>` to give the proper shadow.

As it's implemented, it's not possible to set a single shadow for the row of tabs, they incorrectly have their own shadows.

**Comment by asyncLiz** [comment]
Reference b/316459034 to clean this up
