### ISSUE TITLE
Button at the bottom causes vertical scroll due to inconsistent height

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#5143]
### What is affected?

Component

### Description

When a button (I have tested with `<md-text-button>`, `<md-filled-button>` and `<md-elevated-button>` so far) is situated at the bottom (for example by a Flex container), it would cause the container to be "bigger" than it should and cause vertical scrollbar appear:

![image](https://github.com/material-components/material-web/assets/6388546/3b5586b6-6d94-4357-8826-9455d513d1f0)

The reason is the button has the height of 40px but its `span.touch` is 48px (though it has `translateY(-50%)`). If I put a `padding-bottom: 5px` or `margin-bottom: 5px` to the button it's fixed.

![image](https://github.com/material-components/material-web/assets/6388546/737f205c-ecf3-4283-acab-6e1ae995ae4a)

Same code with the standard button that does not have the issue:

![image](https://github.com/material-components/material-web/assets/6388546/38e0f21f-7c7d-453b-bbc2-62010d448afb)

### Reproduction

[Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiOyJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgXG4gIDxzdHlsZT5cbiAgICBib2R5IHtcbiAgICAgIGhlaWdodDogMTAwdmg7XG4gICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IGNvcm5mbG93ZXJibHVlO1xuICAgICAgcm93LWdhcDogMXJlbTtcbiAgICAgIG92ZXJmbG93OiBhdXRvO1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgcGFkZGluZzogMDtcbiAgICB9XG4gIDwvc3R5bGU-XG48L2hlYWQ-XG48Ym9keT5cbiAgPGRpdj5Tb21ldGhpbmc8L2Rpdj5cbiAgXG4gIDxtZC1maWxsZWQtYnV0dG9uIHN0eWxlPVwibWFyZ2luLXRvcDogYXV0bztcIj5IZWxsbzwvbWQtZmlsbGVkLWJ1dHRvbj4gIFxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMi4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjQuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4zLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

### Workaround

Add `margin-bottom: 5px` or `padding-bottom: 5px` to the button or the container.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.1

### Browser/OS/Node environment

Microsoft Edge
Version 118.0.2088.76 (Official build) (64-bit)

Firefox 119.0 (64-bit)

**Comment by asyncLiz** [comment]
This is related to the button's touch target. By default, it extends the bounds of the button without taking up layout space, which can lead to situations like this when the button is against the edge of a container.

Either add a `touch-target="none"` attribute to the button to remove it entirely, or `touch-target="wrapper"` to keep the accessible touch size while also adding default margin to compensate for layout.

```html
<md-filled-button style="margin-top: auto;" touch-target="wrapper">Hello</md-filled-button>
```
