### ISSUE TITLE
Header styles aren't applied in the docs on Firefox

### ISSUE THREAD

**Issue by KTibow** [material-components/material-web#5146]
### Description

Expected behavior:
![image](https://github.com/material-components/material-web/assets/10727862/e007bc09-3586-43a0-af75-1220b4ccf180)
Actual behavior:
![image](https://github.com/material-components/material-web/assets/10727862/2a8beb2f-a9f9-4ba2-a612-99dd521755dd)

### Browser/OS Environment

Browser: Firefox 119.0 (64-bit)
OS: Fedora 38

**Comment by e111077** [comment]
This is because Firefox does not support CSS `:has()` IIRC it should be coming soon. Might make more sense to just wait it out unless someone wants to figure out another implementation

**Comment by LcsGa** [comment]
Hey, this issue can be closed now, right?
