### ISSUE TITLE
Circular progress isn't circular in flex column display

### ISSUE THREAD

**Issue by silamon** [material-components/material-web#5152]
### What is affected?

Component

### Description

See the reproduction 

### Reproduction

[Lit playground](https://lit.dev/playground/#project=W3sibmFtZSI6ImltcG9ydHMudHMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9hbGxcIjtcbmltcG9ydCAnQG1hdGVyaWFsL213Yy1jaXJjdWxhci1wcm9ncmVzcy9td2MtY2lyY3VsYXItcHJvZ3Jlc3MnO1xuXG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vaW1wb3J0cy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gICA8ZGl2IHN0eWxlPVwiZGlzcGxheTpmbGV4O2ZsZXgtZGlyZWN0aW9uOmNvbHVtbjtcIj5cbiAgICAgPG1kLWNpcmN1bGFyLXByb2dyZXNzIGluZGV0ZXJtaW5hdGU-PC9tZC1jaXJjdWxhci1wcm9ncmVzcz4gIFxuICAgPC9kaXY-XG4gICA8bWQtY2lyY3VsYXItcHJvZ3Jlc3MgaW5kZXRlcm1pbmF0ZT48L21kLWNpcmN1bGFyLXByb2dyZXNzPiBcbiAgXG4gICA8ZGl2IHN0eWxlPVwiZGlzcGxheTpmbGV4O2ZsZXgtZGlyZWN0aW9uOmNvbHVtbjtcIj5cbiAgICAgPG13Yy1jaXJjdWxhci1wcm9ncmVzcyBpbmRldGVybWluYXRlPjwvbXdjLWNpcmN1bGFyLXByb2dyZXNzPiAgXG4gICA8L2Rpdj5cbiAgIDxtd2MtY2lyY3VsYXItcHJvZ3Jlc3MgaW5kZXRlcm1pbmF0ZT48L213Yy1jaXJjdWxhci1wcm9ncmVzcz4gXG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjAtcHJlLjFcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMC1wcmUuMVwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjAtcHJlLjFcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wLXByZS4xXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

### Workaround

None

### Is this a regression?

Yes. This used to work, but now it doesn't. 

### Affected versions

1.0.0

### Browser/OS/Node environment

Chrome or Firefox

**Comment by datvm** [comment]
By default the flexbox stretches an item's width. Workaround is to put it in a `<div>` or use `align-self`. [Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6ImltcG9ydHMudHMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9hbGxcIjsifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vaW1wb3J0cy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gICA8ZGl2IHN0eWxlPVwiZGlzcGxheTpmbGV4O2ZsZXgtZGlyZWN0aW9uOmNvbHVtbjtcIj5cbiAgICAgPG1kLWNpcmN1bGFyLXByb2dyZXNzIHN0eWxlPVwiYWxpZ24tc2VsZjogZmxleC1zdGFydDtcIiBpbmRldGVybWluYXRlPjwvbWQtY2lyY3VsYXItcHJvZ3Jlc3M-ICBcbiAgIDwvZGl2PlxuICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6ZmxleDtmbGV4LWRpcmVjdGlvbjpjb2x1bW47XCI-XG4gICAgIDxkaXY-PG1kLWNpcmN1bGFyLXByb2dyZXNzIGluZGV0ZXJtaW5hdGU-PC9tZC1jaXJjdWxhci1wcm9ncmVzcz48L2Rpdj4gICAgIFxuICAgPC9kaXY-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjAtcHJlLjFcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMC1wcmUuMVwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjAtcHJlLjFcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wLXByZS4xXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

**Comment by asyncLiz** [comment]
I think `min-block-size: var(--_size)` and `min-inline-size: var(--_size)` need to be changed with `width: var(--_size)` and `height: var(--_size)`.

Setting these instead will give it the appropriate flex-basis so that it doesn't stretch by default in a flex container. This may be an easy PR if you wanna give it a shot.

**Comment by datvm** [comment]
I can do it unless @silamon wants a go at it.

**Comment by silamon** [comment]
> I can do it unless @silamon wants a go at it.

Sure, go ahead. I don't have much experience with the code base.

**Comment by silamon** [comment]
Thank you @datvm .
