### ISSUE TITLE
Disabled attribute do not block click events

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#5196]
### What is affected?

Component

### Description

Consider this sample code
```html
<md-filter-chip
  disabled
  @click=${() => { console.log('hi'); }}
>...
```
clicking the chip will print "`hi`" in the console even though the element is `disabled`.

### Reproduction

https://lit.dev/playground/#gist=22cb44ea419f713553690e9be1d508fb

### Workaround

One temporary solution is to use `inert` along with `disabled` to make sure events are blocked.

```html
<md-filter-chip
  ?disabled=${shouldBeDisabled}
  ?inert=${shouldBeDisabled}
  ...
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@material/web v1.0.1

### Browser/OS/Node environment

All browsers/environments.

**Comment by asyncLiz** [comment]
Updated the title, I think this is likely a larger issue across multiple components, not just chips.

**Comment by vdegenne** [comment]
@asyncLiz I'm really interested to have your first impression on what the issue might be.

**Comment by asyncLiz** [comment]
The `disabled` attribute by itself won't stop click events from firing, that's a platform feature for interactive controls like `<button disabled>`. We'd need to mimic that for our components.

One idea could be to stop the event when something is disabled.

```ts
constructor() {
  super();
  this.addEventListener('click', event => {
    if (this.disabled) {
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  });
}
```

I think we need to do more investigation into how platform elements handle disabled states with other types of events, especially those that can trigger a `click`, like `pointerdown` and `keydown`.

**Comment by vdegenne** [comment]
@asyncLiz I just can't understand something, the chip element has an internal button and the `disabled` property is conveyed to it. A native disabled button already stop the event from bubbling.
I tried to reproduce with bare minimum to confirm my point : https://lit.dev/playground/#gist=e87850f023204da8b8a3bba17d5fe1f8
And I can't see anything inside the chip that is hijacking the event.
So what does cause the click event to be triggered on the element itself?

**Comment by asyncLiz** [comment]
We should reflect disabled attributes in particular to match the platform's disabled attributes, so that sounds like a good path forward to me
