### ISSUE TITLE
[nightly] filter-chip prevent default behavior

### ISSUE THREAD

**Issue by Bubz43** [material-components/material-web#5199]
### What is affected?

Component

### Description

If you call `preventDefault()` in the click handler and then change the selected state, the boolean is switched after the handler completes. This differs from something like the native `<input type="checkbox">` where calling `preventDefault()` discards any changes to the checked state and reverts to what it was before the click.

### Reproduction

Click on the chip and checkbox to see difference in behavior.

https://lit.dev/playground/#gist=60238cc313499bd82352f93c2d3ecf73

### Workaround

Calling prevent default and changing the state in the click handler is probably a mistake in the first place, but nothing happening is probably better than it seeming like it works but actually being backwards. 

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.2-nightly.6a1fb38.0

### Browser/OS/Node environment

Browser: Vivaldi 6.4.3160.42

**Comment by asyncLiz** [comment]
This will be part of a larger effort to make sure `preventDefault()` works as expected.
