### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. (node:17804) 

### ISSUE THREAD

**Issue by m-asadullah** [material-components/material-web#5204]
### What is affected?

Component, Tooling, Other/unknown

### Step-I: Quick start
`npm install @material/web` 
- [Quick start guide of Material3 web](https://github.com/material-components/material-web/blob/main/docs/quick-start.md)

### Step-II: After installing `material/web` 
`npm install rollup @rollup/plugin-node-resolve`
(node:17804) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings` to show where the warning was created)

added 18 packages, and audited 27 packages in 17s

7 packages are looking for funding
  run `npm fund` for details

### Step-III: After running `npm fund`
projectname@1.0.0
+-- https://github.com/sponsors/sindresorhus
|   `-- is-builtin-module@3.2.1, builtin-modules@3.3.0`
+-- https://github.com/sponsors/ljharb
|   `-- resolve@1.22.8, is-core-module@2.13.1, function-bind@1.1.2, supports-preserve-symlinks-flag@1.0.0`
+-- https://github.com/sponsors/jonschlinkert
    `-- picomatch@2.3.1`

### Output 
- When the project run
- It look like this

![image](https://github.com/material-components/material-web/assets/68208088/9101986b-967e-4083-ae17-de9de5ccb724)

### Workaround

Not found

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing web 1.0.0

#### `Google Chrome: 120.0.6099.28` (Official Build) beta (64-bit) (cohort: Beta)
Revision: f4095e9665f7d7a2531edefcea119d45d899d95b-refs/branch-heads/6099@{694}
#### User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line: "C:\Program Files\Google\Chrome Beta\Application\chrome.exe" --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=WebGPU
Executable Path: C:\Program Files\Google\Chrome Beta\Application\chrome.exe

#### `npm: 10.1.0`

**Comment by asyncLiz** [comment]
I don't think this is a runtime bug with our library, it sounds like an error in your installation of node.

Can you try upgrading or reinstalling node, then try installing the library from npm again?

**Comment by asyncLiz** [comment]
Try adding `node --trace-warnings` when you run the command to install rollup.
