### ISSUE TITLE
md-chip does not ellipsis label text when constrained by a limited width.

### ISSUE THREAD

**Issue by kaseyhinton** [material-components/material-web#5242]
### What is affected?

Component

### Description

I would expect a md-chip when constrained by a max-width to ellipsis text instead of overflowing.

### Reproduction

Here is a link to a reproduction [lit playground example](https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9jaGlwcy9hc3Npc3QtY2hpcC5qc1wiO1xuaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9jaGlwcy9jaGlwLXNldC5qc1wiO1xuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbWF0ZXJpYWwtaW1wb3J0cy5qc1wiPjwvc2NyaXB0PlxuPHN0eWxlPlxuICBtZC1jaGlwLXNldCB7XG4gICAgbWF4LXdpZHRoOiAxNzBweDtcbiAgfVxuICBcbiAgZWxsaXBzaXMtY2hpcCB7XG4gICBkaXNwbGF5OiBibG9jaztcbiAgIGJvcmRlcjogMXB4IHNvbGlkICMwMDA7XG4gICBwYWRkaW5nOiA2cHggMTJweDtcbiAgIGJvcmRlci1yYWRpdXM6IDhweDtcbiAgfVxuICBcbiAgLmVsbGlwc2lzIHtcbiAgIHdoaXRlLXNwYWNlOm5vd3JhcDtcbiAgIHRleHQtb3ZlcmZsb3c6IGVsbGlwc2lzO1xuICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgfVxuPC9zdHlsZT5cbjxtZC1jaGlwLXNldD5cbiAgPG1kLWFzc2lzdC1jaGlwIGNsYXNzPVwiZWxsaXBzaXNcIiBsYWJlbD1cIkEgbWF0ZXJpYWwgY2hpcCB3aXRoIGEgbG9uZyBsYWJlbFwiPjwvbWQtYXNzaXN0LWNoaXA-XG4gIDxtZC1hc3Npc3QtY2hpcCBjbGFzcz1cImVsbGlwc2lzXCIgbGFiZWw9XCJBIG1hdGVyaWFsIGNoaXAgd2l0aCBhIGxvbmcgbGFiZWxcIj48L21kLWFzc2lzdC1jaGlwPlxuICA8ZWxsaXBzaXMtY2hpcCBjbGFzcz1cImVsbGlwc2lzXCI-QSBjdXN0b20gY2hpcCB3aXRoIGEgbG9uZyBsYWJlbDwvZWxsaXBzaXMtY2hpcD5cbjwvbWQtY2hpcC1zZXQ-XG5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

### Workaround

The only way to really manage the md-chips right now is to allow the container to scroll and let the chips grow as wide as they need to be for their labels.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.1

### Browser/OS/Node environment

OS: Windows 11
Browser: Microsoft Edge 119.0.2151.93

**Comment by kaseyhinton** [comment]
any updates on this?

**Comment by asyncLiz** [comment]
Fixed in https://github.com/material-components/material-web/pull/5665
