### ISSUE TITLE
Ignore Linear Progress' Buffer unless it is set?

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#5251]
### What is affected?

Component

### Description

Right now, `<md-linear-progress>` has its `buffer` value default to 1 and if we set `max` to any other value (usually 100 or the number of steps to process, number of files to copy for example), we have to set `buffer` to the same value as well. I think we should not have to worry about `buffer` value unless we actually want to and manually specify it.

While this would be a breaking change, I don't think anyone is having a special case where `buffer` should be at 1 without `max` is also 1.

### Reproduction

[Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiOyJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8bWQtbGluZWFyLXByb2dyZXNzIG1heD1cIjNcIiB2YWx1ZT1cIjBcIj48L21kLWxpbmVhci1wcm9ncmVzcz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4zLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl40LjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMy4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0) where a `max` value is set to 3 and now the buffer runs from 2 to 3:

![image](https://github.com/material-components/material-web/assets/6388546/e391a631-96e2-4915-9d28-83710e60d7c0)

### Workaround

If approved, the current source code can easily be changed to accomplish this:

- Change the `buffer` property to allow `undefined`:

```diff
export class LinearProgress extends Progress {
  /**
   * Buffer amount to display, a fraction between 0 and `max`.
   */
- @property({type: Number}) buffer = 1;
+ @property({type: Number}) buffer: number | undefined = undefined;
```

- Update `dotStyles`, the only place that uses `buffer` for now:

```diff
    const dotStyles = {
      transform: `scaleX(${
-       (this.indeterminate ? 1 : this.buffer / this.max) * 100
+       (this.indeterminate ? 1 : (this.buffer ?? this.max) / this.max) * 100
      }%)`,
    };
```

With the above code, adding and removing `buffer` attribute works as intended too: removing `buffer` HTML attribute sets `buffer` value to `undefined` and the buffer bar doesn't show up again.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.1

### Browser/OS/Node environment

N/A

**Comment by christophe-g** [comment]
In addition, animation on `.dots` should be disabled when `buffer` is `max` (and dots are hidden by buffer).

Infinite progress bar animation can cause performance degradation on some device (at least it does on mine).

**Comment by asyncLiz** [comment]
I'd like to see if we could solve this without changing `buffer`'s type away from `Number`, since that can cause TS strict build failures.

We could follow some other component conventions like text field and use `-1` to indicate no buffer value. I think we could change `buffer = -1` as the default value.

I agree that changing `max` without also changing `buffer` and seeing buffer dots is a bug and not a breaking change.

**Comment by datvm** [comment]
Thanks, I created the PR.

A small note: `buffer` may actually be null anyway. If I set a `buffer` attribute and then remove it, `buffer` property value becomes `null`. This PR doesn't make any attempt to fix this issue and I guess it's an invalid use case for all components.

**Comment by asyncLiz** [comment]
> Thanks, I created the PR.
> 
> A small note: `buffer` may actually be null anyway. If I set a `buffer` attribute and then remove it, `buffer` property value becomes `null`. This PR doesn't make any attempt to fix this issue and I guess it's an invalid use case for all components.

We'll probably still need to handle that use case until Lit has better support for non-nullable number types.
