### ISSUE TITLE
m3 material design components not showing properly on Safari

### ISSUE THREAD

**Issue by reza55n** [material-components/material-web#5276]
### What is affected?

Component

### Description

m3 material design web not showing the components properly on some Safari browsers

### Reproduction

Components tested: button and checkbox

Multiple iOS and Mac devices tested such as Safari version 15.6.1 on macOS Catalina

### Workaround

-

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

m3

### Browser/OS/Node environment

Multiple iOS and Mac devices tested such as Safari version 15.6.1 on macOS Catalina

![photo_2023-12-10_19-09-23](https://github.com/material-components/material-web/assets/13783129/a37309d0-4c38-45f8-89f4-7abe21b14bcc)

Screenshot of <https://material-web.dev/components/checkbox/> URL from an iOS Safari browser

**Comment by asyncLiz** [comment]
Our [browser support](https://github.com/material-components/material-web/blob/main/docs/support.md#browsers) lists Safari 16.4+ at the time of writing, so this is expected. Older versions of Safari may benefit from [`element-internals-polyfill`](https://www.npmjs.com/package/element-internals-polyfill), but we don't officially support it.

**Comment by ronnieroyston** [comment]
Automatic feature detection / polyfill injection would be nice. Safari v 16.4 is less than one year old.
