### ISSUE TITLE
FAB shadow went wrong.

### ISSUE THREAD

**Issue by mai1202** [material-components/material-web#5308]
### What is affected?

Component

### Description

When I use an FAB, like this: 
```
<md-fab label="添加">
     <md-icon slot="icon">add</md-icon>
</md-fab>
```
Hover the cursor over it, it shows:
![image](https://github.com/material-components/material-web/assets/63698132/79e7f8d7-24bc-43af-9c1a-c0b67a0476d1)

### Reproduction

```
<md-fab label="添加">
     <md-icon slot="icon">add</md-icon>
</md-fab>
```

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

v1.1.1

### Browser/OS/Node environment

Chrome 120.0.6099.72
Windows 11
v18.16.1
9.5.1

**Comment by asyncLiz** [comment]
I wasn't able to reproduce with the code provided. Can you add a https://lit.dev/playground reproduction?

**Comment by mai1202** [comment]
> I wasn't able to reproduce with the code provided. Can you add a https://lit.dev/playground reproduction?

How to import material web to Playground? I'm not familiar with Playground.

**Comment by mai1202** [comment]
Embarrassingly, there is a clash with Material Web in my app. It is not Material Web's problem.
