### ISSUE TITLE
md-dialog: Escape key press does not close the dialog completely + navigation back on mobile not working

### ISSUE THREAD

**Issue by kkachniarz220** [material-components/material-web#5313]
### What is affected?

Component

### Description

On escape key press the 'cancel' event is not emitting + backdrop layer is still visible
[screen-capture](https://github.com/material-components/material-web/assets/50884231/630e3402-7a60-4706-8f14-46c44b8ae568)

There is problem also with browser history back - backdrop layer is still visible (as on native browser <dialog>)

### Reproduction

simple md-dialog use

### Workaround

.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.1.1

### Browser/OS/Node environment

Browser: Chrome 120.0.6099.110 
Windows 11
Node version: 18.17.1
npm version: 9.6.7

**Comment by asyncLiz** [comment]
Underlying issue is https://bugs.chromium.org/p/chromium/issues/detail?id=1512224

Think I can add a patch though

**Comment by josepharhar** [comment]
I think that `dialog/internal/dialog.ts` should be looking at both the `close` and `cancel` events. `close` will always fire, but in this case where the closing of the dialog is not preventable, the `cancel` event will not be fired.

It looks like the `close` event is not being listened to: https://github.com/material-components/material-web/blob/50a9ffae46499ec575a38887b5dcce8f5506e576/dialog/internal/dialog.ts#L244

**Comment by asyncLiz** [comment]
The Chromium bug still breaks the ability to detect if a dialog was canceled by pressing the escape key vs calling `dialog.close()`.

Was there a breaking spec change where pressing the escape key closes a dialog without cancelation?

**Comment by josepharhar** [comment]
Yeah we changed the spec here: https://github.com/whatwg/html/pull/9462

**Comment by asyncLiz** [comment]
Got a patch in #5329 that'll fix it for now, but gonna leave this open to track addressing non-cancelable CloseWatcher anti-abuse gestures, such as the Android back button or pressing escape twice.

**Comment by asyncLiz** [comment]
Actually going to track in https://github.com/material-components/material-web/issues/5330 to avoid scope creep with this issue
