### ISSUE TITLE
Ripple Start Position on Touch Event

### ISSUE THREAD

**Issue by Kamilko16** [material-components/material-web#5349]
### What is affected?

Component

### Description

When the button is touched, only the first touch ripple start position is correct (it starts in touch position). Next touches have start position exactly in the middle of the button, no matter where touched.

### Reproduction

Touch the button two or more times, spot the difference. Refreshing page resets the problem.

### Workaround

I haven't found workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.1.1

### Browser/OS/Node environment

Browser: Chrome 120.0.6099.111 on desktop, Chrome 120.0.6099.116 on mobile.
node: v20.9.0

**Comment by asyncLiz** [comment]
Which platforms have the problem (iOS, Android, Mac OS/Windows/ChromeOS with touchscreen)? Both desktop and mobile please :)

**Comment by Kamilko16** [comment]
I only tested it on Windows (mouse works fine, only phone emulation has this problem) and Android also has this problem. The problem is with the ripple compontent itself i think.
