### ISSUE TITLE
Material-web.dev Theme Controls provide wrong palette

### ISSUE THREAD

**Issue by CicciLeo** [material-components/material-web#5359]
### Description

Theme controls in material-web.dev provide a color scheme with medium level of contrast, instead of the standard one.
otherwise, m3.material.io/theme-builder generate standard contrast color scheme, but is out-of-date

**Comment by asyncLiz** [comment]
Can you give steps for how you determined the catalog is giving medium contrast?

In our code, [we're using `0` for contrast](https://github.com/material-components/material-web/blob/035d1553662812e2dcc12aea8d70ea8bf26b164b/catalog/src/utils/material-color-helpers.ts#L98) in material color utilities, which according to its docs [should represent the design standard](https://github.com/material-foundation/material-color-utilities/blob/1217346b9416e6e55c83c6e9295f6aed001e852e/typescript/scheme/dynamic_scheme.ts#L28-L30).

**Comment by CicciLeo** [comment]
I checked again and it seems I made a mistake setting the source color.
with material theme builder my source color generates a light pattern, but with the material-web.dev tool itbecomes very dark. I've had the adjust the tone value of the source color

**Comment by asyncLiz** [comment]
Glad to hear you found the problem!
