### ISSUE TITLE
Ripple not showing sometimes on mobile

### ISSUE THREAD

**Issue by TeamBusylj** [material-components/material-web#5361]
### What is affected?

Component

### Description

When you press a button and keep pressing or swipe finger away the ripple shows. But when you do it again the ripple does not show. It works on computer, but not on mobile. It is working in material 2 components.

### Reproduction

[Look here](https://stackblitz.com/edit/web-platform-qrd1jz?file=index.html) under material 3 button and try.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

All versions

### Browser/OS/Node environment

I use chrome 120 on mobile with android 14.

**Comment by asyncLiz** [comment]
I recently updated ripple to fix some mobile bugs, does this still happen on `@material/web@nightly`?

**Comment by TeamBusylj** [comment]
I checked and it is working now.
Thanks!
