### ISSUE TITLE
Add harness to npm package

### ISSUE THREAD

**Issue by Christian24** [material-components/material-web#5397]
### Description

Hi, 
I am currently working on a Lit integration for Tanstack Form. I am currently in the process of writing tests and sadly there is no good framework for writing web component tests. 

I have opened a couple testing library PRs but they haven't been merged in ages: https://github.com/testing-library/user-event/pull/1033

Hence, I am looking for a different way to simulate input in my tests. Since I am using Material Web for components I thought maybe I could use the `Harness`: https://github.com/material-components/material-web/blob/main/testing/harness.ts Sadly, it seems harness is not part of the npm package however. 

Is there a reason for this? Angular Material does provide component harnesses and I would welcome if Material web did too.

**Comment by asyncLiz** [comment]
Uh oh! This looks like an oversight.

We do ship per-component harnesses (like [`@material/web/button/harness.js`](https://unpkg.com/browse/@material/web@1.1.1/button/harness.js)), but it looks like we're excluding the testing folder which it needs 😬

**Comment by Christian24** [comment]
Oh! I opened a PR that should fix this then @asyncLiz :)
