### ISSUE TITLE
Figma false declation of dark/tertiary fixed-dim

### ISSUE THREAD

**Issue by Jafoson** [material-components/material-web#5430]
### What is affected?

Theming

### Description

Hello,

I wanted to use the design system from Material Design that you have released. When I used this, I noticed that there is an error in the dark mode of the Styles Colour Guidance.

Namely in the tertiary fixed dim, the showcase container is in light instead of dark. This is not a serious error. Nevertheless, I just wanted to draw your attention to it.

Yours sincerely
Jason
<img width="677" alt="Bildschirmfoto 2024-01-26 um 13 34 31" src="https://github.com/material-components/material-web/assets/81825412/0f1524eb-0e25-465e-85fa-00d66ec11894">

### Reproduction

/

### Workaround

/

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

/

### Browser/OS/Node environment

/

**Comment by asyncLiz** [comment]
Great callout! I've reached out to figure out where we can post this bug to get fixed.

Leaving this open for now, and I'll close once we get the info where it needs to go. That's for the design team, so not much we can do on our end about it.

**Comment by asyncLiz** [comment]
It has been fixed! May take a moment before it shows up (I'm not sure how the figma stickersheet is updated)

For future reference, folks can message [m3-design-kit-feedback@google.com](mailto:m3-design-kit-feedback@google.com) if they find other issues :)
