### ISSUE TITLE
Radio button can't be initially checked

### ISSUE THREAD

**Issue by PatrickStephansen** [material-components/material-web#5461]
### What is affected?

Component

### Description

When I set the `checked` attribute on an `md-radio` (boolean attribute - by set, I mean it's present), I expect the property to also be true, and for the button to be visually checked.

### Reproduction

Load test page with html `<md-radio checked></md-radio>` 

### Workaround

Maybe it can be programmatically checked on load, but I haven't had success with that.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.1.1

### Browser/OS/Node environment

Browser: Chrome - Version 121.0.6167.160 (Official Build) (arm64), OS: Mac

**Comment by PatrickStephansen** [comment]
I'm pretty sure this line is the culprit:   `[CHECKED] = false;`: https://github.com/material-components/material-web/blob/6b95a13ee1fd4203140aeda89c24c7afb8acdde1/radio/internal/radio.ts#L73

**Comment by asyncLiz** [comment]
I'm [not able to reproduce in this jsbin](https://jsbin.com/bacukutefo/edit?html,output), can you provide an online reproduction?

```html
<script type="module" src="https://esm.run/@material/web/radio/radio.js"></script>
<md-radio checked></md-radio>
```

**Comment by PatrickStephansen** [comment]
Sorry, it seems my test environment was misconfigured. It works in the right context.
