### ISSUE TITLE
Checkbox does not work with form in Safari as intended 

### ISSUE THREAD

**Issue by IvanDreamer** [material-components/material-web#5471]
### What is affected?

Component

### Description

In Safari when I put a checkbox in a form, data is not set as it should be, but in Chrome it works.

```
<form>
  <md-checkbox name="subscription" checked value="test">Subscribe</md-checkbox>
  <md-outlined-button>Save</md-outlined-button>
  <div id="result"></div>
</form>
```

### Reproduction

[Example in Lit playground](https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi9idXR0b24vb3V0bGluZWQtYnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2NoZWNrYm94L2NoZWNrYm94LmpzXCI7XG5cbmxldCBmb3JtID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcImZvcm1cIik7XG5sZXQgcmVzdWx0ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIiNyZXN1bHRcIik7XG5mb3JtLmFkZEV2ZW50TGlzdGVuZXIoXCJzdWJtaXRcIiwgKGUpID0-IHtcbiAgZS5wcmV2ZW50RGVmYXVsdCgpO1xuICBjb25zdCBkYXRhID0gbmV3IEZvcm1EYXRhKGUudGFyZ2V0KTtcbiAgY29uc29sZS5sb2coWy4uLmRhdGEuZW50cmllcygpXSk7XG4gIHJlc3VsdC5pbm5lckhUTUwgPSBbLi4uZGF0YS5lbnRyaWVzKCldO1xufSk7XG4gICAgIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbWF0ZXJpYWwtaW1wb3J0cy5qc1wiPjwvc2NyaXB0PlxuXG48Zm9ybT5cbiAgPG1kLWNoZWNrYm94IG5hbWU9XCJzdWJzY3JpcHRpb25cIiBjaGVja2VkIHZhbHVlPVwidGVzdFwiPlN1YnNjcmliZTwvbWQtY2hlY2tib3g-XG4gIDxtZC1vdXRsaW5lZC1idXR0b24-U2F2ZTwvbWQtb3V0bGluZWQtYnV0dG9uPlxuICA8aDQ-Rm9ybSBkYXRhIHRvIGJlIHN1Ym5pdHRlZDo8L2g0PlxuICA8ZGl2IGlkPVwicmVzdWx0XCI-PC9kaXY-XG48L2Zvcm0-In0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ) 

In Safari result is not showing in checked or unchecked state, but in Chrome data is showing in result.

### Workaround

Use chrome maybe .)

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.2.0

### Browser/OS/Node environment

Safari Version 16.6 (18615.3.12.11.2)
OSX Version 13.5.1 (22G90)

**Comment by asyncLiz** [comment]
Closing to inactivity, please comment with error messages if you're still seeing the issue!
