### ISSUE TITLE
Switch misses input event handler

### ISSUE THREAD

**Issue by JakobVogelsang** [material-components/material-web#5486]
### What is affected?

Component

### Description

When I listen on and input event on the component `md-switch` the `evt.target.selected` is not updated. This is not what the documentation of this component is stating and I think this is because and `handleInput` is missing that converts the underlying `<input typ="checkbox" />` `checked` attribute to `md-switch` `selected` attribute as it does for the `@change` event.

### Reproduction

Add event listener to switch and see it that `evt.target.selected` does not reflect the supposed value-

### Workaround

I am using @change for now, but it makes my code a bit more complicated, and I would love to work with the @input event.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.20

### Browser/OS/Node environment

Chrome

**Comment by datvm** [comment]
I can confirm it is happening [Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuICBcbiAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2ljb24_ZmFtaWx5PU1hdGVyaWFsK1N5bWJvbHMrT3V0bGluZWRcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8ZGl2PlxuICAgIDxwPlxuICAgICAgPGxhYmVsPlxuICAgICAgICA8bWQtc3dpdGNoPjwvbWQtc3dpdGNoPlxuICAgICAgICBIZWxsb1xuICAgICAgPC9sYWJlbD4gICAgXG4gICAgPC9wPlxuICAgIDxwPlxuICAgICAgPGxhYmVsPlxuICAgICAgICA8bWQtcmFkaW8gaWQ9XCJyMVwiIG5hbWU9XCJyXCI-PC9tZC1yYWRpbz5cbiAgICAgICAgSGVsbG9cbiAgICAgIDwvbGFiZWw-XG4gICAgICBcbiAgICAgIDxsYWJlbD5cbiAgICAgICAgPG1kLXJhZGlvIGlkPVwicjJcIiBuYW1lPVwiclwiPjwvbWQtcmFkaW8-XG4gICAgICAgIEhlbGxvXG4gICAgICA8L2xhYmVsPlxuICAgIDwvcD5cbiAgPC9kaXY-XG4gIFxuICA8c2NyaXB0PlxuICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCJkaXZcIikuYWRkRXZlbnRMaXN0ZW5lcihcImNoYW5nZVwiLCAoZSkgPT4ge1xuICAgICAgYWxlcnQoXCJDaGFuZ2U6IFwiICsgKGUudGFyZ2V0LnNlbGVjdGVkIHx8IGUudGFyZ2V0LmNoZWNrZWQpKTtcbiAgICB9KTtcbiAgICBcbiAgICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiZGl2XCIpLmFkZEV2ZW50TGlzdGVuZXIoXCJpbnB1dFwiLCAoZSkgPT4ge1xuICAgICAgYWxlcnQoXCJJbnB1dDogXCIgKyBlLnRhcmdldC5pZCArIFwiIFwiICsgKGUudGFyZ2V0LnNlbGVjdGVkIHx8IGUudGFyZ2V0LmNoZWNrZWQpKTtcbiAgICB9KTtcbiAgPC9zY3JpcHQ-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d).

It doesn't happen to `md-radio` but for some reason the `input` event is fired twice.

**Comment by vdegenne** [comment]
@JakobVogelsang As a side note, this repository is open to contribution. If you think you found the problem to an issue (which in this case you did correctly!) and it doesn't require much of a modification in code, *and you have few minutes to spare*, always feel free to propose a PR, it helps everyone in the end.
Thanks for the report though!

**Comment by JakobVogelsang** [comment]
You are very correct. I will keep that in mind should there be another issue
