### ISSUE TITLE
md-tabs: scroll to active tab on init shouldn't be smooth behaviour

### ISSUE THREAD

**Issue by kkachniarz220** [material-components/material-web#5497]
### What is affected?

Component

### Description

Scrolling to active tab on component init should be immediate, now it is smooth.

In addition there is weird behaviour with playground:

[screen-capture (9).webm](https://github.com/material-components/material-web/assets/50884231/a9504787-07f6-4ce4-b43c-ab11b74d84c9)

### Reproduction

[lit.dev](https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi90YWJzL3RhYnNcIjtcbmltcG9ydCBcIkBtYXRlcmlhbC93ZWIvdGFicy9wcmltYXJ5LXRhYlwiOyJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL21hdGVyaWFsLWltcG9ydHMuanNcIj48L3NjcmlwdD5cblxuPG1kLXRhYnMgYWN0aXZlLXRhYi1pbmRleD1cIjIwXCI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgMTwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgMjwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgMzwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNDwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNTwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNjwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNzwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgMTwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgMjwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgMzwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNDwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNTwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNjwvbWQtcHJpbWFyeS10YWI-XG4gIDxtZC1wcmltYXJ5LXRhYj50YWIgNzwvbWQtcHJpbWFyeS10YWI-XG4gICA8bWQtcHJpbWFyeS10YWI-dGFiIDE8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDI8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDM8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDQ8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDU8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDY8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDc8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDE8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDI8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDM8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDQ8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDU8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDY8L21kLXByaW1hcnktdGFiPlxuICA8bWQtcHJpbWFyeS10YWI-dGFiIDc8L21kLXByaW1hcnktdGFiPlxuPC9tZC10YWJzPlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

### Workaround

I have not found a reproduction

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.3.0

### Browser/OS/Node environment

Chrome 121.0.6167.187
Windows 11

**Comment by asyncLiz** [comment]
Looks like the boolean logic was flipping and we were smooth scrolling on init and instant scrolling on arrow key navigation, whoops!

I'm fixing this in https://github.com/material-components/material-web/pull/5499. It'll also fix setting `scroll-behavior: instant` on the tabs to turn off the default smooth scrolling.
