### ISSUE TITLE
MdTextField inherits text-align from parents

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#5509]
### What is affected?

Component

### Description

See [Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiOyJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8ZGl2IHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyO1wiPlxuICAgIDxtZC1maWxsZWQtdGV4dC1maWVsZCB2YWx1ZT1cIlRoaXMgdGV4dCBpcyBjZW50ZXJlZFwiIHN0eWxlPVwid2lkdGg6IDEwMCU7XCI-PC9tZC1maWxsZWQtdGV4dC1maWVsZD5cbiAgICA8aW5wdXQgdmFsdWU9XCJUaGlzIHRleHQgaXMgc3RpbGwgbGVmdC1hbGlnbmVkXCIgc3R5bGU9XCJ3aWR0aDogMTAwJTtcIiAvPlxuICA8L2Rpdj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4zLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl40LjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMy4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0). I am not sure if it's intended but right now parents' `text-align` would affect the text fields as well. Maybe because it's `inline-flex` instead of `inline-block` like the standard's `input`?

```html
  <div style="text-align: center;">
    <md-filled-text-field value="This text is centered" style="width: 100%;"></md-filled-text-field>
    <input value="This text is still left-aligned" style="width: 100%;" />
  </div>
```

![image](https://github.com/material-components/material-web/assets/6388546/dae58f6c-df0a-4764-a8dc-1c3863137c87)

### Reproduction

See above.

### Workaround

Manually set the text field text-align back.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

v1.3.0

### Browser/OS/Node environment

Windows 11 Pro

Microsoft Edge
Version 122.0.2365.66 (Official build) (64-bit)

Google Chrome
Version 122.0.6261.95 (Official Build) (64-bit)

**Comment by asyncLiz** [comment]
`<input>` has `text-align: start` as a default style. It makes sense to me to add this to the default `:host` styles of the text field so it doesn't inherit it from parents.

Would appreciate a PR if you can put one together!

**Comment by datvm** [comment]
@asyncLiz Thanks, I have not worked with SCSS intensively so I am not very familiar with it. Don't know if there is a way so both `md-outlined-text-field` and `md-filled-text-field` can inherit the same change.

A small note, currently the internal `input` has an invalid `direction` property value:

![image](https://github.com/material-components/material-web/assets/6388546/b2f7f9ba-dd77-4c93-aed7-fc612ccb26eb)

Also it's pretty hard to contribute to styling from Windows because this command cannot be run on Windows and WSL (Windows Subsystem for Linux) somehow takes a few minutes to finish (GitHub Actions takes only a few seconds). I am not sure if there is a solution for this.

```
sass --style=compressed --load-path=node_modules --load-path=node_modules/sass-true/sass $(ls -d */ | grep -vE 'node_modules|catalog')
```
