### ISSUE TITLE
Better dialog customization

### ISSUE THREAD

**Issue by shadow-identity** [material-components/material-web#5517]
### Description

We're making our date picker component following Material guidelines, and I was trying to use md-dialog to show the calendar in docked or modal modes. But it does not seem to be possible because of reasons I described below. Generally speaking, the `md-dialog` lacks of `md-menu`-like properties and behavior.
- I can not disable `scrim`.  I can set it to transparent tho, but the first click is interrupted by `md-dialog`, so if user have the date picker in docked mode open, and they wants to press the button on the main layer, it is expected that the button can be pressed (closing the docked date picker at the same time). But in fact, user have to press the button twice -- to close the date picker and to press the button.
- Without the scirm the dialog may require elevation setting to distinguish it from the underlying content, but there is no way to do it. I was trying to set `md-dialog { --md-sys-elevation: 5; }`, but it does not work. Setting of `box-shadow` on the element also does not work.
- I can not position it relatively to the triggering element (which could be the `md-text-field` for example) because it does not react on positioning properties (like if I set `position: relative; top: 40px; left: 30px`. 

Having these issues solved could make it easy to build custom date picker unless it is not released by the material-web project.

**Comment by asyncLiz** [comment]
Can you describe your use case more? A menu surface popup is the appropriate component to use for use cases like datepicker popups, which have a different accessibility pattern than dialog that addresses those issues.

**Comment by shadow-identity** [comment]
I thought `md-menu` should be used only together with `md-menu-item`. I was wrong, it works perfectly with my custom content. Sorry to bother you.
