### ISSUE TITLE
md-slider track background

### ISSUE THREAD

**Issue by TeamBusylj** [material-components/material-web#5518]
### What is affected?

Theming

### Description

Hi, I want to set slider tick's color tolinear-gradient with setting --_active-track-color variable to gradient. But it doesn't work because the variable sets background-color of tick instead of background. background-color doesnt support linear gradient.
Is there a way to bypass or fix it?

### Reproduction

 It doesn't work.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.3

### Browser/OS/Node environment

All platforms

**Comment by asyncLiz** [comment]
Can you provide some screenshots of the design you're trying to achieve? The tick marks are very small, so I'm not sure a linear gradient would be perceivable.

**Comment by TeamBusylj** [comment]
Hi, i have changed track-height variable to it is taller. This is how it looks like when i set background to gradient in devtools.
![image](https://github.com/material-components/material-web/assets/88550318/b2a24956-20b6-4b20-897d-5d0e1e6f56a0)

**Comment by asyncLiz** [comment]
Gotcha, thanks for the screenshot! Cute slider!

Changing places we're using background-color to background makes sense to me. Could you send a PR?

**Comment by TeamBusylj** [comment]
Hi i have created pull request and committed it, but I'm not authorized
user.

**Comment by asyncLiz** [comment]
Thanks! I'm reviewing it now :)

**Comment by TeamBusylj** [comment]
Thanks:)
