### ISSUE TITLE
I cannot found where the md-typescale.js is.

### ISSUE THREAD

**Issue by gkj17** [material-components/material-web#5524]
### Description

import {styles as typescaleStyles} from '../../typography/md-typescale.js';

**Comment by asyncLiz** [comment]
Looks like it [isn't getting published](https://cdn.jsdelivr.net/npm/@material/web@1.3.1-nightly.8f7cb4c.0/typography/). I'll check on that

**Comment by gkj17** [comment]
Thanks, looking forward to your reply!

**Comment by asyncLiz** [comment]
This will be good to go in 1.4.0, which should be published tomorrow.
