### ISSUE TITLE
Dialog header is bold when it shouldn't be

### ISSUE THREAD

**Issue by dylan904** [material-components/material-web#5541]
### What is affected?

Component

### Description

When using the dialog component, it's always seen to have a bold header. However, if you look at the [Figma file](https://www.figma.com/community/file/1035203688168086460), or in the [MD3 components overview](https://m3.material.io/components/dialogs/overview) you can see the font weight should be normal, not bold.

### Reproduction

Confirm the bold header in their demo [here](https://material-web.dev/components/dialog/stories/).

### Workaround

There seems to be no workaround at the moment, even if I try to use the following, it somehow applies "normal" to the computed styles, but still renders as bold. I'm guessing something to do with the shadow DOM.

`slot[name="headline"]::slotted(*) {
    font-weight: normal;
}`

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failed in 1.3.0 and 1.4.0

### Browser/OS/Node environment

Browser: Chrome 122.0.6261.129 (Official Build)
Node: 20.3.1
NPM: 9.6.7
Mac OS: 11.6

**Comment by asyncLiz** [comment]
Let us know if you're still seeing this issue. If so, post a screenshot and we can re-open.
