### ISSUE TITLE
Add support for alternative menu animation

### ISSUE THREAD

**Issue by aksdog** [material-components/material-web#5551]
### Description

Add support for legacy Material Design 2 animation

https://kstatic.googleusercontent.com/files/e640e0522edecb81d7957409e9277cde9728adade05a4929bcbbf46f4acfb3af8478f9d0146d55e5baa53ed53f82f14925dedd7add889137d4c5e1a1e1180a51

**Comment by asyncLiz** [comment]
Providing M2 animations is out of scope for this library, which implements M3.

See https://github.com/material-components/material-web/discussions/5549#discussioncomment-8933947 for more info on plans to support customizable motion.
