### ISSUE TITLE
safari compatibility issues

### ISSUE THREAD

**Issue by gkj17** [material-components/material-web#5567]
### What is affected?

Component, Theming

### Description

On my ios14 phone.
document.adoptedStyleSheets.push (typescaleStyles.styleSheet);
This doesn't work because he's a relatively new api.

Secondly, text-field and menu's and buttons also have problems displaying.
For example, the login box for my website [http://one.guankejian.top] does not show the input box on ios14 phones.
The menu in the top right corner, for example, doesn't show up anymore, but is spread out.
For example, the [login] button, the status is also incorrect.

Failure：
![WechatIMG14876](https://github.com/material-components/material-web/assets/31543062/e17e9220-37d4-405b-9d4f-abc248eb2a61)

Success：
![WechatIMG79](https://github.com/material-components/material-web/assets/31543062/89317186-f32a-4694-948c-768a479c322a)

### Reproduction

ios14

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@material/web@1.4.0  failure

### Browser/OS/Node environment

ios14 failure

**Comment by asyncLiz** [comment]
MWC 1.4.0 only supports [Safari 16.4 and up](https://github.com/material-components/material-web/blob/main/docs/support.md#browsers). You may be able to get things working by using polyfills, but it isn't tested.

**Comment by kr05** [comment]
I have come across this issue recently, unfortunately it's a real blocker if your app is trying to reach as many people as possible, especially if you are still growing and even one new user that subscribes matters. I had to revert to using native inputs styled with css to get my app working again after receiving some angry emails from already paying users. At some point I'd like to help track all these compatibility issues and document how to fix them with polyfills or possible workarounds.
