### ISSUE TITLE
md-dailog max-height calculation is same as the min-height

### ISSUE THREAD

**Issue by Bl0kkie** [material-components/material-web#5573]
### What is affected?

Component

### Description

The max-height of the md-dialog (and so the viewport of the scroll window)  calculation is always 560px even there is a lot more space

```
    max-height: min(560px, 100% - 48px);
```

### Reproduction

Open a md-dialog and check :host rules of the tag-css

### Workaround

Can do with a important, but isnt a good solution.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.3.0

### Browser/OS/Node environment

Chrome Version 123.0.6312.106 (Official Build) (64-bit)
OS windows 10 enterprise

**Comment by asyncLiz** [comment]
The [`max-height` is the same as `max-width`, but not the `min-height` (140px)](https://github.com/material-components/material-web/blob/df6923e85c0c11bf2e8e11fb5a14b5bd875231bd/dialog/internal/_dialog.scss#L41-L44).

Both can be customized without `!important` using CSS.

```css
md-dialog.larger {
  max-height: 800px;
  min-height: 250px;
}
```
