### ISSUE TITLE
Chrome's "Suggest Password" not working with password text fields

### ISSUE THREAD

**Issue by drjon72** [material-components/material-web#5595]
### What is affected?

Component

### Description

Right click on a Material 3 text field of type "password" shows a drop down with "Suggest Password", however, nothing seems to happen when clicked. 

### Reproduction

Reproducible on [https://material-web.dev/components/text-field/](https://material-web.dev/components/text-field/)

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing @material/web@1.4.1-nightly.df6923e.0

### Browser/OS/Node environment

Chrome Version 123.0.6312.107 (Official Build) (arm64)
MacOS 13.6.6

**Comment by austinw-fineart** [comment]
Definitely an issue amongst the major browsers. I found [this Chromium issue](https://issues.chromium.org/issues/41276841) which claims to be fixed but from my testing is definitely not. Firefox users will also encounter a [similar issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1629226). Tested on Windows btw. I don't have a way of testing Safari but [they claim to have fixed it](https://bugs.webkit.org/show_bug.cgi?id=172567).

**Comment by TeamBusylj** [comment]
Try to put the password field in a <form> tag and set the form action attribute to action="javascript:void(0);" to prevent reloads.

**Comment by drjon72** [comment]
This is being tracked in chromium issue: https://issues.chromium.org/issues/326260437

They have a fix and will run an experiment
