### ISSUE TITLE
Github update api docs action is broken (missing checkbox events section)

### ISSUE THREAD

**Issue by ShreckYe** [material-components/material-web#5600]
### Description

There isn't an "events" section in [the docs for Checkbox](https://github.com/material-components/material-web/blob/main/docs/components/checkbox.md). Does it have similar events to [those for Switch](https://github.com/material-components/material-web/blob/main/docs/components/switch.md#events) since these 2 components are quite similar? I guess a similar section should be added if so.

**Comment by asyncLiz** [comment]
Yes, the checkbox mimics an `<input type="checkbox">`. `change` is typically the event listened to for checkboxes, but it will dispatch `input` as well.

We have the [jsdoc for checkbox's events](https://github.com/material-components/material-web/blob/faf03c2c9323493f0845eb71460c91f9f0bdf74b/checkbox/internal/checkbox.ts#L43-L48), but our [GitHub action to update API docs is broken](https://github.com/material-components/material-web/actions/workflows/update-docs-on-main.yml) :(

I'll update this issue to reflect fixing that action.

**Comment by silamon** [comment]
This one is solved now that the documentation workflow is working again?

**Comment by asyncLiz** [comment]
Yes, thank you!
