### ISSUE TITLE
lab / <md-navigation-drawer> doesn't work

### ISSUE THREAD

**Issue by Dakotys** [material-components/material-web#5604]
### What is affected?

Component

### Description

It seems like there was some change with class names and now shared css doesn't contain class that defines opened state for both `md-navigation-drawer` and `md-navigation-drawer-modal` but only the latter so the normal `md-navigation-drawer` cant be opened nor used. Also what is the purpose of pivot attribute since flex is not set to flex-direction: column? 

### Reproduction

Example using both: 
https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0ICdAbWF0ZXJpYWwvd2ViL2xhYnMvbmF2aWdhdGlvbmRyYXdlci9uYXZpZ2F0aW9uLWRyYXdlcidcbmltcG9ydCAnQG1hdGVyaWFsL3dlYi9sYWJzL25hdmlnYXRpb25kcmF3ZXIvbmF2aWdhdGlvbi1kcmF3ZXItbW9kYWwnIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbWF0ZXJpYWwtaW1wb3J0cy5qc1wiPjwvc2NyaXB0PlxuXG48bWQtbmF2aWdhdGlvbi1kcmF3ZXIgb3BlbmVkPlxuICBkZnNmc2ZcbjwvbWQtbmF2aWdhdGlvbi1kcmF3ZXI-XG5cbjwhLS0gPG1kLW5hdmlnYXRpb24tZHJhd2VyLW1vZGFsIG9wZW5lZD5cbiAgZGZzZnNmXG48L21kLW5hdmlnYXRpb24tZHJhd2VyLW1vZGFsPiAtLT4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d

### Workaround

Change of classes

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@material/web: 1.4.1

### Browser/OS/Node environment

Seems like general issue

**Comment by asyncLiz** [comment]
The nav drawer is still in development, which is why it's in the labs folder. It does not work right now.

**Comment by Dakotys** [comment]
Of course I understand that, but even small change like changing [sharedcss](https://github.com/material-components/material-web/blob/main/labs/navigationdrawer/internal/_shared.scss) from styling only modal to styling both would make the component usable. Just replacing it with this should suffice and make it usable:

```
.md3-navigation-drawer-modal, .md3-navigation-drawer {
	 background-color: var(--_container-color);
	 border-radius: var(--_container-shape);
	 height: var(--_container-height);
}
.md3-navigation-drawer-modal.md3-navigation-drawer-modal--opened, .md3-navigation-drawer.md3-navigation-drawer--opened {
	 inline-size: var(--_container-width);
}
.md3-navigation-drawer-modal .md3-navigation-drawer-modal__slot-content, .md3-navigation-drawer .md3-navigation-drawer__slot-content {
	 min-inline-size: var(--_container-width);
	 max-inline-size: var(--_container-width);
}
```

**Comment by Dakotys** [comment]
> The nav drawer is still in development, which is why it's in the labs folder. It does not work right now.

#

> The nav drawer is still in development, which is why it's in the labs folder. It does not work right now.

Of course I understand that, but even small change like changing [sharedcss](https://github.com/material-components/material-web/blob/main/labs/navigationdrawer/internal/_shared.scss) from styling only modal to styling both would make the component usable. Just replacing it with this should suffice and make it usable:

```
.md3-navigation-drawer-modal, .md3-navigation-drawer {
	 background-color: var(--_container-color);
	 border-radius: var(--_container-shape);
	 height: var(--_container-height);
}
.md3-navigation-drawer-modal.md3-navigation-drawer-modal--opened, .md3-navigation-drawer.md3-navigation-drawer--opened {
	 inline-size: var(--_container-width);
}
.md3-navigation-drawer-modal .md3-navigation-drawer-modal__slot-content, .md3-navigation-drawer .md3-navigation-drawer__slot-content {
	 min-inline-size: var(--_container-width);
	 max-inline-size: var(--_container-width);
}
```

**Comment by Dakotys** [comment]
#5606

**Comment by asyncLiz** [comment]
> #5606

I was just about to suggest opening one! :)
