### ISSUE TITLE
Unsure, but documentation for change event seems wrong for md-tabs

### ISSUE THREAD

**Issue by Dakotys** [material-components/material-web#5610]
### Description

In documentation are mentioned [link](https://material-web.dev/components/tabs/#mdprimarytab-lessmd-primary-tabgreater:~:text=the%20target's%20selected%20or%20selecteditem%20and%20previousselected%20or%20previousselecteditem)  [link2](https://github.com/material-components/material-web/blob/e77ce061b61d903df0888d6ded8d93fc04ddb97d/tabs/internal/tabs.ts#L15-L16) `selectedItem `property and other properties that no longer exist, they have been at some point replaced with `activeTabIndex `[link](https://github.com/material-components/material-web/blob/e77ce061b61d903df0888d6ded8d93fc04ddb97d/tabs/internal/tabs.ts#L67C7-L67C21).
Also maybe example of eventListener directly in documentation for Events could be helpful. (I wouldn't have to question my js knowledge and whether I am doing something wrong and instead would check potention flaws in source code first.  )<3

**Comment by asyncLiz** [comment]
Thanks for the issue, and sorry for the delay! I'm sending out https://github.com/material-components/material-web/pull/5627 to fix the docs.

For the event doc examples, I agree that would be a good enhancement! Maybe add a comment on [Better docs needed (#5407)](https://github.com/material-components/material-web/discussions/5407)?
