### ISSUE TITLE
md-*-text-field focus() does not work

### ISSUE THREAD

**Issue by shadow-identity** [material-components/material-web#5621]
### What is affected?

Accessibility, Component

### Description

.focus() method called on md-*-text-field instance returns `undefined`, but does not do anything.

### Reproduction

[Lit.dev repro](https://lit.dev/playground/#project=W3sibmFtZSI6Im1hdGVyaWFsLWltcG9ydHMuanMiLCJjb250ZW50IjoiaW1wb3J0IFwiQG1hdGVyaWFsL3dlYi90ZXh0ZmllbGQvZmlsbGVkLXRleHQtZmllbGQuanNcIjtcblxuY29uc3QgdGV4dEZpZWxkID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3RmJylcbiAgICBcbmNvbnN0IHJlcG9ydEZvY3VzID0gKCkgPT4gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2xvZycpLmlubmVyVGV4dCA9IGRvY3VtZW50LmFjdGl2ZUVsZW1lbnQgPT09IHRleHRGaWVsZFxuXG5yZXBvcnRGb2N1cygpXG4gICAgXG50ZXh0RmllbGQuZm9jdXMoKVxuICAgIFxucmVwb3J0Rm9jdXMoKVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbWF0ZXJpYWwtaW1wb3J0cy5qc1wiPjwvc2NyaXB0PlxuXG48bWQtZmlsbGVkLXRleHQtZmllbGQgaWQ9J3RmJyBsYWJlbD0naGknIGF1dG9mb2N1cz5BIG1hdGVyaWFsIGJ1dHRvbjwvbWQtZmlsbGVkLXRleHQtZmllbGQ-XG48cCBpZD0nbG9nJz48L3A-In0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

### Workaround

Would be great to know how it can be worked around

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.4.1

### Browser/OS/Node environment

Tested on Firefox 127.0b2 (64-bit) and Chrome Version 124.0.6367.207 (Official Build) (x86_64)

**Comment by asyncLiz** [comment]
It looks like you're calling `textField.focus()` too early before the custom element is upgraded by the browser. Try waiting for `customElements.whenDefined()` and `textField.updateComplete` before focusing.

```js
reportFocus();

customElements.whenDefined('md-filled-text-field').then(async() => {
  await textField.updateComplete;
  textField.focus();
  reportFocus();
});
```

After the lit.dev playground loads, press the refresh button (focusing in iframes is a bit weird) https://lit.dev/playground/#gist=977b358fe1b2176685160bd2c4b7bf08

Let us know if that helps!

**Comment by shadow-identity** [comment]
That seems to be working, thanks!
