### ISSUE TITLE
Remove the md-menu padding by default

### ISSUE THREAD

**Issue by ismartcoding** [material-components/material-web#5640]
### What is affected?

Component, Theming

### Description

Can we remove the default padding from the `md-menu`?

I noticed there is a `.item-padding` class that adds padding, which looks like this:

```css
.item-padding {
    padding-block: 8px;
}
```

![image](https://github.com/material-components/material-web/assets/92670034/d6aeced1-aa07-4e7b-9cb2-1c11871308d6)

The padding in the `md-menu` makes the menu appear unattractive.

![image](https://github.com/material-components/material-web/assets/92670034/85b43421-693d-4c24-8399-e8ad321a3e44)

### Reproduction

Check this https://material-web.dev/components/menu

### Workaround

No

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.5.0

### Browser/OS/Node environment

-

**Comment by VBasko** [comment]
https://m3.material.io/components/menus/specs#cd6409d5-9523-4099-9db7-42d1e1d2d194

Look here. It seems that the menu should have top and bottom padding equals to 8px


![#5640-menu-spec-measurements](https://github.com/material-components/material-web/assets/106957194/dc50af40-1448-42f0-aff7-665c1ca441af)

**Comment by VBasko** [comment]
As well as left and right paddings

**Comment by ismartcoding** [comment]
@VBasko Thank you for sharing the link. I'm uncertain why it needs to be that way in the specs, but removing the padding does seem to enhance the appearance of the hover style.

![image](https://github.com/material-components/material-web/assets/92670034/4048a96b-96af-44bc-b98d-7a2bde25f655)

![image](https://github.com/material-components/material-web/assets/92670034/a65875ae-c1b5-44f9-98f5-3b984497350d)

**Comment by asyncLiz** [comment]
Closing as WAI since the spec adds padding to the menu. In the future, this could be customizable by spacing tokens.
