### ISSUE TITLE
Button documentation, the supported values for property "type" should be "button", "submit" and "reset".

### ISSUE THREAD

**Issue by cshong87** [material-components/material-web#5650]
### Description

I am reporting an issue with documentation, for the button component in Material Design Web.

Documentation link: [https://github.com/material-components/material-web/blob/main/docs/components/button.md](https://github.com/material-components/material-web/blob/main/docs/components/button.md)

In your documentation, for all button variants, the documentation stated that the supported values for the property "type" are "text", "reset", or "submit". The value "text" is wrong. The supported values for property "type" should be "button", "reset", or "submit".

Please have a look at the documentation for html button "type" attribute at [https://www.w3schools.com/tags/att_button_type.asp](https://www.w3schools.com/tags/att_button_type.asp). The supported values for "type" attribute include "button" but do not include "text". Therefore, "text" is not a supported value for attribute "type".

In my project, there are a few buttons in a form. There is a button, which I do not want it to submit form on click. If I set "text" as type of button, the button behave like a submit button. It submit the form on click. I fixed this issue by setting the type value to "button".

Therefore, your documentation should be corrected.

### Browser/OS Environment

Browsers:

1. Microsoft Edge version 126.0.2592.61.
2. Google Chrome version 126.0.6478.63.
3. Mozilla Firefox version 127.0.

OS: Windows 10

**Comment by asyncLiz** [comment]
Thanks for catching this! Fix incoming soon
