### ISSUE TITLE
Checkbox theme not usable due to lost reference to tokens.$md-comp-checkbox-supported-tokens

### ISSUE THREAD

**Issue by randymorman-nisc** [material-components/material-web#5651]
### What is affected?

Theming

### Description

The reference of `tokens.$md-comp-checkbox-supported-tokens `  was changed to `$md-comp-checkbox-supported-tokens` . This is preventing the compiling of the theme.

```
28 │   $supported-tokens: $md-comp-checkbox-supported-tokens;
   │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@material/web/checkbox/internal/_checkbox.scss 28:22  theme()
  src/styles.scss 6:3                                                create-checkbox-theme()
  src/styles.scss 10:3                                               root stylesheet [plugin angular-sass]

    angular:styles/global:styles:1:8:
      1 │ @import 'src/styles.scss';
```

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-qcknxm?file=src%2Fstyles.scss

```
@use '@material/web/tokens/index' as tokens;
@use '@material/web/checkbox/checkbox' as checkbox;
@use 'sass:map';

@mixin create-checkbox-theme() {
  @include checkbox.theme(tokens.md-comp-checkbox-values());
}

```

### Workaround

I have not found a workaround.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing since 1.3.0 works in 1.2.0

### Browser/OS/Node environment

Node v.20.14.0
NPM v.10.7.0

**Comment by asyncLiz** [comment]
Good catch! I'll send out a fix shortly
