### ISSUE TITLE
option for a id="" cause it was never added in the methods 

### ISSUE THREAD

**Issue by Duplore** [material-components/material-web#5652]
### Description

option for a id="" cause it was never added in the properties
 

https://github.com/material-components/material-web/blob/main/docs/components/text-field.md#mdfilledtextfield-md-filled-text-field

**Comment by asyncLiz** [comment]
Can you add more details to this issue? You can provide an `id` attribute to the text field as-is and it will work right now.

```html
<md-outlined-text-field id="first-name" label="First"></md-outlined-text-field>
```

**Comment by Duplore** [comment]
@asyncLiz it does not communicate with the input.

**Comment by Duplore** [comment]
![image](https://github.com/material-components/material-web/assets/40915035/b3981887-59fa-4514-9338-79169d0f9721)
![image](https://github.com/material-components/material-web/assets/40915035/b0fbc033-738f-49a8-bcb7-6389eedc3151)

i put an id="" in here hoping it would also add it into the input which i would expect but it does not.

**Comment by asyncLiz** [comment]
IDs are scoped to light dom only, forwarding the id attribute to the inner `<input>` wouldn't allow you to use it where you're using the `<md-outlined-text-field>`.

What are you trying to do with the id?

**Comment by Duplore** [comment]
for a login cause the login needs the input to have an id

**Comment by asyncLiz** [comment]
How are you accessing the inner `<input>`? It's encapsulated within the text field's shadow dom and shouldn't be visible to your login. Are you breaking encapsulation to query it, or using something like `event.composedPath()` to access it?

An id with `<md-outlined-text-field>` can be used in login forms and report the correct id. I don't think I have enough information of how your code is using it. Can you post a small reproduction highlighting the issue?

**Comment by Duplore** [comment]
i was showing what i did in inspect element to show it did not add the id="" needed for the login to work with the input

**Comment by asyncLiz** [comment]
The devtools inspector is not a full reproduction and doesn't represent what happens when your login code runs.

At runtime, JavaScript and HTML code **do not** have the same visibility or access into the inner workings of the `<md-outlined-text-field>` as the debugger does.

What code is your login running? Is it an HTML `<form>` that posts to a server? Do you use JavaScript to read values and call `fetch()`? At what point in the process does something break because the `<input>` does not have an ID on it? What breaks? Is there an error thrown, or an unexpected result?

**Comment by Duplore** [comment]
vuejs

**Comment by asyncLiz** [comment]
Please provide a reproduction online using a playground editor, such as https://stackblitz.com or https://lit.dev/playground.

**Comment by Duplore** [comment]
we're already doing this on a live server test that uses vuejs 3

**Comment by Duplore** [comment]
<input
          class="input"
          style=${styleMap(style)}
          aria-describedby="description"
          aria-invalid=${this.hasError}
          aria-label=${ariaLabel}
          autocomplete=${autocomplete || nothing}
          name=${this.name || nothing}
          ?disabled=${this.disabled}
          inputmode=${inputMode || nothing}
          max=${(this.max || nothing) as unknown as number}
          maxlength=${hasMaxLength ? this.maxLength : nothing}
          min=${(this.min || nothing) as unknown as number}
          minlength=${hasMinLength ? this.minLength : nothing}
          pattern=${this.pattern || nothing}
          placeholder=${this.placeholder || nothing}
          ?readonly=${this.readOnly}
          ?required=${this.required}
          ?multiple=${this.multiple}
          step=${(this.step || nothing) as unknown as number}
          type=${this.type}
          .value=${live(this.value)}
          @change=${this.redispatchEvent}
          @focus=${this.handleFocusChange}
          @blur=${this.handleFocusChange}
          @input=${this.handleInput}
          @select=${this.redispatchEvent} />
          
          Can you some how add in a id="" to the <input> that will match the TextFieldType?

**Comment by asyncLiz** [comment]
The ID is not needed on the `<input>`, and you haven't provided information on why you think it is needed. Please answer the following:

1. What happened to make you inspect the text field to look for IDs?
2. Are you using an HTML `<form>`?
3. Are you accessing `mdOutlinedTextField.shadowRoot`?
4. Are you calling `event.composedPath()` and seeing an `<input>` without an ID?
5. Is an error being thrown? If yes, what is the error and how did it happen?
6. Why does your login code need an ID? Is it to identify the username/password? Can you use the `name` attribute instead, which is used to identify form controls?

**Comment by Duplore** [comment]
<form class="card py-3 px-3 shadow-sm w-100" style="max-width: 34.9rem;">
    <md-outlined-text-field type="text" label="Username" class="md-normal-input darker-border d-block md-outlined-text-field" required></md-outlined-text-field>
    <md-outlined-text-field  type="password" label="Password" class="md-normal-input darker-border d-block mt-3 md-outlined-text-field" required></md-outlined-text-field>
     <div class="d-flex align-items-center mt-4 w-100">
       <md-filled-button class="md-button-primary md-button-small px-4 py-2 ripple-light" href="">Login</md-filled-button>
       <a class="ms-auto fw-semibold fs-sm text-decoration-none" href="">Forgot Password</a>
     </div>
  </form>

 The md-outlined-text-field is not being picked up even tho I have it connected using v-model=""  for example the <md-filled-button> has a id="button" that works beacuse the <button> has a id in there that is id="button" so that works with out a problem

**Comment by Duplore** [comment]
``` <form class="card py-3 px-3 shadow-sm w-100" style="max-width: 34.9rem;" @submit.prevent="login">
    <md-outlined-text-field v-model="user.username" type="text" label="Username" class="md-normal-input darker-border d-block md-outlined-text-field" required></md-outlined-text-field>
    <md-outlined-text-field  v-model="user.password" type="password" label="Password" class="md-normal-input darker-border d-block mt-3 md-outlined-text-field" required></md-outlined-text-field>
     <div class="d-flex align-items-center mt-4 w-100">
       <md-filled-button class="md-button-primary md-button-small px-4 py-2 ripple-light" id="button" type="submit">Login</md-filled-button>
       <a class="ms-auto fw-semibold fs-sm text-decoration-none" href="/none">Forgot Password</a>
     </div>
  </form> ```

The md-outlined-text-field is not being picked up even tho I have it connected using v-model=""  for example the <md-filled-button> has a id="button" that works beacuse the <button> has a id in there that is id="button" so that works with out a problem

**Comment by Duplore** [comment]
```
<form class="card py-3 px-3 shadow-sm w-100" style="max-width: 34.9rem;" @submit.prevent="login">
    <md-outlined-text-field v-model="user.username" type="text" label="Username" class="md-normal-input darker-border d-block md-outlined-text-field" required></md-outlined-text-field>
    <md-outlined-text-field  v-model="user.password" type="password" label="Password" class="md-normal-input darker-border d-block mt-3 md-outlined-text-field" required></md-outlined-text-field>
     <div class="d-flex align-items-center mt-4 w-100">
       <md-filled-button class="md-button-primary md-button-small px-4 py-2 ripple-light" id="button" type="submit">Login</md-filled-button>
       <a class="ms-auto fw-semibold fs-sm text-decoration-none" href="/none">Forgot Password</a>
     </div>
  </form>
```
The md-outlined-text-field is not being picked up even tho I have it connected using v-model=""  for example the <md-filled-button> has a id="button" that works beacuse the <button> has a id in there that is id="button" so that works with out a problem

**Comment by asyncLiz** [comment]
Thanks for the template! Can you try adding the `name` attributes to the username and password fields? The name attribute is required for `<form>` elements to add their values to the submitted data.

```html
<md-outlined-text-field v-model="user.username" name="username" ...>
<md-outlined-text-field v-model="user.password" name="password" ...>
```

**Comment by Duplore** [comment]
is it possible to use id cause i can't use name cause it's already being not related to this framework

**Comment by asyncLiz** [comment]
Unfortunately the name attribute is required for use in HTML forms.

Is the problem that the v-model user property is not updated when your JavaScript form submit code runs? Does adding the name attribute fix it?
