### ISSUE TITLE
Accessibility issue with aria-hidden="true" attribute in <md-radio> component

### ISSUE THREAD

**Issue by pennin-style** [material-components/material-web#5699]
### What is affected?

Accessibility

### Description

When clicking the button part of the radio button in the Shadow DOM of the <md-radio> component, the following error occurs:

```
Blocked aria-hidden on a <input> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. 
```

This is caused by the aria-hidden="true" attribute assigned to the button part of the radio button, which hides the focused element from accessibility tools.

To solve this problem, we propose replacing the aria-hidden attribute with the inert attribute. The inert attribute prevents focus as well as hides the element from accessibility tools.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wdxt3x?file=app.vue

### Workaround

Instead of aria-hidden=“true”, use the inert attribute.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.0.0

### Browser/OS/Node environment

Browser: Chrome 127.0.6533.120
OS: macOS 14.6.1
Node version: 18.20.3
npm version: 10.2.3

**Comment by asyncLiz** [comment]
Looking through the code history of radio, this happened when I swapped aria from using the inner `<input>` to the outer `<md-radio>` element. The `<input>` is only being used as the touch target now.

I think we can replace the input entirely with a div touch target instead. Adding `inert` will make the touch target stop working, since it won't receive pointer events.

**Comment by pennin-style** [comment]
@asyncLiz 

Thank you for informing me about the drawbacks of using the inert attribute.
I have made adjustments and would appreciate it if you could take a look.
