### ISSUE TITLE
[mwc-textarea] Color CSS Custom Properties don't work except the primary-color

### ISSUE THREAD

**Issue by contis2908** [material-components/material-web#581]
**I'm submitting a:**
- [X] bug report
- [ ] feature request

**What OS are you using?**
macOS High Sierra

**What browser(s) is this bug affecting:**
Tested it only in Chrome

**Current behavior:**
All custom css properties that manipulate the border color are not applied besides the primary color. I did test it with the mwc-textfield and it did work. However, the mwc-textarea isn't.
This includes:
--mdc-text-area-outlined-idle-border-color
--mdc-text-area-outlined-hover-border-color
--mdc-text-area-outlined-disabled-border-colo

**Expected behavior:**
Expected outcome wpuld be a changed border color.

**Comment by azakus** [comment]
There are actually quite a few spots in the MDC Sass that do not fully support CSS Custom Properties, and I've created an upstream issue (https://github.com/material-components/material-components-web/issues/5242) to track that.

**Comment by asyncLiz** [comment]
Fixed in M3
