### ISSUE TITLE
Support dense text fields

### ISSUE THREAD

**Issue by abdonrd** [material-components/material-web#654]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

Support dense text fields

Docs: https://material.io/components/text-fields/#outlined-text-field

![mio-components_assets_1NuXrmrchha20V57ug2zrRifpmR_EecS0_textfields-dense-outlined-example](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1NuXrmrchha20V57ug2zrRifpmR_EecS0%2Ftextfields-dense-outlined-example.png)

**Comment by jsidrach** [comment]
Any update on this?

**Comment by holgerengels** [comment]
I read in the mdc-textfield documentation, that the _dense_ variant of the text field will be removed in an upcoming release .. see this [GitHub Issue](https://github.com/material-components/material-components-web/issues/4142) for details

**Comment by cintaccs** [comment]
From my test of the web-component implementation in this repo (material-components-web-components) - the density is not implemented on text fields - however it is available on the (material-components-web) repository. As I understand the actual "components" is a wrapper on top - which however (temporarily I hope...) lacks the option to specify density (according to what I could figure out).

**Comment by dfreedm** [comment]
We currently have no good way to expose density.
Blocking issue #841

**Comment by asyncLiz** [comment]
Tracking in https://github.com/material-components/material-web/issues/841
