### ISSUE TITLE
Ability to customize mwc-dialog's heading

### ISSUE THREAD

**Issue by govis** [material-components/material-web#675]
It would be very useful to be able to customize the heading of a <code>mwc-dialog</code> to provide background, html content such as tab-bar, x button, etc

**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Related code:**

```js
<div class="mdc-dialog__surface">
    ${this.renderHeading() || ''}
    <div id="content" class="mdc-dialog__content">
```

```js
renderHeading() {
    if(this.heading)
        return html`
            <h2 id="title" class="mdc-dialog__title">${this.heading}</h2>`;
}
```
One could then extend <code>DialogBase</code> and override <code>renderHeading</code>

**Comment by e111077** [comment]
Unfortunately extending the header to something other than text this is outside of the [material design dialog spec](https://material.io/components/dialogs/).

We ask that you please instead override the render function as that is outside of our support surface.

**Comment by govis** [comment]
Here's a screenshot of a dialog in Google Forms:

![image](https://user-images.githubusercontent.com/971651/70154124-fa0b7780-167d-11ea-9446-4e862028d4de.png)

As you can see the header has tab-bar and an x button. Making a header like this with a colored background would be a matter of 5 lines of code with a simple forward thinking change in <code>mwc-dialog-base</code> versus 50 lines to copy and maintain a copy of the entire render function.

**Comment by e111077** [comment]
Reopening for further discussion

**Comment by jmgarcia98** [comment]
Hello, 
My soluction is:

you can extends to dialog and you can use your own MWCDialogCustom:
`import { Dialog } from '@material/mwc-dialog';
import { customElement, html, TemplateResult } from 'lit-element';

@customElement('mwc-dialog-base-mod')
export class MwcDialogMod extends Dialog {
  protected renderHeading(): TemplateResult {
    return html`
      <h2 id="title" class="mdc-dialog__title">
        ${this.heading} <button>X</button>
      </h2>
    `;
  }
}
`
![image](https://user-images.githubusercontent.com/62557105/119527201-64d3d580-bd80-11eb-8838-2b8c273d2051.png)

**Comment by shadow-light** [comment]
Use this to allow anything within the header via a slot and still preserve the default behaviour:

```ts

import {Dialog} from '@material/mwc-dialog'
import {customElement, html} from 'lit-element'


@customElement('mwc-dialog-header')
export class MWCDialogHeader extends Dialog {

    protected override renderHeading(){
        return html`
            <div class="mdc-dialog__header">
                <slot name="headerSlot">
                    <h2 id="title" class="mdc-dialog__title">${this.heading}</h2>
                </slot>
            </div>
        `
    }

}
```

**Comment by asyncLiz** [comment]
Fixed in M3
