### ISSUE TITLE
Higher level mwc-dialog-base

### ISSUE THREAD

**Issue by govis** [material-components/material-web#683]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

It appears that <code>DialogBase</code> is designed to be very opinionated (not possible to customize header, footer etc) making it difficult to use in many user interaction scenarios (sign in, popup input form, multi step interaction - see #675)

As such a class providing basic overlay functionality would be useful

**Comment by 3mo-arshia** [comment]
Yep, the dialog is really not suitable for web apps which for instance are offering **multiple themes** and **dark mode**, as many dialog related CSS classes e.g. `.mdc-dialog` aren't using the global CSS variables of the MDC framework. Waiting for this enhancement in upcoming updates.

**Comment by e111077** [comment]
Heya we hear you. We are going to discuss our strategy on extensibility.

**Comment by e111077** [comment]
#602

**Comment by asyncLiz** [comment]
Obsolete with M3
