### ISSUE TITLE
mwc-button height changes when icon added

### ISSUE THREAD

**Issue by vikjung** [material-components/material-web#704]
**I'm submitting a:**

- [ X] bug report
- [ ] feature request

**What OS are you using?**

Mac OS HighSierra

**What browser(s) is this bug affecting:**
Chrome Version 78.0.3904.108 (Official Build) (64-bit)
**Current behavior:**
Have two mwc buttons next to each other.  One has an icon added other does not.  When icon is added then they do not align vertically.  The one with the icon shifts slightly up.

**Expected behavior:**

Both buttons should have stayed aligned.

**Steps to reproduce:**

**Related code:**

```
        <div class="row">
          <mwc-button outlined id="male" label="Male"  dense icon="clear" @click="${e =>  this._setbutton(e)}" ></mwc-button>
          <mwc-button outlined id="female" label="Male"  dense icon="" @click="${e =>  this._setbutton(e)}" ></mwc-button>
        </div>
```

**Other information:**

**Comment by asyncLiz** [comment]
Fixed in M3
