### ISSUE TITLE
Icon indicator not aligned in IE

### ISSUE THREAD

**Issue by e111077** [material-components/material-web#714]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Windows 10 (saucelabs)

**What browser(s) is this bug affecting:**

IE 11

**Current behavior:**

custom indicator is not aligned correctly
![image](https://user-images.githubusercontent.com/5981958/71133676-34156700-21b0-11ea-8602-69a299693f2f.png)

**Expected behavior:**

Chrome:
![image](https://user-images.githubusercontent.com/5981958/71133706-527b6280-21b0-11ea-9f91-2d8446b5e198.png)

**Steps to reproduce:**

Run the demos in IE (might have to include changes from #713)

**Related code:**

```js
// insert any relevant code here or add a include a codepen
```

**Other information:**

**Comment by fernandopasik** [comment]
Just for reference to find this example you can go to: https://mwc-demos.glitch.me/demos/tabs.html and look for **Icon Indicator**
