### ISSUE TITLE
mwc-top-app-bar  doesn't play nice with tab-bar

### ISSUE THREAD

**Issue by sujato** [material-components/material-web#781]
**I'm submitting a:**

- [X] bug report
- [ ] feature request

**What OS are you using?**
Ubuntu 19.10

**What browser(s) is this bug affecting:**
Chromium 75

**Current behavior:**
If you put a tab-bar inside a top-app-bar its behavior and animation is separate. It seems the animation behavior is applied to a header element within the top-app-bar, and there's no way to join it with the tab-bar. This is similar to the behavior that's *not* recommended in the MD spec.

**Expected behavior:**
See the MD specs:

https://material.io/components/tabs/#behavior

We should have an option to choose either of the two recommended behaviors, i.e. "When tabs are attached to a top app bar, they can scroll off the screen with the bar and lock in place at the top of the screen." or "Tabs can scroll offscreen on scroll, and reappear when the page is scrolled up." Given that these are the two behaviors intended in the spec, it should be explicit and documented.

**Steps to reproduce:**

    <mwc-top-app-bar>
        <span slot="title" class="app-bar-title">My Title</span>
    <mwc-icon-button icon="search" slot="actionItems" class="notCenter"></mwc-icon-button>
    <mwc-tab-bar>
      <mwc-tab label="introduction"></mwc-tab>
      <mwc-tab label="what’s new"></mwc-tab>
    </mwc-tab-bar>
      </mwc-top-app-bar>

**Comment by asyncLiz** [comment]
Thanks for the issue! We're tracking support for this in https://github.com/material-components/material-components-web/issues/3633

**Comment by asyncLiz** [comment]
Obsolete with M3
