### ISSUE TITLE
mwc-button height is always fixed

### ISSUE THREAD

**Issue by ainvaltin** [material-components/material-web#81]
`mwc-button` doesn't adjust it's height when it's content's height is bigger than the default, ie when using code like

    <mwc-button><img src="image.png"/></mwc-button>

the width of the button will grow according to the width of the image but height stays fixed so that the bottom part of the image is cut off.

The `paper-button` of the Polymer 2 adjusted it's size so that the whole image is visible.

**Comment by azakus** [comment]
We'll need to figure out if the material-components-web MDCButton is supposed to adjust its height with children.

**Comment by bennypowers** [comment]
This was incredibly straightforward with paper-button - just add content.

https://material.io/design/components/buttons.html#anatomy shows an example of a button flowing to adjust to inline content.

A use case for adjusting height is for image buttons

**Comment by finity69x2** [comment]
I'm using a custom entity row that has buttons included and the switch to mwc-button breaks the style of the button.

here is the code of the style I'm trying to achieve:

```
            <style>
                :host {
                    line-height: 1.5;
                }
                .speed {
                    min-width: 30px;
                    max-width: 30px;
		    margin-left: 2px;
                    margin-right: 2px;
    	            background-color:#759aaa;
	            border: 1px solid lightgrey; 
	            font-size: 10px !important;
	            float: right !important;   
                }
            </style>
            <hui-generic-entity-row hass="[[hass]]" config="[[_config]]">
                <div class='horizontal justified layout' on-click="stopPropagation">
                    <mwc-button
                        class='speed'
			style='[[_lowOnColor]]'
                        toggles name="low"
                        on-click='setSpeed'
                        disabled='[[_isOnLow]]'>LOW</mwc-button>
```

This is what it used to look like with paper-button:

![ex](https://user-images.githubusercontent.com/32221243/53328774-b26aea80-38b8-11e9-85d9-ca58e0fbc075.gif)


this is what it looks like now with mwc-button with the same style:

![ex3](https://user-images.githubusercontent.com/32221243/53328828-d29aa980-38b8-11e9-9c29-f5c7056122ba.gif)

the bottom row in the above picture is still using paper-button.

For some reason the mwc-button isn't respecting the style.

**Comment by elf-pavlik** [comment]
https://material.io/design/components/buttons.html#usage has only 4 types of buttons, non of them an image button.

**Comment by straversi** [comment]
I tried this in the latest material-components-web, results below. Images inside buttons will be resized to fit (left side). Trying to force the height of the image with explicit styling (right side) causes undefined behavior.

![image in button](https://user-images.githubusercontent.com/7411489/55350827-d00c1080-5471-11e9-929e-5984ff4eccb9.png)

**Comment by bennypowers** [comment]
Image buttons are far from the only use case here

consider this grid:

<img width="1040" alt="Screen Shot 2019-12-18 at 12 52 00" src="https://user-images.githubusercontent.com/1466420/71656377-9f7c3e80-2d43-11ea-82ec-cebc54dfecf7.png">

in which the button is misaligned and shorter than the inputs.

The [button has height controls in SASS](https://github.com/material-components/material-components-web/blob/9468dfbd4d9a5e643c1ad9472e91a74dcd9c49e0/packages/mdc-button/_variables.scss#L26). It should have in the browser as well.

**Comment by arthurevans** [comment]
Note that the Shrine theme calls for customizing the button size. From the images, it looks like they're using 360px x 48px for contained buttons. We can't currently do this with MWC.

See "Contained buttons" in the Components section:

https://material.io/design/material-studies/shrine.html#components

**Comment by notwaldorf** [comment]
Even if the size isn't updated automatically, could there be a custom property exposed that controls the height? I just wrote the line `this.shadowRoot.querySelector('.some-button').shadowRoot.querySelector('button').style.height = '60px';` and it didn't feel great :)

I can open this as a separate issue if it doesn't fit here.

**Comment by asyncLiz** [comment]
There will eventually be a way to change the height that is part of the [density](https://github.com/material-components/material-components-web-components/issues/841) system that we're working on.

**Comment by MarcSkovMadsen** [comment]
I would also need this.

**Comment by andyvanee** [comment]
I don't believe this is resolved yet, and this point wasn't raised: it would be nice to have control over both `height` and `min-height`. In the following screenshot I've done similar styling as @notwaldorf to fix the issue, and it didn't feel great for me as well:)

![Screen Shot 2021-11-04 at 4 56 22 PM](https://user-images.githubusercontent.com/212280/140432002-f96185ed-f9dd-4b91-90a9-f46161731987.png)

**Comment by asyncLiz** [comment]
Height is now configurable in M3
