### ISSUE TITLE
mwc-textfield: Remove the need to call layout()

### ISSUE THREAD

**Issue by aarondrabeck** [material-components/material-web#812]
After using mwc-textfield in a number of productions applications I find that our code-base is littered with ```input.layout()``` in order to fix the empty floating label bug.   

In my opinion, this should not be the responsibility of the consumer to patch up the internals of the input, under very particular conditions, in order to prevent it from improperly drawing it self.   Our teams have used a number of material themed components with floating labels, including paper-input, and this was never an issue.  

Additionally in larger applications, you do not always immediately know if your page will be removed from the DOM or just hidden as that might be handled by routing a few layers above you.  This adds to the developer confusion and increases the chances of broken inputs.  

I realize this might be an upstream issue but if there is anyway to eventually have the label do proper calcs (or no calcs just use flow) regardless if it has a width or not yet it would be very helpful. 

Thanks for all the hard work on these inputs!

**Comment by CaptainCodeman** [comment]
This may be what I was just seeing which I came to raise an issue for ...

An `mwc-textfield` that is inside some hidden element doesn't render correctly when the other element is unhidden - the label is empty.

We're not seriously meant to track what may or may not be changed and go calling methods on the child elements to have them render correctly are we?

**Comment by aarondrabeck** [comment]
> This may be what I was just seeing which I came to raise an issue for ...
> 
> An `mwc-textfield` that is inside some hidden element doesn't render correctly when the other element is unhidden - the label is empty.
> 
> We're not seriously meant to track what may or may not be changed and go calling methods on the child elements to have them render correctly are we?

This sounds similar.  Are you changing the label from something to empty while hidden?

**Comment by CaptainCodeman** [comment]
> This sounds similar. Are you changing the label from something to empty while hidden?

No, the label is completely static text, the component is just inside a container that is initially hidden - when the container is shown the label is missing.

**Comment by aarondrabeck** [comment]
> > This sounds similar. Are you changing the label from something to empty while hidden?
> 
> No, the label is completely static text, the component is just inside a container that is initially hidden - when the container is shown the label is missing.

Yep, this is the issue.  Unfortunately you have to call layout after the input has a width (unhidden)...at least for now.  Hopefully this can be engineered out.

**Comment by CaptainCodeman** [comment]
yeah, if it's not an immediate child it's not really usable as it is now

**Comment by asyncLiz** [comment]
Fixed in M3
