### ISSUE TITLE
Broken textfield autocomplete

### ISSUE THREAD

**Issue by ranjeet-choudhary** [material-components/material-web#82]
The autosuggest fails until input tag is inside form tag.
https://github.com/material-components/material-components-web/issues/3174

But It doesn't work for form level autosuggest. https://github.com/w3c/webcomponents/issues/572

**Comment by BenRacicot** [comment]
@azakus  Any movement on this? I can't believe we cannot override Chrome's background-color with `input:-webkit-autofill`. What an enormous gotcha with a floating label pattern input.

Doesn't [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=46543) void the use of the floating label pattern?

**Comment by ranjeet-choudhary** [comment]
@azakus Haven't tried yet but looks promising, should take care of form-related issues. Form-associated custom elements  https://docs.google.com/document/d/1JO8puctCSpW-ZYGU8lF-h4FWRIDQNDVexzHoOQ2iQmY/edit?pli=1#heading=h.c5n73clvajkz
