### ISSUE TITLE
Support for a dense mwc-list-item

### ISSUE THREAD

**Issue by holgerengels** [material-components/material-web#833]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Current behavior:**
The horizontal paddings of mwc-list-item can be configured with custom css property. But there's no means to reduce the height of a mwc-list-item.

**Expected behavior:**
There should be a custom property for vertical padding or an attribute dense should be supported.

```js
<mwc-list-item dense>...</mwc-list-item>
```

**Comment by dfreedm** [comment]
We currently have no good way to expose density.
Blocking issue #841

**Comment by asyncLiz** [comment]
Tracking in https://github.com/material-components/material-web/issues/841
