### ISSUE TITLE
Implement Date and Time Pickers

### ISSUE THREAD

**Issue by PaulHMason** [material-components/material-web#843]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Other information:**
There doesn't appear to be a feature request for Material Design date and time pickers. The Material Design site has guidance for date pickers, but not time pickers (I seem to recall V1 having time pickers though). Only Flutter seems to have implemented them.

https://material.io/components/pickers/

**Comment by asyncLiz** [comment]
Thanks for the issue. Currently date picker and time picker have not been prioritized in MDC, and won't be implemented in MWC until then. You can follow https://github.com/material-components/material-components-web/issues/54 and https://github.com/material-components/material-components-web/issues/55 to be notified of progress on them.

**Comment by cintaccs** [comment]
funny that these components have no priority considering the amount of thumbs up 👍❤️ and hearts ... I can’t recall having seen that much communitty “up-voting” in these two repos.... but it seems to be ignored for unknown reasons

**Comment by asyncLiz** [comment]
The only specs for details date and time pickers are for mobile, and those components have already been implemented for native. We're waiting on good design specs for a desktop date/time picker. 

In the meantime, the browser's built-in `<input type="date">`, `type="time"`, and `type="datetime"` are supported for the Material textfield.

**Comment by cintaccs** [comment]
I am not "complaining" and my comment shouldn't been understood negative! however I am almost certain that 90% or more of the solutions that uses your repos are implementing own "crappy" date and time pickers. The browsers built-in date, time and date-time pickers are very very seldom used in applications that implement any kind of modern design because the design is weird and the date-formats seldom fits etc.

**Comment by motss** [comment]
@cintaccs @PaulHMason @asyncLiz 

Meanwhile you can look at a relevant datepicker element [here].

[here]: https://github.com/motss/app-datepicker

**Comment by cintaccs** [comment]
@motss 
That is excellent! Thanks a lot! I will join your efforts and probably use your component. Your component provides a number of the things that I requested (week start, week numbers, year picker) and you don't bother with IE older compatibility (we really shouldn't) and it is based on Lit etc. GREAT!! THANKS!

**Comment by motss** [comment]
It should work on IE11 but I decided not to support it anymore especially when it complicates the tests. Plus Chromium Edge is now stable, why don't just use that? 😂

**Comment by asyncLiz** [comment]
Closing as obsolete since date and time pickers will be available in Material 3
