### ISSUE TITLE
mwc-top-app-bar prominent hidden content

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#857]
When using `prominent`, if the action items list or the element is too long, the title on the left part is hidden if too long too. On small devices it can be annoying. Without the `prominent` it is expected to have the title hidden to reveal the action items but when it's prominent shouldn't the title have all the free available space to the right ?

If that's not clear here's a screenshot of an example

<img src="https://i.imgur.com/zYs8uxr.png">

While it should be written "Valentin Degenne", the title is trimmed at the end because the action item which is a `mwc-select` in this case is extending the right section.
What do you think ?

Thanks.

**Comment by dfreedm** [comment]
Can you add a bit more detail about how to reproduce this?
A demo with the screensize you're seeing this interaction in would be great!

**Comment by vdegenne** [comment]
Sure, I made this simple repro on glitch : https://mwc-top-app-bar-long-action-items-and-title.glitch.me

I understand `mwc-select` is not really designed to be used as an action item in a `mwc-top-app-bar` I suppose but in my use case I wanted to use a select element for selecting the language of the interface, similar to the one on Web Fundamentals website : 

<img src="https://i.imgur.com/S0nrgwx.png">

On small devices Web Fundamentals displaces the element at the bottom of the page which is a good alternative I am thinking about but I wanted to open this ticket because I always like to push the customization a bit further for modularity purpose.

So in prominent context the select element seems to integrate well except the right section is hiding the left title.

**Comment by asyncLiz** [comment]
Obsolete with M3
