### ISSUE TITLE
mwc-icon outlined icons missing

### ISSUE THREAD

**Issue by imarian97** [material-components/material-web#86]
`mwc-icon` doesn't support the new icon themes (including outlined icons).

**Comment by azakus** [comment]
Should just need to rev the material-components-web version.

**Comment by straversi** [comment]
This should just be a matter of loading the `Material+Icons+Outlined` font in mwc-icon-font.ts, then specifying `Material Icons Outlined` as the `--mdc-icon-font`. Before PRing this, it'd be good to reconcile this idea with #195. This is a good argument for letting users load their own Material Icon sets.

**Comment by rjsteinert** [comment]
Anyone out there looking at this ticket and wondering why their `<mwc-icon>` elements stopped working after an upgrade, add the following import.

```
import '@material/mwc-icon/mwc-icon-font.js'
```

**Comment by aomarks** [comment]
We're actually now recommending just loading the font in your application HTML file. See https://github.com/material-components/material-components-web-components#fonts. We may remove the `mwc-icon-font.js` file in an upcoming breaking change release.

**Comment by rjsteinert** [comment]
Aha, gotcha. Thanks for the heads up, I'll use that method. It might be on your radar, but just in case, the [README.md for mwc-icon](https://github.com/material-components/material-components-web-components/tree/master/packages/icon) could use some of these updates.

**Comment by dfreedm** [comment]
Is this working for you now?

**Comment by e111077** [comment]
@dfreedm do you mind documenting this process in `mwc-icon`

**Comment by dfreedm** [comment]
Yeah I can do that

**Comment by treeder** [comment]
Will this be fixed in material 3?  And will it use Material Symbols instead of icons?

**Comment by asyncLiz** [comment]
Fixed in M3, see [icon docs](https://github.com/material-components/material-web/blob/main/docs/components/icon.md) for usage on loading outlined icons
