### ISSUE TITLE
<mwc-switch> sprouts unexpected inline position: relative style

### ISSUE THREAD

**Issue by cdata** [material-components/material-web#890]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**
Mac OS

**What browser(s) is this bug affecting:**
Chrome

**Current behavior:**
`<mwc-switch>` sprouts an unexpected `style="position: relative"` attribute.

**Expected behavior:**
`<mwc-switch>` does not sprout unexpected attributes, particularly inline styles.

**Steps to reproduce:**
 1. Put an `<mwc-switch>` on a page
 2. Open it in your browser
 3. Inspect the element and note the `style` attribute

**Related code:**

```html
<mwc-switch></mwc-switch>
```

**Other information:**
This was discovered when creating this demo: http://lopsided-motion.glitch.me/090-mwc.html

**Comment by dfreedm** [comment]
This is probably due to how the ripple is applied.

**Comment by asyncLiz** [comment]
Fixed in M3
