### ISSUE TITLE
Refactor components for compatibility for internal tooling

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-web#892]
To make MWC more compatible with some internal tooling, we need to perform some refactoring of our usage of MDC, Sass, and LitElement/lit-html.

The major consequence will be that the components should have a more idiomatic usage of LitElement and lit-html.

## Changes
- Use the render methods to drive all DOM mutations
  - Remove Foundations and Adapters in components where all logic is handled by the render methods
- Limit usage of lit-html directives
- Annotate certain patterns and methods for static analysis
- Make a linting tool to enforce internal requirements

**Comment by asyncLiz** [comment]
Closing as obsolete with Material 3
