### ISSUE TITLE
[docs]: Document How to Produce Icon Fonts

### ISSUE THREAD

**Issue by bennypowers** [material-components/material-web#952]
**Is your feature request related to a problem? Please describe.**
A developer needs to extend the default `Material Icons` icon font. She wants to use icons from https://materialdesignicons.com/, which does not include ligatures in their published font. https://materialdesignicons.com/ has also [stated](https://github.com/Templarian/MaterialDesign-Webfont/issues/45) that they don't intend to support their font as a first-class product going forward, so it's unlikely that ligatures will be added.

**Describe the solution you'd like**
Back with Polymer's `iron-icon`, adding an svg icon was a simple copy-paste affair, but with `mwc-icon`, developers will have to compile and serve their own icon fonts. I'd like for this project to document that process, so that our developer can go from no-knowledge to working icon font by following some clear steps,

**Describe alternatives you've considered**
A feature like `iron-icon`'s `iron-iconset-svg` would also work.

**Additional context**
Pinging @asyncLiz 
> We could coordinate with the icons team and see what tools they're using to generate the fonts.

**Comment by asyncLiz** [comment]
Obsolete with M3
