### ISSUE TITLE
mwc-radio selection controller doesn't work with array.map and dynamic data

### ISSUE THREAD

**Issue by neilvanlandingham** [material-components/material-web#955]
**Describe the bug**
When using array.map in a template to render a group of radio buttons, and when updating the component's properties to trigger a rerender of the radio group with a new unique group name, the radio group selection controller does not work as expected.

**To Reproduce**
https://jsbin.com/nofomes/edit?html,console,output

Wait three seconds for the data to update, click the radio buttons, and you will observe that the radio button grouping is no longer respected by the selection controller. 

**Expected behavior**
Only one radio button should be selected at a time within a radio group.

**Browser Version (please complete the following information):**
Chrome on Windows

**Comment by dfreedm** [comment]
Thanks for the repro case!

**Comment by MendyBerger** [comment]
@WeftDigital I think the reason the radio buttons are not grouped is because all radios have different names, try naming them just `radio` (without `question.id`)

**Comment by asyncLiz** [comment]
Should be fixed in M3
