### ISSUE TITLE
mwc-drawer seems to be blocking user input

### ISSUE THREAD

**Issue by govis** [material-components/material-web#973]
**Describe the bug**
After closing a nested drawer page stops responding to events such as mouse click

**To Reproduce**

1. Click on '=' to open drawer
2. Click on 'Page Two'
3. Click on '=' to open drawer
4. Click on 'Main Page'
5. Input is now blocked - can't open the drawer anymore

**Expected behavior**
Controls such as mwc-icon-button respond to mouse click event

**Screenshots**
https://stackblitz.com/edit/typescript-cjyw9q

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.132

**Comment by govis** [comment]
On a related note, why does main content need to be slotted into the drawer - can't the drawer be independent overlay for just the drawer content like mwc-menu-surface?

**Comment by govis** [comment]
Played a bit more and made another repro. It has 2 pages one with a top-app-bar and another with a drawer (it's not a nested drawer anymore) . When you navigate to the second page (icon-button click) and back (drawer list-item click) the page stops responding to mouse click:

https://typescript-hprmdk.stackblitz.io/

**Comment by govis** [comment]
It appears that MDCModalDrawerFoundation <code>closed</code>,  <code>adapter.releaseFocus</code>,  <code>adapter.restoreFocus</code>, etc are not being called when the page containing the drawer is navigated away/from

**Comment by asyncLiz** [comment]
Should be fixed in M3
